// ════════════════════════════════════════════════════════════════════════════
//  MIMs procurement booklet, edition: ga
//
//  GENERATED by gen_typ.py from content/ga.json + shared.json + quotes.json.
//  Do not edit: change the JSON and run ./build.sh.
//
//  How to read it: the file runs top to bottom in page order. Each #name(…)
//  is one block on the page; what the block looks like (sizes, colours,
//  spacing) is described next to its definition in ../style.typ.
//  #fit-page("name")[ … ] is one physical page.
//  One-letter prepositions may be followed by a no-break space (U+00A0),
//  which looks like a normal space here.
//
//  Build:  typst compile --root .. --font-path ../tools/fonts booklet-ga.typ
// ════════════════════════════════════════════════════════════════════════════
#import "../style.typ": *

#show: booklet.with(title: "Seicliosta Soláthair · a úsáideann na Meicníochtaí · Idir-inoibritheachta Íosta (MIMs)", lang: "ga",
  nav: (overview: "Forbhreathnú", clauses: "Clásail", example: "Sampla", table: "Tábla comhlíonta", glossary: "Gluais", list: "Seicliosta", back: "ar ais go dtí an seicliosta", page: "lch."),
  mims: ("MIM0", "MIM1", "MIM2", "MIM3", "MIM6", "MIM7", "MIM8",))


// ════════════════════════════════════════════════════════════════════════════
//  COVER
// ════════════════════════════════════════════════════════════════════════════
#cover(
  title:    "Seicliosta Soláthair · a úsáideann na Meicníochtaí · Idir-inoibritheachta Íosta (MIMs)",
  subtitle: "Cad le cur i dtairiscint ionas go gcoimeádfaidh do chathair a cuid sonraí",
  tagline:  "Do MIMs Plus 9.0 le OASC",
  footer:   "D'oifigigh soláthair, do bhainisteoirí tionscadail agus do Phríomhoifigigh Faisnéise de chuid bardais Eorpacha",
  author:   "Údar an leabhráin: Marek Mráz",
)


// ════════════════════════════════════════════════════════════════════════════
//  WHY THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("why")[
  #band("Cén fáth an leabhrán seo")

  #lead("Gach bliain, ceannaíonn cathracha bogearraí: córais pháirceála, ardáin braiteoirí, tairseacha léarscáile, cúplaí digiteacha. Go rómhinic, bíonn na sonraí a bhailíonn na córais sin faoi ghlas iontu féin. Nuair a thagann deireadh leis an gconradh, imíonn na sonraí — ar íocadh as le hairgead poiblí — leis an soláthraí, nó fágtar i bhformáid nach féidir le haon duine eile a léamh.")

  #lead("Ní gá go mbeadh sé mar seo. Déanann na Meicníochtaí Idir-inoibritheachta Íosta (MIMs), atá á gcothabháil ag Open & Agile Smart Cities (OASC) agus formhuinithe tríd an ngluaiseacht Eorpach living-in.eu, cur síos ar na híoscheanglais theicniúla a choimeádann do chuid sonraí oscailte, ath-inúsáidte agus neodrach ó thaobh díoltóra de. Tá siad d'aon ghnó beag: ní ailtireacht mhór atá iontu, ach na fíorbheagán rudaí nach mór a bheith fíor ionas gur féidir le córais caint le chéile.")

  #lead("Ní gá duit a bheith i d'innealtóir chun iad a úsáid. Déanann gach seicliosta míreanna seicliosta i ngnáthfhocail de cheann amháin de na MIMs ar féidir leat a chóipeáil isteach i dtairiscint, mar aon leis an gcúis a gcosnaíonn gach ceann díobh thú. Díreach i ndiaidh an tseicliosta aimsíonn tú gach ceanglas de chuid an MIM sin, focal ar fhocal, ionas gur féidir le do chomhghleacaithe teicniúla agus le do thairgeoirí na sonraí a sheiceáil.")

  #lead("Cathracha a éilíonn na MIMs, ceannaíonn siad uair amháin agus athúsáideann siad go minic: cothaíonn sonraí cháilíocht an aeir deais na scoile, cothaíonn fardal na soilse sráide an plean fuinnimh, agus tosaíonn an chéad soláthraí eile san áit ar fhág an soláthraí deiridh as. Sin a chiallaíonn idir-inoibritheacht go praiticiúil — agus táthar ag súil leis níos mó ná riamh i dtionscadail arna maoiniú ag an AE.")

  #pull-quote(
    "Cumasaíonn na meicníochtaí idir-inoibritheachta íosta (MIMs) leibhéal íosta ach leordhóthanach idir-inoibritheachta do shonraí, do chórais agus do sheirbhísí go sonrach i gcomhthéacs réiteach cathrach cliste. · Is iad an lucht féachana beartaithe don doiciméad seo: · 1. Soláthraithe réiteach ar mian leo a chinntiú go bhfuil a gcuid réiteach idir-inoibritheach le réitigh eile agus go gceadaíonn siad malartú sreabhach sonraí laistigh de chomhthéacs Cathracha agus Pobail Chliste. · 2. Soláthróirí ar mian leo réitigh a sholáthar a bheidh oiriúnach don todhchaí agus a cheadaíonn comhtháthú cost-éifeachtach laistigh d'ailtireacht Theicneolaíocht na Faisnéise agus na Cumarsáide (TFC) atá ann cheana do Chathracha agus Pobail Chliste.",
  )

  #policy-box("Conas a luíonn na MIMs le dlí an AE",
    "Is sonraíocht theicniúil iad na MIMs, ní dlí. Díríonn siad sa treo céanna le rialacha an AE a bhaineann cheana féin le sonraí poiblí agus seirbhísí digiteacha:",
    law("Treoir maidir le Soláthar Poiblí", "Treoir 2014/24/AE, Airteagal 42",
      "féadfaidh sonraíochtaí teicniúla tagairt do chaighdeáin, i gcónaí le “nó a chomhionann”; mar riail ghinearálta ní fhéadfaidh siad déanamh ná táirge ar leith a ainmniú."),
    law("An Gníomh Sonraí", "Rialachán (AE) 2023/2854",
      "rochtain ar shonraí ó tháirgí nasctha, agus aistriú idir soláthraithe néil gan glasáil isteach."),
    law("An Gníomh um Eoraip Idir-inoibritheach", "Rialachán (AE) 2024/903",
      "measúnuithe idir-inoibritheachta do sheirbhísí poiblí digiteacha trasteorann, agus athúsáid réiteach oscailte."),
    law("An Treoir maidir le Sonraí Oscailte", "Treoir (AE) 2019/1024",
      "tacair shonraí ardluacha arna bhfoilsiú saor in aisce, meaisín-inléite, trí APIanna."),
    law("Treoir NIS2", "Treoir (AE) 2022/2555",
      "buntreoir chibearshlándála; cinneann an dlí náisiúnta cé chomh fada a chlúdaíonn sí an riarachán áitiúil."),
    law("RGCS", "Rialachán (AE) 2016/679",
      "sonraí pearsanta i gcórais chathrach (páirceáil, ceamaraí, soghluaisteacht)."),
    law("An Gníomh um Intleacht Shaorga", "Rialachán (AE) 2024/1689",
      "rialacha do chórais intleachta saorga; ábhartha do mhúnlaí IS i gcúplaí digiteacha."),
    note: "Mar threoir amháin. Seiceáil conas a thrasuíodh gach gníomh i do thír féin.",
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  HOW TO USE THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("howto")[
  #band("Conas an leabhrán seo a úsáid")

  #steps(
    step("Ullmhaigh",
      "Léigh na seacht seicliosta. Cuir tic leis na cinn a bhaineann leis an méid atá á cheannach agat. Teastaíonn MIM0, MIM1, MIM2 agus MIM6 ó fhormhór na dtairiscintí; cuir MIM3 leis nuair a roinntear sonraí le tríú páirtithe nó trí thairseach sonraí, MIM7 d'aon rud a bhfuil léarscáil aige, MIM8 do chúplaí digiteacha."),
    step("Tairg",
      "Cóipeáil na míreanna seicliosta a bhfuil tic curtha leo isteach i do cheanglais. Tá gach mír scríofa mar abairt is féidir leat a ghreamú. Cuir na clásail thrasghearrtha leis: is beag a chosnaíonn siad agus seachnaíonn siad glasáil isteach.",
      links: (("clauses", "Clásail"), ("example", "Sampla"), )),
    step("Déan meastóireacht",
      "Iarr ar thairgeoirí a léiriú, seachas a ghealladh (féach an clásal faoin ainm sin). Fíoraigh comhlíonadh i gcoinne an tábla comhlíonta a líon an tairgeoir.",
      links: (("table", "Tábla comhlíonta"), )),
    step("Seachad",
      "Ag am an ghlactha, atástáil gach mír a chuir tú tic léi. Ceanglas nach ndéantar a thástáil ag am an tseachadta, ní raibh sé ina cheanglas riamh i ndáiríre.",
      links: (("table", "Tábla comhlíonta"), )),
  )

  #legend("Na luachana sonraíochta a léamh",
    note: "Deir na míreanna seicliosta “ní mór” fiú nuair nach ndéanann an tsonraíocht ach moladh (ba chóir) nó nuair a liostaíonn sí meicníocht is iarrthóir. Sin cinneadh an údaráis chonarthaigh.",
    entry("NÍ MÓR (SHALL / MUST)", "éigeantach. Ní chomhlíonann an córas gan é."),
    entry("NÍ CEADMHACH (MUST NOT)", "toirmiscthe. Córas a dhéanann é, ní chomhlíonann sé."),
    entry("BA CHÓIR (SHOULD)", "molta go láidir. Teastaíonn cúis mhaith scríofa le diallais."),
    entry("FÉADFAIDH (MAY)", "roghnach. Deas a bheith ann, ní theastaíonn sé riamh."),
    entry("IS FÉIDIR (CAN)", "féidearthacht, ní ceanglas. Deir sé cad is féidir agus ní chuireann sé d'oibleagáid ar dhuine ar bith."),
  )

  #note("Tá tagairt bheag ar gach mír seicliosta ar nós → MIM0 R1.1. Sin an ceanglas i MIMs Plus 9.0 óna dtagann sé; díreach i ndiaidh an tseicliosta aimsíonn tú gach ceanglas de chuid an MIM sin focal ar fhocal. Ní shainíonn ach MIM0 na heochairfhocail: tá tábhacht leo nuair a scríobhtar i litreacha móra iad, coinbhinsiún IETF RFC 2119 agus RFC 8174 (tagann IS FÉIDIR (CAN) ó Threoracha ISO/IEC, Cuid 2). Níl aon sainmhíniú ag na MIMs eile: scríobhann MIM6 SHALL i litreacha móra den chuid is mó, scríobhann MIM2, MIM3, MIM7 agus MIM8 shall, should agus must i gcás íochtair, agus ní úsáideann MIM1 iad ach i gcur síos ar mheicníocht (MUST NOT i rannán 3.1). Léann an leabhrán seo na focail cháis íochtair ar an mbealach céanna; féadfaidh tairgeoir iad a léamh ar bhealach níos scaoilte.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  THE SEVEN MIMs AT A GLANCE
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glance")[
  #band("Seacht MIM agus trí uirlis", id: "glance")

  #intro("Seacht meicníocht bheaga, sprioc amháin: fanann do chuid sonraí agat féin, agus is féidir le do chórais caint le chéile.")

  #glance(
    note: "Maidir leis an uimhriú: sonraíonn MIMs Plus 9.0 seacht meicníocht, uimhrithe 0, 1, 2, 3, 6, 7 agus 8. Baineann MIM4 (sonraí pearsanta) agus MIM5 (IS chóir) le leaganacha níos luaithe de chuid OASC agus ní cuid de 9.0 iad. Níl aon rud ar iarraidh ón leabhrán seo.",
    card("MIM0", "Rochtain ar Shonraí",
      "An féidir linn ár gcuid sonraí a fháil amach?",
      "Is féidir sonraí a aisghabháil trí APIanna caighdeánacha gréasáin, i bhformáidí meaisín-inléite.",
      "https://mims.oascities.org/accessing-data"),
    card("MIM1", "Idirnascadh Sonraí",
      "An bhfuil ainm buan ar gach rud?",
      "Tá aitheantóir uathúil buan ag gach braiteoir, lampa agus foirgneamh.",
      "https://mims.oascities.org/interlinking-data"),
    card("MIM2", "Léiriú Sonraí",
      "An labhraímid teanga choiteann?",
      "Leanann sonraí samhlacha sonraí caighdeánacha doiciméadaithe le haonaid shainráite.",
      "https://mims.oascities.org/representing-data"),
    card("MIM3", "Malartú Sonraí",
      "An féidir linn comhroinnt faoi théarmaí soiléire?",
      "Déantar tacair shonraí a chatalógú agus a roinnt faoi theimpléid ceadúnais agus faoi rialachas soiléir.",
      "https://mims.oascities.org/exchanging-data"),
    card("MIM6", "Slánú Sonraí",
      "An bhfuil ár gcuid sonraí sábháilte?",
      "Aistriú criptithe, logálacha isteach caighdeánacha, rochtain rólbhunaithe, logaí iniúchta.",
      "https://mims.oascities.org/securing-data"),
    card("MIM7", "Sonraí Geospásúla",
      "An oibríonn sé ar léarscáil?",
      "Úsáideann sonraí spásúla comhéadain OGC, formáidí oscailte agus córais chomhordanáidí dearbhaithe.",
      "https://mims.oascities.org/geospatial-data"),
    card("MIM8", "Cúplaí Digiteacha Áitiúla",
      "An féidir lenár gcúpla digiteach fás?",
      "Fanann sonraí, samhlacha agus torthaí an chúpla inrochtana, doiciméadaithe agus ath-inúsáidte.",
      "https://mims.oascities.org/local-digital-twins"),
  )

  #tools("Uirlisí do do thairiscint",
    tool("clauses", "Clásail thrasghearrtha tairisceana",
      "Cad a bhaineann le gach conradh?",
      "Scoir, cearta sonraí, cobhsaíocht API."),
    tool("example", "Sampla: braiteoirí cháilíocht an aeir",
      "Cén chuma atá air go praiticiúil?",
      "Cad a théann cén áit, agus téacs samplach le greamú."),
    tool("table", "Tábla comhlíonta",
      "Conas a chruthaíonn an tairgeoir é?",
      "Líonta ag an tairgeoir, fíoraithe ag an gcoiste, i gceangal leis an gconradh."),
  )

  #menu-line(("glossary", "Gluais bheag"), ("more", "Cá bhfaighfear tuilleadh eolais"))
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 checklist")[
  #mim-page(
    id:       "MIM0",
    name:     "Rochtain ar Shonraí",
    question: "An féidir linn ár gcuid sonraí a fháil amach?",
    url:      "https://mims.oascities.org/accessing-data",
    intro:    "Seo an bhunchloch. Mura féidir le sonraí an córas a fhágáil trí chomhéadan caighdeánach, níl i ngach rud eile sa leabhrán seo ach teoiric. Iarrann MIM0 rud amháin ar gach córas a cheannaíonn tú: ní mór na sonraí a bheith inrochtana, i bhfoirm is féidir le meaisíní a léamh, tríd an ngnáthghréasán.",
    list:     "Seicliosta",
  )

  #item("Is féidir na sonraí go léir a bhailíonn nó a tháirgeann an córas a aisghabháil i bhformáid mheaisín-inléite amháin ar a laghad (m.sh. JSON, CSV) thar API caighdeánach gréasáin.",
    why:  "Féadfaidh do chéad chonraitheoir eile — nó d'fhoireann féin — na sonraí a úsáid gan cead a iarraidh ar an díoltóir.",
    refs: "MIM0 R1.1, R1.2",
    num:  "0.1")

  #item("Déantar cur síos foirmiúil ar an API i ndoiciméad oscailte meaisín-inléite (mar shampla OpenAPI) a fhoilsítear ag seoladh cobhsaí.",
    why:  "Is féidir le haon fhorbróir ceangal a dhéanamh gan “ceardlann chomhtháthaithe” le pá a íoc as.",
    refs: "MIM0 R1.3",
    num:  "0.2")

  #item("Is féidir sonraí a scagadh de réir ama, suímh agus tréithe go díreach san API.",
    why:  "Faigheann tú a bhfuil uait, ní dumpáil iomlán gach oíche.",
    refs: "MIM0 R2.1, R2.2",
    num:  "0.3")

  #item("Nuair a bhíonn gá le sonraí beo don chás úsáide, féadfaidh tomhaltóirí liostáil d'athruithe (crúcaí gréasáin, MQTT nó a leithéid) in ionad vótaíochta leanúnaí.",
    why:  "Bíonn deaisanna agus foláirimh fíor-ama indéanta agus saor.",
    refs: "MIM0 R3.1",
    num:  "0.4")

  #item("Úsáideann earráidí, taisceadh agus teorainneacha ráta gnáthchoinbhinsiúin HTTP agus tá siad doiciméadaithe.",
    why:  "Teipeann ar chomhtháthuithe go feiceálach agus go h-inréitithe, ní go ciúin.",
    refs: "MIM0 C2",
    num:  "0.5")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Fanann sonraí ar íoc tú astu inúsáidte tar éis don chonradh dul in éag.",
      "Tógann seirbhísí nua ar shean-sonraí in ionad tosú ón tús.",
      "Titeann costais chomhtháthaithe do gach tionscadal a leanann.",
    )),
    flags: ("Bratacha dearga", (
      "“Easpórtáil sonraí ar iarraidh tríár bhfoireann tacaíochta.”",
      "“Tá an API ar fáil mar mhodúl breiseán ar leith le híoc as.”",
      "Praghsáil in aghaidh an iarratais ar shonraí na cathrach féin (féach an clásal “Gan aon táillí in aghaidh an tsuíocháin / an iarratais”).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM0",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM0",
    capability("C1", "Machine-readable data is retrievable through the web",
      tr: "Tá sonraí meaisín-inléite in-aisghabhála tríd an ngréasán"),
    req("R1.1",
      tr: "NÍ MÓR do chórais aisghabháil sonraí a cheadú i bhformáid mheaisín-inléite amháin ar a laghad. Is féidir formáidí a shonrú trí Idirbheartaíocht Ábhair HTTP",
      en: "Systems SHALL allow retrieval of data in at least one machine-readable format. Formats can be specified through HTTP Content-Negotiation"),
    req("R1.2",
      tr: "NÍ MÓR sonraí a bheith in-aisghabhála trí mheicníocht ghréasánbhunaithe chaighdeánach amháin ar a laghad",
      en: "Data SHALL be retrievable via at least one standard web-based mechanism"),
    req("R1.3",
      tr: "NÍ MÓR cur síos foirmiúil a dhéanamh ar mheicníocht(aí) rochtana",
      en: "Access mechanism(s) SHALL be formally described"),
    req("R1.4",
      tr: "Ba chóir na Samhlacha Sonraí a úsáideann pálastaí a shonrú (féach MIM2)",
      en: "Data Models used by payloads should be specified (see MIM2)"),
    capability("C2", "Access is structured and queryable",
      tr: "Tá rochtain struchtúrtha agus incheistithe"),
    req("R2.1",
      tr: "NÍ MÓR do chórais sonraí a sholáthar trí chomhéadan struchtúrtha comhsheasmhach",
      en: "Systems SHALL provide data through a structured and consistent interface"),
    req("R2.2",
      tr: "NÍ MÓR do chórais tacú le buncheistiú agus/nó le bunscagadh (m.sh. de réir ama, suímh, tréithe)",
      en: "Systems SHALL support basic querying and/or filtering (e.g. by time, location, attributes)"),
    capability("C2 best practice", "Additional best practice to consider:",
      tr: "Dea-chleachtas breise le breithniú:", sub: true),
    req("C2",
      tr: "BA CHÓIR do APIanna tacú le haisghabháil sonraí reatha · BA CHÓIR do APIanna tacú le haisghabháil sonraí stairiúla nuair is infheidhme · BA CHÓIR do APIanna tacú le ceistiú geospásúil nuair is infheidhme (féach MIM7) · BA CHÓIR do APIanna tacú le síntiús d'athruithe nuair is infheidhme · BA CHÓIR do APIanna an chéad stampa ama nuashonraithe eile a bhfuiltear ag súil leis a nochtadh · BA CHÓIR do APIanna tacú le leaganú sainráite ar phointí foirceanta · BA CHÓIR do APIanna samplaí de phálastaí nó de cheisteanna tástála a sholáthar · BA CHÓIR do APIanna tacú le ceanntásca taisceála caighdeánacha HTTP · BA CHÓIR do APIanna stádas teorann ráta a chur in iúl trí cheanntásca caighdeánacha HTTP · BA CHÓIR do APIanna comhlachtaí struchtúrtha earráide a thabhairt ar ais · FÉADFAIDH APIanna tacú le freagraí páirteacha nó le réamh-mheastacháin cheisteanna · FÉADFAIDH APIanna pointe foirceanta sláinte/stádais caighdeánach a nochtadh",
      en: "APIs SHOULD support retrieval of current data · APIs SHOULD support retrieval of historical data when applicable · APIs SHOULD support geospatial querying when applicable (see MIM7) · APIs SHOULD support subscription to changes when applicable · APIs SHOULD expose next expected update timestamp · APIs SHOULD support explicit versioning of endpoints · APIs SHOULD provide example payloads or test queries · APIs SHOULD support standard HTTP caching headers · APIs SHOULD communicate rate limit status via standard HTTP headers · APIs SHOULD return structured error bodies · APIs MAY support partial responses or query projections · APIs MAY expose a standard health/status endpoint"),
    capability("C3", "Changes in data can be subscribed to",
      tr: "Is féidir liostáil d'athruithe ar shonraí"),
    req("R3.1",
      tr: "NÍ MÓR do chórais do chásanna úsáide a dteastaíonn fógraí uathu meicníocht amháin ar a laghad a sholáthar chun nuashonruithe a fháil ar athruithe sonraí",
      en: "Systems for use cases that require notifications SHALL provide at least one mechanism to receive updates on data changes"),
    req("R3.2",
      tr: "FÉADFAIDH córais tacú le meicníochtaí iolracha síntiúis ag brath ar an gcás úsáide",
      en: "Systems MAY support multiple subscription mechanisms depending on use case"),
    capability("C4", "Access to information can be restricted",
      tr: "Is féidir srian a chur le rochtain ar fhaisnéis"),
    req("C4",
      tr: "Má tá srianta den sórt sin i bhfeidhm, NÍ MÓR dóibh na ceanglais a shainítear i MIM3 agus MIM6 a leanúint, go sonrach: sainaithint gníomhaí (MIM3.C5.R0), údarú agus róil ghníomhaithe (MIM6.C1.R4), beartais ar leibhéal sócmhainní sonraí (MIM6.C1.R4)",
      en: "If such restrictions are in place, they SHALL follow the requirements defined in MIM3 and MIM6, specifically: actor identification (MIM3.C5.R0), authorization and actor roles (MIM6.C1.R4), data asset-level policies (MIM6.C1.R4)"),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/accessing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 checklist")[
  #mim-page(
    id:       "MIM1",
    name:     "Idirnascadh Sonraí",
    question: "An bhfuil ainm buan ar gach rud?",
    url:      "https://mims.oascities.org/interlinking-data",
    intro:    "Tá cathair lán de rudaí: lampaí, píopaí, foirgnimh, spásanna páirceála. Tagann córais agus imíonn siad, ach fanann na rudaí. Éilíonn MIM1 go bhfaigheann gach rud ainm — aitheantóir — a mhaireann níos faide ná na bogearraí a thaifead ar dtús é, ionas go maireann a stair agus a naisc le sonraí eile tar éis gach imirce.",
    list:     "Seicliosta",
  )

  #item("Tá aitheantóir uathúil buan ag gach eintiteas (braiteoir, lampa, foirgneamh, spás páirceála…) nach n-athraíonn nuair a chuirtear bogearraí nua ina n-áit.",
    why:  "Maireann an stair agus naisc thar chórais tar éis an tsoláthraí.",
    refs: "MIM1 R1.1, R1.5",
    num:  "1.1")

  #item("Is féidir an t-aitheantóir a chuardach chun sonraí an eintitis agus a bhrí (cineál) a aisghabháil ar bhealach meaisín-inléite.",
    why:  "Féadfaidh córais eile an nasc a leanúint go huathoibríoch.",
    refs: "MIM1 R1.2, R2.1, R2.2",
    num:  "1.2")

  #item("Nuair a bhíonn an rud fíorsaoil céanna i láthair i roinnt córas, is féidir aitheantóirí a mhapáil ar a chéile.",
    why:  "Is féidir a chruthú gurb é foirgneamh an GIS agus foirgneamh an chórais fuinnimh an foirgneamh céanna go díreach.",
    refs: "MIM1 R1.3, R1.4",
    num:  "1.3")

  #item("Ní chuimsíonn aitheantóirí mionsonraí inmheánacha an díoltóra (IDanna sraithe bunachair sonraí, ainmneacha freastalaí).",
    why:  "Seachas sin faigheann na hIDanna bás leis an gconradh.",
    refs: "MIM1 M1 §3.1",
    num:  "1.4")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Fanann deich mbliana de thomhais ceangailte leis an bpost soilse ceart.",
      "Stopann ranna de chúig chlár contrártha den tsócmhainn chéanna a choinneáil.",
      "Bíonn nascadh tacar sonraí ina fhiosrúchán, ní ina thionscadal comhairleoireachta.",
    )),
    flags: ("Bratacha dearga", (
      "“Tá IDanna inmheánach dár n-ardán.”",
      "Déantar aitheantóirí a athghiniúint ar gach imirce sonraí.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM1",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM1",
    capability("C1", "Entities are identified using unique identifiers",
      tr: "Sainaithnítear eintitis ag baint úsáide as aitheantóirí uathúla"),
    req("R1.1",
      tr: "Tá aitheantóir uathúil ag gach eintiteas laistigh den chóras",
      en: "Every entity within the system has a unique identifier"),
    req("R1.2",
      tr: "Tá bealach ann chun faisnéis faoi eintiteas a aisghabháil tríd an aitheantóir a chuardach laistigh de chóras",
      en: "There exists a way to retrieve information about an entity by looking up the identifier within a system"),
    req("R1.3",
      tr: "má thagraíonn aitheantóir uathúil don eintiteas céanna laistigh de chórais iolracha, is féidir an bealach a dhíorthú chun faisnéis faoi a chuardach i ngach ceann de na córais sin",
      en: "if a unique identifier points to the same entity within multiple systems, it is possible to derive the way to look up information about it in each of these systems"),
    req("R1.4",
      tr: "má thagraíonn aitheantóirí uathúla iolracha don eintiteas céanna, is féidir iad a mhapáil",
      en: "if a multiple [sic] unique identifiers point to the same entity, it is possible to map them"),
    req("R1.5",
      tr: "Is féidir aitheantóirí atá buan le himeacht ama a chruthú",
      en: "It is possible to create identifiers that are persistent over time"),
    capability("C2", "Entities can be typed",
      tr: "Is féidir eintitis a chineálú"),
    req("R2.1",
      tr: "Tá bealach ann chun shéimeantaic eintitis a aisghabháil, ag baint úsáide as a aitheantóir uathúil amháin",
      en: "There is a way to retreive [sic] the semantics of an entity, only using its unique identifier"),
    req("R2.2",
      tr: "Déantar cur síos ar an séimeantaic seo i bhformáid mheaisín-inléite",
      en: "These semantics are described in a machine-readable format"),
    capability("C3", "Entities can be (de)referenced",
      tr: "Is féidir eintitis a (dhí)thagairt"),
    req("R3.1",
      tr: "Tá bealach ann chun díthagairt a dhéanamh do ghaol atá sainithe ar eintiteas",
      en: "There exists a way to dereference a relation defined on an entity"),
    req("R3.2",
      tr: "Tá bealach ann chun séimeantaic bhreise a chur i bhfeidhm ar oineolaíocht atá ann cheana",
      en: "There exists a way to apply additional semantics to an existing ontology"),
    capability("M1", "Mechanism 1, section 3.1: Entity Identification with Globally Unique IRIs",
      tr: "Meicníocht 1, rannán 3.1: Sainaithint Eintitis le hIRIanna atá Uathúil go Domhanda"),
    req("§3.1",
      tr: "Caitear leis an IRI mar an t-aitheantóir canónta i ngach córas iartheachtach; NÍ CEADMHACH do chur i bhfeidhm IRIanna a ghiniúint a chuimsíonn sonraí cur i bhfeidhm luaineacha amhail IDanna sraithe bunachair sonraí nó óstainmneacha freastalaí.",
      en: "The IRI is treated as the canonical identifier in all downstream systems; implementations MUST NOT generate IRIs that embed volatile implementation details such as database row IDs or server hostnames."),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/interlinking-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 checklist")[
  #mim-page(
    id:       "MIM2",
    name:     "Léiriú Sonraí",
    question: "An labhraímid teanga choiteann?",
    url:      "https://mims.oascities.org/representing-data",
    intro:    "Is féidir le dhá chóras JSON a easpórtáil agus gan tuiscint a bheith acu ar a chéile fós. Baineann MIM2 le brí: úsáid a bhaint as samhlacha sonraí comhroinnte doiciméadaithe — le haonaid agus formáidí sainráite — ionas go gciallaíonn “teocht”, “spás páirceála” nó “cáilíocht an aeir” an rud céanna i ngach córas atá agat.",
    list:     "Seicliosta",
  )

  #item("Úsáideann sonraí samhlacha sonraí caighdeánacha a aithnítear go coitianta cibé áit a bhfuil siad ann (m.sh. Smart Data Models, SAREF, ISO/IEC 5087); tá údar scríofa le diallais.",
    why:  "Cumascann sonraí ó dhá sholáthraí gan tionscadal aistriúcháin.",
    refs: "MIM2 R1.2a",
    num:  "2.1")

  #item("Déantar gach samhail sonraí atá in úsáid a dhoiciméadú go sainráite, agus aonaid tomhais agus formáidí dáta/ama luaite.",
    why:  "Níl aon mhaith le “Teocht: 23” mura scríobh aon duine síos °C i gcoinne °F.",
    refs: "MIM2 R1.1",
    num:  "2.2")

  #item("Seachadtar síntí mar phróifílí/breiseanna doiciméadaithe ar bharr an tsamhail chaighdeánaigh — riamh mar ghabhal príobháideach modhnaithe.",
    why:  "Fanann tú comhoiriúnach leis an bpobal agus le nuashonruithe amach anseo.",
    refs: "MIM2 R1.2b, R4.1, R4.2",
    num:  "2.3")

  #item("Tá srathú oscailte amháin ar a laghad ag gach samhail is féidir a bhailíochtú de réir scéime (m.sh. JSON le JSON Schema).",
    why:  "Is féidir sonraí atá ag teacht isteach a sheiceáil go huathoibríoch ag an doras.",
    refs: "MIM2 R3.1, R3.4",
    num:  "2.4")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Léann deais amháin sonraí ó go leor soláthraithe gan oiriúnóirí.",
      "Tuigeann uirlisí cathracha eile do chuid sonraí — agus tuigeann do chuid uirlisí a gcuid sonraí siúd.",
      "Gabhann bailíochtú uathoibríoch sonraí briste sula leathnaíonn siad.",
    )),
    flags: ("Bratacha dearga", (
      "“Tá ár samhail sonraí dílseánaigh níos saibhre ná an caighdeán.”",
      "Doiciméadú ar fáil faoi chomhaontú neamhnochtana (NDA) amháin.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM2",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM2",
    capability("C1", "All entities included in data sources are described using consistent data models to enable interoperability for applications and systems",
      tr: "Déantar cur síos ar gach eintiteas a áirítear i bhfoinsí sonraí ag baint úsáide as samhlacha comhsheasmhacha sonraí chun idir-inoibritheacht a chumasú d'fheidhmchláir agus do chórais"),
    req("R1.1",
      tr: "déanfar samhlacha sonraí a úsáidtear do gach eintiteas in aon fhoinse sonraí a chur in iúl go sainráite. Beidh siad doiciméadaithe go maith agus beidh meiteashonraí tuairisciúla acu, áit a mbeidh na téarmaí a úsáidtear neamh-dhébhríoch ó thaobh séimeantaice de. Maidir le tréithe a bhaineann le haonaid tomhais, formáidí ama srl., déanfar na haonaid, na formáidí srl., a úsáidtear a chur in iúl go sainráite. Ba chóir na samhlacha sonraí a chatalógú ionas gur féidir iad a fháil go héasca.",
      en: "Data models used for all entities in any data source shall be made explicit. They shall be well documented and have descriptive metadata, where the terms used shall be semantically unambiguous. For attributes related to units of measurement, time formats etc, the units, formats etc, used shall be made explicit. The data models should be catalogued so that they can be easily findable."),
    req("R1.2a",
      tr: "beidh samhlacha sonraí a úsáidtear bunaithe (nuair is féidir) ar shamhlacha sonraí caighdeánaithe a aithnítear go coitianta mar a liostaítear thíos",
      en: "Data models used shall be based (wherever possible) on commonly recognised standardised data models as listed below"),
    req("R1.2b",
      tr: "Nuair nach féidir samhlacha sonraí caighdeánaithe atá ann cheana a úsáid, déanfar iarrachtaí chun samhlacha sonraí caighdeánaithe atá ann cheana agus is dlúithe atá ailínithe a leathnú nó cinn nua a shainiú, de réir an dea-chleachtais agus choinbhinsiúin an phobail nó na heagraíochta a shainíonn na samhlacha sonraí.",
      en: "Where it is not possible to use existing standardised data models, efforts shall be made to extend existing standardised data models that are most closely aligned or to define new ones, following best practice and conventions of the community or organisation defining the data models."),
    req("R1.3",
      tr: "tacóidh samhlacha sonraí a úsáidtear le malartú sonraí trí úsáid a bhaint as ceanglais ábhartha na MIMs maidir le Rochtain ar shonraí agus Idirnascadh sonraí",
      en: "Data models used shall support the exchange of data by using the relevant requirements of the MIMs on Accessing data and Interlinking data"),
    capability("C2", "Different data models for the same entity that are used within a common data sharing ecosystem should be easily transformable into a common data model",
      tr: "Ba chóir go mbeadh samhlacha sonraí éagsúla don eintiteas céanna a úsáidtear laistigh d'éiceachóras coiteann comhroinnte sonraí in-chlaochlaithe go héasca go samhail choiteann sonraí"),
    req("R2.1",
      tr: "Ba chóir samhail choiteann sonraí do gach príomh-eintiteas a fhorbairt d'aon éiceachóras sonraí. Ba chóir go mbeadh na réimsí uile a áirítear laistigh de na samhlacha sonraí éagsúla don eintiteas sin a úsáidtear laistigh den éiceachóras sonraí sin sa tsamhail sonraí choiteann sin. D'fhéadfaí gach samhail sonraí éagsúil a úsáidtear laistigh den éiceachóras sonraí sin a chlaochlú ansin go dtí an tsamhail sonraí choiteann.",
      en: "A common data model for each key entity should be developed for any data ecosystem. That common data model should contain all the fields included within the different data models for that entity that are used within that data ecosystem. Each different data model used within that data ecosystem could then be transformed into the common data model."),
    capability("C3", "Any data and its associated metadata can be shared in open, standardised, data transport formats so that data can be exchanged and interpreted consistently by different tools and implementations",
      tr: "Is féidir aon sonraí agus a meiteashonraí gaolmhara a roinnt i bhformáidí oscailte, caighdeánaithe, iompair sonraí ionas gur féidir sonraí a mhalartú agus a léirmhíniú go comhsheasmhach ag uirlisí agus feidhmithe éagsúla"),
    req("R3.1",
      tr: "beidh formáid iompair sonraí mheaisín-inléite shainithe amháin ar a laghad (“srathú”) ag gach samhail sonraí a úsáidtear atá oscailte, ar fáil go poiblí agus neamhspleách ar chur i bhfeidhm.",
      en: "Each data model used shall have at least one defined machine-readable data transport format (“serialisation”) that is open, publicly available and implementation-independent."),
    req("R3.2",
      tr: "Ba chóir go mbeadh doiciméadú na formáide iompair sonraí leordhóthanach chun go bhféadfaí feidhmchlár nó ateangaire neamhdhílseánach a chruthú atá in ann na sonraí go léir atá stóráilte i bhformáid sonraí den sórt sin a athchruthú.",
      en: "The documentation of the data transport format should be sufficient to allow the creation of non-proprietary application or interpretor that is able to reconstruct all the data stored in such a data format."),
    req("R3.3",
      tr: "Nuair a thacaítear le formáidí iompair sonraí iolracha don tsamhail sonraí chéanna, léireoidh siad an t-ábhar faisnéise céanna go comhsheasmhach agus gan cailleadh brí.",
      en: "Where multiple data transport formats are supported for the same data model, they shall represent the same information content consistently and without loss of meaning."),
    req("R3.4",
      tr: "Ba chóir go dtacódh an léiriú le bailíochtú ag baint úsáide as scéimeanna, gramadaí, nó srianta coibhéiseacha meaisín-inléite a fhoilsítear go hoscailte, nuair atá meicníochtaí bailíochtaithe den sórt sin ann don fhormáid roghnaithe.",
      en: "The representation should support validation using openly published schemas, grammars, or equivalent machine-readable constraints, where such validation mechanisms exist for the chosen format."),
    capability("C4", "When useful, it should be possible to create \"Application Profiles\" for a data model, so that use case specific attributes can be added or specified without changing the underlying data model",
      tr: "Nuair is úsáideach, ba chóir go mbeadh sé indéanta \"Próifílí Feidhmchláir\" a chruthú do shamhail sonraí, ionas gur féidir tréithe a bhaineann go sonrach le cás úsáide a chur leis nó a shonrú gan an bhunshamhail sonraí a athrú"),
    req("R4.1",
      tr: "Níor cheart go ndéanfadh Próifílí Feidhmchláir a leathnaíonn samhail sonraí difear don tsamhail atá ann cheana féin agus dá húsáideoirí",
      en: "Application Profiles that extend a data model should not impact the already existing model and its users"),
    req("R4.2",
      tr: "Ba chóir na speisialtachtaí nó na síntí a thugtar isteach i bPróifíl Feidhmchláir na samhla a dhoiciméadú go maith, ar leithligh ón mbunshamhail sonraí",
      en: "The specialisations or extensions introduced in the Application Profile of the model should be well documented, separate from the base data model"),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/representing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 checklist")[
  #mim-page(
    id:       "MIM3",
    name:     "Malartú Sonraí",
    question: "An féidir linn comhroinnt faoi théarmaí soiléire?",
    url:      "https://mims.oascities.org/exchanging-data",
    intro:    "Ní féidir sonraí uile na cathrach a fhoilsiú go simplí: tá cuid acu tráchtála, cuid acu íogair. Baineann MIM3 leis an gcuid eile a roinnt ar aon nós, go sábháilte: catalóg ar féidir le daoine a chuardach, ceadúnais ó theimpléid in ionad téarmaíocht dhlíthiúil shaincheaptha, agus rialacha rialachais ar féidir le gach duine a léamh. Deir an tsonraíocht beagnach gach cuid de MIM3 mar mholadh (féach lch. 3).",
    list:     "Seicliosta",
  )

  #item("Déantar cur síos ar gach tacar sonraí a thairgeann an córas le meiteashonraí caighdeánacha (mar shampla DCAT-AP) i gcatalóg, ionas gur féidir le daoine eile é a aimsiú.",
    why:  "Sonraí nach féidir le haon duine a aimsiú, ní úsáideann aon duine iad.",
    refs: "MIM3 RC4.1–RC4.3",
    num:  "3.1")

  #item("Tagann téarmaí agus ceadúnais d'úsáid sonraí ó theimpléid aitheanta (m.sh. ceadúnais oscailte, gnáth-chomhaontuithe comhroinnte sonraí), ní ó théarmaíocht dhlíthiúil shaincheaptha in aghaidh an tacair sonraí.",
    why:  "Bíonn comhaontuithe inscálaithe; ní bhíonn dlíodóirí ina mbacainn.",
    refs: "MIM3 RC2.2, RC2.3",
    num:  "3.2")

  #item("Féadfaidh an chathair a shainiú cé a fhéadfaidh teacht ar cén tsócmhainn sonraí agus faoi cad iad na coinníollacha, agus é sin a athrú gan rannpháirtíocht an díoltóra.",
    why:  "Fanann an rialachas ag an mbardas.",
    refs: "MIM3 RC1.1, RC2.1",
    num:  "3.3")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Tógann cuideachtaí áitiúla agus taighdeoirí ar shonraí cathrach — fanann luach sa réigiún.",
      "Is féidir sonraí íogaire a roinnt go díreach leis na comhpháirtithe cearta, ní le gach duine ná le héinne.",
      "Tagann leabhar rialacha amháin in ionad go leor conarthaí aonair comhroinnte sonraí.",
    )),
    flags: ("Bratacha dearga", (
      "Maíonn an díoltóir cearta ar shonraí na cathrach (féach an clásal “Úinéireacht sonraí”).",
      "Teastaíonn toiliú an díoltóra nó táillí chun roinnt le tríú páirtí.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM3",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM3",
    capability("C1", "Governance rules for the data sharing ecosystem can be defined",
      tr: "Is féidir rialacha rialachais don éiceachóras comhroinnte sonraí a shainiú"),
    req("RC1.1",
      tr: "Ba chóir go mbeadh stiúrthóir éiceachórais sonraí in ann samhail rialachais a shainiú (m.sh. leabhar rialacha) a leagann amach rialacha ballraíochta, róil, freagrachtaí agus oibleagáidí rannpháirtithe an éiceachórais, agus na prionsabail fhoriomlána a rialaíonn malartú sonraí eatarthu.",
      en: "The orchestrator of a data ecosystem should be able to define a governance model (e.g. a rulebook) that outlines membership rules, the roles, responsibilities and obligations of ecosystem participants, and the overall principles that govern data exchange between them."),
    req("RC1.2",
      tr: "Ba chóir do bhaill a ghlacann páirt in éiceachóras sonraí a bheith ar an eolas faoina shamhail rialachais agus faoi aon athruithe a dhéantar uirthi.",
      en: "Members who participate in a data ecosystem should be aware of its governance model and any changes made to it."),
    req("RC1.3",
      tr: "Ba chóir go mbeadh an tsamhail rialachais intuigthe go héasca ag gach rannpháirtí san éiceachóras.",
      en: "The governance model should be easily comprehensible by all ecosystem participants."),
    capability("C2", "Terms and conditions for data sharing can be defined",
      tr: "Is féidir téarmaí agus coinníollacha maidir le comhroinnt sonraí a shainiú"),
    req("RC2.1",
      tr: "Bíonn soláthraithe sonraí saor chun téarmaí agus coinníollacha a shainiú faoinar mian leo a gcuid sonraí a mhalartú. (Nóta: Sula roinneann siad sócmhainní sonraí, ba chóir do sholáthraithe sonraí a chinntiú go bhfuil cead leordhóthanach acu ó úinéirí sonraí.)",
      en: "Data providers are free to define terms and conditions under which they want their data to be exchanged. (Note: Before sharing data assets, data providers should ensure they have adequate permission from data owners.)"),
    req("RC2.2",
      tr: "Ba chóir cur síos soiléir agus neamh-dhébhríoch a dhéanamh ar théarmaí agus ar choinníollacha do mhalartú sonraí ionas go mbeidh siad intuigthe go héasca d'úsáideoirí sonraí.",
      en: "Terms and conditions for a data exchange should be described clearly and unambiguously so that they are easily understandable for data users."),
    req("RC2.3",
      tr: "Ba chóir téarmaí agus coinníollacha do mhalartú sonraí a chur in iúl trí cheadúnais sonraí nó trí chomhaontuithe comhroinnte sonraí bunaithe ar theimpléid nó ar chaighdeáin atá sainithe go maith.",
      en: "Terms and conditions for a data exchange should be expressed through data licences or data sharing agreements based on well-defined templates or standards."),
    req("RC2.4",
      tr: "Ba chóir do théarmaí agus do choinníollacha a bheith i gcomhréir le samhail rialachais fhoriomlán an éiceachórais sonraí agus ní cead dóibh teacht salach uirthi. (Nóta: Is féidir le soláthraí sonraí cinneadh a dhéanamh gan páirt a ghlacadh in éiceachóras sonraí má tá an tsamhail rialachais bhunúsach ró-shriantach nó ró-cheadúil.)",
      en: "Terms and conditions should be in line with the overall governance model of the data ecosystem and must not conflict with it. (Note: A data provider can decide not to participate in a data ecosystem if the underlying governance model is too restrictive or too permissive.)"),
    capability("C3", "Compliance with data sharing terms and conditions can be validated",
      tr: "Is féidir comhlíonadh théarmaí agus choinníollacha comhroinnte sonraí a bhailíochtú"),
    req("RC3.1",
      tr: "Ní mór do stiúrthóir éiceachórais sonraí a bheith in ann comhlíonadh a rannpháirtithe leis an tsamhail rialachais bhunúsach a fháil amach.",
      en: "The orchestrator of a data ecosystem must be able to ascertain compliance of its participants with the underlying governance model."),
    req("RC3.2",
      tr: "Ba chóir do sholáthraithe sonraí a bheith in ann a fháil amach go gcomhlíonann úsáid sonraí ag úsáideoir sonraí téarmaí agus coinníollacha a comhaontaíodh roimhe sin.",
      en: "Data providers should be able to ascertain that the use of data by a data user complies with previously agreed-upon terms and conditions."),
    req("RC3.3",
      tr: "Ba chóir d'úsáideoirí sonraí a bheith in ann a fháil amach go leanann soláthar sonraí an tsoláthraí sonraí téarmaí agus coinníollacha a comhaontaíodh roimhe sin.",
      en: "Data users should be able to ascertain that the data provider's supply of data follows previously agreed-upon terms and conditions."),
    capability("C4", "Available data assets can be discovered",
      tr: "Is féidir sócmhainní sonraí atá ar fáil a aimsiú"),
    req("RC4.1",
      tr: "Ba chóir d'úsáideoirí sonraí a bheith in ann a fháil amach cad iad na sonraí atá ar fáil in éiceachóras comhroinnte sonraí gan eolas a bheith acu orthu roimh ré.",
      en: "Data users should be able to discover what data is available in a data sharing ecosystem without prior knowledge of it."),
    req("RC4.2",
      tr: "Ba chóir cur síos leordhóthanach a dhéanamh ar shócmhainní sonraí le meiteashonraí ionas gur féidir le húsáideoirí sonraí cinntí iontaofa a dhéanamh faoin úsáid bheartaithe bhreise a bhainfear astu.",
      en: "Data assets should be adequately described with metadata so that data users can make reliable decisions about their further intended use."),
    req("RC4.3",
      tr: "Ba chóir go mbeadh meiteashonraí a úsáidtear chun cur síos a dhéanamh ar shócmhainní sonraí bunaithe ar fhormáidí tuairiscithe dea-shainithe atá éasca le tuiscint agus atá inléite ag daoine agus ag meaisíní araon.",
      en: "Metadata used to describe data assets should be based on well-defined, easy-to-understand description formats that are both human- and machine-readable."),
    capability("C5", "Ecosystem participants can be discovered",
      tr: "Is féidir rannpháirtithe san éiceachóras a aimsiú"),
    req("RC5.1",
      tr: "Ba chóir do rannpháirtithe an éiceachórais (m.sh. úsáideoirí agus soláthraithe sonraí) a bheith in ann a chéile a fháil amach laistigh d'éiceachóras comhroinnte sonraí.",
      en: "Ecosystem participants (e.g. data users and providers) should be able to discover each other within a data-sharing ecosystem."),
    req("RC5.2",
      tr: "Ba chóir go mbeadh dóthain meiteashonraí faoi gach rannpháirtí san éiceachóras ar fáil chun a n-iontaoibh atá ábhartha do mhalartú sonraí a fháil amach.",
      en: "Sufficient metadata about each ecosystem participant should be available to ascertain their trustworthiness relevant for data exchange."),
    req("RC5.3",
      tr: "Ba chóir do sholáthraithe sonraí a bheith in ann úsáideoirí sonraí ar mian leo teacht ar a gcuid sócmhainní sonraí a shainaithint go hiontaofa agus a meiteashonraí a fhíorú sula dtugtar rochtain.",
      en: "Data providers should be able to reliably identify data users who want to access their data assets and verify their metadata before granting access."),
    req("RC5.4",
      tr: "Ba chóir d'úsáideoirí sonraí a bheith in ann soláthraithe sonraí a roinneann sonraí in éiceachóras sonraí a shainaithint sula ndéanann siad rochtain ar na sonraí sin nó sula n-úsáideann siad iad.",
      en: "Data users should be able to identify data providers who share data in a data ecosystem before accessing or using that data."),
    req("RC5.5",
      tr: "Féadfaidh rannpháirtithe an éiceachórais a roghnú freisin fanacht gan ainm má cheadaíonn samhail rialachais an éiceachórais comhroinnte sonraí é sin. Sa chás seo, is féidir neamhaird a dhéanamh de RC5.1 go RC5.4.",
      en: "Ecosystem participants may also choose to remain anonymous if the governance model of the data-sharing ecosystem allows for it. In this case, RC5.1 to RC5.4 can be ignored."),
    capability("C6", "Data exchange can be agreed upon",
      tr: "Is féidir comhaontú a dhéanamh ar mhalartú sonraí"),
    req("RC6.1",
      tr: "Ba chóir d'úsáideoirí agus do sholáthraithe sonraí a bheith in ann aontú le malartú sonraí agus leis na téarmaí agus na coinníollacha a bhaineann leis (m.sh. glacadh le téarmaí, síniú dlíthiúil comhaontaithe, nó caibidlíocht).",
      en: "Data users and providers should be able to agree to a data exchange and the terms and conditions associated with it (e.g. acceptance of terms, legal signature of an agreement, or negotiation)."),
    req("RC6.2",
      tr: "Ba chóir d'úsáideoirí agus do sholáthraithe sonraí a bheith in ann deireadh a chur le malartú sonraí a comhaontaíodh roimhe sin i gcomhréir leis na téarmaí agus na coinníollacha a bhaineann leis.",
      en: "Data users and providers should be able to terminate a previously agreed-upon data exchange in accordance with the terms and conditions associated with it."),
    req("RC6.3",
      tr: "Nuair is féidir, féadfar modhanna leictreonacha a sholáthar maidir le comhaontú agus foirceannadh malartaithe sonraí.",
      en: "Where possible, electronic means for the agreement and termination of a data exchange may be provided."),
    capability("C7", "New data currently not available can be requested",
      tr: "Is féidir sonraí nua nach bhfuil ar fáil faoi láthair a iarraidh"),
    req("RC7.1",
      tr: "Ba chóir d'úsáideoirí sonraí a bheith in ann a spéis i sócmhainní sonraí nach bhfuil ar fáil faoi láthair san éiceachóras comhroinnte sonraí a chur in iúl.",
      en: "Data users should be able to express their interest in data assets currently unavailable in the data sharing ecosystem."),
    req("RC7.2",
      tr: "Ba chóir do sholáthraithe sonraí a bheith in ann iarratais a dhéanann úsáideoirí sonraí ar shócmhainní sonraí nua a fháil.",
      en: "Data providers should be able to obtain requests made by data users for new data assets."),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/exchanging-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 checklist")[
  #mim-page(
    id:       "MIM6",
    name:     "Slánú Sonraí",
    question: "An bhfuil ár gcuid sonraí sábháilte faoi bhealach agus in úsáid?",
    url:      "https://mims.oascities.org/securing-data",
    intro:    "Is spriocanna iad cathracha cliste. Coimeádann MIM6 an scóip cúng agus praiticiúil d'aon ghnó: criptigh sonraí atá ag gluaiseacht, úsáid logálacha isteach caighdeánacha in ionad cinn dhílseánaigh, rialaigh agus logáil cé a dhéanann rochtain ar cad é. Níl aon chuid de aitheanta mar rud coimhthíoch — ní mór dó ar fad a bheith sa chonradh.",
    list:     "Seicliosta",
  )

  #item("Déantar gach aistriú sonraí a chriptiú (TLS 1.3 nó an dea-chleachtas reatha).",
    why:  "Bunchoinníoll sláinteachais; tá súil ag NIS2 leis freisin san áit a mbaineann sé leat.",
    refs: "MIM6 R2.1, M1.1",
    num:  "6.1")

  #item("Úsáideann logáil isteach agus rochtain meaisín caighdeáin oscailte — OAuth 2.0 / OpenID Connect — agus is féidir iad a phlocáil isteach i soláthraí aitheantais reatha na cathrach.",
    why:  "Cuntas amháin in aghaidh an fhostaí, ní ceann amháin in aghaidh tháirge an díoltóra; cailleann daoine a fhágann rochtain i ngach áit ag an am céanna.",
    refs: "MIM6 R3.1, M1.2, M1.3",
    num:  "6.2")

  #item("Tá cearta rochtana rólbhunaithe, in-athbhreithnithe, agus inbhainte; déantar gníomhartha rochtana agus riaracháin a logáil.",
    why:  "Bíonn iniúchtaí agus freagairt ar theagmhais indéanta. Is é logáil rialú 8.15 de ISO/IEC 27001:2022, Iarscríbhinn A, a liostaíonn MIM6 i measc a réamhriachtanas.",
    refs: "MIM6 R1.1, R1.3, 8.15",
    num:  "6.3")

  #item("Ní mór don soláthraí ailíniú le ISO/IEC 27001:2022 (nó a chomhionann) a léiriú don tseirbhís a oibríonn siad.",
    why:  "Próiseas is ea an tslándáil, ní ticbhosca ag an seachadadh. Luann an tsonraíocht rialuithe ISO/IEC 27001, ní teastas.",
    refs: "MIM6 C1–C3 (ISO/IEC 27001)",
    num:  "6.4",
    label: "Baineann sé leis na coinníollacha rannpháirtíochta, ní leis an tsonraíocht theicniúil")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Ní osclaíonn sárú i gcóras amháin gach córas.",
      "San áit a mbaineann NIS2 leat, éiríonn sé i bhfad níos éasca é a chomhlíonadh mar aon le rialacha cibearshlándála náisiúnta.",
      "Nuair a théann rud éigin mícheart, insíonn na logaí duit cad é agus cé hé.",
    )),
    flags: ("Bratacha dearga", (
      "Logáil isteach dílseánach amháin.",
      "“Logaí ar fáil ar iarraidh.”",
      "Cuntais riarthóra chomhroinnte.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM6",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM6",
    capability("C1", "Data is only accessible to users that should have access to it",
      tr: "Níl sonraí inrochtana ach d'úsáideoirí ar chóir go mbeadh rochtain acu orthu"),
    req("R1.1",
      tr: "NÍ MÓR rialacha chun rochtain fhisiciúil agus loighciúil ar fhaisnéis agus ar shócmhainní gaolmhara eile a rialú a bhunú agus a chur i bhfeidhm bunaithe ar cheanglais ghnó agus slándála faisnéise. (ISO 27001 5.15 Rialú rochtana)",
      en: "Rules to control physical and logical access to information and other associated assets SHALL be established and implemented based on business and information security requirements. (ISO 27001 5.15 Access control)"),
    req("R1.2",
      tr: "NÍ MÓR leithdháileadh agus bainistiú faisnéise fíordheimhnithe a rialú trí phróiseas bainistíochta, lena n-áirítear comhairle a thabhairt do phearsanra maidir le láimhseáil chuí faisnéise fíordheimhnithe. (ISO 27001 5.17: Faisnéis fhíordheimhnithe)",
      en: "Allocation and management of authentication information SHALL be controlled by a management process, including advising personnel on appropriate handling of authentication information. (ISO 27001 5.17: Authentication information)"),
    req("R1.3",
      tr: "NÍ MÓR cearta rochtana ar fhaisnéis agus ar shócmhainní gaolmhara eile a sholáthar, a athbhreithniú, a mhodhnú agus a bhaint i gcomhréir le beartas agus rialacha sonracha an eagraigh maidir le rialú rochtana. (ISO 27001 5.18: Cearta rochtana)",
      en: "Access rights to information and other associated assets SHALL be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control. (ISO 27001 5.18: Access rights)"),
    capability("C2", "Data accessed by users has not been altered",
      tr: "Níor athraíodh sonraí a ndearna úsáideoirí rochtain orthu"),
    req("R2.1",
      tr: "NÍ MÓR rialacha d'úsáid éifeachtach na cripteagrafaíochta, lena n-áirítear bainistíocht eochracha cripteagrafacha, a shainiú agus a chur i bhfeidhm. (ISO 27001 8.24 Úsáid cripteagrafaíochta)",
      en: "Rules for the effective use of cryptography, including cryptographic key management, SHALL be defined and implemented. (ISO 27001 8.24 Use of cryptography)"),
    capability("C3", "Data accessed by users originates from a verified source",
      tr: "Tagann sonraí a ndéanann úsáideoirí rochtain orthu ó fhoinse fhíoraithe"),
    req("R3.1",
      tr: "cuirfear teicneolaíochtaí agus nósanna imeachta slána fíordheimhnithe i bhfeidhm bunaithe ar shrianta rochtana faisnéise agus ar an mbeartas a bhaineann go sonrach leis an ábhar maidir le rialú rochtana. (ISO 27001 8.5 Fíordheimhniú slán)",
      en: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control. (ISO 27001 8.5 Secure authentication)"),
    capability("M1", "Mechanism candidate",
      tr: "Meicníocht is iarrthóir"),
    req("M1.1",
      tr: "Prótacal Slándála an Chiseáil Iompair (TLS), Leagan 1.3",
      en: "The Transport Layer Security (TLS) Protocol, Version 1.3"),
    req("M1.2",
      tr: "Creat Údaraithe OAuth 2.0",
      en: "The OAuth 2.0 Authorization Framework"),
    req("M1.3",
      tr: "OpenID Connect 1.0, Ciseal aitheantais d'fhíordheimhniú ar OAuth 2.0",
      en: "OpenID Connect 1.0, Identity layer for authentication on OAuth 2.0"),
    req("M1.4",
      tr: "OIDC4VCI / OIDC4VP, OpenID le haghaidh Eisiúint agus Léiriú Dintiúir Infhíoraithe",
      en: "OIDC4VCI / OIDC4VP, OpenID for Verifiable Credential Issuance and Presentations"),
    capability("P", "Pre- and Post-requisites (based on ISO 27001 Annex A): the control this booklet refers to",
      tr: "Réamh- agus Iar-riachtanais (bunaithe ar ISO 27001 Iarscríbhinn A): an rialú a dtagraíonn an leabhrán seo dó"),
    req("8.15",
      tr: "Logáil. Déanfar logaí a thaifeadann gníomhaíochtaí, eisceachtaí, lochtanna agus imeachtaí ábhartha eile a tháirgeadh, a stóráil, a chosaint agus a anailísiú.",
      en: "Logging. Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed."),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/securing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 checklist")[
  #mim-page(
    id:       "MIM7",
    name:     "Sonraí Geospásúla",
    question: "An oibríonn sé ar léarscáil?",
    url:      "https://mims.oascities.org/geospatial-data",
    intro:    "Tá áit ag beagnach gach rud atá ag cathair. Cinntíonn MIM7 nach gabháil scáileáin atá san áit sin: sreabhann sonraí spásúla trí chomhéadain chaighdeánacha OGC, i bhformáidí oscailte, agus an córas comhordanáidí fógartha i gcónaí — ionas go n-ailíníonn gach sraith léarscáile a cheannaíonn tú le gach sraith atá agat cheana féin.",
    list:     "Seicliosta",
  )

  #item("Nochtar sonraí geospásúla trí chomhéadain bunaithe ar chaighdeáin (OGC API Features, SensorThings; tá WFS inghlactha do chórais leagáide).",
    why:  "Is féidir le gach uirlis GIS ar an margadh é a léamh láithreach.",
    refs: "MIM7 R1.1",
    num:  "7.1")

  #item("Ionchódaítear sonraí geospásúla i bhformáidí oscailte (GeoJSON, CityJSON; GML/CityGML nuair is gá).",
    why:  "Gan ceadúnais tiontaire, gan aon chaochbhóithre.",
    refs: "MIM7 R2.1",
    num:  "7.2")

  #item("Dearbhaítear an córas tagartha comhordanáidí i gcónaí (cód EPSG) agus is féidir sonraí a athrú go CRS coiteann.",
    why:  "Ailíníonn sraitheanna ó fhoinsí éagsúla ar an léarscáil i ndáiríre.",
    refs: "MIM7 R5.1",
    num:  "7.3")

  #item("Iompraíonn gnéithe spásúla na haitheantóirí buana céanna agus atá i MIM1.",
    why:  "Is é an ponc ar an léarscáil agus an taifead sa chlár an rud céanna go díreach.",
    refs: "MIM7 R4.1",
    num:  "7.4")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Léarscáil chathrach amháin in ionad deich bhféachantóir díoltóra.",
      "Éiríonn oibleagáidí INSPIRE agus tairsí geo náisiúnta níos éasca, ní níos deacra.",
      "Féadfaidh sonraí 3D agus BIM dul isteach sa phictiúr céanna níos déanaí.",
    )),
    flags: ("Bratacha dearga", (
      "Níl sonraí léarscáile beo ach taobh istigh d'fhéachantóir an díoltóra.",
      "“Easpórtáil mar PDF/gabháil scáileáin.”",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM7",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM7",
    capability("C1", "Cities and communities can easily transfer geospatial data between internal and external (including IoT-related) IT systems",
      tr: "Is féidir le cathracha agus pobail sonraí geospásúla a aistriú go héasca idir córais TF inmheánacha agus sheachtracha (lena n-áirítear córais a bhaineann le IoT)"),
    req("R1.1",
      tr: "nochtfar sonraí geospásúla trí chomhéadan seirbhíse gréasáin bunaithe ar chaighdeáin.",
      en: "Geospatial data shall be exposed through a standards-based web service interface."),
    capability("C2", "Cities and communities can integrate 2D and 3D geospatial data coming from a variety of sources, for example geodata and building information models, and share that data within and between them in an interoperable way",
      tr: "Is féidir le cathracha agus pobail sonraí geospásúla 2D agus 3D a chomhtháthú a thagann ó fhoinsí éagsúla, mar shampla geoshonraí agus samhlacha faisnéise foirgnimh, agus na sonraí sin a roinnt laistigh díobh agus eatarthu ar bhealach idir-inoibritheach"),
    req("R2.1",
      tr: "ionchódófar sonraí geospásúla ag baint úsáide as caighdeáin oscailte. Moltar caighdeáin ábhartha ó OGC agus BuildingSMART International a úsáid.",
      en: "Geospatial data shall be encoded using open standards. It is recommended to use relevant standards from OGC and BuildingSMART International."),
    capability("C3", "Cities and communities can integrate geospatial data with other data that can provide further information about the context",
      tr: "Is féidir le cathracha agus pobail sonraí geospásúla a chomhtháthú le sonraí eile ar féidir leo tuilleadh faisnéise a sholáthar faoin gcomhthéacs"),
    req("R3.1",
      tr: "Déanfaidh gach tacar sonraí a úsáidtear chun tuilleadh faisnéise a sholáthar faoin gcomhthéacs a chlúdaíonn sonraí geospásúla MIM1 agus MIM2 a chomhlíonadh.",
      en: "All data sets used to provide further information about the context covered by geospatial data shall comply with MIM1 and MIM2."),
    capability("C4", "Cities and communities have a consistent and persistent way of describing individual instances of all features, things or entities included in the geospatial data sources",
      tr: "Tá bealach comhsheasmhach agus buan ag cathracha agus ag pobail chun cur síos a dhéanamh ar chásanna aonair de na gnéithe, na rudaí nó na heintitis go léir a áirítear sna foinsí sonraí geospásúla"),
    req("R4.1",
      tr: "Úsáidfear aitheantóirí uathúla agus buana chun cásanna ar leith d'aon eintiteas a úsáidtear i dtacair shonraí a shainaithint. (Féach MIM1: Idirnascadh Sonraí.)",
      en: "Unique and persistent identifiers shall be used to identify particular instances of any entity used in data sets. (See MIM1: Interlinking Data.)"),
    capability("C5", "Coordinate Reference Systems (CRS) used in data sharing are easily transformable into a common CRS",
      tr: "Is féidir Córais Tagartha Comhordanáidí (CRS) a úsáidtear i gcomhroinnt sonraí a athrú go héasca go CRS coiteann"),
    req("R5.1",
      tr: "Comhlíonfaidh Córais Tagartha Comhordanáidí (CRS) caighdeáin, agus cuirfear faisnéis ar fáil maidir le cén caighdeán (m.sh. EPSG:4326, EPSG:3857) atá á úsáid. Áirítear leis seo an uimhir EPSG nó an uimhir WGS, mar aon le faisnéis faoi aon athrú bunaithe ar chórais náisiúnta amhail LKS-92 na Laitvia, ionas gur féidir sonraí a athrú go CRS coiteann. (Nóta: Laistigh den AE, maidir le sonraí geospásúla éilítear meiteashonraí a úsáid atá i gcomhréir leis an Treoir INSPIRE, lena n-áirítear na meiteashonraí is gá chun cur síos a dhéanamh ar fhaisnéis CRS.)",
      en: "Coordinate Reference Systems (CRS) shall comply with standards, and information shall be provided regarding which standard (e.g. EPSG:4326, EPSG:3857) is being used. This includes the EPSG number or WGS number, along with information about any variation based on national systems such as the Latvian LKS-92, so that data can be transformed to a common CRS. (Note: Within the EU, for geospatial data it is required to use metadata compliant with the INSPIRE Directive, including the metadata needed to describe the CRS information.)"),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/geospatial-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 checklist")[
  #mim-page(
    id:       "MIM8",
    name:     "Cúplaí Digiteacha Áitiúla",
    question: "An féidir lenár gcúpla digiteach fás?",
    url:      "https://mims.oascities.org/local-digital-twins",
    intro:    "Infheistíocht fhadtéarmach is ea cúpla digiteach: sonraí, samhlacha 3D, ionsamhlúcháin, cinntí. Cosnaíonn MIM8 an infheistíocht sin — fanann sonraí agus samhlacha an chúpla inrochtana agus doiciméadaithe, is féidir torthaí a atáirgeadh, agus féadfaidh comhpháirteanna ó thionscadal amháin fónamh don chéad cheann eile. Úsáid an leathanach seo agus ardáin cúpla, samhlacha ionsamhlúcháin nó uirlisí cathrach 3D á gceannach agat.",
    list:     "Seicliosta",
  )

  #item("Tá tacair shonraí, ionchuir mhúnla agus aschuir ionsamhlúcháin inrochtana trí APIanna (de réir MIM0), ní gafa sa chúpla.",
    why:  "Cothaíonn torthaí tuarascálacha, deaisanna agus an chéad tionscadal eile.",
    refs: "MIM8 R1.1",
    num:  "8.1")

  #item("Tá samhlacha doiciméadaithe (modh, paraiméadair, ionchuir/aschuir) agus inghlaoite trí chomhéadan doiciméadaithe.",
    why:  "Múnla tuilte a cheannaítear uair amháin, is féidir é a athúsáid thar ranna — agus ag cathracha eile.",
    refs: "MIM8 R3.1, R3.2",
    num:  "8.2")

  #item("Úsáideann aschuir formáidí caighdeánacha (GeoJSON, CityJSON, 3D Tiles, NetCDF…) ar féidir le huirlisí nach gceannaíonn tú ón díoltóir seo iad a thomhailt.",
    why:  "Fanann léirshamhlú agus anailís ina margaí iomaíocha.",
    refs: "MIM8 M2",
    num:  "8.3")

  #item("Taifeadann sreafaí oibre bunús: cén leagan sonraí, cén samhail, cad iad na paraiméadair a tháirg toradh.",
    why:  "Is féidir cinntí bunaithe ar an gcúpla a mhíniú agus a chosaint níos déanaí.",
    refs: "MIM8 R4.4",
    num:  "8.4")

  #panels(
    why:   ("Cén fáth a bhfuil tábhacht leis", (
      "Maireann an cúpla níos faide ná aon soláthraí aonair nó buiséad tionscadail.",
      "Is féidir ionsamhlúcháin a sheiceáil, a athdhéanamh agus a chosaint i gcinnteoireacht bhardasach.",
      "Is féidir samhlacha agus comhpháirteanna a roinnt idir cathracha.",
    )),
    flags: ("Bratacha dearga", (
      "Torthaí ionsamhlúcháin le feiceáil i dtairseach an díoltóra amháin.",
      "Samhlacha mar bhoscaí dubha séalaithe gan aon mheiteashonraí.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM8",
    title:  "Cad a deir an tsonraíocht",
    leadin: "Gach ceanglas de chuid an MIM seo, focal ar fhocal ó MIMs Plus 9.0: Níl an tsonraíocht ar fáil ach i mBéarla: is aistriúchán neamhoifigiúil é an téacs Gaeilge le húdar an leabhráin seo; tá an bunleagan Béarla faoi ina cheangal dlí.",
    back:   "ar ais go dtí an seicliosta",
  )

  #spec-list(mim: "MIM8",
    capability("C1", "Provide access to datasets used within the LDT, including static, real-time, and simulation data and calculation models",
      tr: "Rochtain a sholáthar ar thacair shonraí a úsáidtear laistigh den LDT, lena n-áirítear sonraí statacha, fíor-ama agus ionsamhlúcháin agus samhlacha ríofa"),
    req("R1.1",
      tr: "Soláthróidh an LDT rochtain ar aschuir ionsamhlúcháin agus ar ionchuir mhúnla ríofa nuair a theastaíonn siad mar chuid de shreafaí oibre LDT.",
      en: "The LDT shall provide access to simulation outputs and calculation-model inputs where these are needed as part of LDT workflows."),
    req("R1.2",
      tr: "Ba chóir don LDT idirdhealú soiléir a dhéanamh idir bunshonraí amha, sonraí atá réidh le haghaidh sreafa oibre claochlaithe, ionchuir mhúnla, agus aschuir mhúnla.",
      en: "The LDT should distinguish clearly between raw source data, transformed workflow-ready data, model inputs, and model outputs."),
    capability("C2", "Exchange data with external systems and other LDTs using interoperable interfaces",
      tr: "Sonraí a mhalartú le córais sheachtracha agus le LDTanna eile ag baint úsáide as comhéadain idir-inoibritheacha"),
    req("C2",
      tr: "Braitheann an cumas seo ar MIM3 (Malartú Sonraí) le haghaidh malartú sonraí.",
      en: "This capability relies on MIM3 (Exchanging Data) for data exchange."),
    capability("C3", "Reuse deterministic or AI models across different domains, communities, use cases, and/or LDTs",
      tr: "Samhlacha cinnteacha nó IS a athúsáid thar réimsí, pobail, cásanna úsáide, agus/nó LDTanna éagsúla"),
    req("R3.1",
      tr: "Ba chóir don mhúnla meiteashonraí caighdeánacha múnla a sholáthar, lena n-áirítear cur síos ar a mhodhanna agus a pharaiméadair, agus sonraí-pharaiméadair (trí luach nó trí thagairt). Chuige sin ba chóir úsáid a bhaint as caighdeáin choiteanna meiteashonraí.",
      en: "The model should provide standard model metadata, including a description of its methods and parameters, and data-parameters (either by value or by reference). To this end common metadata standards should be used."),
    req("R3.2",
      tr: "Nochtfaidh an múnla comhéadan doiciméadaithe nó beidh sé inghlaoite trí chomhéadan doiciméadaithe, de rogha ag baint úsáide as API caighdeánaithe aitheanta. Déanfar cur síos ar an tacar sonraí arb é toradh an mhúnla é (ar leibhéal na sonraí).",
      en: "The model shall expose or be callable through a documented interface, preferably using a known standardised API. The dataset that forms the outcome of the model shall be described (at data-level)."),
    req("R3.3",
      tr: "Ba chóir úsáid iontaofa, fhónta agus eiticiúil modhanna nuálacha (LLManna, IS ghníomhaireach, etc.) a chosaint. Ba chóir claonadh a íoslaghdú nuair is infheidhme. Ba chóir cur síos a dhéanamh ar na modhanna a úsáidtear chun é seo a ráthú.",
      en: "Trustworthy, reliable, and ethical use of innovative methods (LLMs, agentic AI, etc.) should be safeguarded. Bias should minimised [sic] where applicable. The methods used to guarantee this, should be described."),
    req("R3.4",
      tr: "Ní mór don mhúnla a bheith in ann rochtain a fháil ar shonraí thar ceann an úsáideora deiridh nó na heagraíochta. Féach MIM3",
      en: "The model must be able to access data on behalf of the end-user or organisation. See MIM3"),
    req("R3.5",
      tr: "Chun go n-úsáidfear sonraí i múnlaí IS, ba chóir bunús agus iontaoibh a ráthú. I gcásanna áirithe, ní mór foinse údarásach, amhail gníomhaireacht rialtais, a liostú.",
      en: "For data to be used in AI models, provenance and trust should be guaranteed. In some cases, an authoratitive sourc [sic], such as a government agency must be listed."),
    capability("C4", "Coordinate and manage data, models, and processing workflows within an LDT (intra-LDT) and across LDTs (inter-LDT)",
      tr: "Sonraí, samhlacha, agus sreafaí oibre próiseála a chomhordú agus a bhainistiú laistigh de LDT (laistigh de LDT) agus trasna LDTanna (idir-LDT)"),
    req("R4.1",
      tr: "Tacaíonn an LDT le sreafaí oibre a nascann foinsí sonraí, claochluithe sonraí, forghníomhú samhlacha, próisis ionsamhlúcháin, agus aschuir.",
      en: "The LDT supports workflows that connect data sources, data transformations, model execution, simulation processes, and outputs."),
    req("R4.2",
      tr: "Slabhraíonn an LDT céimeanna sreafa oibre, áit ar féidir aschur céime amháin a úsáid mar ionchur do chéim eile.",
      en: "The LDT chains workflow steps, where the output of one step can be used as the input for another."),
    req("R4.3",
      tr: "Déanann an LDT monatóireacht ar stádas forghníomhaithe an tsreafa oibre, lena n-áirítear próisis chríochnaithe, theipthe agus bhriste.",
      en: "The LDT monitors workflow execution status, including completed, failed, and interrupted processes."),
    req("R4.4",
      tr: "Taifeadann an LDT bunús an tsreafa oibre, lena n-áirítear tacair shonraí a úsáideadh (lena n-áirítear leagan, stampáilte le ham), samhlacha a forghníomhaíodh, paraiméadair a roghnaíodh, agus aschuir a gineadh.",
      en: "The LDT records workflow provenance, including datasets used (including version, timestamped), models executed, parameters selected, and outputs generated."),
    capability("C5", "Provide multiple visualisations of data and results (e.g. 2D, 3D, dashboards) from common underlying data and models for interaction and comparison",
      tr: "Léirshamhluithe iolracha ar shonraí agus ar thorthaí (m.sh. 2D, 3D, deaisanna) a sholáthar ó shonraí agus ó shamhlacha bunúsacha coiteanna le haghaidh idirghníomhaíochta agus comparáide"),
    req("R5.1",
      tr: "Soláthraíonn an LDT meiteashonraí a mhíníonn cad atá á léirshamhlú, lena n-áirítear stampa ama, raon feidhme spásúil, foinse sonraí, agus toimhdí cásanna agus leaganacha nuair is ábhartha.",
      en: "The LDT provides metadata explaining what is visualised, including timestamp, spatial scope, data source, and scenario- and variant-assumptions where relevant."),
    req("R5.2",
      tr: "Tacaíonn an LDT le cineálacha éagsúla léirshamhlaithe idirghníomhacha, amhail léarscáileanna 2D, radhairc 3D, deaisanna, tuarascálacha, nó radhairc phoiblí.",
      en: "The LDT supports different interactive visualisation types, such as 2D maps, 3D scenes, dashboards, reports, or public-facing views."),
    capability("C6", "Ensure that data exchanged (and simulation outputs) within and between LDTs can be interpreted consistently through shared or mapped semantics and clear provenance",
      tr: "A chinntiú gur féidir sonraí a mhalartaítear (agus aschuir ionsamhlúcháin) laistigh de LDTanna agus eatarthu a léirmhíniú go comhsheasmhach trí shéimeantaic chomhroinnte nó mhapáilte agus trí bhunús soiléir"),
    req("R6.1",
      tr: "Ba chóir don LDT bearnaí séimeantacha neamhréitithe, toimhdí, nó mapálacha a dhoiciméadú a d'fhéadfadh dul i bhfeidhm ar léirmhíniú, athúsáid nó comparáid torthaí.",
      en: "The LDT should document unresolved semantic gaps, assumptions, or mappings that may affect the interpretation, reuse, or comparison of results."),
    capability("M", "Mechanisms (under active development)",
      tr: "Meicníochtaí (faoi fhorbairt ghníomhach)"),
    req("M1",
      tr: "Rochtain ar Acmhainní LDT Bunaithe ar API",
      en: "API-based LDT Resource Access"),
    req("M2",
      tr: "Formáidí Sonraí agus Aschuir Chaighdeánaithe",
      en: "Standardised Data and Output Formats"),
    req("M3",
      tr: "Múnla-mar-Sheirbhís",
      en: "Model-as-a-Service"),
    req("M4",
      tr: "Stiúradh Sreafa Oibre LDT",
      en: "LDT Workflow Orchestration"),
    req("M5",
      tr: "Rochtain ar Aschur Il-radhairc agus ar Léirshamhlú",
      en: "Multi-view Output and Visualisation Access"),
  )

  #spec-link("Sonraíocht iomlán:", "https://mims.oascities.org/local-digital-twins")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  CROSS-CUTTING CONTRACT CLAUSES
// ════════════════════════════════════════════════════════════════════════════
#fit-page("clauses")[
  #band("Clásail thrasghearrtha tairisceana", sub: "Cosaintí ar ghlasáil isteach", id: "clauses")

  #intro(size: 9.8pt, "Baineann na clásail seo le gach tairiscint, is cuma cad atá á cheannach agat. Eascraíonn siad as cleachtas soláthair timpeall ar na MIMs agus living-in.eu. Ní bhraitheann formhór acu ar cheanglas sonraíochta aonair, mar sin ní iompraíonn siad aon chóid tagartha (is moladh MIM0 C2 é leaganú API freisin). Is beag a chosnaíonn sé iad a chur san áireamh; féadfaidh gach rud a bheith caillte má fhágtar ar lár iad.")

  #clauses(
    clause("Clásal scoir",
      "Ag deireadh an chonartha, déantar sonraí uile na cathrach (agus cumraíocht) a thabhairt ar láimh i bhformáidí oscailte doiciméadaithe gan aon chostas breise."),
    clause("Cearta sna sonraí",
      "Baineann gach ceart sna sonraí a bhailítear agus a dhíorthaítear faoin gconradh leis an údarás conarthach."),
    clause("Gan táillí in aghaidh an tsuíocháin / an iarratais",
      "Gan táillí ar an gcathair as rochtain a fháil ar a sonraí féin."),
    clause("Cobhsaíocht agus leaganú API",
      "Coinníonn an soláthraí an API comhoiriúnach siar ar feadh théarma iomlán an chonartha. Fógraítear athruithe a bhriseann comhoiriúnacht 6 mhí ar a laghad roimh ré agus eiseofar iad mar leagan nua, agus fanann an leagan roimhe sin ar fáil go dtí an dáta aistrithe comhaontaithe."),
    clause("Léirigh, ná geall",
      "Léiríonn tairgeoirí comhlíonadh le linn mheastóireacht na dtairiscintí in ionad féindhearbhuithe a chur isteach. Maidir le API ciallaíonn sé seo doiciméadú idirghníomhach foilsithe (mar shampla OpenAPI) agus glao beo a thugann sonraí bailí ar ais. Déantar gach mír a bhfuil tic léi a thástáil arís ag am an ghlactha."),
    clause("Caighdeáin oscailte ainmnithe",
      "Ainmníonn an tairiscint na caighdeáin thuas; ní mór do mhaíomh “comhoiriúnach le” an comhéadan agus an leagan cruinn a lua. Glacann gach tagairt do chaighdeán nó do shonraíocht theicniúil le réiteach coibhéiseach; cruthaíonn an tairgeoir an choibhéis."),
    clause("Ráiteas comhlíonta MIMs",
      "Líonann an tairgeoir an tábla comhlíonta (lch. 23); tagann sé chun bheith ina iarscríbhinn a ghabhann leis an gconradh."),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT
// ════════════════════════════════════════════════════════════════════════════
#fit-page("example")[
  #band("Sampla: ceannaíonn cathair líonra de bhraiteoirí cháilíocht an aeir", id: "example")

  #intro(size: 9.8pt, "Leathanaigh mharcáilte: MIM0, MIM1, MIM2, MIM6 agus MIM7 (téann na sonraí ar léarscáil). Ó MIM3 mír 3.1 amháin (foilsítear sonraí cháilíocht an aeir mar shonraí oscailte, mar sin baineann sé le catalóg); ní MIM8: ní cúpla digiteach é seo.")

  #text(size: 10pt, weight: "bold", fill: eu-blue, "Cad a théann cén áit")
  #v(4pt)

  #doc-table(
    ("Doiciméad", "Téarma i dTreoir 2014/24/AE", "Cad le cur ann"),
    (
      ("Sonraíocht theicniúil",
       "sonraíochtaí teicniúla (Airt. 42)",
       "na míreanna marcáilte de MIM0, MIM1, MIM2, MIM3 (3.1 amháin), MIM6 (seachas 6.4) agus MIM7, focal ar fhocal, leis an gcód sonraíochta, móide an abairt ar choibhéis"),
      ("Coinníollacha rannpháirtíochta",
       "critéir roghnúcháin (Airt. 58 agus 62)",
       "ailíniú léirithe le ISO/IEC 27001:2022 nó a chomhionann (mír 6.4)"),
      ("Modhanna cruthúnais",
       "tuarascálacha tástála, deimhniú agus modhanna eile cruthúnais (Airt. 44)",
       "an tábla comhlíonta mar iarscríbhinn éigeantach a ghabhann leis an tairiscint: C, E nó N do gach mír, leis an bhfianaise (seoladh doiciméadaithe API, rochtain tástála)"),
      ("Dréachtchonradh",
       "coinníollacha maidir le feidhmíocht conarthaí (Airt. 70)",
       "Clásal scoir, Úinéireacht sonraí, Gan aon táillí in aghaidh an tsuíocháin / an iarratais, Cobhsaíocht agus leaganú API; an tábla comhlíonta comhlánaithe mar iarscríbhinn"),
      ("Prótacal glactha",
       "coinníollacha maidir le feidhmíocht conarthaí (Airt. 70)",
       "an colún “Fíoraithe” den tábla comhlíonta mar an bprótacal tástála"),
    ),
  )

  #sample-text("Téacs samplach don sonraíocht theicniúil", (
    "4.3 Idir-inoibritheacht agus rochtain ar shonraí",
    "4.3.1 Is féidir na sonraí go léir a bhailíonn nó a tháirgeann an córas a aisghabháil i bhformáid mheaisín-inléite amháin ar a laghad (m.sh. JSON, CSV) thar API caighdeánach gréasáin. (MIMs Plus 9.0, MIM0 R1.1, R1.2)",
    "4.3.2 Déantar cur síos foirmiúil ar an API i ndoiciméad oscailte meaisín-inléite (mar shampla OpenAPI) a fhoilsítear ag seoladh cobhsaí. (MIM0 R1.3)",
    "4.3.3 Ligeann an API sonraí a scagadh de réir am agus áit an tomhais. (MIM0 R2.1, R2.2)",
    "… 4.3.4 go 4.3.21: míreanna marcáilte breise …",
    "4.3.22 Glacann gach tagairt do chaighdeán nó do shonraíocht theicniúil le réiteach coibhéiseach; cruthaíonn an tairgeoir an choibhéis.",
    "4.3.23 Líonann an tairgeoir an tábla comhlíonta (iarscríbhinn a ghabhann leis na doiciméid soláthair) agus tugann sé an fhianaise do gach mír riachtanach. Léiríonn an tairgeoir pointí 4.3.1 go 4.3.21 le glao beo API le linn mheastóireacht na dtairiscintí; déanann an t-údarás conarthach iad a thástáil arís ag am an ghlactha. Is cúis é gan iad a chomhlíonadh le diúltú do ghlacadh.",
  ))

  #note(size: 9pt, "Léiríonn pointe 4.3.3 go bhféadfaidh tú mír a ghéarú chun freastal ar an gceannachán: i gcás braiteoirí tá ciall leis scagadh de réir ama agus áit an tomhais a iarraidh.")

  #v(4pt)
  #text(size: 10pt, weight: "bold", fill: eu-blue, "Tábla comhlíonta comhlánaithe (sliocht)")
  #v(4pt)

  #filled-table(
    ("#", "Ceanglas (gearr)", "C / E / N", "Fianaise: conas agus cá háit", "Fíoraithe"),
    (
      ("0.1", "Sonraí meaisín-inléite trí API caighdeánach gréasáin", "C", "Tugann REST API JSON agus CSV ar ais; doiciméadú ag an seoladh a tugadh sa tairiscint, lch. 12; rochtain tástála in iarscríbhinn 3", "✓"),
      ("0.4", "Síntiús d'athruithe nuair is gá", "N", "ní thacaítear leis go fóill; beartaithe don chéad leagan eile", "—"),
      ("7.2", "Formáidí geo oscailte", "E", "seachadann GeoPackage, gnáthchaighdeán OGC, in ionad GeoJSON; mínítear an choibhéis sa tairiscint, lch. 15", "✓"),
    ),
  )

  #note(size: 9pt, gap: 5pt, "Is é N gealltanas don todhchaí: ní fhíoraíonn an coiste ach an méid is féidir leis an tairgeoir a thaispeáint.")

  #note(size: 9pt, gap: 5pt, "Cuir an leagan cainte in oiriúint don dlí náisiúnta agus iarr ar an duine atá freagrach as soláthar é a sheiceáil.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)
// ════════════════════════════════════════════════════════════════════════════
#band("Tábla comhlíonta", id: "table")

#intro(size: 9.4pt, gap: 5pt, "Sraith amháin in aghaidh na míre. Cuireann an t-údarás conarthach tic leis an méid a éilíonn an conradh agus ceanglaíonn sé an tábla leis na doiciméid soláthair mar iarscríbhinn éigeantach a ghabhann leis an tairiscint. I gcás gach míre riachtanaí cuireann an tairgeoir C (comhlíonann), E (comhlíonann le réiteach coibhéiseach) nó N (ní chomhlíonann) isteach, go hachomair conas, agus cá bhfuil an fhianaise: seoladh doiciméadaithe, rochtain tástála, leathanach den tairiscint. Ní leor dearbhú gan fhianaise. Fíoraíonn an coiste meastóireachta gach mír agus tairiscintí á measúnú agus arís ag am an ghlactha (✓ deimhnithe, ✗ gan deimhniú, — gan seiceáil).")

#intro(size: 9.4pt, gap: 8pt, "Tá an tábla comhlánaithe mar chuid den tairiscint agus tagann sé chun bheith ina iarscríbhinn a ghabhann leis an gconradh. Fíoraíonn sé go gcomhlíontar na ceanglais maidir le hábhar an chonartha (comhlíonta nó gan comhlíonadh); ní critéar dámhachtana é. Chun scór a thabhairt do chomhlíonadh, luaigh é sin i measc na gcritéar dámhachtana a fhoilsítear roimh ré sna doiciméid soláthair (Treoir 2014/24/AE, Airteagal 67).")

#score-sheet(
  headers: ("#", "Ceanglas (gearr)", "Tag. sonraíochta", "Riachtanach?", "C / E / N", "Fianaise: conas agus cá háit", "Fíoraithe"),
  roles: ("údarás", "tairgeoir", "tairgeoir", "coiste"),
  section("MIM0 · An féidir linn ár gcuid sonraí a fháil amach?",
    ("0.1", "Sonraí meaisín-inléite trí API caighdeánach gréasáin", "MIM0 R1.1, R1.2"),
    ("0.2", "Cur síos oscailte API (OpenAPI) ag seoladh cobhsaí", "MIM0 R1.3"),
    ("0.3", "Scagadh de réir ama, suímh, tréithe", "MIM0 R2.1, R2.2"),
    ("0.4", "Síntiús d'athruithe nuair is gá", "MIM0 R3.1"),
    ("0.5", "Earráidí caighdeánacha HTTP, taisceadh, teorainneacha ráta", "MIM0 C2"),
  ),
  section("MIM1 · An bhfuil ainm buan ar gach rud?",
    ("1.1", "Aitheantóir uathúil buan in aghaidh an eintitis", "MIM1 R1.1, R1.5"),
    ("1.2", "Aisghabhann cuardach aitheantóra sonraí + cineál", "MIM1 R1.2, R2.1, R2.2"),
    ("1.3", "Mapáil aitheantóirí thar chórais", "MIM1 R1.3, R1.4"),
    ("1.4", "Gan mionsonraí inmheánacha díoltóra in aitheantóirí", "MIM1 M1 §3.1"),
  ),
  section("MIM2 · An labhraímid teanga choiteann?",
    ("2.1", "Samhlacha sonraí caighdeánacha nuair is féidir", "MIM2 R1.2a"),
    ("2.2", "Samhlacha doiciméadaithe, aonaid shainráite", "MIM2 R1.1"),
    ("2.3", "Síntí mar phróifílí, gan a bheith ina ngabhail riamh", "MIM2 R1.2b, R4.1, R4.2"),
    ("2.4", "Srathú oscailte inbhailíochtaithe de réir scéime", "MIM2 R3.1, R3.4"),
  ),
  section("MIM3 · An féidir linn comhroinnt faoi théarmaí soiléire?",
    ("3.1", "Tacair shonraí catalógaithe le meiteashonraí caighdeánacha", "MIM3 RC4.1–RC4.3"),
    ("3.2", "Teimpléid ceadúnais agus comhaontuithe", "MIM3 RC2.2, RC2.3"),
    ("3.3", "Rialaíonn an chathair féin téarmaí rochtana", "MIM3 RC1.1, RC2.1"),
  ),
  section("MIM6 · An bhfuil ár gcuid sonraí sábháilte faoi bhealach agus in úsáid?",
    ("6.1", "Aistriú criptithe (TLS 1.3)", "MIM6 R2.1, M1.1"),
    ("6.2", "Logáil isteach chaighdeánach (OAuth 2.0 / OIDC)", "MIM6 R3.1, M1.2, M1.3"),
    ("6.3", "Rochtain rólbhunaithe + logaí iniúchta", "MIM6 R1.1, R1.3, 8.15"),
    ("6.4", "Ailíniú le ISO/IEC 27001:2022 léirithe", "MIM6 C1–C3 (ISO/IEC 27001)"),
  ),
  section("MIM7 · An oibríonn sé ar léarscáil?",
    ("7.1", "Comhéadain chaighdeánacha OGC", "MIM7 R1.1"),
    ("7.2", "Formáidí geo oscailte", "MIM7 R2.1"),
    ("7.3", "CRS dearbhaithe (EPSG)", "MIM7 R5.1"),
    ("7.4", "IDanna buana ar ghnéithe spásúla (féach 1.1)", "MIM7 R4.1"),
  ),
  section("MIM8 · An féidir lenár gcúpla digiteach fás?",
    ("8.1", "Sonraí cúpla agus aschuir trí APIanna", "MIM8 R1.1"),
    ("8.2", "Samhlacha doiciméadaithe agus inghlaoite", "MIM8 R3.1, R3.2"),
    ("8.3", "Formáidí caighdeánacha aschuir", "MIM8 M2"),
    ("8.4", "Bunús an tsreafa oibre taifeadta", "MIM8 R4.4"),
  ),
  section("Clásail thrasghearrtha tairisceana", accent: magenta, note: "Deimhníonn an tairgeoir go nglacann sé le coinníoll an chonartha (C / N).",
    ("X.1", "Clásal scoir: tabhairt ar láimh saor in aisce i bhformáidí oscailte", "—"),
    ("X.2", "Baineann cearta sna sonraí leis an údarás conarthach", "—"),
    ("X.3", "Gan aon táillí ar rochtain ar shonraí féin", "—"),
    ("X.4", "Cobhsaíocht API: leaganaithe, fógra 6 mhí faoi athruithe", "—"),
  ),
)

#note(size: 8.4pt, gap: 6pt, "Seasann lipéid ghearra thíos do na míreanna iomlána seicliosta ar leathanaigh na MIMs — i gcás amhrais, is é téacs iomlán na míre a bheidh i réim.")
#spec-link("Tá leagan ineagarthóireachta den tábla ag:", "https://marek-mraz.github.io/mims-procurement-checklist/")
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  GLOSSARY AND FURTHER READING
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glossary")[
  #band("Gluais bheag", id: "glossary")

  #glossary(
    term("API",
      "Bealach trína n-iarrann clár amháin sonraí ar chlár eile — thar an ngréasán, gan duine ag cliceáil."),
    term("Samhail sonraí",
      "Cruth comhaontaithe na sonraí: cad iad na réimsí atá ann, cad a chiallaíonn siad, cad iad na haonaid a úsáideann siad."),
    term("DCAT-AP",
      "Próifíl mheiteashonraí Eorpach do chatalóga sonraí; ligeann sí do thacair shonraí a bheith aimsithe ar thairseacha náisiúnta agus Eorpacha freisin."),
    term("EPSG",
      "Clárlann de chóid uimhriúla do chórais tagartha comhordanáidí (m.sh. EPSG:4326 do WGS 84)."),
    term("Aitheantóir",
      "Ainm buan ar rud amháin (lampa amháin, foirgneamh amháin) a úsáideann gach córas chun an rud sin a chur in iúl."),
    term("Idir-inoibritheacht",
      "Cumas córas ó dhíoltóirí éagsúla sonraí a mhalartú agus a thuiscint."),
    term("IRI",
      "Foirm idirnáisiúnta d'aitheantóir gréasáin (cosúil le URL, le carachtair neamh-ASCII ceadaithe). Ainmníonn MIM1 eintitis leis."),
    term("LDT",
      "Cúpla Digiteach Áitiúil: múnla digiteach de chathair nó de chuid di, ceangailte le sonraí agus ionsamhlúcháin."),
    term("Meaisín-inléite",
      "Struchtúrtha ionas gur féidir le clár é a phróiseáil go díreach (JSON, CSV) — níl PDF de thábla meaisín-inléite."),
    term("Meiteashonraí",
      "Sonraí faoi shonraí: cad atá i dtacar sonraí, cé a sholáthraíonn é, cé chomh reatha agus atá sé, faoi cén ceadúnas."),
    term("OAuth 2.0 / OIDC",
      "Caighdeáin oscailte do logáil isteach agus do dheonú rochtana. Cuireann OpenID Connect (OIDC) fíorú aitheantais le OAuth 2.0."),
    term("OGC",
      "Open Geospatial Consortium: an comhlacht a fhoilsíonn caighdeáin do shonraí agus do sheirbhísí geospásúla (OGC API, WFS, SensorThings)."),
    term("Caighdeán oscailte",
      "Riail theicniúil a fhéadfaidh aon duine a léamh agus a chur i bhfeidhm gan íoc as ná cead a iarraidh."),
    term("OpenAPI",
      "Formáid oscailte do chur síos meaisín-inléite ar API gréasáin: seoltaí, paraiméadair, freagraí."),
    term("Srathú",
      "Sonraí a scríobh i bhformáid nithiúil (m.sh. JSON, XML) ionas gur féidir iad a stóráil nó a sheoladh."),
    term("TLS",
      "An prótacal a chriptíonn sonraí faoi bhealach thar líonra (bunús HTTPS)."),
    term("Glasáil isteach ag díoltóir",
      "Nuair a chosnaíonn sé an oiread sin soláthraí a fhágáil — i sonraí, i bhformáidí nó i dtáillí — nach féidir leat é a dhéanamh go praiticiúil."),
    term("Crúca gréasáin / MQTT",
      "Dhá bhealach do chóras athrú a thuairisciú é féin: glaonn crúca gréasáin ar do sheoladh, seachadann MQTT teachtaireachtaí do rannpháirtithe."),
  )

  #more-links("Cá bhfaighfear tuilleadh eolais",
    more-link("mims.oascities.org", "Sonraíocht iomlán MIMs Plus, á cothabháil ag OASC."),
    more-link("living-in.eu", "An ghluaiseacht Eorpach um chlaochlú digiteach cathracha — dearbhú agus comhthéacs MIMs Plus."),
    more-link("smartdatamodels.org", "An leabharlann oscailte de shamhlacha sonraí caighdeánacha (FIWARE, TM Forum, IUDX, OASC)."),
    more-link("oascities.org/academy", "CITYxCITY Academy — cúrsaí d'fhoireann na cathrach, arna gcur ar fáil ag cathracha."),
  )
]


// ════════════════════════════════════════════════════════════════════════════
//  BACK COVER
// ════════════════════════════════════════════════════════════════════════════
#pagebreak()
#back-cover(
  "Tiomsaithe ó Shonraíocht MIMs Plus 9.0 le Open & Agile Smart Cities (mims.oascities.org). Ábhar na sonraíochta © OASC. Is compánach neamhspleách i ngnáth-theanga é an leabhrán seo do sholáthar bardasach; i gcás amhrais, is í an tsonraíocht a bheidh i réim.",
  "Déanta le huirlisí oscailte. Athúsáid agus cuir in oiriúint go saor do do chathair.",
  author: "Údar an leabhráin: Marek Mráz",
)
