// ════════════════════════════════════════════════════════════════════════════
//  MIMs procurement booklet, edition: it
//
//  GENERATED by gen_typ.py from content/it.json + shared.json + quotes.json.
//  Do not edit: change the JSON and run ./build.sh.
//
//  How to read it: the file runs top to bottom in page order. Each #name(…)
//  is one block on the page; what the block looks like (sizes, colours,
//  spacing) is described next to its definition in ../style.typ.
//  #fit-page("name")[ … ] is one physical page.
//  One-letter prepositions may be followed by a no-break space (U+00A0),
//  which looks like a normal space here.
//
//  Build:  typst compile --root .. --font-path ../tools/fonts booklet-it.typ
// ════════════════════════════════════════════════════════════════════════════
#import "../style.typ": *

#show: booklet.with(title: "Checklist per gli appalti · basata sui Meccanismi · Minimi di Interoperabilità · (MIM)", lang: "it",
  nav: (overview: "Panoramica", clauses: "Clausole", example: "Esempio", table: "Tabella di conformità", glossary: "Glossario", list: "Checklist", back: "torna alla checklist", page: "pag."),
  mims: ("MIM0", "MIM1", "MIM2", "MIM3", "MIM6", "MIM7", "MIM8",))


// ════════════════════════════════════════════════════════════════════════════
//  COVER
// ════════════════════════════════════════════════════════════════════════════
#cover(
  title:    "Checklist per gli appalti · basata sui Meccanismi · Minimi di Interoperabilità · (MIM)",
  subtitle: "Cosa inserire nel bando affinché il comune mantenga i propri dati",
  tagline:  "Per MIMs Plus 9.0 di OASC",
  footer:   "Per responsabili degli appalti, responsabili di progetto e CIO dei comuni europei",
  author:   "Autore della guida: Marek Mráz",
)


// ════════════════════════════════════════════════════════════════════════════
//  WHY THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("why")[
  #band("Perché questa guida")

  #lead("Ogni anno le città acquistano software: sistemi di sosta, piattaforme di sensori, portali cartografici, gemelli digitali. Troppo spesso i dati raccolti da questi sistemi finiscono per rimanervi bloccati all'interno. Al termine del contratto i dati — pagati con fondi pubblici — se ne vanno con il fornitore, oppure restano intrappolati in un formato illeggibile per chiunque altro.")

  #lead("Non deve necessariamente andare così. I Meccanismi Minimi di Interoperabilità (MIM), gestiti da Open & Agile Smart Cities (OASC) e approvati dal movimento europeo living-in.eu, definiscono i requisiti tecnici minimi che mantengono i dati aperti, riutilizzabili e neutrali rispetto ai fornitori. Sono volutamente essenziali: non una mastodontica architettura, ma solo le poche condizioni necessarie affinché i sistemi possano dialogare tra loro.")

  #lead("Non occorre essere ingegneri per usarli. Ogni checklist traduce un MIM in voci chiare e pratiche da copiare nei capitolati, indicando il motivo per cui ciascuna tutela l'ente. Subito dopo la checklist si trova ogni singolo requisito del MIM, parola per parola, affinché i colleghi tecnici e gli offerenti possano verificarne i dettagli.")

  #lead("Le città che richiedono i MIM acquistano una volta sola e riutilizzano molte volte: i dati sulla qualità dell'aria alimentano la dashboard delle scuole, l'inventario dell'illuminazione pubblica alimenta il piano energetico e il fornitore successivo riparte da dove il precedente ha concluso. Ecco cosa significa interoperabilità nella pratica — un requisito sempre più atteso nei progetti finanziati dall'UE.")

  #pull-quote(
    "I meccanismi minimi di interoperabilità (MIM) consentono un livello minimo ma sufficiente di interoperabilità per dati, sistemi e servizi, nello specifico nell'ambito delle soluzioni per le città intelligenti. · I destinatari previsti di questo documento sono: · 1. Fornitori di soluzioni che desiderano garantire che le proprie soluzioni siano interoperabili con altre e permettano uno scambio fluido di dati nel contesto di Città e Comunità Intelligenti. · 2. Acquirenti pubblici che intendono acquistare soluzioni a prova di futuro e consentire un'integrazione economicamente vantaggiosa all'interno di un'architettura ICT preesistente per Città e Comunità Intelligenti.",
  )

  #policy-box("In che modo i MIM si raccordano al diritto dell'UE",
    "I MIM sono una specifica tecnica, non una legge. Si muovono nella stessa direzione delle norme UE già applicabili a dati pubblici e servizi digitali:",
    law("Direttiva sugli appalti pubblici", "Direttiva 2014/24/UE, Articolo 42",
      "le specifiche tecniche possono fare riferimento a norme, sempre con la dicitura «o equivalente»; di norma non possono menzionare una fabbricazione o un prodotto specifici."),
    law("Data Act", "Regolamento (UE) 2023/2854",
      "accesso ai dati dei prodotti connessi e passaggio da un fornitore di servizi cloud all'altro senza vincoli (lock-in)."),
    law("Interoperable Europe Act", "Regolamento (UE) 2024/903",
      "valutazioni dell'interoperabilità per i servizi pubblici digitali transfrontalieri e riutilizzo di soluzioni aperte."),
    law("Direttiva Open Data", "Direttiva (UE) 2019/1024",
      "serie di dati di elevato valore pubblicate gratuitamente, in formato leggibile meccanicamente, mediante API."),
    law("Direttiva NIS 2", "Direttiva (UE) 2022/2555",
      "livello di base per la cibersicurezza; il diritto nazionale stabilisce in che misura si applica alla pubblica amministrazione locale."),
    law("GDPR", "Regolamento (UE) 2016/679",
      "dati personali nei sistemi cittadini (sosta, telecamere, mobilità)."),
    law("AI Act", "Regolamento (UE) 2024/1689",
      "regole per i sistemi di intelligenza artificiale; rilevante per i modelli di IA nei gemelli digitali."),
    note: "A solo scopo orientativo. Verificare come il proprio Paese ha recepito ciascun atto.",
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  HOW TO USE THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("howto")[
  #band("Come usare questa guida")

  #steps(
    step("Preparare",
      "Leggere le sette checklist. Selezionare quelle pertinenti all'oggetto dell'acquisto. La maggior parte delle gare richiede MIM0, MIM1, MIM2 e MIM6; aggiungere MIM3 se i dati sono condivisi con terzi o su un portale dati, MIM7 per mappe, MIM8 per gemelli digitali."),
    step("Appaltare",
      "Copiare le voci selezionate della checklist nelle specifiche tecniche. Ciascuna voce è formulata come frase pronta da incollare. Aggiungere le clausole trasversali: costano poco ed evitano il lock-in.",
      links: (("clauses", "Clausole"), ("example", "Esempio"), )),
    step("Valutare",
      "Chiedere agli offerenti di dimostrare, non promettere (si veda la clausola omonima). Verificare la conformità sulla base della tabella di conformità compilata dall'offerente.",
      links: (("table", "Tabella di conformità"), )),
    step("Collaudare",
      "Al momento del collaudo, riverificare ogni voce selezionata. Un requisito non testato alla consegna non è mai stato davvero un requisito.",
      links: (("table", "Tabella di conformità"), )),
  )

  #legend("Come leggere le citazioni della specifica",
    note: "Le voci della checklist usano «deve» anche laddove la specifica formula solo una raccomandazione (dovrebbe) o elenca un meccanismo candidato. Si tratta di una scelta della stazione appaltante.",
    entry("DEVE, DEVONO (SHALL / MUST)", "obbligatorio. Senza di esso il sistema non è conforme."),
    entry("NON DEVE, NON DEVONO (MUST NOT)", "vietato. Un sistema che lo fa non è conforme."),
    entry("DOVREBBE, DOVREBBERO (SHOULD)", "fortemente raccomandato. Le deroghe richiedono una valida motivazione scritta."),
    entry("PUÒ, POSSONO [FACOLTÀ] (MAY)", "facoltativo. Opportuno averlo, mai obbligatorio."),
    entry("PUÒ, POSSONO [POSSIBILITÀ] (CAN)", "una possibilità, non un requisito. Indica cosa è possibile e non obbliga nessuno."),
  )

  #note("Ciascuna voce della checklist riporta un riferimento sintetico come → MIM0 R1.1. Indica il requisito di MIMs Plus 9.0 da cui deriva; subito dopo la checklist si trova ogni requisito di quel MIM parola per parola. Solo MIM0 definisce le parole chiave: hanno valore prescrittivo se scritte in lettere maiuscole, secondo la convenzione delle norme IETF RFC 2119 e RFC 8174 (CAN deriva dalle Direttive ISO/IEC, Parte 2). Gli altri MIM non contengono definizioni: MIM6 scrive SHALL per lo più in maiuscolo, MIM2, MIM3, MIM7 e MIM8 scrivono shall, should e must in minuscolo, e MIM1 li impiega solo nella descrizione di un meccanismo (MUST NOT nella sezione 3.1). Questa guida interpreta i termini in minuscolo allo stesso modo; un offerente potrebbe interpretarli in senso meno vincolante.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  THE SEVEN MIMs AT A GLANCE
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glance")[
  #band("Sette MIM e tre strumenti", id: "glance")

  #intro("Sette meccanismi essenziali, un solo obiettivo: i dati restano tuoi e i tuoi sistemi possono dialogare tra loro.")

  #glance(
    note: "Sulla numerazione: MIMs Plus 9.0 specifica sette meccanismi, numerati 0, 1, 2, 3, 6, 7 e 8. MIM4 (dati personali) e MIM5 (IA equa) appartengono a versioni precedenti di OASC e non fanno parte della 9.0. Non manca nulla in questa guida.",
    card("MIM0", "Accesso ai dati",
      "Possiamo estrarre i nostri dati?",
      "I dati sono recuperabili tramite API web standard, in formati leggibili meccanicamente.",
      "https://mims.oascities.org/accessing-data"),
    card("MIM1", "Interconnessione dei dati",
      "Ogni cosa ha un identificatore durevole?",
      "Ogni sensore, lampione ed edificio ha un identificatore univoco e persistente.",
      "https://mims.oascities.org/interlinking-data"),
    card("MIM2", "Rappresentazione dei dati",
      "Parliamo un linguaggio comune?",
      "I dati seguono modelli dati standard e documentati, con unità di misura esplicite.",
      "https://mims.oascities.org/representing-data"),
    card("MIM3", "Scambio di dati",
      "Possiamo condividere a condizioni chiare?",
      "I dati sono catalogati e condivisi con licenze standard e una governance chiara.",
      "https://mims.oascities.org/exchanging-data"),
    card("MIM6", "Sicurezza dei dati",
      "I nostri dati sono al sicuro?",
      "Trasferimento cifrato, accessi standard, ruoli definiti e registri di audit.",
      "https://mims.oascities.org/securing-data"),
    card("MIM7", "Dati geospaziali",
      "Funziona su una mappa?",
      "I dati spaziali usano interfacce OGC, formati aperti e sistemi di coordinate dichiarati.",
      "https://mims.oascities.org/geospatial-data"),
    card("MIM8", "Gemelli digitali locali",
      "Il nostro gemello digitale può evolversi?",
      "Dati, modelli ed esiti del gemello restano accessibili, documentati e riutilizzabili.",
      "https://mims.oascities.org/local-digital-twins"),
  )

  #tools("Strumenti per la gara d'appalto",
    tool("clauses", "Clausole contrattuali trasversali",
      "Cosa deve esserci in ogni contratto?",
      "Uscita, diritti sui dati, stabilità delle API."),
    tool("example", "Esempio: sensori di qualità dell'aria",
      "Come si presenta nella pratica?",
      "Cosa inserire nei vari atti e testi di esempio da incollare."),
    tool("table", "Tabella di conformità",
      "Come lo dimostra l'offerente?",
      "Compilata dall'offerente, verificata dalla commissione, allegata al contratto."),
  )

  #menu-line(("glossary", "Piccolo glossario"), ("more", "Dove approfondire"))
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 checklist")[
  #mim-page(
    id:       "MIM0",
    name:     "Accesso ai dati",
    question: "Possiamo estrarre i nostri dati?",
    url:      "https://mims.oascities.org/accessing-data",
    intro:    "Questa è la base. Se i dati non possono uscire dal sistema tramite un'interfaccia standard, tutto il resto in questa guida rimane teoria. MIM0 richiede una sola cosa a ogni sistema acquistato: i dati devono essere accessibili, in formato leggibile meccanicamente, attraverso il normale web.",
    list:     "Checklist",
  )

  #item("Tutti i dati raccolti o generati dal sistema sono recuperabili in almeno un formato leggibile meccanicamente (es. JSON, CSV) tramite una normale API web.",
    why:  "L'appaltatore successivo — o il personale interno — può utilizzare i dati senza dipendere dal fornitore.",
    refs: "MIM0 R1.1, R1.2",
    num:  "0.1")

  #item("L'API è descritta formalmente in un documento aperto e leggibile meccanicamente (ad esempio OpenAPI) pubblicato a un indirizzo stabile.",
    why:  "Qualsiasi sviluppatore può connettersi senza dover pagare costose «giornate di integrazione».",
    refs: "MIM0 R1.3",
    num:  "0.2")

  #item("I dati possono essere filtrati per intervallo temporale, posizione geografica e attributi direttamente nell'API.",
    why:  "Si recupera solo ciò che serve, non un dump completo notturno.",
    refs: "MIM0 R2.1, R2.2",
    num:  "0.3")

  #item("Laddove il caso d'uso richieda dati in tempo reale, i fruitori possono iscriversi alle modifiche (webhook, MQTT o analoghi) invece di fare continue interrogazioni.",
    why:  "Dashboard in tempo reale e sistemi di allerta diventano possibili a costi contenuti.",
    refs: "MIM0 R3.1",
    num:  "0.4")

  #item("Gli errori, la memorizzazione nella cache e i limiti di frequenza seguono le convenzioni HTTP standard e sono documentati.",
    why:  "Le integrazioni falliscono in modo evidente e correggibile, non silente.",
    refs: "MIM0 C2",
    num:  "0.5")

  #panels(
    why:   ("Perché è importante", (
      "I dati già pagati restano utilizzabili anche al termine del contratto.",
      "I nuovi servizi si innestano sui dati esistenti senza dover ripartire da capo.",
      "I costi di integrazione diminuiscono per tutti i progetti futuri.",
    )),
    flags: ("Segnali d'allarme", (
      "«Esportazione dati su richiesta tramite la nostra assistenza.»",
      "«L'API è disponibile come modulo aggiuntivo a pagamento.»",
      "Tariffazione per singola richiesta per accedere ai dati del comune (si veda la clausola «Nessun costo per utente o richiesta»).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM0",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM0",
    capability("C1", "Machine-readable data is retrievable through the web",
      tr: "I dati leggibili meccanicamente sono recuperabili attraverso il web"),
    req("R1.1",
      tr: "I sistemi DEVONO consentire il recupero dei dati in almeno un formato leggibile meccanicamente. I formati possono essere specificati mediante la negoziazione dei contenuti HTTP",
      en: "Systems SHALL allow retrieval of data in at least one machine-readable format. Formats can be specified through HTTP Content-Negotiation"),
    req("R1.2",
      tr: "I dati DEVONO essere recuperabili tramite almeno un meccanismo standard basato sul web",
      en: "Data SHALL be retrievable via at least one standard web-based mechanism"),
    req("R1.3",
      tr: "I meccanismi di accesso DEVONO essere descritti formalmente",
      en: "Access mechanism(s) SHALL be formally described"),
    req("R1.4",
      tr: "I modelli dati utilizzati dal carico utile dovrebbero essere specificati (si veda MIM2)",
      en: "Data Models used by payloads should be specified (see MIM2)"),
    capability("C2", "Access is structured and queryable",
      tr: "L'accesso è strutturato e interrogabile"),
    req("R2.1",
      tr: "I sistemi DEVONO fornire i dati mediante un'interfaccia strutturata e coerente",
      en: "Systems SHALL provide data through a structured and consistent interface"),
    req("R2.2",
      tr: "I sistemi DEVONO supportare interrogazioni e/o filtri di base (ad es. per ora, luogo, attributi)",
      en: "Systems SHALL support basic querying and/or filtering (e.g. by time, location, attributes)"),
    capability("C2 best practice", "Additional best practice to consider:",
      tr: "Ulteriori migliori prassi da considerare:", sub: true),
    req("C2",
      tr: "Le API DOVREBBERO supportare il recupero dei dati correnti · Le API DOVREBBERO supportare il recupero dei dati storici ove applicabile · Le API DOVREBBERO supportare interrogazioni geospaziali ove applicabile (si veda MIM7) · Le API DOVREBBERO supportare l'iscrizione alle modifiche ove applicabile · Le API DOVREBBERO esporre la marca temporale del successivo aggiornamento previsto · Le API DOVREBBERO supportare il versionamento esplicito degli endpoint · Le API DOVREBBERO fornire carichi utili di esempio o query di test · Le API DOVREBBERO supportare le intestazioni standard di memorizzazione nella cache HTTP · Le API DOVREBBERO comunicare lo stato del limite di frequenza tramite intestazioni HTTP standard · Le API DOVREBBERO restituire corpi di errore strutturati · Le API POSSONO supportare risposte parziali o proiezioni di query · Le API POSSONO esporre un endpoint standard di stato/integrità",
      en: "APIs SHOULD support retrieval of current data · APIs SHOULD support retrieval of historical data when applicable · APIs SHOULD support geospatial querying when applicable (see MIM7) · APIs SHOULD support subscription to changes when applicable · APIs SHOULD expose next expected update timestamp · APIs SHOULD support explicit versioning of endpoints · APIs SHOULD provide example payloads or test queries · APIs SHOULD support standard HTTP caching headers · APIs SHOULD communicate rate limit status via standard HTTP headers · APIs SHOULD return structured error bodies · APIs MAY support partial responses or query projections · APIs MAY expose a standard health/status endpoint"),
    capability("C3", "Changes in data can be subscribed to",
      tr: "È possibile iscriversi alle modifiche dei dati"),
    req("R3.1",
      tr: "I sistemi per casi d'uso che richiedono notifiche DEVONO fornire almeno un meccanismo per ricevere aggiornamenti sulle modifiche dei dati",
      en: "Systems for use cases that require notifications SHALL provide at least one mechanism to receive updates on data changes"),
    req("R3.2",
      tr: "I sistemi POSSONO supportare molteplici meccanismi di iscrizione a seconda del caso d'uso",
      en: "Systems MAY support multiple subscription mechanisms depending on use case"),
    capability("C4", "Access to information can be restricted",
      tr: "L'accesso alle informazioni può essere limitato"),
    req("C4",
      tr: "Se tali restrizioni sono presenti, esse DEVONO seguire i requisiti definiti in MIM3 e MIM6, nello specifico: identificazione degli attori (MIM3.C5.R0), autorizzazione e ruoli degli attori (MIM6.C1.R4), policy a livello di risorsa di dati (MIM6.C1.R4)",
      en: "If such restrictions are in place, they SHALL follow the requirements defined in MIM3 and MIM6, specifically: actor identification (MIM3.C5.R0), authorization and actor roles (MIM6.C1.R4), data asset-level policies (MIM6.C1.R4)"),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/accessing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 checklist")[
  #mim-page(
    id:       "MIM1",
    name:     "Interconnessione dei dati",
    question: "Ogni cosa ha un identificatore durevole?",
    url:      "https://mims.oascities.org/interlinking-data",
    intro:    "Una città è fatta di cose: lampioni, tubature, edifici, stalli di sosta. I software vanno e vengono, ma le cose restano. MIM1 richiede che ogni cosa riceva un nome — un identificatore — che sopravviva al software che l'ha censita la prima volta, così che la sua cronologia e i collegamenti ad altri dati resistano a ogni migrazione.",
    list:     "Checklist",
  )

  #item("Ogni entità (sensore, lampione, edificio, stallo di sosta…) ha un identificatore univoco e persistente che non cambia con la sostituzione del software.",
    why:  "La cronologia e i collegamenti tra sistemi sopravvivono al cambio di fornitore.",
    refs: "MIM1 R1.1, R1.5",
    num:  "1.1")

  #item("L'identificatore può essere risolto per recuperare i dati dell'entità e il suo significato (tipo) in formato leggibile meccanicamente.",
    why:  "Gli altri sistemi possono seguire il collegamento automaticamente.",
    refs: "MIM1 R1.2, R2.1, R2.2",
    num:  "1.2")

  #item("Se la stessa cosa del mondo reale è presente in più sistemi, gli identificatori possono essere mappati tra loro.",
    why:  "L'edificio nel GIS e quello nella gestione energetica risultano con certezza lo stesso edificio.",
    refs: "MIM1 R1.3, R1.4",
    num:  "1.3")

  #item("Gli identificatori non contengono riferimenti interni del fornitore (ID di riga nel database, nomi dei server).",
    why:  "Altrimenti gli identificatori cessano con il contratto.",
    refs: "MIM1 M1 §3.1",
    num:  "1.4")

  #panels(
    why:   ("Perché è importante", (
      "Dieci anni di rilevazioni rimangono sempre associati al lampione corretto.",
      "I vari uffici smettono di gestire cinque registri discordanti degli stessi beni.",
      "Collegare insiemi di dati diventa una semplice interrogazione, non una costosa consulenza.",
    )),
    flags: ("Segnali d'allarme", (
      "«Gli ID sono a uso interno della nostra piattaforma.»",
      "Gli identificatori vengono rigenerati a ogni migrazione dei dati.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM1",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM1",
    capability("C1", "Entities are identified using unique identifiers",
      tr: "Le entità sono identificate tramite identificatori univoci"),
    req("R1.1",
      tr: "Ogni entità all'interno del sistema ha un identificatore univoco",
      en: "Every entity within the system has a unique identifier"),
    req("R1.2",
      tr: "Esiste un modo per recuperare informazioni su un'entità cercando l'identificatore all'interno di un sistema",
      en: "There exists a way to retrieve information about an entity by looking up the identifier within a system"),
    req("R1.3",
      tr: "se un identificatore univoco punta alla medesima entità all'interno di più sistemi, è possibile ricavare il modo per cercarne le informazioni in ciascuno di questi sistemi",
      en: "if a unique identifier points to the same entity within multiple systems, it is possible to derive the way to look up information about it in each of these systems"),
    req("R1.4",
      tr: "se molteplici identificatori univoci puntano alla stessa entità, è possibile mapparli tra loro",
      en: "if a multiple [sic] unique identifiers point to the same entity, it is possible to map them"),
    req("R1.5",
      tr: "È possibile creare identificatori che siano persistenti nel tempo",
      en: "It is possible to create identifiers that are persistent over time"),
    capability("C2", "Entities can be typed",
      tr: "Le entità POSSONO essere tipizzate"),
    req("R2.1",
      tr: "Esiste un modo per recuperare la semantica di un'entità, unicamente usando il suo identificatore univoco",
      en: "There is a way to retreive [sic] the semantics of an entity, only using its unique identifier"),
    req("R2.2",
      tr: "Tale semantica è descritta in un formato leggibile meccanicamente",
      en: "These semantics are described in a machine-readable format"),
    capability("C3", "Entities can be (de)referenced",
      tr: "Le entità possono essere (de)referenziate"),
    req("R3.1",
      tr: "Esiste un modo per dereferenziare una relazione definita su un'entità",
      en: "There exists a way to dereference a relation defined on an entity"),
    req("R3.2",
      tr: "Esiste un modo per applicare un'ulteriore semantica a un'ontologia esistente",
      en: "There exists a way to apply additional semantics to an existing ontology"),
    capability("M1", "Mechanism 1, section 3.1: Entity Identification with Globally Unique IRIs",
      tr: "Meccanismo 1, sezione 3.1: Identificazione delle entità con IRI globalmente univoci"),
    req("§3.1",
      tr: "L'IRI è trattato come l'identificatore canonico in tutti i sistemi a valle; le implementazioni NON DEVONO generare IRI che incorporino dettagli volatili di implementazione quali ID di riga del database o nomi host dei server.",
      en: "The IRI is treated as the canonical identifier in all downstream systems; implementations MUST NOT generate IRIs that embed volatile implementation details such as database row IDs or server hostnames."),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/interlinking-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 checklist")[
  #mim-page(
    id:       "MIM2",
    name:     "Rappresentazione dei dati",
    question: "Parliamo un linguaggio comune?",
    url:      "https://mims.oascities.org/representing-data",
    intro:    "Due sistemi possono entrambi esportare file JSON e ciononostante non capirsi affatto. MIM2 riguarda il significato: utilizzare modelli dati condivisi e documentati — con unità di misura e formati espliciti — affinché «temperatura», «stallo di sosta» o «qualità dell'aria» abbiano lo stesso significato in ogni sistema dell'ente.",
    list:     "Checklist",
  )

  #item("I dati adottano modelli dati standard ampiamente riconosciuti ovunque esistano (es. Smart Data Models, SAREF, ISO/IEC 5087); ogni deroga è motivata per iscritto.",
    why:  "I dati di due fornitori diversi si uniscono senza bisogno di progetti di conversione.",
    refs: "MIM2 R1.2a",
    num:  "2.1")

  #item("Tutti i modelli dati utilizzati sono esplicitamente documentati, con indicazione chiara delle unità di misura e dei formati di data e ora.",
    why:  "«Temperatura: 23» è un dato inutile se nessuno ha specificato se si tratta di °C o °F.",
    refs: "MIM2 R1.1",
    num:  "2.2")

  #item("Le estensioni sono fornite come profili o integrazioni documentate sul modello standard — mai come fork proprietari modificati.",
    why:  "Si mantiene la piena compatibilità con la comunità e con gli aggiornamenti futuri.",
    refs: "MIM2 R1.2b, R4.1, R4.2",
    num:  "2.3")

  #item("Ogni modello dispone di almeno una serializzazione aperta e validabile tramite schema (es. JSON con JSON Schema).",
    why:  "I dati in ingresso possono essere controllati automaticamente prima di essere acquisiti.",
    refs: "MIM2 R3.1, R3.4",
    num:  "2.4")

  #panels(
    why:   ("Perché è importante", (
      "Un'unica dashboard legge i dati di più fornitori senza necessità di adattatori.",
      "I dati della tua città sono compresi dagli applicativi di altri enti — e viceversa.",
      "La validazione automatica rileva i dati errati prima che si propaghino nel sistema.",
    )),
    flags: ("Segnali d'allarme", (
      "«Il nostro modello dati proprietario è molto più ricco di quello standard.»",
      "Documentazione disponibile solo sotto accordo di riservatezza (NDA).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM2",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM2",
    capability("C1", "All entities included in data sources are described using consistent data models to enable interoperability for applications and systems",
      tr: "Tutte le entità incluse nelle sorgenti di dati sono descritte mediante modelli dati coerenti per consentire l'interoperabilità tra applicazioni e sistemi"),
    req("R1.1",
      tr: "I modelli dati utilizzati per tutte le entità in qualsiasi sorgente di dati devono essere resi espliciti. Essi devono essere ben documentati e disporre di metadati descrittivi, dove i termini impiegati devono essere semanticamente univoci. Per gli attributi relativi a unità di misura, formati temporali ecc., le unità, i formati ecc., impiegati devono essere resi espliciti. I modelli dati dovrebbero essere catalogati in modo da essere facilmente reperibili.",
      en: "Data models used for all entities in any data source shall be made explicit. They shall be well documented and have descriptive metadata, where the terms used shall be semantically unambiguous. For attributes related to units of measurement, time formats etc, the units, formats etc, used shall be made explicit. The data models should be catalogued so that they can be easily findable."),
    req("R1.2a",
      tr: "I modelli dati utilizzati devono basarsi (ovunque possibile) su modelli dati standardizzati comunemente riconosciuti come elencati di seguito",
      en: "Data models used shall be based (wherever possible) on commonly recognised standardised data models as listed below"),
    req("R1.2b",
      tr: "Laddove non sia possibile utilizzare modelli dati standardizzati esistenti, devono essere compiuti sforzi per estendere i modelli dati standardizzati esistenti più affini o per definirne di nuovi, seguendo le migliori prassi e le convenzioni della comunità o dell'organizzazione che definisce i modelli dati.",
      en: "Where it is not possible to use existing standardised data models, efforts shall be made to extend existing standardised data models that are most closely aligned or to define new ones, following best practice and conventions of the community or organisation defining the data models."),
    req("R1.3",
      tr: "I modelli dati utilizzati devono supportare lo scambio di dati applicando i requisiti pertinenti dei MIM sull'Accesso ai dati e sull'Interconnessione dei dati",
      en: "Data models used shall support the exchange of data by using the relevant requirements of the MIMs on Accessing data and Interlinking data"),
    capability("C2", "Different data models for the same entity that are used within a common data sharing ecosystem should be easily transformable into a common data model",
      tr: "I diversi modelli dati utilizzati all'interno di un comune ecosistema di condivisione dei dati per la medesima entità dovrebbero essere facilmente trasformabili in un modello dati comune"),
    req("R2.1",
      tr: "Un modello dati comune per ogni entità fondamentale dovrebbe essere sviluppato per qualsiasi ecosistema di dati. Tale modello dati comune dovrebbe contenere tutti i campi inclusi nei diversi modelli dati utilizzati per quell'entità all'interno dell'ecosistema di dati. Ciascun diverso modello dati utilizzato all'interno dell'ecosistema di dati potrebbe quindi essere trasformato nel modello dati comune.",
      en: "A common data model for each key entity should be developed for any data ecosystem. That common data model should contain all the fields included within the different data models for that entity that are used within that data ecosystem. Each different data model used within that data ecosystem could then be transformed into the common data model."),
    capability("C3", "Any data and its associated metadata can be shared in open, standardised, data transport formats so that data can be exchanged and interpreted consistently by different tools and implementations",
      tr: "Tutti i dati e i relativi metadati possono essere condivisi in formati di trasporto dati aperti e standardizzati affinché possano essere scambiati e interpretati in modo coerente da strumenti e implementazioni differenti"),
    req("R3.1",
      tr: "Ogni modello dati utilizzato deve avere almeno un formato di trasporto dati leggibile meccanicamente («serializzazione») definito che sia aperto, accessibile al pubblico e indipendente dall'implementazione.",
      en: "Each data model used shall have at least one defined machine-readable data transport format (“serialisation”) that is open, publicly available and implementation-independent."),
    req("R3.2",
      tr: "La documentazione del formato di trasporto dati dovrebbe essere sufficiente a consentire la creazione di un'applicazione o interprete non proprietario in grado di ricostruire tutti i dati archiviati in tale formato.",
      en: "The documentation of the data transport format should be sufficient to allow the creation of non-proprietary application or interpretor that is able to reconstruct all the data stored in such a data format."),
    req("R3.3",
      tr: "Laddove siano supportati molteplici formati di trasporto dati per lo stesso modello dati, essi devono rappresentare lo stesso contenuto informativo in modo coerente e senza perdita di significato.",
      en: "Where multiple data transport formats are supported for the same data model, they shall represent the same information content consistently and without loss of meaning."),
    req("R3.4",
      tr: "La rappresentazione dovrebbe supportare la validazione mediante schemi, grammatiche o equivalenti vincoli leggibili meccanicamente pubblicati apertamente, laddove tali meccanismi di validazione esistano per il formato prescelto.",
      en: "The representation should support validation using openly published schemas, grammars, or equivalent machine-readable constraints, where such validation mechanisms exist for the chosen format."),
    capability("C4", "When useful, it should be possible to create \"Application Profiles\" for a data model, so that use case specific attributes can be added or specified without changing the underlying data model",
      tr: "Ove opportuno, dovrebbe essere possibile creare «Profili di Applicazione» per un modello dati, così da poter aggiungere o specificare attributi propri del caso d'uso senza modificare il modello dati sottostante"),
    req("R4.1",
      tr: "I Profili di Applicazione che estendono un modello dati non dovrebbero avere impatti sul modello preesistente e sui suoi utenti",
      en: "Application Profiles that extend a data model should not impact the already existing model and its users"),
    req("R4.2",
      tr: "Le specializzazioni o estensioni introdotte nel Profilo di Applicazione del modello dovrebbero essere ben documentate, separatamente dal modello dati di base",
      en: "The specialisations or extensions introduced in the Application Profile of the model should be well documented, separate from the base data model"),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/representing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 checklist")[
  #mim-page(
    id:       "MIM3",
    name:     "Scambio di dati",
    question: "Possiamo condividere a condizioni chiare?",
    url:      "https://mims.oascities.org/exchanging-data",
    intro:    "Non tutti i dati comunali possono essere semplicemente pubblicati: alcuni sono commerciali, altri riservati. MIM3 disciplina la condivisione sicura di tutti gli altri: un catalogo consultabile, licenze basate su modelli standard anziché clausole legali create ad hoc e regole di governance chiare per tutti. La specifica formula quasi tutto il MIM3 come raccomandazione (si veda pag. 3).",
    list:     "Checklist",
  )

  #item("Ogni serie di dati offerta dal sistema è descritta con metadati standard (ad esempio DCAT-AP) in un catalogo, affinché altri possano trovarla.",
    why:  "I dati che nessuno trova sono dati che nessuno usa.",
    refs: "MIM3 RC4.1–RC4.3",
    num:  "3.1")

  #item("Condizioni e licenze d'uso dei dati derivano da modelli consolidati (es. licenze aperte, accordi standard di condivisione dati), non da clausole create ad hoc.",
    why:  "Gli accordi scalano; l'ufficio legale non diventa un collo di bottiglia.",
    refs: "MIM3 RC2.2, RC2.3",
    num:  "3.2")

  #item("Il comune può stabilire chi può accedere a ciascuna risorsa di dati e a quali condizioni, modificando tali regole senza l'intervento del fornitore.",
    why:  "La governance resta in capo all'amministrazione comunale.",
    refs: "MIM3 RC1.1, RC2.1",
    num:  "3.3")

  #panels(
    why:   ("Perché è importante", (
      "Aziende e ricercatori locali creano valore sui dati comunali — l'indotto resta sul territorio.",
      "I dati riservati possono essere condivisi solo con partner qualificati, non con tutti o con nessuno.",
      "Un unico regolamento generale sostituisce decine di singoli contratti di condivisione.",
    )),
    flags: ("Segnali d'allarme", (
      "Il fornitore rivendica diritti sui dati dell'ente (si veda la clausola «Titolarità dei dati»).",
      "La condivisione con terzi richiede il consenso o il pagamento di canoni al fornitore.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM3",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM3",
    capability("C1", "Governance rules for the data sharing ecosystem can be defined",
      tr: "Le regole di governance per l'ecosistema di condivisione dei dati possono essere definite"),
    req("RC1.1",
      tr: "L'orchestratore di un ecosistema di dati dovrebbe essere in grado di definire un modello di governance (ad es. un regolamento) che delinei le regole di adesione, i ruoli, le responsabilità e gli obblighi dei partecipanti all'ecosistema, nonché i principi generali che ne regolano lo scambio di dati.",
      en: "The orchestrator of a data ecosystem should be able to define a governance model (e.g. a rulebook) that outlines membership rules, the roles, responsibilities and obligations of ecosystem participants, and the overall principles that govern data exchange between them."),
    req("RC1.2",
      tr: "I membri che partecipano a un ecosistema di dati dovrebbero essere a conoscenza del suo modello di governance e di qualsiasi modifica apportata allo stesso.",
      en: "Members who participate in a data ecosystem should be aware of its governance model and any changes made to it."),
    req("RC1.3",
      tr: "Il modello di governance dovrebbe essere facilmente comprensibile da parte di tutti i partecipanti all'ecosistema.",
      en: "The governance model should be easily comprehensible by all ecosystem participants."),
    capability("C2", "Terms and conditions for data sharing can be defined",
      tr: "Termini e condizioni per la condivisione dei dati possono essere definiti"),
    req("RC2.1",
      tr: "I fornitori di dati sono liberi di definire i termini e le condizioni a cui desiderano che i propri dati vengano scambiati. (Nota: prima di condividere risorse di dati, i fornitori di dati dovrebbero assicurarsi di disporre dell'adeguata autorizzazione da parte dei titolari dei dati.)",
      en: "Data providers are free to define terms and conditions under which they want their data to be exchanged. (Note: Before sharing data assets, data providers should ensure they have adequate permission from data owners.)"),
    req("RC2.2",
      tr: "Termini e condizioni per lo scambio di dati dovrebbero essere descritti in modo chiaro e inequivocabile affinché risultino facilmente comprensibili agli utenti dei dati.",
      en: "Terms and conditions for a data exchange should be described clearly and unambiguously so that they are easily understandable for data users."),
    req("RC2.3",
      tr: "Termini e condizioni per lo scambio di dati dovrebbero essere espressi mediante licenze sui dati o accordi di condivisione dei dati basati su modelli o standard ben definiti.",
      en: "Terms and conditions for a data exchange should be expressed through data licences or data sharing agreements based on well-defined templates or standards."),
    req("RC2.4",
      tr: "Termini e condizioni dovrebbero essere in linea con il modello generale di governance dell'ecosistema di dati e non devono essere in contrasto con esso. (Nota: un fornitore di dati può decidere di non partecipare a un ecosistema di dati se il modello di governance sottostante è troppo restrittivo o troppo permissivo.)",
      en: "Terms and conditions should be in line with the overall governance model of the data ecosystem and must not conflict with it. (Note: A data provider can decide not to participate in a data ecosystem if the underlying governance model is too restrictive or too permissive.)"),
    capability("C3", "Compliance with data sharing terms and conditions can be validated",
      tr: "La conformità ai termini e alle condizioni di condivisione dei dati può essere validata"),
    req("RC3.1",
      tr: "L'orchestratore di un ecosistema di dati deve essere in grado di accertare la conformità dei propri partecipanti al modello di governance sottostante.",
      en: "The orchestrator of a data ecosystem must be able to ascertain compliance of its participants with the underlying governance model."),
    req("RC3.2",
      tr: "I fornitori di dati dovrebbero essere in grado di accertare che l'uso dei dati da parte di un utente dei dati sia conforme ai termini e alle condizioni precedentemente concordati.",
      en: "Data providers should be able to ascertain that the use of data by a data user complies with previously agreed-upon terms and conditions."),
    req("RC3.3",
      tr: "Gli utenti dei dati dovrebbero essere in grado di accertare che la fornitura di dati da parte del fornitore di dati rispetti i termini e le condizioni precedentemente concordati.",
      en: "Data users should be able to ascertain that the data provider's supply of data follows previously agreed-upon terms and conditions."),
    capability("C4", "Available data assets can be discovered",
      tr: "Le risorse di dati disponibili possono essere scoperte"),
    req("RC4.1",
      tr: "Gli utenti dei dati dovrebbero essere in grado di scoprire quali dati sono disponibili in un ecosistema di condivisione dei dati senza averne conoscenza preventiva.",
      en: "Data users should be able to discover what data is available in a data sharing ecosystem without prior knowledge of it."),
    req("RC4.2",
      tr: "Le risorse di dati dovrebbero essere adeguatamente descritte con metadati affinché gli utenti dei dati possano prendere decisioni affidabili in merito all'uso ulteriore a cui sono destinate.",
      en: "Data assets should be adequately described with metadata so that data users can make reliable decisions about their further intended use."),
    req("RC4.3",
      tr: "I metadati utilizzati per descrivere le risorse di dati dovrebbero basarsi su formati di descrizione ben definiti e facili da comprendere, che siano leggibili sia dall'uomo sia da una macchina.",
      en: "Metadata used to describe data assets should be based on well-defined, easy-to-understand description formats that are both human- and machine-readable."),
    capability("C5", "Ecosystem participants can be discovered",
      tr: "I partecipanti all'ecosistema possono essere scoperti"),
    req("RC5.1",
      tr: "I partecipanti all'ecosistema (ad es. utenti e fornitori di dati) dovrebbero essere in grado di scoprirsi reciprocamente all'interno di un ecosistema di condivisione dei dati.",
      en: "Ecosystem participants (e.g. data users and providers) should be able to discover each other within a data-sharing ecosystem."),
    req("RC5.2",
      tr: "Metadati sufficienti su ciascun partecipante all'ecosistema dovrebbero essere disponibili per accertarne l'affidabilità rilevante ai fini dello scambio di dati.",
      en: "Sufficient metadata about each ecosystem participant should be available to ascertain their trustworthiness relevant for data exchange."),
    req("RC5.3",
      tr: "I fornitori di dati dovrebbero essere in grado di identificare in modo affidabile gli utenti dei dati che intendono accedere alle loro risorse di dati e di verificarne i metadati prima di concedere l'accesso.",
      en: "Data providers should be able to reliably identify data users who want to access their data assets and verify their metadata before granting access."),
    req("RC5.4",
      tr: "Gli utenti dei dati dovrebbero essere in grado di identificare i fornitori di dati che condividono dati in un ecosistema di dati prima di accedere a tali dati o di utilizzarli.",
      en: "Data users should be able to identify data providers who share data in a data ecosystem before accessing or using that data."),
    req("RC5.5",
      tr: "I partecipanti all'ecosistema possono anche scegliere di rimanere anonimi se il modello di governance dell'ecosistema di condivisione dei dati lo consente. In questo caso, i requisiti da RC5.1 a RC5.4 possono essere ignorati.",
      en: "Ecosystem participants may also choose to remain anonymous if the governance model of the data-sharing ecosystem allows for it. In this case, RC5.1 to RC5.4 can be ignored."),
    capability("C6", "Data exchange can be agreed upon",
      tr: "Lo scambio di dati può essere concordato"),
    req("RC6.1",
      tr: "Gli utenti e i fornitori di dati dovrebbero essere in grado di concordare uno scambio di dati e i relativi termini e condizioni (ad es. accettazione dei termini, firma formale di un accordo o negoziazione).",
      en: "Data users and providers should be able to agree to a data exchange and the terms and conditions associated with it (e.g. acceptance of terms, legal signature of an agreement, or negotiation)."),
    req("RC6.2",
      tr: "Gli utenti e i fornitori di dati dovrebbero essere in grado di risolvere uno scambio di dati precedentemente concordato in conformità con i termini e le condizioni a esso associati.",
      en: "Data users and providers should be able to terminate a previously agreed-upon data exchange in accordance with the terms and conditions associated with it."),
    req("RC6.3",
      tr: "Ove possibile, possono essere forniti strumenti elettronici per la stipula e la risoluzione di uno scambio di dati.",
      en: "Where possible, electronic means for the agreement and termination of a data exchange may be provided."),
    capability("C7", "New data currently not available can be requested",
      tr: "Nuovi dati attualmente non disponibili possono essere richiesti"),
    req("RC7.1",
      tr: "Gli utenti dei dati dovrebbero essere in grado di esprimere il proprio interesse per risorse di dati attualmente non disponibili nell'ecosistema di condivisione dei dati.",
      en: "Data users should be able to express their interest in data assets currently unavailable in the data sharing ecosystem."),
    req("RC7.2",
      tr: "I fornitori di dati dovrebbero essere in grado di ricevere le richieste avanzate dagli utenti dei dati per nuove risorse di dati.",
      en: "Data providers should be able to obtain requests made by data users for new data assets."),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/exchanging-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 checklist")[
  #mim-page(
    id:       "MIM6",
    name:     "Sicurezza dei dati",
    question: "I nostri dati sono al sicuro in transito e durante l'uso?",
    url:      "https://mims.oascities.org/securing-data",
    intro:    "Le smart city sono bersagli sensibili. MIM6 mantiene un perimetro mirato e concreto: cifrare i dati in transito, adottare sistemi di autenticazione standard anziché proprietari, controllare e registrare chi accede a cosa. Nulla di esotico — ma ogni elemento deve figurare nel contratto.",
    list:     "Checklist",
  )

  #item("Tutti i trasferimenti di dati sono cifrati (TLS 1.3 o le migliori prassi attuali).",
    why:  "Sicurezza informatica di base; richiesta anche dalla direttiva NIS 2 ove applicabile.",
    refs: "MIM6 R2.1, M1.1",
    num:  "6.1")

  #item("L'autenticazione di utenti e applicazioni usa standard aperti — OAuth 2.0 / OpenID Connect — e si integra con il provider di identità del comune.",
    why:  "Una sola utenza per dipendente, non una per fornitore; chi lascia l'ente perde subito ogni accesso.",
    refs: "MIM6 R3.1, M1.2, M1.3",
    num:  "6.2")

  #item("I diritti di accesso si basano su ruoli, sono revocabili e verificabili; gli accessi e le operazioni di amministrazione sono registrati.",
    why:  "Verifiche ispettive e gestione degli incidenti diventano possibili. Il logging è previsto dal controllo 8.15 dell'ISO/IEC 27001:2022, prerequisito di MIM6.",
    refs: "MIM6 R1.1, R1.3, 8.15",
    num:  "6.3")

  #item("Il fornitore deve dimostrare la conformità a ISO/IEC 27001:2022 (o equivalente) per il servizio gestito.",
    why:  "La sicurezza è un processo continuo, non una casella da spuntare alla consegna. La specifica cita i controlli ISO/IEC 27001, non un certificato formale.",
    refs: "MIM6 C1–C3 (ISO/IEC 27001)",
    num:  "6.4",
    label: "Da inserire nei criteri di selezione, non nelle specifiche tecniche")

  #panels(
    why:   ("Perché è importante", (
      "Una violazione in un sistema non apre ogni sistema.",
      "Ove applicabile la direttiva NIS 2, rispettare le norme nazionali sulla cibersicurezza risulta assai più agevole.",
      "Quando qualcosa non va, i log dicono cosa e chi.",
    )),
    flags: ("Segnali d'allarme", (
      "Solo accesso proprietario.",
      "«Log disponibili su richiesta.»",
      "Account amministrativi condivisi.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM6",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM6",
    capability("C1", "Data is only accessible to users that should have access to it",
      tr: "I dati sono accessibili esclusivamente agli utenti che dovrebbero avervi accesso"),
    req("R1.1",
      tr: "Le regole per il controllo dell'accesso fisico e logico alle informazioni e agli altri asset associati DEVONO essere definite e implementate sulla base dei requisiti di business e di sicurezza delle informazioni. (ISO 27001 5.15 Controllo degli accessi)",
      en: "Rules to control physical and logical access to information and other associated assets SHALL be established and implemented based on business and information security requirements. (ISO 27001 5.15 Access control)"),
    req("R1.2",
      tr: "L'assegnazione e la gestione delle informazioni di autenticazione DEVONO essere regolate da un processo di gestione, compresa l'istruzione del personale sulla corretta gestione delle informazioni di autenticazione. (ISO 27001 5.17: Informazioni di autenticazione)",
      en: "Allocation and management of authentication information SHALL be controlled by a management process, including advising personnel on appropriate handling of authentication information. (ISO 27001 5.17: Authentication information)"),
    req("R1.3",
      tr: "I diritti di accesso alle informazioni e agli altri asset associati DEVONO essere assegnati, riesaminati, modificati e revocati in conformità alla specifica politica dell'organizzazione e alle regole per il controllo degli accessi. (ISO 27001 5.18: Diritti di accesso)",
      en: "Access rights to information and other associated assets SHALL be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control. (ISO 27001 5.18: Access rights)"),
    capability("C2", "Data accessed by users has not been altered",
      tr: "I dati a cui gli utenti accedono non hanno subito alterazioni"),
    req("R2.1",
      tr: "Le regole per l'uso efficace della crittografia, compresa la gestione delle chiavi crittografiche, DEVONO essere definite e implementate. (ISO 27001 8.24 Uso della crittografia)",
      en: "Rules for the effective use of cryptography, including cryptographic key management, SHALL be defined and implemented. (ISO 27001 8.24 Use of cryptography)"),
    capability("C3", "Data accessed by users originates from a verified source",
      tr: "I dati a cui gli utenti accedono provengono da una sorgente verificata"),
    req("R3.1",
      tr: "Le tecnologie e le procedure di autenticazione sicura devono essere implementate sulla base delle restrizioni di accesso alle informazioni e della politica specifica per il controllo degli accessi. (ISO 27001 8.5 Autenticazione sicura)",
      en: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control. (ISO 27001 8.5 Secure authentication)"),
    capability("M1", "Mechanism candidate",
      tr: "Candidato al meccanismo"),
    req("M1.1",
      tr: "Il protocollo Transport Layer Security (TLS), Versione 1.3",
      en: "The Transport Layer Security (TLS) Protocol, Version 1.3"),
    req("M1.2",
      tr: "Il framework di autorizzazione OAuth 2.0",
      en: "The OAuth 2.0 Authorization Framework"),
    req("M1.3",
      tr: "OpenID Connect 1.0, Livello di identità per l'autenticazione su OAuth 2.0",
      en: "OpenID Connect 1.0, Identity layer for authentication on OAuth 2.0"),
    req("M1.4",
      tr: "OIDC4VCI / OIDC4VP, OpenID per il rilascio e la presentazione di credenziali verificabili",
      en: "OIDC4VCI / OIDC4VP, OpenID for Verifiable Credential Issuance and Presentations"),
    capability("P", "Pre- and Post-requisites (based on ISO 27001 Annex A): the control this booklet refers to",
      tr: "Prerequisiti e requisiti successivi (basati su ISO 27001 Allegato A): il controllo a cui fa riferimento questa guida"),
    req("8.15",
      tr: "Registrazione delle attività (logging). I registri che tengono traccia di attività, eccezioni, anomalie e altri eventi rilevanti devono essere prodotti, archiviati, protetti e analizzati.",
      en: "Logging. Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed."),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/securing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 checklist")[
  #mim-page(
    id:       "MIM7",
    name:     "Dati geospaziali",
    question: "Funziona su una mappa?",
    url:      "https://mims.oascities.org/geospatial-data",
    intro:    "Quasi ogni risorsa di una città ha una collocazione nello spazio. MIM7 assicura che tale posizione non sia una mera schermata grafica: i dati spaziali transitano mediante interfacce OGC standard, in formati aperti, con sistema di coordinate sempre dichiarato — affinché ogni strato cartografico acquisito si sovrapponga a quelli già in uso.",
    list:     "Checklist",
  )

  #item("I dati geospaziali sono esposti mediante interfacce standardizzate (OGC API Features, SensorThings; WFS accettato per sistemi preesistenti).",
    why:  "Qualsiasi applicativo GIS disponibile sul mercato può leggerli nativamente.",
    refs: "MIM7 R1.1",
    num:  "7.1")

  #item("I dati geospaziali sono codificati in formati aperti (GeoJSON, CityJSON; GML/CityGML ove prescritto).",
    why:  "Nessuna licenza di conversione, nessun vicolo cieco.",
    refs: "MIM7 R2.1",
    num:  "7.2")

  #item("Il sistema di coordinate di riferimento è sempre dichiarato (codice EPSG) e i dati sono convertibili in un CRS comune.",
    why:  "I diversi strati informativi cartografici combaciano perfettamente sulla mappa.",
    refs: "MIM7 R5.1",
    num:  "7.3")

  #item("Gli elementi spaziali utilizzano gli stessi identificatori persistenti previsti da MIM1.",
    why:  "Il punto visualizzato sulla mappa e la voce presente nel registro descrivono la medesima cosa.",
    refs: "MIM7 R4.1",
    num:  "7.4")

  #panels(
    why:   ("Perché è importante", (
      "Un'unica mappa della città invece di dieci visualizzatori di fornitori.",
      "Rispettare gli obblighi della direttiva INSPIRE e dei geoportali nazionali diventa più semplice.",
      "I dati 3D e BIM possono unirsi al medesimo quadro in seguito.",
    )),
    flags: ("Segnali d'allarme", (
      "I dati cartografici risiedono solo nel visualizzatore del fornitore.",
      "«Esportazione come PDF/schermata.»",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM7",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM7",
    capability("C1", "Cities and communities can easily transfer geospatial data between internal and external (including IoT-related) IT systems",
      tr: "Città e comunità possono trasferire agevolmente dati geospaziali tra sistemi informatici interni ed esterni (inclusi quelli correlati all'IoT)"),
    req("R1.1",
      tr: "I dati geospaziali devono essere esposti mediante un'interfaccia di servizio web basata su standard.",
      en: "Geospatial data shall be exposed through a standards-based web service interface."),
    capability("C2", "Cities and communities can integrate 2D and 3D geospatial data coming from a variety of sources, for example geodata and building information models, and share that data within and between them in an interoperable way",
      tr: "Città e comunità possono integrare dati geospaziali 2D e 3D provenienti da fonti eterogenee, come dati geografici e modelli BIM, condividendoli al proprio interno e tra loro in modo interoperabile"),
    req("R2.1",
      tr: "I dati geospaziali devono essere codificati utilizzando standard aperti. Si raccomanda di utilizzare gli standard pertinenti di OGC e di BuildingSMART International.",
      en: "Geospatial data shall be encoded using open standards. It is recommended to use relevant standards from OGC and BuildingSMART International."),
    capability("C3", "Cities and communities can integrate geospatial data with other data that can provide further information about the context",
      tr: "Città e comunità possono integrare i dati geospaziali con altri dati in grado di offrire maggiori informazioni sul contesto"),
    req("R3.1",
      tr: "Tutte le serie di dati utilizzate per fornire ulteriori informazioni sul contesto coperto dai dati geospaziali devono essere conformi a MIM1 e MIM2.",
      en: "All data sets used to provide further information about the context covered by geospatial data shall comply with MIM1 and MIM2."),
    capability("C4", "Cities and communities have a consistent and persistent way of describing individual instances of all features, things or entities included in the geospatial data sources",
      tr: "Città e comunità dispongono di una modalità coerente e persistente per descrivere le singole istanze di tutti gli elementi, oggetti o entità presenti nelle sorgenti di dati geospaziali"),
    req("R4.1",
      tr: "Devono essere utilizzati identificatori univoci e persistenti per identificare le singole istanze di qualsiasi entità utilizzata nelle serie di dati. (Si veda MIM1: Interconnessione dei dati.)",
      en: "Unique and persistent identifiers shall be used to identify particular instances of any entity used in data sets. (See MIM1: Interlinking Data.)"),
    capability("C5", "Coordinate Reference Systems (CRS) used in data sharing are easily transformable into a common CRS",
      tr: "I sistemi di riferimento di coordinate (CRS) impiegati nella condivisione dei dati sono facilmente convertibili in un CRS comune"),
    req("R5.1",
      tr: "I sistemi di riferimento di coordinate (CRS) devono essere conformi agli standard e devono essere fornite informazioni in merito allo standard utilizzato (es. EPSG:4326, EPSG:3857). Ciò comprende il codice EPSG o il codice WGS, unitamente alle informazioni su qualsiasi variante basata su sistemi nazionali come il lettone LKS-92, in modo che i dati possano essere convertiti in un CRS comune. (Nota: all'interno dell'UE, per i dati geospaziali è richiesto l'uso di metadati conformi alla direttiva INSPIRE, inclusi i metadati necessari per descrivere le informazioni sul CRS.)",
      en: "Coordinate Reference Systems (CRS) shall comply with standards, and information shall be provided regarding which standard (e.g. EPSG:4326, EPSG:3857) is being used. This includes the EPSG number or WGS number, along with information about any variation based on national systems such as the Latvian LKS-92, so that data can be transformed to a common CRS. (Note: Within the EU, for geospatial data it is required to use metadata compliant with the INSPIRE Directive, including the metadata needed to describe the CRS information.)"),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/geospatial-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 checklist")[
  #mim-page(
    id:       "MIM8",
    name:     "Gemelli digitali locali",
    question: "Il nostro gemello digitale può evolversi?",
    url:      "https://mims.oascities.org/local-digital-twins",
    intro:    "Un gemello digitale è un investimento di lungo periodo: dati, modelli 3D, simulazioni, decisioni. MIM8 tutela questo investimento: dati e modelli restano accessibili e documentati, i risultati sono riproducibili e i moduli sviluppati per un progetto possono servire al successivo. Usare questa pagina per piattaforme di gemelli, modelli o strumenti 3D.",
    list:     "Checklist",
  )

  #item("Serie di dati, parametri di input e risultati delle simulazioni sono accessibili tramite API (secondo MIM0), non vincolati alla piattaforma.",
    why:  "I risultati alimentano relazioni, dashboard e il progetto successivo.",
    refs: "MIM8 R1.1",
    num:  "8.1")

  #item("I modelli sono documentati (metodo, parametri, input/output) e invocabili tramite un'interfaccia documentata.",
    why:  "Un modello idraulico acquistato una volta può essere riutilizzato da altri uffici e da altri enti.",
    refs: "MIM8 R3.1, R3.2",
    num:  "8.2")

  #item("Gli output usano formati aperti e standard (GeoJSON, CityJSON, 3D Tiles, NetCDF…) elaborabili con strumenti di terze parti.",
    why:  "Visualizzazione e analisi restano mercati concorrenziali.",
    refs: "MIM8 M2",
    num:  "8.3")

  #item("I flussi di lavoro tracciano la provenienza: quale versione dei dati, quale modello e quali parametri hanno generato un risultato.",
    why:  "Le decisioni basate sulle simulazioni possono essere motivate e difese con precisione in seguito.",
    refs: "MIM8 R4.4",
    num:  "8.4")

  #panels(
    why:   ("Perché è importante", (
      "Il gemello sopravvive al singolo fornitore o budget di progetto.",
      "Le simulazioni possono essere verificate, ripetute e poste a base delle decisioni dell'ente.",
      "Modelli e componenti possono essere condivisi tra città.",
    )),
    flags: ("Segnali d'allarme", (
      "Risultati delle simulazioni consultabili solo all'interno del portale del fornitore.",
      "Modelli come scatole nere sigillate senza metadati.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM8",
    title:  "Cosa dice la specifica",
    leadin: "Ogni requisito di questo MIM, testuale da MIMs Plus 9.0: La specifica esiste solo in lingua inglese: il testo in italiano è una traduzione non ufficiale a cura dell'autore di questa guida; il testo originale inglese sottostante fa fede.",
    back:   "torna alla checklist",
  )

  #spec-list(mim: "MIM8",
    capability("C1", "Provide access to datasets used within the LDT, including static, real-time, and simulation data and calculation models",
      tr: "Fornire l'accesso alle serie di dati impiegate nel gemello digitale locale, compresi dati statici, in tempo reale e di simulazione, nonché ai modelli di calcolo"),
    req("R1.1",
      tr: "Il gemello digitale locale deve fornire l'accesso ai risultati delle simulazioni e agli input dei modelli di calcolo laddove siano necessari nell'ambito dei flussi di lavoro del gemello stesso.",
      en: "The LDT shall provide access to simulation outputs and calculation-model inputs where these are needed as part of LDT workflows."),
    req("R1.2",
      tr: "Il gemello digitale locale dovrebbe distinguere chiaramente tra dati di origine grezzi, dati trasformati pronti per il flusso di lavoro, input dei modelli e output dei modelli.",
      en: "The LDT should distinguish clearly between raw source data, transformed workflow-ready data, model inputs, and model outputs."),
    capability("C2", "Exchange data with external systems and other LDTs using interoperable interfaces",
      tr: "Scambiare dati con sistemi esterni e con altri gemelli digitali locali impiegando interfacce interoperabili"),
    req("C2",
      tr: "Questa capacità fa affidamento su MIM3 (Scambio di dati) per lo scambio dei dati.",
      en: "This capability relies on MIM3 (Exchanging Data) for data exchange."),
    capability("C3", "Reuse deterministic or AI models across different domains, communities, use cases, and/or LDTs",
      tr: "Riutilizzare modelli deterministici o di IA tra differenti domini, comunità, casi d'uso e/o gemelli digitali locali"),
    req("R3.1",
      tr: "Il modello dovrebbe fornire metadati standard del modello, comprendenti una descrizione dei relativi metodi e parametri, e i parametri dei dati (sia per valore sia per riferimento). A tale scopo dovrebbero essere utilizzati standard comuni di metadati.",
      en: "The model should provide standard model metadata, including a description of its methods and parameters, and data-parameters (either by value or by reference). To this end common metadata standards should be used."),
    req("R3.2",
      tr: "Il modello deve esporre o essere invocabile attraverso un'interfaccia documentata, preferibilmente utilizzando un'API standardizzata nota. La serie di dati che costituisce il risultato del modello deve essere descritta (a livello di dati).",
      en: "The model shall expose or be callable through a documented interface, preferably using a known standardised API. The dataset that forms the outcome of the model shall be described (at data-level)."),
    req("R3.3",
      tr: "Un uso affidabile, fidato ed etico dei metodi innovativi (LLM, IA agentica, ecc.) dovrebbe essere salvaguardato. Le distorsioni (bias) dovrebbero essere ridotte al minimo ove applicabile. I metodi impiegati per garantire ciò dovrebbero essere descritti.",
      en: "Trustworthy, reliable, and ethical use of innovative methods (LLMs, agentic AI, etc.) should be safeguarded. Bias should minimised [sic] where applicable. The methods used to guarantee this, should be described."),
    req("R3.4",
      tr: "Il modello deve essere in grado di accedere ai dati per conto dell'utente finale o dell'organizzazione. Si veda MIM3",
      en: "The model must be able to access data on behalf of the end-user or organisation. See MIM3"),
    req("R3.5",
      tr: "Affinché i dati possano essere utilizzati nei modelli di IA, la provenienza e l'affidabilità dovrebbero essere garantite. In alcuni casi, deve essere indicata una fonte autorevole, come un'agenzia governativa.",
      en: "For data to be used in AI models, provenance and trust should be guaranteed. In some cases, an authoratitive sourc [sic], such as a government agency must be listed."),
    capability("C4", "Coordinate and manage data, models, and processing workflows within an LDT (intra-LDT) and across LDTs (inter-LDT)",
      tr: "Coordinare e gestire dati, modelli e flussi di elaborazione all'interno di un gemello digitale locale (intra-LDT) e tra diversi gemelli digitali locali (inter-LDT)"),
    req("R4.1",
      tr: "Il gemello digitale locale supporta flussi di lavoro che connettono sorgenti di dati, trasformazioni dei dati, esecuzione di modelli, processi di simulazione e risultati.",
      en: "The LDT supports workflows that connect data sources, data transformations, model execution, simulation processes, and outputs."),
    req("R4.2",
      tr: "Il gemello digitale locale concatena le fasi del flusso di lavoro, in cui l'output di una fase può essere utilizzato come input per un'altra.",
      en: "The LDT chains workflow steps, where the output of one step can be used as the input for another."),
    req("R4.3",
      tr: "Il gemello digitale locale monitora lo stato di esecuzione del flusso di lavoro, compresi i processi completati, non riusciti e interrotti.",
      en: "The LDT monitors workflow execution status, including completed, failed, and interrupted processes."),
    req("R4.4",
      tr: "Il gemello digitale locale registra la provenienza del flusso di lavoro, comprese le serie di dati utilizzate (con versione e marca temporale), i modelli eseguiti, i parametri selezionati e i risultati generati.",
      en: "The LDT records workflow provenance, including datasets used (including version, timestamped), models executed, parameters selected, and outputs generated."),
    capability("C5", "Provide multiple visualisations of data and results (e.g. 2D, 3D, dashboards) from common underlying data and models for interaction and comparison",
      tr: "Offrire molteplici visualizzazioni di dati e risultati (es. 2D, 3D, dashboard) a partire da dati e modelli sottostanti condivisi per l'interazione e il confronto"),
    req("R5.1",
      tr: "Il gemello digitale locale fornisce metadati che spiegano cosa viene visualizzato, comprendenti marca temporale, ambito spaziale, sorgente di dati e, ove rilevante, ipotesi di scenari e varianti.",
      en: "The LDT provides metadata explaining what is visualised, including timestamp, spatial scope, data source, and scenario- and variant-assumptions where relevant."),
    req("R5.2",
      tr: "Il gemello digitale locale supporta diversi tipi di visualizzazione interattiva, come mappe 2D, scene 3D, dashboard, report o viste accessibili al pubblico.",
      en: "The LDT supports different interactive visualisation types, such as 2D maps, 3D scenes, dashboards, reports, or public-facing views."),
    capability("C6", "Ensure that data exchanged (and simulation outputs) within and between LDTs can be interpreted consistently through shared or mapped semantics and clear provenance",
      tr: "Garantire che i dati scambiati (e i risultati delle simulazioni) all'interno di e tra gemelli digitali locali possano essere interpretati in modo coerente attraverso semantiche condivise o mappate e una chiara provenienza"),
    req("R6.1",
      tr: "Il gemello digitale locale dovrebbe documentare disallineamenti semantici irrisolti, ipotesi o mappature che potrebbero influenzare l'interpretazione, il riutilizzo o il confronto dei risultati.",
      en: "The LDT should document unresolved semantic gaps, assumptions, or mappings that may affect the interpretation, reuse, or comparison of results."),
    capability("M", "Mechanisms (under active development)",
      tr: "Meccanismi (in corso di sviluppo)"),
    req("M1",
      tr: "Accesso alle risorse LDT basato su API",
      en: "API-based LDT Resource Access"),
    req("M2",
      tr: "Formati standardizzati di dati e output",
      en: "Standardised Data and Output Formats"),
    req("M3",
      tr: "Model-as-a-Service",
      en: "Model-as-a-Service"),
    req("M4",
      tr: "Orchestrazione dei flussi di lavoro LDT",
      en: "LDT Workflow Orchestration"),
    req("M5",
      tr: "Accesso a viste multiple di output e visualizzazione",
      en: "Multi-view Output and Visualisation Access"),
  )

  #spec-link("Specifica completa:", "https://mims.oascities.org/local-digital-twins")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  CROSS-CUTTING CONTRACT CLAUSES
// ════════════════════════════════════════════════════════════════════════════
#fit-page("clauses")[
  #band("Clausole contrattuali trasversali", sub: "Misure di tutela contro il lock-in", id: "clauses")

  #intro(size: 9.8pt, "Queste clausole dovrebbero comparire in ogni bando, a prescindere dall'oggetto della fornitura. Derivano dalla prassi degli appalti legata ai MIM e a living-in.eu. La maggior parte non poggia su un singolo requisito tecnico, pertanto non riporta codici di riferimento (il versionamento delle API è anche una raccomandazione di MIM0 C2). Hanno un impatto economico nullo; ometterle può costare moltissimo.")

  #clauses(
    clause("Clausola di uscita (exit clause)",
      "Alla scadenza contrattuale, tutti i dati dell'ente (e le configurazioni) sono restituiti in formati aperti e documentati, senza costi aggiuntivi."),
    clause("Titolarità dei dati",
      "Tutti i diritti sui dati raccolti ed elaborati nell'ambito dell'esecuzione del contratto appartengono esclusivamente alla stazione appaltante."),
    clause("Nessun costo per utente o richiesta",
      "Nessun costo per l'accesso della città ai propri dati."),
    clause("Stabilità e versionamento delle API",
      "L'appaltatore garantisce la retrocompatibilità dell'API per l'intera durata del contratto. Le modifiche sostanziali sono comunicate con almeno 6 mesi di anticipo e rilasciate in una nuova versione, mantenendo attiva la precedente fino alla data concordata per la dismissione."),
    clause("Dimostrare, non promettere",
      "I concorrenti dimostrano la conformità in sede di valutazione delle offerte anziché limitarsi a dichiararla. Per le API ciò richiede documentazione interattiva pubblica (es. OpenAPI) e una chiamata di test attiva con dati validi. Ogni voce selezionata è nuovamente collaudata alla consegna."),
    clause("Standard aperti specificati",
      "Il bando indica gli standard richiamati; le dichiarazioni di conformità devono specificare l'interfaccia esatta e la versione. Ogni richiamo a norme o specifiche tecniche consente una soluzione equivalente; l'onere della prova dell'equivalenza incombe sull'offerente."),
    clause("Dichiarazione di conformità ai MIM",
      "L'offerente compila la tabella di conformità (pag. 23), che costituirà parte integrante del contratto d'appalto."),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT
// ════════════════════════════════════════════════════════════════════════════
#fit-page("example")[
  #band("Esempio: appalto per una rete di sensori di qualità dell'aria", id: "example")

  #intro(size: 9.8pt, "Pagine selezionate: MIM0, MIM1, MIM2, MIM6 e MIM7 (i dati vanno su mappa). Da MIM3 solo la voce 3.1 (i dati sull'aria sono aperti, vanno catalogati); escluso MIM8: non si tratta di un gemello digitale.")

  #text(size: 10pt, weight: "bold", fill: eu-blue, "Cosa inserire nei vari documenti di gara")
  #v(4pt)

  #doc-table(
    ("Documento", "Termine nella Direttiva 2014/24/UE", "Contenuto da inserire"),
    (
      ("Capitolato tecnico",
       "specifiche tecniche (Art. 42)",
       "le voci selezionate di MIM0, MIM1, MIM2, MIM3 (solo 3.1), MIM6 (eccetto 6.4) e MIM7, parola per parola, con il codice della specifica, oltre alla clausola sull'equivalenza"),
      ("Disciplinare di gara",
       "criteri di selezione (Art. 58 e 62)",
       "dimostrazione di conformità a ISO/IEC 27001:2022 o equivalente (voce 6.4)"),
      ("Mezzi di prova",
       "relazioni di prova, certificazione e altri mezzi di prova (Art. 44)",
       "tabella di conformità come allegato obbligatorio all'offerta: C, E o N per ciascuna voce, con le relative prove (indirizzo documentazione API, credenziali di test)"),
      ("Schema di contratto",
       "condizioni di esecuzione dell'appalto (Art. 70)",
       "clausola di uscita, titolarità dei dati, divieto di costi per utente/richiesta, stabilità e versionamento API; tabella di conformità compilata in allegato"),
      ("Verbale di collaudo",
       "condizioni di esecuzione dell'appalto (Art. 70)",
       "colonna «Verificato» della tabella di conformità come verbale di collaudo"),
    ),
  )

  #sample-text("Esempio di testo per le specifiche tecniche", (
    "4.3 Interoperabilità e accesso ai dati",
    "4.3.1 Tutti i dati raccolti o generati dal sistema sono recuperabili in almeno un formato leggibile meccanicamente (es. JSON, CSV) tramite una normale API web. (MIMs Plus 9.0, MIM0 R1.1, R1.2)",
    "4.3.2 L'API è descritta formalmente in un documento aperto e leggibile meccanicamente (ad esempio OpenAPI) pubblicato a un indirizzo stabile. (MIM0 R1.3)",
    "4.3.3 L'API consente il filtraggio dei dati per intervallo temporale e luogo di misurazione. (MIM0 R2.1, R2.2)",
    "… da 4.3.4 a 4.3.21: ulteriori voci selezionate …",
    "4.3.22 Ogni riferimento a una norma o specifica tecnica ammette una soluzione equivalente; l'offerente dimostra l'equivalenza.",
    "4.3.23 L'offerente compila la tabella di conformità (allegato ai documenti di gara) fornendo le evidenze per ciascuna voce richiesta. L'offerente dimostra i punti da 4.3.1 a 4.3.21 tramite una chiamata API in tempo reale durante la valutazione delle offerte; la stazione appaltante li verifica nuovamente in sede di collaudo. L'esito negativo costituisce motivo di rifiuto del collaudo.",
  ))

  #note(size: 9pt, "Il punto 4.3.3 mostra come adattare una voce all'oggetto della fornitura: per i sensori è opportuno richiedere il filtraggio per data e luogo di rilevamento.")

  #v(4pt)
  #text(size: 10pt, weight: "bold", fill: eu-blue, "Estratto di una tabella di conformità compilata")
  #v(4pt)

  #filled-table(
    ("#", "Requisito (sintesi)", "C / E / N", "Evidenza: modalità e riferimenti", "Verificato"),
    (
      ("0.1", "Dati leggibili meccanicamente tramite API web", "C", "API REST che restituisce JSON e CSV; documentazione all'indirizzo indicato nell'offerta, pag. 12; credenziali di test nell'allegato 3", "✓"),
      ("0.4", "Sottoscrizione alle modifiche ove necessario", "N", "funzionalità non ancora supportata; prevista per la versione successiva", "—"),
      ("7.2", "Formati geospaziali aperti", "E", "fornisce GeoPackage, standard aperto OGC, anziché GeoJSON; equivalenza illustrata nell'offerta tecnica, pag. 15", "✓"),
    ),
  )

  #note(size: 9pt, gap: 5pt, "Una promessa futura vale N: la commissione valuta esclusivamente quanto l'offerente è in grado di dimostrare oggi.")

  #note(size: 9pt, gap: 5pt, "Adattare le formule al diritto nazionale e sottoporre il testo alla verifica del responsabile degli appalti.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)
// ════════════════════════════════════════════════════════════════════════════
#band("Tabella di conformità", id: "table")

#intro(size: 9.4pt, gap: 5pt, "Una riga per ciascuna voce. La stazione appaltante contrassegna quanto richiesto dall'appalto e allega la tabella alla documentazione di gara quale allegato obbligatorio all'offerta. Per ogni voce richiesta l'offerente indica C (conforme), E (conforme per equivalenza) o N (non conforme), spiegando sinteticamente come e indicando l'evidenza: link alla documentazione, accesso di test, pagina dell'offerta. Una mera dichiarazione non è sufficiente. La commissione giudicatrice verifica ciascuna voce in gara e poi al collaudo (✓ verificato, ✗ non verificato, — non controllato).")

#intro(size: 9.4pt, gap: 8pt, "La tabella compilata è parte integrante dell'offerta e diviene allegato al contratto. Verifica la conformità ai requisiti posti per l'oggetto dell'appalto (soddisfatto o non soddisfatto); non costituisce un criterio di aggiudicazione. Per attribuire punteggi alla conformità, indicarlo espressamente tra i criteri di aggiudicazione pubblicati preventivamente nei documenti di gara (Direttiva 2014/24/UE, Articolo 67).")

#score-sheet(
  headers: ("#", "Requisito (sintesi)", "Rif. spec.", "Richiesto?", "C / E / N", "Evidenza: modalità e riferimenti", "Verificato"),
  roles: ("amministrazione", "offerente", "offerente", "commissione"),
  section("MIM0 · Possiamo estrarre i nostri dati?",
    ("0.1", "Dati leggibili meccanicamente tramite API web standard", "MIM0 R1.1, R1.2"),
    ("0.2", "Descrizione aperta dell'API (OpenAPI) a indirizzo stabile", "MIM0 R1.3"),
    ("0.3", "Filtro per intervallo temporale, posizione e attributi", "MIM0 R2.1, R2.2"),
    ("0.4", "Sottoscrizione alle modifiche dove necessario", "MIM0 R3.1"),
    ("0.5", "Errori, cache e limiti di frequenza HTTP standard", "MIM0 C2"),
  ),
  section("MIM1 · Ogni cosa ha un identificatore durevole?",
    ("1.1", "Identificatore persistente e univoco per ogni entità", "MIM1 R1.1, R1.5"),
    ("1.2", "Risoluzione identificatore restituisce dati e tipologia", "MIM1 R1.2, R2.1, R2.2"),
    ("1.3", "Mappatura identificatori tra sistemi", "MIM1 R1.3, R1.4"),
    ("1.4", "Nessun riferimento proprietario negli identificatori", "MIM1 M1 §3.1"),
  ),
  section("MIM2 · Parliamo un linguaggio comune?",
    ("2.1", "Modelli dati standard ovunque disponibili", "MIM2 R1.2a"),
    ("2.2", "Modelli documentati e unità di misura esplicite", "MIM2 R1.1"),
    ("2.3", "Estensioni gestite come profili, mai fork proprietari", "MIM2 R1.2b, R4.1, R4.2"),
    ("2.4", "Serializzazione aperta e validabile tramite schema", "MIM2 R3.1, R3.4"),
  ),
  section("MIM3 · Possiamo condividere a condizioni chiare?",
    ("3.1", "Dati catalogati con metadati conformi agli standard", "MIM3 RC4.1–RC4.3"),
    ("3.2", "Modelli standardizzati di accordi e licenze d'uso", "MIM3 RC2.2, RC2.3"),
    ("3.3", "La città controlla le condizioni di accesso", "MIM3 RC1.1, RC2.1"),
  ),
  section("MIM6 · I nostri dati sono al sicuro in transito e durante l'uso?",
    ("6.1", "Trasferimento cifrato dei dati (TLS 1.3)", "MIM6 R2.1, M1.1"),
    ("6.2", "Autenticazione standard (OAuth 2.0 / OIDC)", "MIM6 R3.1, M1.2, M1.3"),
    ("6.3", "Controllo accessi per ruoli e registri di audit", "MIM6 R1.1, R1.3, 8.15"),
    ("6.4", "Conformità dimostrata a ISO/IEC 27001:2022", "MIM6 C1–C3 (ISO/IEC 27001)"),
  ),
  section("MIM7 · Funziona su una mappa?",
    ("7.1", "Interfacce standard OGC", "MIM7 R1.1"),
    ("7.2", "Formati geospaziali aperti", "MIM7 R2.1"),
    ("7.3", "Sistema di coordinate dichiarato (EPSG)", "MIM7 R5.1"),
    ("7.4", "Identificatori persistenti per dati spaziali (cfr. 1.1)", "MIM7 R4.1"),
  ),
  section("MIM8 · Il nostro gemello digitale può evolversi?",
    ("8.1", "Dati e output del gemello tramite API", "MIM8 R1.1"),
    ("8.2", "Modelli interamente documentati e invocabili", "MIM8 R3.1, R3.2"),
    ("8.3", "Formati di output standard", "MIM8 M2"),
    ("8.4", "Provenienza dei flussi di lavoro registrata", "MIM8 R4.4"),
  ),
  section("Clausole contrattuali trasversali", accent: magenta, note: "L'offerente attesta l'accettazione della condizione contrattuale (C / N).",
    ("X.1", "Clausola di uscita: consegna gratuita in formati aperti", "—"),
    ("X.2", "Diritti sui dati riservati alla stazione appaltante", "—"),
    ("X.3", "Nessun costo per l'accesso ai propri dati", "—"),
    ("X.4", "Stabilità API: versionate, preavviso di 6 mesi per rotture", "—"),
  ),
)

#note(size: 8.4pt, gap: 6pt, "Le etichette sintetiche sottostanti richiamano le voci estese delle pagine dei MIM — in caso di dubbio fa fede il testo completo della voce.")
#spec-link("La versione modificabile della tabella è scaricabile su:", "https://marek-mraz.github.io/mims-procurement-checklist/")
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  GLOSSARY AND FURTHER READING
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glossary")[
  #band("Piccolo glossario", id: "glossary")

  #glossary(
    term("API",
      "Un punto di accesso mediante il quale un programma richiede dati a un altro — tramite web, senza l'intervento di un operatore."),
    term("Modello dati",
      "La struttura concordata dei dati: quali campi esistono, cosa indicano e quali unità di misura utilizzano."),
    term("DCAT-AP",
      "Profilo europeo di metadati per i cataloghi dati; permette di rendere i dati ricercabili anche sui portali nazionali ed europei."),
    term("EPSG",
      "Registro di codici numerici per i sistemi di riferimento di coordinate (ad es. EPSG:4326 per WGS 84)."),
    term("Identificatore",
      "Denominazione permanente assegnata a una singola entità (un lampione, un edificio) usata da tutti i sistemi per riferirsi a essa."),
    term("Interoperabilità",
      "La capacità di sistemi realizzati da fornitori diversi di scambiare dati e comprenderne reciprocamente il significato."),
    term("IRI",
      "Forma internazionale di identificatore web (come un URL, con caratteri non-ASCII ammessi). MIM1 identifica le entità per suo tramite."),
    term("LDT",
      "Gemello digitale locale (Local Digital Twin): replica digitale di una città o di una sua area, integrata con dati e simulazioni."),
    term("Leggibile meccanicamente",
      "Dati strutturati affinché un software possa elaborarli direttamente (JSON, CSV) — una tabella scansionata in PDF non lo è."),
    term("Metadati",
      "Dati che descrivono altri dati: contenuto della serie di dati, soggetto che la fornisce, livello di aggiornamento, licenza d'uso."),
    term("OAuth 2.0 / OIDC",
      "Standard aperti per autenticazione e autorizzazione. OpenID Connect (OIDC) integra OAuth 2.0 con la verifica dell'identità."),
    term("OGC",
      "Open Geospatial Consortium: ente internazionale che sviluppa standard per dati e servizi geospaziali (OGC API, WFS, SensorThings)."),
    term("Standard aperto",
      "Specifica tecnica accessibile a chiunque e implementabile senza dover corrispondere diritti né richiedere autorizzazioni."),
    term("OpenAPI",
      "Formato aperto per la descrizione leggibile meccanicamente di un'API web: indirizzi, parametri e risposte restituite."),
    term("Serializzazione",
      "Codifica di dati in un formato strutturato concreto (ad es. JSON o XML) per consentirne il salvataggio o l'invio su rete."),
    term("TLS",
      "Protocollo che cifra i dati in transito attraverso una rete informatica (alla base del protocollo HTTPS)."),
    term("Lock-in del fornitore",
      "Condizione per cui sostituire un fornitore risulta proibitivo — per dispersione di dati, formati chiusi o costi — rimanendone vincolati."),
    term("Webhook / MQTT",
      "Due modalità con cui un sistema notifica autonomamente un evento: il webhook chiama un URL definito, MQTT inoltra messaggi ai sottoscrittori."),
  )

  #more-links("Dove approfondire",
    more-link("mims.oascities.org", "La specifica integrale MIMs Plus, gestita da OASC."),
    more-link("living-in.eu", "Il movimento europeo per la transizione digitale delle città — dichiarazione e quadro di riferimento MIMs Plus."),
    more-link("smartdatamodels.org", "La libreria aperta di modelli dati standardizzati (FIWARE, TM Forum, IUDX, OASC)."),
    more-link("oascities.org/academy", "CITYxCITY Academy — corsi di formazione per il personale comunale, ideati dalle città."),
  )
]


// ════════════════════════════════════════════════════════════════════════════
//  BACK COVER
// ════════════════════════════════════════════════════════════════════════════
#pagebreak()
#back-cover(
  "Tratto dalla specifica MIMs Plus 9.0 di Open & Agile Smart Cities (mims.oascities.org). Contenuto della specifica © OASC. Questa guida è un compendio divulgativo indipendente destinato alle procedure d'appalto comunali; in caso di divergenze, fa fede la specifica tecnica ufficiale.",
  "Realizzato con strumenti aperti. Liberamente riutilizzabile e adattabile per il tuo comune.",
  author: "Autore della guida: Marek Mráz",
)
