// ════════════════════════════════════════════════════════════════════════════
//  MIMs procurement booklet, edition: en
//
//  GENERATED by gen_typ.py from content/en.json + shared.json + quotes.json.
//  Do not edit: change the JSON and run ./build.sh.
//
//  How to read it: the file runs top to bottom in page order. Each #name(…)
//  is one block on the page; what the block looks like (sizes, colours,
//  spacing) is described next to its definition in ../style.typ.
//  #fit-page("name")[ … ] is one physical page.
//  One-letter prepositions may be followed by a no-break space (U+00A0),
//  which looks like a normal space here.
//
//  Build:  typst compile --root .. --font-path ../tools/fonts booklet-en.typ
// ════════════════════════════════════════════════════════════════════════════
#import "../style.typ": *

#show: booklet.with(title: "Procurement Checklist · using the Minimal · Interoperability Mechanisms (MIMs)", lang: "en",
  nav: (overview: "Overview", clauses: "Clauses", example: "Example", table: "Compliance table", glossary: "Glossary", list: "Checklist", back: "back to the checklist", page: "p."),
  mims: ("MIM0", "MIM1", "MIM2", "MIM3", "MIM6", "MIM7", "MIM8",))


// ════════════════════════════════════════════════════════════════════════════
//  COVER
// ════════════════════════════════════════════════════════════════════════════
#cover(
  title:    "Procurement Checklist · using the Minimal · Interoperability Mechanisms (MIMs)",
  subtitle: "What to put in a tender so your city keeps its data",
  tagline:  "For MIMs Plus 9.0 by OASC",
  footer:   "For procurement officers, project managers and CIOs of European municipalities",
  author:   "Author of the booklet: Marek Mráz",
)


// ════════════════════════════════════════════════════════════════════════════
//  WHY THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("why")[
  #band("Why this booklet")

  #lead("Every year, cities buy software: parking systems, sensor platforms, map portals, digital twins. Too often, the data those systems collect ends up locked inside them. When the contract ends, the data — paid for with public money — leaves with the supplier, or stays trapped in a format nobody else can read.")

  #lead("It does not have to be this way. The Minimal Interoperability Mechanisms (MIMs), maintained by Open & Agile Smart Cities (OASC) and endorsed through the European living-in.eu movement, describe the minimal technical requirements that keep your data open, reusable and vendor-neutral. They are deliberately small: not a grand architecture, just the few things that must be true so that systems can talk to each other.")

  #lead("You do not need to be an engineer to use them. Each checklist turns one MIM into plain-words checklist items you can copy into a tender, with the reason why each one protects you. Right after the checklist you find every requirement of that MIM, word for word, so your technical colleagues and your bidders can check the details.")

  #lead("Cities that require the MIMs buy once and reuse many times: the air-quality data feeds the school dashboard, the streetlight inventory feeds the energy plan, and the next supplier picks up where the last one left off. That is what interoperability means in practice — and it is increasingly expected in EU-funded projects.")

  #pull-quote(
    "The minimal interoperability mechanisms (MIMs) enable a minimal but sufficient level of interoperability for data, systems, and services specifically in the context of smart city solutions. · The intended audience for this document are: · 1. Solution providers that wish to make sure their solutions are interoperable with other and allow fluid exchange of data within a Smart Cities and Communities context. · 2. Procurers that wish to procure solutions that are future-proof and allow cost-effective integration within an existing Smart Cities and Communities Information and Communication Technology (ICT) architecture.",
  )

  #policy-box("How the MIMs fit EU law",
    "The MIMs are a technical specification, not a law. They point in the same direction as EU rules that already apply to public data and digital services:",
    law("Public Procurement Directive", "Directive 2014/24/EU, Article 42",
      "technical specifications may refer to standards, always with “or equivalent”; as a rule they may not name a specific make or product."),
    law("Data Act", "Regulation (EU) 2023/2854",
      "access to data from connected products, and switching between cloud providers without lock-in."),
    law("Interoperable Europe Act", "Regulation (EU) 2024/903",
      "interoperability assessments for cross-border digital public services, and reuse of open solutions."),
    law("Open Data Directive", "Directive (EU) 2019/1024",
      "high-value datasets published free of charge, machine-readable, through APIs."),
    law("NIS2 Directive", "Directive (EU) 2022/2555",
      "a cybersecurity baseline; national law decides how far it covers local administration."),
    law("GDPR", "Regulation (EU) 2016/679",
      "personal data in city systems (parking, cameras, mobility)."),
    law("AI Act", "Regulation (EU) 2024/1689",
      "rules for artificial intelligence systems; relevant for AI models in digital twins."),
    note: "For orientation only. Check how your country has transposed each act.",
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  HOW TO USE THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("howto")[
  #band("How to use this booklet")

  #steps(
    step("Prepare",
      "Read the seven checklists. Mark the ones that apply to what you are buying. Most tenders need MIM0, MIM1, MIM2 and MIM6; add MIM3 when data is shared with third parties or through a data portal, MIM7 for anything with a map, MIM8 for digital twins."),
    step("Tender",
      "Copy the ticked checklist items into your requirements. Each item is written as a sentence you can paste. Add the cross-cutting clauses: they cost little and prevent lock-in.",
      links: (("clauses", "Clauses"), ("example", "Example"), )),
    step("Evaluate",
      "Ask bidders to show, not promise (see the clause of that name). Verify compliance against the compliance table the bidder completed.",
      links: (("table", "Compliance table"), )),
    step("Deliver",
      "At acceptance, re-test every item you ticked. A requirement that is not tested at delivery was never really a requirement.",
      links: (("table", "Compliance table"), )),
  )

  #legend("Reading the specification quotes",
    note: "The checklist items say “must” even where the specification only recommends (should) or lists a candidate mechanism. That is the contracting authority’s decision.",
    entry("SHALL / MUST", "mandatory. The system does not comply without it."),
    entry("MUST NOT", "forbidden. A system that does it does not comply."),
    entry("SHOULD", "strongly recommended. Deviations need a good written reason."),
    entry("MAY", "optional. Nice to have, never required."),
    entry("CAN", "a possibility, not a requirement. It says what is possible and obliges nobody."),
  )

  #note("Every checklist item carries a small reference like → MIM0 R1.1. That is the requirement in MIMs Plus 9.0 it comes from; right after the checklist you find every requirement of that MIM word for word. Only MIM0 defines the keywords: they count when written in capitals, the convention of IETF RFC 2119 and RFC 8174 (CAN comes from the ISO/IEC Directives, Part 2). The other MIMs have no definition: MIM6 writes SHALL mostly in capitals, MIM2, MIM3, MIM7 and MIM8 write shall, should and must in lower case, and MIM1 uses them only in the description of a mechanism (MUST NOT in section 3.1). This booklet reads the lower-case words the same way; a bidder may read them more loosely.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  THE SEVEN MIMs AT A GLANCE
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glance")[
  #band("Seven MIMs and three tools", id: "glance")

  #intro("Seven small mechanisms, one goal: your data stays yours, and your systems can talk to each other.")

  #glance(
    note: "About the numbering: MIMs Plus 9.0 specifies seven mechanisms, numbered 0, 1, 2, 3, 6, 7 and 8. MIM4 (personal data) and MIM5 (fair AI) belong to earlier OASC versions and are not part of 9.0. Nothing is missing from this booklet.",
    card("MIM0", "Accessing Data",
      "Can we get our data out?",
      "Data is retrievable through standard web APIs, in machine-readable formats.",
      "https://mims.oascities.org/accessing-data"),
    card("MIM1", "Interlinking Data",
      "Does every thing have a name that lasts?",
      "Every sensor, lamp and building has a unique, persistent identifier.",
      "https://mims.oascities.org/interlinking-data"),
    card("MIM2", "Representing Data",
      "Do we speak a common language?",
      "Data follows standard, documented data models with explicit units.",
      "https://mims.oascities.org/representing-data"),
    card("MIM3", "Exchanging Data",
      "Can we share on clear terms?",
      "Datasets are catalogued and shared under template licences and clear governance.",
      "https://mims.oascities.org/exchanging-data"),
    card("MIM6", "Securing Data",
      "Is our data safe?",
      "Encrypted transfer, standard logins, role-based access, audit logs.",
      "https://mims.oascities.org/securing-data"),
    card("MIM7", "Geospatial Data",
      "Does it work on a map?",
      "Spatial data uses OGC interfaces, open formats and declared coordinate systems.",
      "https://mims.oascities.org/geospatial-data"),
    card("MIM8", "Local Digital Twins",
      "Can our digital twin grow?",
      "Twin data, models and results stay accessible, documented and reusable.",
      "https://mims.oascities.org/local-digital-twins"),
  )

  #tools("Tools for your tender",
    tool("clauses", "Cross-cutting tender clauses",
      "What belongs in every contract?",
      "Exit, data rights, API stability."),
    tool("example", "Example: air-quality sensors",
      "What does it look like in practice?",
      "What goes where, and sample text to paste."),
    tool("table", "Compliance table",
      "How does the bidder prove it?",
      "Filled in by the bidder, verified by the committee, annexed to the contract."),
  )

  #menu-line(("glossary", "Small glossary"), ("more", "Where to learn more"))
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 checklist")[
  #mim-page(
    id:       "MIM0",
    name:     "Accessing Data",
    question: "Can we get our data out?",
    url:      "https://mims.oascities.org/accessing-data",
    intro:    "This is the foundation. If data cannot leave the system through a standard interface, everything else in this booklet is theory. MIM0 asks one thing of every system you buy: the data must be reachable, in a form machines can read, through the ordinary web.",
    list:     "Checklist",
  )

  #item("All data the system collects or produces is retrievable in at least one machine-readable format (e.g. JSON, CSV) over a standard web API.",
    why:  "Your next contractor — or your own staff — can use the data without asking the vendor.",
    refs: "MIM0 R1.1, R1.2",
    num:  "0.1")

  #item("The API is formally described in an open, machine-readable document (for example OpenAPI) published at a stable address.",
    why:  "Any developer can connect without a paid “integration workshop”.",
    refs: "MIM0 R1.3",
    num:  "0.2")

  #item("Data can be filtered by time, place and attributes directly in the API.",
    why:  "You fetch what you need, not a nightly full dump.",
    refs: "MIM0 R2.1, R2.2",
    num:  "0.3")

  #item("Where the use case needs live data, consumers can subscribe to changes (webhooks, MQTT or similar) instead of constant polling.",
    why:  "Real-time dashboards and alerts become possible and cheap.",
    refs: "MIM0 R3.1",
    num:  "0.4")

  #item("Errors, caching and rate limits use standard HTTP conventions and are documented.",
    why:  "Integrations fail loudly and fixably, not silently.",
    refs: "MIM0 C2",
    num:  "0.5")

  #panels(
    why:   ("Why it matters", (
      "Data you paid for stays usable after the contract ends.",
      "New services build on old data instead of starting from zero.",
      "Integration costs drop for every project that follows.",
    )),
    flags: ("Red flags", (
      "“Data export on request via our support team.”",
      "“The API is available as a paid add-on module.”",
      "Per-request pricing for the city’s own data (see the clause “No per-seat / per-request fees”).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM0",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM0",
    capability("C1", "Machine-readable data is retrievable through the web"),
    req("R1.1",
      en: "Systems SHALL allow retrieval of data in at least one machine-readable format. Formats can be specified through HTTP Content-Negotiation"),
    req("R1.2",
      en: "Data SHALL be retrievable via at least one standard web-based mechanism"),
    req("R1.3",
      en: "Access mechanism(s) SHALL be formally described"),
    req("R1.4",
      en: "Data Models used by payloads should be specified (see MIM2)"),
    capability("C2", "Access is structured and queryable"),
    req("R2.1",
      en: "Systems SHALL provide data through a structured and consistent interface"),
    req("R2.2",
      en: "Systems SHALL support basic querying and/or filtering (e.g. by time, location, attributes)"),
    capability("C2 best practice", "Additional best practice to consider:", sub: true),
    req("C2",
      en: "APIs SHOULD support retrieval of current data · APIs SHOULD support retrieval of historical data when applicable · APIs SHOULD support geospatial querying when applicable (see MIM7) · APIs SHOULD support subscription to changes when applicable · APIs SHOULD expose next expected update timestamp · APIs SHOULD support explicit versioning of endpoints · APIs SHOULD provide example payloads or test queries · APIs SHOULD support standard HTTP caching headers · APIs SHOULD communicate rate limit status via standard HTTP headers · APIs SHOULD return structured error bodies · APIs MAY support partial responses or query projections · APIs MAY expose a standard health/status endpoint"),
    capability("C3", "Changes in data can be subscribed to"),
    req("R3.1",
      en: "Systems for use cases that require notifications SHALL provide at least one mechanism to receive updates on data changes"),
    req("R3.2",
      en: "Systems MAY support multiple subscription mechanisms depending on use case"),
    capability("C4", "Access to information can be restricted"),
    req("C4",
      en: "If such restrictions are in place, they SHALL follow the requirements defined in MIM3 and MIM6, specifically: actor identification (MIM3.C5.R0), authorization and actor roles (MIM6.C1.R4), data asset-level policies (MIM6.C1.R4)"),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/accessing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 checklist")[
  #mim-page(
    id:       "MIM1",
    name:     "Interlinking Data",
    question: "Does every thing have a name that lasts?",
    url:      "https://mims.oascities.org/interlinking-data",
    intro:    "A city is full of things: lamps, pipes, buildings, parking spots. Systems come and go, but the things remain. MIM1 asks that every thing gets a name — an identifier — that outlives the software that first recorded it, so its history and its links to other data survive every migration.",
    list:     "Checklist",
  )

  #item("Every entity (sensor, lamp, building, parking spot…) has a unique, persistent identifier that does not change when the software is replaced.",
    why:  "History and links across systems survive the supplier.",
    refs: "MIM1 R1.1, R1.5",
    num:  "1.1")

  #item("The identifier can be looked up to retrieve the entity’s data and its meaning (type) in a machine-readable way.",
    why:  "Other systems can follow the link automatically.",
    refs: "MIM1 R1.2, R2.1, R2.2",
    num:  "1.2")

  #item("Where the same real-world thing exists in several systems, identifiers can be mapped to each other.",
    why:  "The GIS building and the energy-system building are provably the same building.",
    refs: "MIM1 R1.3, R1.4",
    num:  "1.3")

  #item("Identifiers do not embed vendor internals (database row IDs, server names).",
    why:  "Otherwise the IDs die with the contract.",
    refs: "MIM1 M1 §3.1",
    num:  "1.4")

  #panels(
    why:   ("Why it matters", (
      "Ten years of measurements stay attached to the right lamp post.",
      "Departments stop maintaining five contradictory registers of the same assets.",
      "Linking datasets becomes a query, not a consulting project.",
    )),
    flags: ("Red flags", (
      "“IDs are internal to our platform.”",
      "Identifiers are regenerated on every data migration.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM1",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM1",
    capability("C1", "Entities are identified using unique identifiers"),
    req("R1.1",
      en: "Every entity within the system has a unique identifier"),
    req("R1.2",
      en: "There exists a way to retrieve information about an entity by looking up the identifier within a system"),
    req("R1.3",
      en: "if a unique identifier points to the same entity within multiple systems, it is possible to derive the way to look up information about it in each of these systems"),
    req("R1.4",
      en: "if a multiple [sic] unique identifiers point to the same entity, it is possible to map them"),
    req("R1.5",
      en: "It is possible to create identifiers that are persistent over time"),
    capability("C2", "Entities can be typed"),
    req("R2.1",
      en: "There is a way to retreive [sic] the semantics of an entity, only using its unique identifier"),
    req("R2.2",
      en: "These semantics are described in a machine-readable format"),
    capability("C3", "Entities can be (de)referenced"),
    req("R3.1",
      en: "There exists a way to dereference a relation defined on an entity"),
    req("R3.2",
      en: "There exists a way to apply additional semantics to an existing ontology"),
    capability("M1", "Mechanism 1, section 3.1: Entity Identification with Globally Unique IRIs"),
    req("§3.1",
      en: "The IRI is treated as the canonical identifier in all downstream systems; implementations MUST NOT generate IRIs that embed volatile implementation details such as database row IDs or server hostnames."),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/interlinking-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 checklist")[
  #mim-page(
    id:       "MIM2",
    name:     "Representing Data",
    question: "Do we speak a common language?",
    url:      "https://mims.oascities.org/representing-data",
    intro:    "Two systems can both export JSON and still not understand each other. MIM2 is about meaning: using shared, documented data models — with explicit units and formats — so that “temperature”, “parking spot” or “air quality” means the same thing in every system you own.",
    list:     "Checklist",
  )

  #item("Data uses commonly recognised standard data models wherever they exist (e.g. Smart Data Models, SAREF, ISO/IEC 5087); deviations are justified in writing.",
    why:  "Data from two suppliers merges without a translation project.",
    refs: "MIM2 R1.2a",
    num:  "2.1")

  #item("All data models in use are explicitly documented, with units of measurement and date/time formats stated.",
    why:  "“Temperature: 23” is useless if nobody wrote down °C vs °F.",
    refs: "MIM2 R1.1",
    num:  "2.2")

  #item("Extensions are delivered as documented profiles/additions on top of the standard model — never as a modified private fork.",
    why:  "You stay compatible with the community and future updates.",
    refs: "MIM2 R1.2b, R4.1, R4.2",
    num:  "2.3")

  #item("Every model has at least one open, schema-validatable serialisation (e.g. JSON with JSON Schema).",
    why:  "Incoming data can be checked automatically at the door.",
    refs: "MIM2 R3.1, R3.4",
    num:  "2.4")

  #panels(
    why:   ("Why it matters", (
      "One dashboard reads data from many suppliers without adapters.",
      "Your data is understood by other cities’ tools — and theirs by yours.",
      "Automatic validation catches broken data before it spreads.",
    )),
    flags: ("Red flags", (
      "“Our proprietary data model is richer than the standard.”",
      "Documentation available only under NDA.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM2",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM2",
    capability("C1", "All entities included in data sources are described using consistent data models to enable interoperability for applications and systems"),
    req("R1.1",
      en: "Data models used for all entities in any data source shall be made explicit. They shall be well documented and have descriptive metadata, where the terms used shall be semantically unambiguous. For attributes related to units of measurement, time formats etc, the units, formats etc, used shall be made explicit. The data models should be catalogued so that they can be easily findable."),
    req("R1.2a",
      en: "Data models used shall be based (wherever possible) on commonly recognised standardised data models as listed below"),
    req("R1.2b",
      en: "Where it is not possible to use existing standardised data models, efforts shall be made to extend existing standardised data models that are most closely aligned or to define new ones, following best practice and conventions of the community or organisation defining the data models."),
    req("R1.3",
      en: "Data models used shall support the exchange of data by using the relevant requirements of the MIMs on Accessing data and Interlinking data"),
    capability("C2", "Different data models for the same entity that are used within a common data sharing ecosystem should be easily transformable into a common data model"),
    req("R2.1",
      en: "A common data model for each key entity should be developed for any data ecosystem. That common data model should contain all the fields included within the different data models for that entity that are used within that data ecosystem. Each different data model used within that data ecosystem could then be transformed into the common data model."),
    capability("C3", "Any data and its associated metadata can be shared in open, standardised, data transport formats so that data can be exchanged and interpreted consistently by different tools and implementations"),
    req("R3.1",
      en: "Each data model used shall have at least one defined machine-readable data transport format (“serialisation”) that is open, publicly available and implementation-independent."),
    req("R3.2",
      en: "The documentation of the data transport format should be sufficient to allow the creation of non-proprietary application or interpretor that is able to reconstruct all the data stored in such a data format."),
    req("R3.3",
      en: "Where multiple data transport formats are supported for the same data model, they shall represent the same information content consistently and without loss of meaning."),
    req("R3.4",
      en: "The representation should support validation using openly published schemas, grammars, or equivalent machine-readable constraints, where such validation mechanisms exist for the chosen format."),
    capability("C4", "When useful, it should be possible to create \"Application Profiles\" for a data model, so that use case specific attributes can be added or specified without changing the underlying data model"),
    req("R4.1",
      en: "Application Profiles that extend a data model should not impact the already existing model and its users"),
    req("R4.2",
      en: "The specialisations or extensions introduced in the Application Profile of the model should be well documented, separate from the base data model"),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/representing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 checklist")[
  #mim-page(
    id:       "MIM3",
    name:     "Exchanging Data",
    question: "Can we share on clear terms?",
    url:      "https://mims.oascities.org/exchanging-data",
    intro:    "Not all city data can be simply published: some is commercial, some sensitive. MIM3 is about sharing the rest anyway, safely: a catalogue people can search, licences from templates instead of bespoke legalese, and governance rules everyone can read. The specification words almost all of MIM3 as a recommendation (see p. 3).",
    list:     "Checklist",
  )

  #item("Every dataset the system offers is described with standard metadata (for example DCAT-AP) in a catalogue, so others can discover it.",
    why:  "Data nobody can find is data nobody uses.",
    refs: "MIM3 RC4.1–RC4.3",
    num:  "3.1")

  #item("Terms and licences for data use come from well-known templates (e.g. open licences, standard data-sharing agreements), not bespoke legalese per dataset.",
    why:  "Agreements scale; lawyers don’t become the bottleneck.",
    refs: "MIM3 RC2.2, RC2.3",
    num:  "3.2")

  #item("The city can define who may access which data asset and under which conditions, and change this without vendor involvement.",
    why:  "Governance remains with the municipality.",
    refs: "MIM3 RC1.1, RC2.1",
    num:  "3.3")

  #panels(
    why:   ("Why it matters", (
      "Local companies and researchers build on city data — value stays in the region.",
      "Sensitive data can be shared with exactly the right partners, not everyone or no one.",
      "One rulebook replaces many individual data-sharing contracts.",
    )),
    flags: ("Red flags", (
      "The vendor claims rights over the city’s data (see the clause “Data ownership”).",
      "Sharing with a third party requires vendor consent or fees.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM3",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM3",
    capability("C1", "Governance rules for the data sharing ecosystem can be defined"),
    req("RC1.1",
      en: "The orchestrator of a data ecosystem should be able to define a governance model (e.g. a rulebook) that outlines membership rules, the roles, responsibilities and obligations of ecosystem participants, and the overall principles that govern data exchange between them."),
    req("RC1.2",
      en: "Members who participate in a data ecosystem should be aware of its governance model and any changes made to it."),
    req("RC1.3",
      en: "The governance model should be easily comprehensible by all ecosystem participants."),
    capability("C2", "Terms and conditions for data sharing can be defined"),
    req("RC2.1",
      en: "Data providers are free to define terms and conditions under which they want their data to be exchanged. (Note: Before sharing data assets, data providers should ensure they have adequate permission from data owners.)"),
    req("RC2.2",
      en: "Terms and conditions for a data exchange should be described clearly and unambiguously so that they are easily understandable for data users."),
    req("RC2.3",
      en: "Terms and conditions for a data exchange should be expressed through data licences or data sharing agreements based on well-defined templates or standards."),
    req("RC2.4",
      en: "Terms and conditions should be in line with the overall governance model of the data ecosystem and must not conflict with it. (Note: A data provider can decide not to participate in a data ecosystem if the underlying governance model is too restrictive or too permissive.)"),
    capability("C3", "Compliance with data sharing terms and conditions can be validated"),
    req("RC3.1",
      en: "The orchestrator of a data ecosystem must be able to ascertain compliance of its participants with the underlying governance model."),
    req("RC3.2",
      en: "Data providers should be able to ascertain that the use of data by a data user complies with previously agreed-upon terms and conditions."),
    req("RC3.3",
      en: "Data users should be able to ascertain that the data provider's supply of data follows previously agreed-upon terms and conditions."),
    capability("C4", "Available data assets can be discovered"),
    req("RC4.1",
      en: "Data users should be able to discover what data is available in a data sharing ecosystem without prior knowledge of it."),
    req("RC4.2",
      en: "Data assets should be adequately described with metadata so that data users can make reliable decisions about their further intended use."),
    req("RC4.3",
      en: "Metadata used to describe data assets should be based on well-defined, easy-to-understand description formats that are both human- and machine-readable."),
    capability("C5", "Ecosystem participants can be discovered"),
    req("RC5.1",
      en: "Ecosystem participants (e.g. data users and providers) should be able to discover each other within a data-sharing ecosystem."),
    req("RC5.2",
      en: "Sufficient metadata about each ecosystem participant should be available to ascertain their trustworthiness relevant for data exchange."),
    req("RC5.3",
      en: "Data providers should be able to reliably identify data users who want to access their data assets and verify their metadata before granting access."),
    req("RC5.4",
      en: "Data users should be able to identify data providers who share data in a data ecosystem before accessing or using that data."),
    req("RC5.5",
      en: "Ecosystem participants may also choose to remain anonymous if the governance model of the data-sharing ecosystem allows for it. In this case, RC5.1 to RC5.4 can be ignored."),
    capability("C6", "Data exchange can be agreed upon"),
    req("RC6.1",
      en: "Data users and providers should be able to agree to a data exchange and the terms and conditions associated with it (e.g. acceptance of terms, legal signature of an agreement, or negotiation)."),
    req("RC6.2",
      en: "Data users and providers should be able to terminate a previously agreed-upon data exchange in accordance with the terms and conditions associated with it."),
    req("RC6.3",
      en: "Where possible, electronic means for the agreement and termination of a data exchange may be provided."),
    capability("C7", "New data currently not available can be requested"),
    req("RC7.1",
      en: "Data users should be able to express their interest in data assets currently unavailable in the data sharing ecosystem."),
    req("RC7.2",
      en: "Data providers should be able to obtain requests made by data users for new data assets."),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/exchanging-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 checklist")[
  #mim-page(
    id:       "MIM6",
    name:     "Securing Data",
    question: "Is our data safe in transit and in use?",
    url:      "https://mims.oascities.org/securing-data",
    intro:    "Smart cities are targets. MIM6 keeps the scope deliberately narrow and practical: encrypt data on the move, use standard logins instead of proprietary ones, control and log who accesses what. None of it is exotic — all of it must be in the contract.",
    list:     "Checklist",
  )

  #item("All data transfer is encrypted (TLS 1.3 or current best practice).",
    why:  "Baseline hygiene; NIS2 also expects it where it applies to you.",
    refs: "MIM6 R2.1, M1.1",
    num:  "6.1")

  #item("Login and machine access use open standards — OAuth 2.0 / OpenID Connect — and can plug into the city’s existing identity provider.",
    why:  "One account per employee, not one per vendor product; leavers lose access everywhere at once.",
    refs: "MIM6 R3.1, M1.2, M1.3",
    num:  "6.2")

  #item("Access rights are role-based, reviewable, and removable; access and admin actions are logged.",
    why:  "Audits and incident response become possible. Logging is ISO/IEC 27001:2022, Annex A, control 8.15, which MIM6 lists among its prerequisites.",
    refs: "MIM6 R1.1, R1.3, 8.15",
    num:  "6.3")

  #item("The supplier must show alignment with ISO/IEC 27001:2022 (or equivalent) for the service they operate.",
    why:  "Security is a process, not a checkbox at delivery. The specification cites ISO/IEC 27001 controls, not a certificate.",
    refs: "MIM6 C1–C3 (ISO/IEC 27001)",
    num:  "6.4",
    label: "Belongs in the conditions of participation, not in the technical specification")

  #panels(
    why:   ("Why it matters", (
      "A breach in one system does not open every system.",
      "Where NIS2 applies to you, complying with it and with national cyber rules gets measurably easier.",
      "When something goes wrong, the logs tell you what and who.",
    )),
    flags: ("Red flags", (
      "Proprietary login only.",
      "“Logs available on request.”",
      "Shared admin accounts.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM6",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM6",
    capability("C1", "Data is only accessible to users that should have access to it"),
    req("R1.1",
      en: "Rules to control physical and logical access to information and other associated assets SHALL be established and implemented based on business and information security requirements. (ISO 27001 5.15 Access control)"),
    req("R1.2",
      en: "Allocation and management of authentication information SHALL be controlled by a management process, including advising personnel on appropriate handling of authentication information. (ISO 27001 5.17: Authentication information)"),
    req("R1.3",
      en: "Access rights to information and other associated assets SHALL be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control. (ISO 27001 5.18: Access rights)"),
    capability("C2", "Data accessed by users has not been altered"),
    req("R2.1",
      en: "Rules for the effective use of cryptography, including cryptographic key management, SHALL be defined and implemented. (ISO 27001 8.24 Use of cryptography)"),
    capability("C3", "Data accessed by users originates from a verified source"),
    req("R3.1",
      en: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control. (ISO 27001 8.5 Secure authentication)"),
    capability("M1", "Mechanism candidate"),
    req("M1.1",
      en: "The Transport Layer Security (TLS) Protocol, Version 1.3"),
    req("M1.2",
      en: "The OAuth 2.0 Authorization Framework"),
    req("M1.3",
      en: "OpenID Connect 1.0, Identity layer for authentication on OAuth 2.0"),
    req("M1.4",
      en: "OIDC4VCI / OIDC4VP, OpenID for Verifiable Credential Issuance and Presentations"),
    capability("P", "Pre- and Post-requisites (based on ISO 27001 Annex A): the control this booklet refers to"),
    req("8.15",
      en: "Logging. Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed."),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/securing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 checklist")[
  #mim-page(
    id:       "MIM7",
    name:     "Geospatial Data",
    question: "Does it work on a map?",
    url:      "https://mims.oascities.org/geospatial-data",
    intro:    "Almost everything a city owns has a place. MIM7 makes sure the place is not a screenshot: spatial data flows through standard OGC interfaces, in open formats, with the coordinate system always declared — so every map layer you buy aligns with every layer you already have.",
    list:     "Checklist",
  )

  #item("Geospatial data is exposed through standards-based interfaces (OGC API Features, SensorThings; WFS acceptable for legacy).",
    why:  "Every GIS tool on the market can read it out of the box.",
    refs: "MIM7 R1.1",
    num:  "7.1")

  #item("Geospatial data is encoded in open formats (GeoJSON, CityJSON; GML/CityGML where required).",
    why:  "No converter licences, no dead ends.",
    refs: "MIM7 R2.1",
    num:  "7.2")

  #item("The coordinate reference system is always declared (EPSG code) and data is transformable to a common CRS.",
    why:  "Layers from different sources actually align on the map.",
    refs: "MIM7 R5.1",
    num:  "7.3")

  #item("Spatial features carry the same persistent identifiers as in MIM1.",
    why:  "The dot on the map and the record in the register are the same thing.",
    refs: "MIM7 R4.1",
    num:  "7.4")

  #panels(
    why:   ("Why it matters", (
      "One city map instead of ten vendor viewers.",
      "INSPIRE and national geo-portal obligations get easier, not harder.",
      "3D and BIM data can join the same picture later.",
    )),
    flags: ("Red flags", (
      "Map data lives only inside the vendor’s viewer.",
      "“Export as PDF/screenshot.”",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM7",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM7",
    capability("C1", "Cities and communities can easily transfer geospatial data between internal and external (including IoT-related) IT systems"),
    req("R1.1",
      en: "Geospatial data shall be exposed through a standards-based web service interface."),
    capability("C2", "Cities and communities can integrate 2D and 3D geospatial data coming from a variety of sources, for example geodata and building information models, and share that data within and between them in an interoperable way"),
    req("R2.1",
      en: "Geospatial data shall be encoded using open standards. It is recommended to use relevant standards from OGC and BuildingSMART International."),
    capability("C3", "Cities and communities can integrate geospatial data with other data that can provide further information about the context"),
    req("R3.1",
      en: "All data sets used to provide further information about the context covered by geospatial data shall comply with MIM1 and MIM2."),
    capability("C4", "Cities and communities have a consistent and persistent way of describing individual instances of all features, things or entities included in the geospatial data sources"),
    req("R4.1",
      en: "Unique and persistent identifiers shall be used to identify particular instances of any entity used in data sets. (See MIM1: Interlinking Data.)"),
    capability("C5", "Coordinate Reference Systems (CRS) used in data sharing are easily transformable into a common CRS"),
    req("R5.1",
      en: "Coordinate Reference Systems (CRS) shall comply with standards, and information shall be provided regarding which standard (e.g. EPSG:4326, EPSG:3857) is being used. This includes the EPSG number or WGS number, along with information about any variation based on national systems such as the Latvian LKS-92, so that data can be transformed to a common CRS. (Note: Within the EU, for geospatial data it is required to use metadata compliant with the INSPIRE Directive, including the metadata needed to describe the CRS information.)"),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/geospatial-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 checklist")[
  #mim-page(
    id:       "MIM8",
    name:     "Local Digital Twins",
    question: "Can our digital twin grow?",
    url:      "https://mims.oascities.org/local-digital-twins",
    intro:    "A digital twin is a long-term investment: data, 3D models, simulations, decisions. MIM8 protects that investment — the twin’s data and models stay accessible and documented, results can be reproduced, and components from one project can serve the next. Use this page when buying twin platforms, simulation models or 3D city tools.",
    list:     "Checklist",
  )

  #item("Datasets, model inputs and simulation outputs are accessible through APIs (per MIM0), not trapped in the twin.",
    why:  "Results feed reports, dashboards and the next project.",
    refs: "MIM8 R1.1",
    num:  "8.1")

  #item("Models are documented (method, parameters, inputs/outputs) and callable through a documented interface.",
    why:  "A flood model bought once can be reused across departments — and by other cities.",
    refs: "MIM8 R3.1, R3.2",
    num:  "8.2")

  #item("Outputs use standard formats (GeoJSON, CityJSON, 3D Tiles, NetCDF…) consumable by tools you don’t buy from this vendor.",
    why:  "Visualisation and analysis stay competitive markets.",
    refs: "MIM8 M2",
    num:  "8.3")

  #item("Workflows record provenance: which data version, which model, which parameters produced a result.",
    why:  "Decisions based on the twin can be explained and defended later.",
    refs: "MIM8 R4.4",
    num:  "8.4")

  #panels(
    why:   ("Why it matters", (
      "The twin outlives any single supplier or project budget.",
      "Simulations can be checked, repeated and justified in municipal decision-making.",
      "Models and components can be shared between cities.",
    )),
    flags: ("Red flags", (
      "Simulation results viewable only in the vendor portal.",
      "Models as sealed black boxes with no metadata.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM8",
    title:  "What the specification says",
    leadin: "Every requirement of this MIM, verbatim from MIMs Plus 9.0:",
    back:   "back to the checklist",
  )

  #spec-list(mim: "MIM8",
    capability("C1", "Provide access to datasets used within the LDT, including static, real-time, and simulation data and calculation models"),
    req("R1.1",
      en: "The LDT shall provide access to simulation outputs and calculation-model inputs where these are needed as part of LDT workflows."),
    req("R1.2",
      en: "The LDT should distinguish clearly between raw source data, transformed workflow-ready data, model inputs, and model outputs."),
    capability("C2", "Exchange data with external systems and other LDTs using interoperable interfaces"),
    req("C2",
      en: "This capability relies on MIM3 (Exchanging Data) for data exchange."),
    capability("C3", "Reuse deterministic or AI models across different domains, communities, use cases, and/or LDTs"),
    req("R3.1",
      en: "The model should provide standard model metadata, including a description of its methods and parameters, and data-parameters (either by value or by reference). To this end common metadata standards should be used."),
    req("R3.2",
      en: "The model shall expose or be callable through a documented interface, preferably using a known standardised API. The dataset that forms the outcome of the model shall be described (at data-level)."),
    req("R3.3",
      en: "Trustworthy, reliable, and ethical use of innovative methods (LLMs, agentic AI, etc.) should be safeguarded. Bias should minimised [sic] where applicable. The methods used to guarantee this, should be described."),
    req("R3.4",
      en: "The model must be able to access data on behalf of the end-user or organisation. See MIM3"),
    req("R3.5",
      en: "For data to be used in AI models, provenance and trust should be guaranteed. In some cases, an authoratitive sourc [sic], such as a government agency must be listed."),
    capability("C4", "Coordinate and manage data, models, and processing workflows within an LDT (intra-LDT) and across LDTs (inter-LDT)"),
    req("R4.1",
      en: "The LDT supports workflows that connect data sources, data transformations, model execution, simulation processes, and outputs."),
    req("R4.2",
      en: "The LDT chains workflow steps, where the output of one step can be used as the input for another."),
    req("R4.3",
      en: "The LDT monitors workflow execution status, including completed, failed, and interrupted processes."),
    req("R4.4",
      en: "The LDT records workflow provenance, including datasets used (including version, timestamped), models executed, parameters selected, and outputs generated."),
    capability("C5", "Provide multiple visualisations of data and results (e.g. 2D, 3D, dashboards) from common underlying data and models for interaction and comparison"),
    req("R5.1",
      en: "The LDT provides metadata explaining what is visualised, including timestamp, spatial scope, data source, and scenario- and variant-assumptions where relevant."),
    req("R5.2",
      en: "The LDT supports different interactive visualisation types, such as 2D maps, 3D scenes, dashboards, reports, or public-facing views."),
    capability("C6", "Ensure that data exchanged (and simulation outputs) within and between LDTs can be interpreted consistently through shared or mapped semantics and clear provenance"),
    req("R6.1",
      en: "The LDT should document unresolved semantic gaps, assumptions, or mappings that may affect the interpretation, reuse, or comparison of results."),
    capability("M", "Mechanisms (under active development)"),
    req("M1",
      en: "API-based LDT Resource Access"),
    req("M2",
      en: "Standardised Data and Output Formats"),
    req("M3",
      en: "Model-as-a-Service"),
    req("M4",
      en: "LDT Workflow Orchestration"),
    req("M5",
      en: "Multi-view Output and Visualisation Access"),
  )

  #spec-link("Full specification:", "https://mims.oascities.org/local-digital-twins")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  CROSS-CUTTING CONTRACT CLAUSES
// ════════════════════════════════════════════════════════════════════════════
#fit-page("clauses")[
  #band("Cross-cutting tender clauses", sub: "Safeguards against lock-in", id: "clauses")

  #intro(size: 9.8pt, "These clauses belong in every tender, whatever you are buying. They come from procurement practice around the MIMs and living-in.eu. Most of them do not rest on a single specification requirement, so they carry no reference codes (API versioning is also a MIM0 C2 recommendation). They cost little to include; leaving them out can cost everything.")

  #clauses(
    clause("Exit clause",
      "At contract end, all city data (and configuration) is handed over in open, documented formats at no extra cost."),
    clause("Rights in the data",
      "All rights in the data collected and derived under the contract belong to the contracting authority."),
    clause("No per-seat / per-request fees",
      "No fees for the city accessing its own data."),
    clause("API stability and versioning",
      "The supplier keeps the API backwards compatible for the whole contract term. Breaking changes are announced at least 6 months in advance and released as a new version, while the previous version stays available until the agreed switch-over date."),
    clause("Show, don’t promise",
      "Bidders demonstrate compliance during tender evaluation instead of submitting self-declarations. For an API this means published interactive documentation (such as OpenAPI) and a live call that returns valid data. Every ticked item is tested again at acceptance."),
    clause("Open standards named",
      "The tender names the standards above; “compatible with” claims must cite the exact interface and version. Every reference to a standard or technical specification accepts an equivalent solution; the bidder proves the equivalence."),
    clause("MIMs compliance statement",
      "The bidder completes the compliance table (p. 23); it becomes an annex to the contract."),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT
// ════════════════════════════════════════════════════════════════════════════
#fit-page("example")[
  #band("Example: a city buys a network of air-quality sensors", id: "example")

  #intro(size: 9.8pt, "Marked pages: MIM0, MIM1, MIM2, MIM6 and MIM7 (the data goes on a map). From MIM3 only item 3.1 (air-quality data is published as open data, so it belongs in a catalogue); not MIM8: this is no digital twin.")

  #text(size: 10pt, weight: "bold", fill: eu-blue, "What goes where")
  #v(4pt)

  #doc-table(
    ("Document", "Term in Directive 2014/24/EU", "What to put in it"),
    (
      ("Technical specification",
       "technical specifications (Art. 42)",
       "the marked items of MIM0, MIM1, MIM2, MIM3 (3.1 only), MIM6 (except 6.4) and MIM7, word for word, with the specification code, plus the sentence on equivalence"),
      ("Conditions of participation",
       "selection criteria (Art. 58 and 62)",
       "demonstrated alignment with ISO/IEC 27001:2022 or equivalent (item 6.4)"),
      ("Means of proof",
       "test reports, certification and other means of proof (Art. 44)",
       "the compliance table as a mandatory annex to the tender: M, E or N for each item, with the evidence (API documentation address, test access)"),
      ("Draft contract",
       "conditions for performance of contracts (Art. 70)",
       "Exit clause, Data ownership, No per-seat / per-request fees, API stability and versioning; the completed compliance table as an annex"),
      ("Acceptance protocol",
       "conditions for performance of contracts (Art. 70)",
       "the “Verified” column of the compliance table as the test protocol"),
    ),
  )

  #sample-text("Sample wording for the technical specification", (
    "4.3 Interoperability and access to data",
    "4.3.1 All data the system collects or produces is retrievable in at least one machine-readable format (e.g. JSON, CSV) over a standard web API. (MIMs Plus 9.0, MIM0 R1.1, R1.2)",
    "4.3.2 The API is formally described in an open, machine-readable document (for example OpenAPI) published at a stable address. (MIM0 R1.3)",
    "4.3.3 The API allows filtering of data by time and place of measurement. (MIM0 R2.1, R2.2)",
    "… 4.3.4 to 4.3.21: further marked items …",
    "4.3.22 Every reference to a standard or technical specification accepts an equivalent solution; the bidder proves the equivalence.",
    "4.3.23 The bidder completes the compliance table (annex to the procurement documents) and gives the evidence for each required item. The bidder demonstrates points 4.3.1 to 4.3.21 with a live API call during the evaluation of tenders; the contracting authority tests them again at acceptance. Failing them is a reason to refuse acceptance.",
  ))

  #note(size: 9pt, "Point 4.3.3 shows that you may sharpen an item to fit the purchase: for sensors it makes sense to ask for filtering by time and place of measurement.")

  #v(4pt)
  #text(size: 10pt, weight: "bold", fill: eu-blue, "A completed compliance table (extract)")
  #v(4pt)

  #filled-table(
    ("#", "Requirement (short)", "M / E / N", "Evidence: how and where", "Verified"),
    (
      ("0.1", "Machine-readable data via standard web API", "M", "REST API returns JSON and CSV; documentation at the address given in the tender, p. 12; test access in annex 3", "✓"),
      ("0.4", "Subscription to changes where needed", "N", "not supported yet; planned for the next version", "—"),
      ("7.2", "Open geo formats", "E", "delivers GeoPackage, an open OGC standard, instead of GeoJSON; equivalence explained in the tender, p. 15", "✓"),
    ),
  )

  #note(size: 9pt, gap: 5pt, "A promise for the future is N: the committee verifies only what the bidder can show.")

  #note(size: 9pt, gap: 5pt, "Adapt the wording to national law and have the person responsible for procurement check it.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)
// ════════════════════════════════════════════════════════════════════════════
#band("Compliance table", id: "table")

#intro(size: 9.4pt, gap: 5pt, "One row per item. The contracting authority ticks what the contract requires and attaches the table to the procurement documents as a mandatory annex to the tender. For each required item the bidder enters M (meets), E (meets by an equivalent) or N (does not meet), briefly how, and where the evidence is: documentation address, test access, page of the tender. A declaration without evidence is not enough. The evaluation committee verifies each item when evaluating tenders and again at acceptance (✓ confirmed, ✗ not confirmed, — not checked).")

#intro(size: 9.4pt, gap: 8pt, "The completed table is part of the tender and becomes an annex to the contract. It verifies that the requirements for the subject of the contract are met (met or not met); it is not an award criterion. To score compliance, say so among the award criteria published in advance in the procurement documents (Directive 2014/24/EU, Article 67).")

#score-sheet(
  headers: ("#", "Requirement (short)", "Spec ref.", "Required?", "M / E / N", "Evidence: how and where", "Verified"),
  roles: ("authority", "bidder", "bidder", "committee"),
  section("MIM0 · Can we get our data out?",
    ("0.1", "Machine-readable data via standard web API", "MIM0 R1.1, R1.2"),
    ("0.2", "Open API description (OpenAPI) at stable address", "MIM0 R1.3"),
    ("0.3", "Filtering by time, place, attributes", "MIM0 R2.1, R2.2"),
    ("0.4", "Subscription to changes where needed", "MIM0 R3.1"),
    ("0.5", "Standard HTTP errors, caching, rate limits", "MIM0 C2"),
  ),
  section("MIM1 · Does every thing have a name that lasts?",
    ("1.1", "Unique persistent identifier per entity", "MIM1 R1.1, R1.5"),
    ("1.2", "Identifier lookup returns data + type", "MIM1 R1.2, R2.1, R2.2"),
    ("1.3", "Cross-system identifier mapping", "MIM1 R1.3, R1.4"),
    ("1.4", "No vendor internals in identifiers", "MIM1 M1 §3.1"),
  ),
  section("MIM2 · Do we speak a common language?",
    ("2.1", "Standard data models wherever possible", "MIM2 R1.2a"),
    ("2.2", "Models documented, units explicit", "MIM2 R1.1"),
    ("2.3", "Extensions as profiles, never forks", "MIM2 R1.2b, R4.1, R4.2"),
    ("2.4", "Open, schema-validatable serialisation", "MIM2 R3.1, R3.4"),
  ),
  section("MIM3 · Can we share on clear terms?",
    ("3.1", "Datasets catalogued with standard metadata", "MIM3 RC4.1–RC4.3"),
    ("3.2", "Template licences and agreements", "MIM3 RC2.2, RC2.3"),
    ("3.3", "City controls access terms itself", "MIM3 RC1.1, RC2.1"),
  ),
  section("MIM6 · Is our data safe in transit and in use?",
    ("6.1", "Encrypted transfer (TLS 1.3)", "MIM6 R2.1, M1.1"),
    ("6.2", "Standard login (OAuth 2.0 / OIDC)", "MIM6 R3.1, M1.2, M1.3"),
    ("6.3", "Role-based access + audit logs", "MIM6 R1.1, R1.3, 8.15"),
    ("6.4", "ISO/IEC 27001:2022 alignment shown", "MIM6 C1–C3 (ISO/IEC 27001)"),
  ),
  section("MIM7 · Does it work on a map?",
    ("7.1", "OGC standard interfaces", "MIM7 R1.1"),
    ("7.2", "Open geo formats", "MIM7 R2.1"),
    ("7.3", "CRS declared (EPSG)", "MIM7 R5.1"),
    ("7.4", "Persistent IDs on spatial features (see 1.1)", "MIM7 R4.1"),
  ),
  section("MIM8 · Can our digital twin grow?",
    ("8.1", "Twin data and outputs via APIs", "MIM8 R1.1"),
    ("8.2", "Models documented and callable", "MIM8 R3.1, R3.2"),
    ("8.3", "Standard output formats", "MIM8 M2"),
    ("8.4", "Workflow provenance recorded", "MIM8 R4.4"),
  ),
  section("Cross-cutting tender clauses", accent: magenta, note: "The bidder confirms acceptance of the contract condition (M / N).",
    ("X.1", "Exit clause: free handover in open formats", "—"),
    ("X.2", "Rights in the data belong to the contracting authority", "—"),
    ("X.3", "No fees for own-data access", "—"),
    ("X.4", "API stability: versioned, 6 months notice of breaking changes", "—"),
  ),
)

#note(size: 8.4pt, gap: 6pt, "Short labels below stand for the full checklist items on the MIM pages — in case of doubt, the full item text governs.")
#spec-link("An editable version of the table is at:", "https://marek-mraz.github.io/mims-procurement-checklist/")
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  GLOSSARY AND FURTHER READING
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glossary")[
  #band("Small glossary", id: "glossary")

  #glossary(
    term("API",
      "A doorway through which one program asks another for data — over the web, without a human clicking."),
    term("Data model",
      "The agreed shape of the data: which fields exist, what they mean, which units they use."),
    term("DCAT-AP",
      "European metadata profile for data catalogues; it lets datasets be found on national and European portals too."),
    term("EPSG",
      "Registry of numeric codes for coordinate reference systems (e.g. EPSG:4326 for WGS 84)."),
    term("Identifier",
      "A permanent name for one thing (one lamp, one building) that all systems use to mean that thing."),
    term("Interoperability",
      "The ability of systems from different vendors to exchange data and understand it."),
    term("IRI",
      "International form of a web identifier (like a URL, with non-ASCII characters allowed). MIM1 names entities with it."),
    term("LDT",
      "Local Digital Twin: a digital model of a city or a part of it, connected to data and simulations."),
    term("Machine-readable",
      "Structured so a program can process it directly (JSON, CSV) — a PDF of a table is not."),
    term("Metadata",
      "Data about data: what a dataset contains, who provides it, how current it is, under what licence."),
    term("OAuth 2.0 / OIDC",
      "Open standards for login and for granting access. OpenID Connect (OIDC) adds identity verification to OAuth 2.0."),
    term("OGC",
      "Open Geospatial Consortium: the body that publishes standards for geospatial data and services (OGC API, WFS, SensorThings)."),
    term("Open standard",
      "A technical rule anyone may read and implement without paying or asking permission."),
    term("OpenAPI",
      "Open format for a machine-readable description of a web API: addresses, parameters, responses."),
    term("Serialisation",
      "Writing data in a concrete format (e.g. JSON, XML) so that it can be stored or sent."),
    term("TLS",
      "The protocol that encrypts data in transit over a network (the basis of HTTPS)."),
    term("Vendor lock-in",
      "When leaving a supplier costs so much — in data, formats or fees — that you effectively cannot."),
    term("Webhook / MQTT",
      "Two ways for a system to report a change itself: a webhook calls your address, MQTT delivers messages to subscribers."),
  )

  #more-links("Where to learn more",
    more-link("mims.oascities.org", "The full MIMs Plus specification, maintained by OASC."),
    more-link("living-in.eu", "The European movement for digital transformation of cities — declaration and MIMs Plus context."),
    more-link("smartdatamodels.org", "The open library of standard data models (FIWARE, TM Forum, IUDX, OASC)."),
    more-link("oascities.org/academy", "CITYxCITY Academy — courses for city staff, by cities."),
  )
]


// ════════════════════════════════════════════════════════════════════════════
//  BACK COVER
// ════════════════════════════════════════════════════════════════════════════
#pagebreak()
#back-cover(
  "Compiled from the MIMs Plus Specification 9.0 by Open & Agile Smart Cities (mims.oascities.org). Specification content © OASC. This booklet is an independent plain-language companion for municipal procurement; in case of doubt, the specification governs.",
  "Made with open tools. Reuse and adapt freely for your city.",
  author: "Author of the booklet: Marek Mráz",
)
