// ════════════════════════════════════════════════════════════════════════════
//  MIMs procurement booklet, edition: pl
//
//  GENERATED by gen_typ.py from content/pl.json + shared.json + quotes.json.
//  Do not edit: change the JSON and run ./build.sh.
//
//  How to read it: the file runs top to bottom in page order. Each #name(…)
//  is one block on the page; what the block looks like (sizes, colours,
//  spacing) is described next to its definition in ../style.typ.
//  #fit-page("name")[ … ] is one physical page.
//  One-letter prepositions may be followed by a no-break space (U+00A0),
//  which looks like a normal space here.
//
//  Build:  typst compile --root .. --font-path ../tools/fonts booklet-pl.typ
// ════════════════════════════════════════════════════════════════════════════
#import "../style.typ": *

#show: booklet.with(title: "Lista kontrolna zamówień · oparta na Minimalnych · Mechanizmach Interoperacyjności (MIMs)", lang: "pl",
  nav: (overview: "Przegląd", clauses: "Klauzule", example: "Przykład", table: "Tabela zgodności", glossary: "Glosariusz", list: "Lista", back: "powrót do listy", page: "str."),
  mims: ("MIM0", "MIM1", "MIM2", "MIM3", "MIM6", "MIM7", "MIM8",))


// ════════════════════════════════════════════════════════════════════════════
//  COVER
// ════════════════════════════════════════════════════════════════════════════
#cover(
  title:    "Lista kontrolna zamówień · oparta na Minimalnych · Mechanizmach Interoperacyjności (MIMs)",
  subtitle: "Co określić w dokumentach zamówienia, aby miasto zachowało kontrolę nad swoimi danymi",
  tagline:  "Specyfikacja: MIMs Plus 9.0 autorstwa OASC",
  footer:   "Dla specjalistów ds. zamówień, kierowników projektów i dyrektorów IT europejskich miast",
  author:   "Autor poradnika: Marek Mráz",
)


// ════════════════════════════════════════════════════════════════════════════
//  WHY THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("why")[
  #band("Cel niniejszego poradnika")

  #lead("Co roku miasta kupują oprogramowanie: systemy parkingowe, platformy czujników, portale mapowe, cyfrowe bliźniaki. Zbyt często dane zbierane przez te systemy zostają w nich uwięzione. Gdy umowa wygasa, dane — sfinansowane ze środków publicznych — odchodzą wraz z dostawcą lub pozostają w formacie, którego nikt inny nie potrafi odczytać.")

  #lead("Nie musi tak być. Minimalne Mechanizmy Interoperacyjności (MIMs), rozwijane przez Open & Agile Smart Cities (OASC) i wspierane przez europejski ruch living-in.eu, opisują minimalne wymagania techniczne gwarantujące, że Twoje dane pozostaną otwarte, zdatne do ponownego wykorzystania i neutralne wobec dostawców. Są celowo ograniczone: to nie obszerna architektura, lecz zaledwie kilka warunków koniecznych do tego, by systemy mogły wymieniać dane.")

  #lead("Do korzystania z niniejszego poradnika nie jest wymagane przygotowanie techniczne. Każda lista kontrolna przekłada jeden mechanizm MIM na sformułowane prostym językiem punkty, które można skopiować do dokumentacji zamówienia, wraz z uzasadnieniem, dlaczego każdy z nich chroni zamawiającego. Bezpośrednio po liście kontrolnej znajduje się dosłowne brzmienie każdego wymogu danego MIM, dzięki czemu eksperci techniczni i wykonawcy mogą sprawdzić szczegóły.")

  #lead("Miasta wymagające MIMs kupują raz, a korzystają wielokrotnie: dane o jakości powietrza zasilają tablice w szkołach, ewidencja latarni wspiera planowanie energetyczne, a kolejny dostawca kontynuuje pracę tam, gdzie zakończył poprzedni. Na tym polega interoperacyjność w praktyce — i tego coraz częściej oczekuje się w projektach finansowanych przez UE.")

  #pull-quote(
    "Minimalne mechanizmy interoperacyjności (MIMs) zapewniają minimalny, lecz wystarczający poziom interoperacyjności danych, systemów i usług, w szczególności w kontekście rozwiązań dla inteligentnych miast. · Grupą docelową tego dokumentu są: · 1. Dostawcy rozwiązań, którzy chcą zapewnić interoperacyjność swoich produktów z innymi oraz umożliwić płynną wymianę danych w kontekście inteligentnych miast i społeczności. · 2. Zamawiający, którzy pragną pozyskiwać rozwiązania przyszłościowe, pozwalające na efektywną kosztowo integrację z istniejącą architekturą teleinformatyczną (ICT) inteligentnych miast i społeczności.",
  )

  #policy-box("Jak mechanizmy MIM wpisują się w prawo UE",
    "MIMs stanowią specyfikację techniczną, a nie akt prawny. Wskazują ten sam kierunek, co przepisy UE obowiązujące już w odniesieniu do danych publicznych i usług cyfrowych:",
    law("Dyrektywa w sprawie zamówień publicznych", "Dyrektywa 2014/24/UE, art. 42",
      "specyfikacje techniczne mogą odsyłać do norm, zawsze z dopiskiem „lub równoważne”; co do zasady nie mogą wskazywać konkretnej marki lub produktu."),
    law("Akt w sprawie danych", "Rozporządzenie (UE) 2023/2854",
      "dostęp do danych z produktów skomunikowanych oraz zmiana dostawców usług w chmurze bez uzależnienia od dostawcy (lock-in)."),
    law("Akt na rzecz interoperacyjnej Europy", "Rozporządzenie (UE) 2024/903",
      "oceny interoperacyjności transgranicznych cyfrowych usług publicznych oraz ponowne wykorzystywanie otwartych rozwiązań."),
    law("Dyrektywa o otwartych danych", "Dyrektywa (UE) 2019/1024",
      "zbiory danych o wysokiej wartości publikowane bezpłatnie, w formacie maszynowym, za pośrednictwem interfejsów API."),
    law("Dyrektywa NIS2", "Dyrektywa (UE) 2022/2555",
      "podstawowe środki cyberbezpieczeństwa; prawo krajowe określa zakres objęcia nimi administracji samorządowej."),
    law("RODO", "Rozporządzenie (UE) 2016/679",
      "dane osobowe w systemach miejskich (parkingi, kamery, mobilność)."),
    law("Akt w sprawie sztucznej inteligencji", "Rozporządzenie (UE) 2024/1689",
      "zasady dla systemów sztucznej inteligencji; istotne dla modeli AI w cyfrowych bliźniakach."),
    note: "Wyłącznie w celach informacyjnych. Sprawdź, w jaki sposób Twój kraj dokonał transpozycji każdego z tych aktów.",
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  HOW TO USE THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("howto")[
  #band("Jak korzystać z tego poradnika")

  #steps(
    step("Przygotuj",
      "Przeczytaj siedem list kontrolnych. Zaznacz te, które dotyczą Twojego zamówienia. Większość przetargów wymaga MIM0, MIM1, MIM2 i MIM6; dodaj MIM3, gdy dane są udostępniane podmiotom trzecim lub przez portal danych, MIM7 w przypadku rozwiązań z mapą, MIM8 dla cyfrowych bliźniaków."),
    step("Przygotuj postępowanie",
      "Skopiuj zaznaczone pozycje z listy do swoich wymagań. Każdy punkt sformułowano jako zdanie gotowe do wklejenia. Dodaj klauzule horyzontalne: kosztują niewiele, a zapobiegają uzależnieniu od dostawcy.",
      links: (("clauses", "Klauzule"), ("example", "Przykład"), )),
    step("Oceń",
      "Wymagaj od wykonawców dowodów, a nie deklaracji (zob. klauzula o tej nazwie). Zweryfikuj zgodność na podstawie tabeli zgodności wypełnionej przez wykonawcę.",
      links: (("table", "Tabela zgodności"), )),
    step("Odbierz",
      "Przy odbiorze ponownie przetestuj każdy zaznaczony punkt. Wymóg, który nie został sprawdzony przy odbiorze, nigdy nie był prawdziwym wymogiem.",
      links: (("table", "Tabela zgodności"), )),
  )

  #legend("Jak czytać cytaty ze specyfikacji",
    note: "Pozycje listy kontrolnej formułują każdy punkt jako wymóg, nawet jeśli specyfikacja jedynie go zaleca (should) lub wymienia jako mechanizm kandydacki. Jest to suwerenna decyzja zamawiającego.",
    entry("MUSI / MA OBOWIĄZEK (SHALL / MUST)", "obowiązkowe. Bez tego system nie spełnia wymagań."),
    entry("NIE MOŻE / NIE MA PRAWA (MUST NOT)", "niedozwolone. System wykazujący takie działanie nie spełnia wymagań."),
    entry("POWINIEN / POWINNY (SHOULD)", "usilnie zalecane. Odstępstwa wymagają rzetelnego uzasadnienia pisemnego."),
    entry("MOŻE / MOGĄ (MAY)", "opcjonalne. Mile widziane, lecz nigdy niewymagane."),
    entry("MOŻE (CAN)", "możliwość, a nie wymóg. Opisuje, co jest technicznie możliwe, i do niczego nie zobowiązuje."),
  )

  #note("Każda pozycja listy kontrolnej zawiera krótkie odniesienie, np. → MIM0 R1.1. Wskazuje ono wymóg w MIMs Plus 9.0, z którego pochodzi; zaraz za listą kontrolną znajduje się dosłowne brzmienie każdego wymogu danego MIM. Jedynie MIM0 definiuje słowa kluczowe: mają one moc wiążącą, gdy są pisane wielkimi literami, zgodnie z konwencją IETF RFC 2119 i RFC 8174 (słowo CAN pochodzi z ISO/IEC Directives, Part 2). Pozostałe MIMs nie zawierają definicji: MIM6 zapisuje SHALL przeważnie wielkimi literami, MIM2, MIM3, MIM7 i MIM8 używają shall, should i must małymi literami, a MIM1 stosuje je wyłącznie w opisie mechanizmu (MUST NOT w sekcji 3.1). W niniejszym poradniku słowa pisane małymi literami traktowane są identycznie; wykonawca może interpretować je swobodniej.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  THE SEVEN MIMs AT A GLANCE
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glance")[
  #band("Siedem mechanizmów MIM i trzy narzędzia", id: "glance")

  #intro("Siedem zwięzłych mechanizmów, jeden cel: dane pozostają pod kontrolą miasta, a systemy ze sobą współpracują.")

  #glance(
    note: "Informacja o numeracji: MIMs Plus 9.0 określa siedem mechanizmów o numerach 0, 1, 2, 3, 6, 7 i 8. Mechanizmy MIM4 (dane osobowe) i MIM5 (etyczna AI) należą do wcześniejszych wersji OASC i nie wchodzą w skład wersji 9.0. W tym poradniku niczego nie brakuje.",
    card("MIM0", "Dostęp do danych",
      "Czy możemy wydobyć nasze dane?",
      "Dane można pobrać przez standardowe interfejsy API, w formatach odczytywanych maszynowo.",
      "https://mims.oascities.org/accessing-data"),
    card("MIM1", "Łączenie danych",
      "Czy każdy obiekt ma trwałą nazwę?",
      "Każdy czujnik, latarnia i budynek posiada unikalny, trwały identyfikator.",
      "https://mims.oascities.org/interlinking-data"),
    card("MIM2", "Reprezentacja danych",
      "Czy mówimy wspólnym językiem?",
      "Dane są zgodne ze standardowymi, udokumentowanymi modelami danych z jawnymi jednostkami.",
      "https://mims.oascities.org/representing-data"),
    card("MIM3", "Wymiana danych",
      "Czy możemy udostępniać na jasnych warunkach?",
      "Zbiory danych są skatalogowane i udostępniane na podstawie wzorcowych licencji i przejrzystych reguł.",
      "https://mims.oascities.org/exchanging-data"),
    card("MIM6", "Bezpieczeństwo danych",
      "Czy nasze dane są bezpieczne?",
      "Szyfrowana transmisja, standardowe logowanie, dostęp oparty na rolach, logi audytowe.",
      "https://mims.oascities.org/securing-data"),
    card("MIM7", "Dane geoprzestrzenne",
      "Czy to działa na mapie?",
      "Dane przestrzenne wykorzystują interfejsy OGC, otwarte formaty i zadeklarowane układy współrzędnych.",
      "https://mims.oascities.org/geospatial-data"),
    card("MIM8", "Lokalne cyfrowe bliźniaki",
      "Czy nasz cyfrowy bliźniak może się rozwijać?",
      "Dane bliźniaka, modele i wyniki pozostają dostępne, udokumentowane i gotowe do ponownego użycia.",
      "https://mims.oascities.org/local-digital-twins"),
  )

  #tools("Narzędzia do Twojego postępowania",
    tool("clauses", "Horyzontalne klauzule umowne",
      "Co powinno znaleźć się w każdej umowie?",
      "Wyjście z umowy, prawa do danych, stabilność API."),
    tool("example", "Przykład: czujniki jakości powietrza",
      "Jak to wygląda w praktyce?",
      "Struktura dokumentacji i przykładowe zapisy do wklejenia."),
    tool("table", "Tabela zgodności",
      "Jak wykonawca ma to udowodnić?",
      "Wypełniana przez wykonawcę, weryfikowana przez komisję, załączana do umowy."),
  )

  #menu-line(("glossary", "Krótki słowniczek"), ("more", "Gdzie dowiedzieć się więcej"))
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 checklist")[
  #mim-page(
    id:       "MIM0",
    name:     "Dostęp do danych",
    question: "Czy możemy wydobyć nasze dane?",
    url:      "https://mims.oascities.org/accessing-data",
    intro:    "To jest fundament. Jeśli dane nie mogą opuścić systemu przez standardowy interfejs, cała reszta tego poradnika pozostaje teorią. MIM0 stawia jeden wymóg każdemu kupowanemu systemowi: dane muszą być dostępne w postaci odczytywalnej maszynowo, za pośrednictwem zwykłego internetu.",
    list:     "Lista",
  )

  #item("Wszystkie dane zbierane lub generowane przez system można pobrać w co najmniej jednym formacie odczytywalnym maszynowo (np. JSON, CSV) za pośrednictwem standardowego interfejsu API.",
    why:  "Twój kolejny wykonawca — lub Twoi pracownicy — mogą korzystać z danych bez konieczności pytania dostawcy o zgodę.",
    refs: "MIM0 R1.1, R1.2",
    num:  "0.1")

  #item("API jest formalnie opisane w otwartym, odczytywalnym maszynowo dokumencie (na przykład OpenAPI), opublikowanym pod stabilnym adresem.",
    why:  "Każdy programista może się połączyć bez płatnych „warsztatów integracyjnych”.",
    refs: "MIM0 R1.3",
    num:  "0.2")

  #item("Dane można filtrować bezpośrednio w API według czasu, lokalizacji oraz atrybutów.",
    why:  "Pobierasz to, czego potrzebujesz, a nie codzienny pełny zrzut.",
    refs: "MIM0 R2.1, R2.2",
    num:  "0.3")

  #item("Jeżeli dany przypadek użycia wymaga danych bieżących, odbiorcy mogą subskrybować powiadomienia o zmianach (webhooks, MQTT lub pokrewne) zamiast ciągłego odpytywania (polling).",
    why:  "Pulpity nawigacyjne i alerty w czasie rzeczywistym stają się możliwe i tanie.",
    refs: "MIM0 R3.1",
    num:  "0.4")

  #item("Obsługa błędów, cache’owanie i limity zapytań wykorzystują standardowe konwencje protokołu HTTP i są udokumentowane.",
    why:  "Integracje zgłaszają błędy w sposób jawny i naprawialny, a nie po cichu.",
    refs: "MIM0 C2",
    num:  "0.5")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Dane, za które zapłacono, pozostają zdatne do użytku po zakończeniu umowy.",
      "Nowe usługi bazują na dotychczasowych danych, zamiast startować od zera.",
      "Koszty integracji maleją przy każdym kolejnym projekcie.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "„Eksport danych na żądanie za pośrednictwem naszego działu wsparcia”.",
      "„Interfejs API jest dostępny jako płatny moduł dodatkowy”.",
      "Opłaty za pojedyncze zapytania przy dostępie do własnych danych miasta (zob. klauzula „Brak opłat za własne dane”).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM0",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM0",
    capability("C1", "Machine-readable data is retrievable through the web",
      tr: "Dane odczytywalne maszynowo można pobierać przez sieć internetową"),
    req("R1.1",
      tr: "Systemy MAJĄ OBOWIĄZEK umożliwiać pobieranie danych w co najmniej jednym formacie odczytywalnym maszynowo. Formaty MOŻNA określać za pomocą mechanizmu negocjacji treści HTTP (HTTP Content-Negotiation)",
      en: "Systems SHALL allow retrieval of data in at least one machine-readable format. Formats can be specified through HTTP Content-Negotiation"),
    req("R1.2",
      tr: "Dane MUSZĄ być możliwe do pobrania za pośrednictwem co najmniej jednego standardowego mechanizmu internetowego",
      en: "Data SHALL be retrievable via at least one standard web-based mechanism"),
    req("R1.3",
      tr: "Mechanizm(y) dostępu MAJĄ OBOWIĄZEK być formalnie opisane",
      en: "Access mechanism(s) SHALL be formally described"),
    req("R1.4",
      tr: "Modele danych używane w payloadach powinny być określone (zob. MIM2)",
      en: "Data Models used by payloads should be specified (see MIM2)"),
    capability("C2", "Access is structured and queryable",
      tr: "Dostęp jest ustrukturyzowany i umożliwia odpytywanie"),
    req("R2.1",
      tr: "Systemy MAJĄ OBOWIĄZEK udostępniać dane za pośrednictwem ustrukturyzowanego i spójnego interfejsu",
      en: "Systems SHALL provide data through a structured and consistent interface"),
    req("R2.2",
      tr: "Systemy MAJĄ OBOWIĄZEK obsługiwać podstawowe zapytania lub filtrowanie (np. według czasu, lokalizacji, atrybutów)",
      en: "Systems SHALL support basic querying and/or filtering (e.g. by time, location, attributes)"),
    capability("C2 best practice", "Additional best practice to consider:",
      tr: "Dodatkowe najlepsze praktyki do rozważenia:", sub: true),
    req("C2",
      tr: "Interfejsy API POWINNY obsługiwać pobieranie danych bieżących · Interfejsy API POWINNY obsługiwać pobieranie danych historycznych, gdy ma to zastosowanie · Interfejsy API POWINNY obsługiwać zapytania geoprzestrzenne, gdy ma to zastosowanie (zob. MIM7) · Interfejsy API POWINNY obsługiwać subskrypcję zmian, gdy ma to zastosowanie · Interfejsy API POWINNY ujawniać znacznik czasu kolejnej oczekiwanej aktualizacji · Interfejsy API POWINNY obsługiwać jednoznaczne wersjonowanie punktów końcowych · Interfejsy API POWINNY udostępniać przykładowe struktury danych lub zapytania testowe · Interfejsy API POWINNY obsługiwać standardowe nagłówki buforowania HTTP · Interfejsy API POWINNY komunikować status limitów zapytań za pomocą standardowych nagłówków HTTP · Interfejsy API POWINNY zwracać ustrukturyzowaną treść komunikatów o błędach · Interfejsy API MOGĄ obsługiwać odpowiedzi częściowe lub projekcje zapytań · Interfejsy API MOGĄ udostępniać standardowy punkt końcowy sprawdzania stanu technicznego/gotowości (health/status)",
      en: "APIs SHOULD support retrieval of current data · APIs SHOULD support retrieval of historical data when applicable · APIs SHOULD support geospatial querying when applicable (see MIM7) · APIs SHOULD support subscription to changes when applicable · APIs SHOULD expose next expected update timestamp · APIs SHOULD support explicit versioning of endpoints · APIs SHOULD provide example payloads or test queries · APIs SHOULD support standard HTTP caching headers · APIs SHOULD communicate rate limit status via standard HTTP headers · APIs SHOULD return structured error bodies · APIs MAY support partial responses or query projections · APIs MAY expose a standard health/status endpoint"),
    capability("C3", "Changes in data can be subscribed to",
      tr: "Istnieje możliwość subskrybowania zmian w danych"),
    req("R3.1",
      tr: "Systemy obsługujące przypadki użycia wymagające powiadomień MAJĄ OBOWIĄZEK zapewnić co najmniej jeden mechanizm otrzymywania powiadomień o zmianach danych",
      en: "Systems for use cases that require notifications SHALL provide at least one mechanism to receive updates on data changes"),
    req("R3.2",
      tr: "Systemy MOGĄ obsługiwać wiele mechanizmów subskrypcji w zależności od przypadku użycia",
      en: "Systems MAY support multiple subscription mechanisms depending on use case"),
    capability("C4", "Access to information can be restricted",
      tr: "Dostęp do informacji może podlegać ograniczeniom"),
    req("C4",
      tr: "Jeżeli wprowadza się takie ograniczenia, MAJĄ OBOWIĄZEK być one zgodne z wymaganiami zdefiniowanymi w MIM3 i MIM6, a w szczególności dotyczącymi: identyfikacji uczestników (MIM3.C5.R0), autoryzacji i ról uczestników (MIM6.C1.R4) oraz zasad na poziomie zasobów danych (MIM6.C1.R4)",
      en: "If such restrictions are in place, they SHALL follow the requirements defined in MIM3 and MIM6, specifically: actor identification (MIM3.C5.R0), authorization and actor roles (MIM6.C1.R4), data asset-level policies (MIM6.C1.R4)"),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/accessing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 checklist")[
  #mim-page(
    id:       "MIM1",
    name:     "Łączenie danych",
    question: "Czy każdy obiekt ma trwałą nazwę?",
    url:      "https://mims.oascities.org/interlinking-data",
    intro:    "Miasto składa się z wielu obiektów: latarni, rurociągów, budynków, miejsc parkingowych. Systemy teleinformatyczne pojawiają się i znikają, a obiekty trwają. MIM1 wymaga, aby każdy obiekt otrzymał nazwę — identyfikator — który przetrwa oprogramowanie, w którym został po raz pierwszy zapisany, dzięki czemu jego historia i relacje z innymi danymi przetrwają każdą migrację.",
    list:     "Lista",
  )

  #item("Każdy obiekt (czujnik, latarnia, budynek, miejsce parkingowe…) ma unikalny, trwały identyfikator, który nie ulega zmianie w przypadku wymiany oprogramowania.",
    why:  "Historia oraz powiązania pomiędzy systemami przetrwają zmianę wykonawcy.",
    refs: "MIM1 R1.1, R1.5",
    num:  "1.1")

  #item("Identyfikator można odpytać, aby pobrać dane obiektu oraz jego znaczenie semantyczne (typ) w formacie odczytywalnym maszynowo.",
    why:  "Inne systemy mogą automatycznie podążać za takimi powiązaniami.",
    refs: "MIM1 R1.2, R2.1, R2.2",
    num:  "1.2")

  #item("W przypadku gdy ten sam obiekt fizyczny istnieje w kilku systemach, jego identyfikatory można wzajemnie powiązać (zmapować).",
    why:  "Można bezspornie wykazać, że budynek w systemie GIS i budynek w systemie energetycznym to ten sam obiekt.",
    refs: "MIM1 R1.3, R1.4",
    num:  "1.3")

  #item("Identyfikatory nie zawierają wewnętrznych struktur dostawcy (np. identyfikatorów wierszy w bazie, nazw serwerów).",
    why:  "W przeciwnym razie identyfikatory znikają wraz z umową.",
    refs: "MIM1 M1 §3.1",
    num:  "1.4")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Pomiary z dziesięciu lat pozostają przypisane do właściwego słupa oświetleniowego.",
      "Wydziały przestają prowadzić pięć wzajemnie sprzecznych rejestrów tego samego majątku.",
      "Łączenie zbiorów danych staje się prostym zapytaniem, a nie osobnym projektem doradczym.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "„Identyfikatory są wewnętrzne dla naszej platformy”.",
      "Identyfikatory są generowane na nowo przy każdej migracji danych.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM1",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM1",
    capability("C1", "Entities are identified using unique identifiers",
      tr: "Obiekty są identyfikowane za pomocą unikalnych identyfikatorów"),
    req("R1.1",
      tr: "Każdy obiekt w systemie posiada unikalny identyfikator",
      en: "Every entity within the system has a unique identifier"),
    req("R1.2",
      tr: "Istnieje sposób na pobranie informacji o obiekcie poprzez wyszukanie jego identyfikatora w systemie",
      en: "There exists a way to retrieve information about an entity by looking up the identifier within a system"),
    req("R1.3",
      tr: "Jeżeli unikalny identyfikator wskazuje ten sam obiekt w wielu systemach, istnieje możliwość ustalenia sposobu wyszukania informacji o nim w każdym z tych systemów",
      en: "if a unique identifier points to the same entity within multiple systems, it is possible to derive the way to look up information about it in each of these systems"),
    req("R1.4",
      tr: "Jeżeli wiele unikalnych identyfikatorów wskazuje ten sam obiekt, istnieje możliwość ich wzajemnego zmapowania",
      en: "if a multiple [sic] unique identifiers point to the same entity, it is possible to map them"),
    req("R1.5",
      tr: "Istnieje możliwość tworzenia identyfikatorów, które są trwałe w czasie",
      en: "It is possible to create identifiers that are persistent over time"),
    capability("C2", "Entities can be typed",
      tr: "Obiekty mogą być typowane"),
    req("R2.1",
      tr: "Istnieje sposób na pobranie semantyki obiektu wyłącznie przy użyciu jego unikalnego identyfikatora",
      en: "There is a way to retreive [sic] the semantics of an entity, only using its unique identifier"),
    req("R2.2",
      tr: "Semantyka ta jest opisana w formacie odczytywalnym maszynowo",
      en: "These semantics are described in a machine-readable format"),
    capability("C3", "Entities can be (de)referenced",
      tr: "Obiekty mogą być (de)referencjonowane"),
    req("R3.1",
      tr: "Istnieje sposób na dereferencję relacji zdefiniowanej dla obiektu",
      en: "There exists a way to dereference a relation defined on an entity"),
    req("R3.2",
      tr: "Istnieje sposób na zastosowanie dodatkowej semantyki do istniejącej ontologii",
      en: "There exists a way to apply additional semantics to an existing ontology"),
    capability("M1", "Mechanism 1, section 3.1: Entity Identification with Globally Unique IRIs",
      tr: "Mechanizm 1, sekcja 3.1: Identyfikacja obiektów za pomocą globalnie unikalnych identyfikatorów IRI"),
    req("§3.1",
      tr: "Identyfikator IRI traktuje się jako kanoniczny identyfikator we wszystkich systemach podrzędnych; implementacje NIE MAJĄ PRAWA generować identyfikatorów IRI zawierających zmienne szczegóły implementacyjne, takie jak identyfikatory wierszy w bazie danych czy nazwy hostów serwerów.",
      en: "The IRI is treated as the canonical identifier in all downstream systems; implementations MUST NOT generate IRIs that embed volatile implementation details such as database row IDs or server hostnames."),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/interlinking-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 checklist")[
  #mim-page(
    id:       "MIM2",
    name:     "Reprezentacja danych",
    question: "Czy mówimy wspólnym językiem?",
    url:      "https://mims.oascities.org/representing-data",
    intro:    "Dwa systemy mogą eksportować pliki JSON, a mimo to zupełnie się nie rozumieć. MIM2 dotyczy semantyki: stosowania wspólnych, udokumentowanych modeli danych — z jawnymi jednostkami miar i formatami — tak aby „temperatura”, „miejsce parkingowe” lub „jakość powietrza” oznaczały dokładnie to samo w każdym posiadanym systemie.",
    list:     "Lista",
  )

  #item("Dane wykorzystują powszechnie uznane, standardowe modele danych, o ile takie istnieją (np. Smart Data Models, SAREF, ISO/IEC 5087); wszelkie odstępstwa są uzasadniane na piśmie.",
    why:  "Dane od dwóch różnych wykonawców łączą się bez konieczności ich żmudnej konwersji.",
    refs: "MIM2 R1.2a",
    num:  "2.1")

  #item("Wszystkie wykorzystywane modele danych są jednoznacznie udokumentowane, z podaniem jednostek miar oraz formatów daty i czasu.",
    why:  "Wpis „Temperatura: 23” jest bezużyteczny, jeśli nikt nie zapisał °C czy °F.",
    refs: "MIM2 R1.1",
    num:  "2.2")

  #item("Rozszerzenia są dostarczane jako udokumentowane profile lub uzupełnienia bazowego modelu standardowego — nigdy jako zmodyfikowany prywatny fork.",
    why:  "Zachowujesz zgodność ze społecznością i możliwość wdrażania przyszłych aktualizacji.",
    refs: "MIM2 R1.2b, R4.1, R4.2",
    num:  "2.3")

  #item("Każdy model posiada co najmniej jedną otwartą serializację z możliwością walidacji schematem (np. JSON z JSON Schema).",
    why:  "Przychodzące dane można automatycznie sprawdzać już na wejściu.",
    refs: "MIM2 R3.1, R3.4",
    num:  "2.4")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Jeden pulpit menedżerski pobiera dane od wielu dostawców bez budowania dodatkowych adapterów.",
      "Twoje dane są zrozumiałe dla narzędzi używanych w innych miastach — a ich dane dla Twoich narzędzi.",
      "Automatyczna walidacja wychwytuje uszkodzone dane, zanim trafią one do reszty systemów.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "„Nasz własnościowy model danych jest bogatszy niż standard”.",
      "Dokumentacja dostępna wyłącznie na podstawie umowy NDA.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM2",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM2",
    capability("C1", "All entities included in data sources are described using consistent data models to enable interoperability for applications and systems",
      tr: "Wszystkie obiekty zawarte w źródłach danych są opisywane za pomocą spójnych modeli danych w celu zapewnienia interoperacyjności aplikacji i systemów"),
    req("R1.1",
      tr: "Modele danych stosowane dla wszystkich obiektów w dowolnym źródle danych muszą zostać jawnie określone. Mają obowiązek być dobrze udokumentowane i posiadać opisowe metadane, w których użyte terminy muszą być jednoznaczne pod względem semantycznym. W odniesieniu do atrybutów związanych z jednostkami miar, formatami czasu itp., zastosowane jednostki, formaty itp. muszą zostać jawnie określone. Modele danych powinny zostać skatalogowane, tak aby można je było łatwo odnaleźć.",
      en: "Data models used for all entities in any data source shall be made explicit. They shall be well documented and have descriptive metadata, where the terms used shall be semantically unambiguous. For attributes related to units of measurement, time formats etc, the units, formats etc, used shall be made explicit. The data models should be catalogued so that they can be easily findable."),
    req("R1.2a",
      tr: "Stosowane modele danych muszą opierać się (tam, gdzie to możliwe) na powszechnie uznanych, standaryzowanych modelach danych wymienionych poniżej",
      en: "Data models used shall be based (wherever possible) on commonly recognised standardised data models as listed below"),
    req("R1.2b",
      tr: "W przypadkach, w których nie jest możliwe zastosowanie istniejących standaryzowanych modeli danych, należy podjąć wysiłki w celu rozszerzenia istniejących standaryzowanych modeli danych, które są najbardziej zbliżone, lub zdefiniowania nowych, zgodnie z najlepszymi praktykami i konwencjami społeczności lub organizacji definiującej te modele danych.",
      en: "Where it is not possible to use existing standardised data models, efforts shall be made to extend existing standardised data models that are most closely aligned or to define new ones, following best practice and conventions of the community or organisation defining the data models."),
    req("R1.3",
      tr: "Stosowane modele danych muszą wspierać wymianę danych poprzez spełnienie odpowiednich wymagań mechanizmów MIM w zakresie dostępu do danych oraz łączenia danych",
      en: "Data models used shall support the exchange of data by using the relevant requirements of the MIMs on Accessing data and Interlinking data"),
    capability("C2", "Different data models for the same entity that are used within a common data sharing ecosystem should be easily transformable into a common data model",
      tr: "Różne modele danych dla tego samego obiektu, stosowane we wspólnym ekosystemie wymiany danych, powinny dawać się łatwo przekształcić do postaci wspólnego modelu danych"),
    req("R2.1",
      tr: "Dla każdego ekosystemu danych powinien zostać opracowany wspólny model danych dla każdego kluczowego obiektu. Taki wspólny model danych powinien zawierać wszystkie pola występujące w różnych modelach danych tego obiektu, które są stosowane w danym ekosystemie danych. Każdy odmienny model danych używany w tym ekosystemie danych mógłby wówczas zostać przekształcony do postaci wspólnego modelu danych.",
      en: "A common data model for each key entity should be developed for any data ecosystem. That common data model should contain all the fields included within the different data models for that entity that are used within that data ecosystem. Each different data model used within that data ecosystem could then be transformed into the common data model."),
    capability("C3", "Any data and its associated metadata can be shared in open, standardised, data transport formats so that data can be exchanged and interpreted consistently by different tools and implementations",
      tr: "Dowolne dane wraz z powiązanymi z nimi metadanymi mogą być udostępniane w otwartych, standaryzowanych formatach przesyłania danych, co umożliwia spójną wymianę i interpretację informacji przez różne narzędzia i implementacje"),
    req("R3.1",
      tr: "Każdy stosowany model danych musi posiadać co najmniej jeden zdefiniowany, odczytywalny maszynowo format przesyłania danych („serializację”), który jest otwarty, publicznie dostępny i niezależny od implementacji.",
      en: "Each data model used shall have at least one defined machine-readable data transport format (“serialisation”) that is open, publicly available and implementation-independent."),
    req("R3.2",
      tr: "Dokumentacja formatu przesyłania danych powinna być wystarczająca, aby umożliwić stworzenie otwartej aplikacji lub interpretera zdolnego do odtworzenia wszystkich danych zapisanych w takim formacie danych.",
      en: "The documentation of the data transport format should be sufficient to allow the creation of non-proprietary application or interpretor [sic] that is able to reconstruct all the data stored in such a data format."),
    req("R3.3",
      tr: "W przypadku gdy dla tego samego modelu danych obsługiwanych jest wiele formatów przesyłania danych, muszą one reprezentować tę samą zawartość informacyjną w sposób spójny i bez utraty znaczenia semantycznego.",
      en: "Where multiple data transport formats are supported for the same data model, they shall represent the same information content consistently and without loss of meaning."),
    req("R3.4",
      tr: "Reprezentacja powinna umożliwiać walidację przy użyciu publicznie opublikowanych schematów, gramatyk lub równoważnych reguł odczytywalnych maszynowo, o ile takie mechanizmy walidacji istnieją dla wybranego formatu.",
      en: "The representation should support validation using openly published schemas, grammars, or equivalent machine-readable constraints, where such validation mechanisms exist for the chosen format."),
    capability("C4", "When useful, it should be possible to create \"Application Profiles\" for a data model, so that use case specific attributes can be added or specified without changing the underlying data model",
      tr: "W uzasadnionych przypadkach powinna istnieć możliwość tworzenia „Profili Aplikacji” dla danego modelu danych, tak aby atrybuty specyficzne dla danego przypadku użycia mogły być dodawane lub precyzowane bez modyfikacji bazowego modelu danych"),
    req("R4.1",
      tr: "Profile aplikacji rozszerzające model danych nie powinny wpływać na już istniejący model ani na jego użytkowników",
      en: "Application Profiles that extend a data model should not impact the already existing model and its users"),
    req("R4.2",
      tr: "Wyszczególnienia lub rozszerzenia wprowadzone w profilu aplikacji danego modelu powinny być rzetelnie udokumentowane w postaci odrębnej od bazowego modelu danych",
      en: "The specialisations or extensions introduced in the Application Profile of the model should be well documented, separate from the base data model"),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/representing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 checklist")[
  #mim-page(
    id:       "MIM3",
    name:     "Wymiana danych",
    question: "Czy możemy udostępniać na jasnych warunkach?",
    url:      "https://mims.oascities.org/exchanging-data",
    intro:    "Nie wszystkie dane miejskie można po prostu opublikować: część ma charakter komercyjny, część to dane wrażliwe. MIM3 dotyczy bezpiecznego udostępniania pozostałych zasobów: katalogu z możliwością wyszukiwania, licencji opartych na wzorcach zamiast pisanych na zamówienie tekstów prawnych oraz reguł zarządzania dostępnych dla każdego. Specyfikacja formułuje niemal cały MIM3 w formie zalecenia (zob. str. 3).",
    list:     "Lista",
  )

  #item("Każdy zbiór danych oferowany przez system jest opisany w katalogu za pomocą standardowych metadanych (na przykład DCAT-AP), dzięki czemu inni mogą go łatwo odnaleźć.",
    why:  "Dane, których nikt nie może znaleźć, to dane, z których nikt nie korzysta.",
    refs: "MIM3 RC4.1–RC4.3",
    num:  "3.1")

  #item("Warunki i licencje na korzystanie z danych pochodzą ze znanych wzorców (np. otwarte licencje, standardowe umowy wymiany danych), a nie z indywidualnie tworzonych tekstów prawnych dla każdego zbioru danych.",
    why:  "Porozumienia można skalować bez konieczności każdorazowej analizy prawnej.",
    refs: "MIM3 RC2.2, RC2.3",
    num:  "3.2")

  #item("Miasto może samodzielnie definiować, kto i na jakich warunkach ma dostęp do określonych zasobów danych, oraz zmieniać te reguły bez udziału dostawcy.",
    why:  "Zarządzanie danymi pozostaje wyłączną kompetencją samorządu.",
    refs: "MIM3 RC1.1, RC2.1",
    num:  "3.3")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Lokalne firmy i naukowcy tworzą rozwiązania w oparciu o dane miejskie — wartość dodana zostaje w regionie.",
      "Wrażliwe dane mogą być udostępniane precyzyjnie dobranym partnerom, zamiast stosowania zasady „wszystko albo nic”.",
      "Jeden zbiór reguł zastępuje dziesiątki indywidualnych umów o udostępnianie danych.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "Dostawca rości sobie prawa do danych miasta (zob. klauzula „Prawa do danych”).",
      "Udostępnianie podmiotom trzecim wymaga zgody wykonawcy lub opłat.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM3",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM3",
    capability("C1", "Governance rules for the data sharing ecosystem can be defined",
      tr: "Istnieje możliwość definiowania reguł zarządzania ekosystemem wymiany danych"),
    req("RC1.1",
      tr: "Koordynator ekosystemu danych powinien mieć możliwość zdefiniowania modelu zarządzania (np. zbioru reguł), który określa zasady członkostwa, role, obowiązki i powinności uczestników ekosystemu oraz ogólne zasady regulujące wymianę danych między nimi.",
      en: "The orchestrator of a data ecosystem should be able to define a governance model (e.g. a rulebook) that outlines membership rules, the roles, responsibilities and obligations of ecosystem participants, and the overall principles that govern data exchange between them."),
    req("RC1.2",
      tr: "Uczestnicy biorący udział w ekosystemie danych powinni znać jego model zarządzania oraz wszelkie wprowadzane w nim zmiany.",
      en: "Members who participate in a data ecosystem should be aware of its governance model and any changes made to it."),
    req("RC1.3",
      tr: "Model zarządzania powinien być łatwo zrozumiały dla wszystkich uczestników ekosystemu.",
      en: "The governance model should be easily comprehensible by all ecosystem participants."),
    capability("C2", "Terms and conditions for data sharing can be defined",
      tr: "Istnieje możliwość definiowania warunków wymiany danych"),
    req("RC2.1",
      tr: "Dostawcy danych mają swobodę definiowania warunków, na jakich chcą wymieniać swoje dane. (Uwaga: Przed udostępnieniem zasobów danych dostawcy danych powinni upewnić się, że posiadają odpowiednie uprawnienia od właścicieli danych).",
      en: "Data providers are free to define terms and conditions under which they want their data to be exchanged. (Note: Before sharing data assets, data providers should ensure they have adequate permission from data owners.)"),
    req("RC2.2",
      tr: "Warunki wymiany danych powinny być opisane w sposób jasny i jednoznaczny, tak aby były łatwo zrozumiałe dla użytkowników danych.",
      en: "Terms and conditions for a data exchange should be described clearly and unambiguously so that they are easily understandable for data users."),
    req("RC2.3",
      tr: "Warunki wymiany danych powinny być wyrażone za pomocą licencji na dane lub umów o współdzieleniu danych, opracowanych w oparciu o precyzyjnie zdefiniowane szablony lub standardy.",
      en: "Terms and conditions for a data exchange should be expressed through data licences or data sharing agreements based on well-defined templates or standards."),
    req("RC2.4",
      tr: "Warunki powinny być zgodne z ogólnym modelem zarządzania ekosystemem danych i nie mogą być z nim sprzeczne. (Uwaga: Dostawca danych może zdecydować o rezygnacji z udziału w ekosystemie danych, jeżeli leżący u jego podstaw model zarządzania jest zbyt restrykcyjny lub zbyt liberalny).",
      en: "Terms and conditions should be in line with the overall governance model of the data ecosystem and must not conflict with it. (Note: A data provider can decide not to participate in a data ecosystem if the underlying governance model is too restrictive or too permissive.)"),
    capability("C3", "Compliance with data sharing terms and conditions can be validated",
      tr: "Zgodność z warunkami wymiany danych może podlegać weryfikacji"),
    req("RC3.1",
      tr: "Koordynator ekosystemu danych musi mieć możliwość weryfikacji zgodności działań jego uczestników z obowiązującym modelem zarządzania.",
      en: "The orchestrator of a data ecosystem must be able to ascertain compliance of its participants with the underlying governance model."),
    req("RC3.2",
      tr: "Dostawcy danych powinni mieć możliwość upewnienia się, że wykorzystanie danych przez użytkownika danych jest zgodne z uprzednio uzgodnionymi warunkami.",
      en: "Data providers should be able to ascertain that the use of data by a data user complies with previously agreed-upon terms and conditions."),
    req("RC3.3",
      tr: "Użytkownicy danych powinni mieć możliwość upewnienia się, że dostarczanie danych przez dostawcę danych odbywa się zgodnie z uprzednio uzgodnionymi warunkami.",
      en: "Data users should be able to ascertain that the data provider's supply of data follows previously agreed-upon terms and conditions."),
    capability("C4", "Available data assets can be discovered",
      tr: "Dostępne zasoby danych mogą być wyszukiwane i odkrywane"),
    req("RC4.1",
      tr: "Użytkownicy danych powinni mieć możliwość sprawdzenia, jakie dane są dostępne w ekosystemie wymiany danych, bez konieczności posiadania wcześniejszej wiedzy na ten temat.",
      en: "Data users should be able to discover what data is available in a data sharing ecosystem without prior knowledge of it."),
    req("RC4.2",
      tr: "Zasoby danych powinny być odpowiednio opisane metadanymi, aby użytkownicy danych mogli podejmować wiarygodne decyzje dotyczące ich dalszego, zamierzonego wykorzystania.",
      en: "Data assets should be adequately described with metadata so that data users can make reliable decisions about their further intended use."),
    req("RC4.3",
      tr: "Metadane stosowane do opisu zasobów danych powinny opierać się na precyzyjnie zdefiniowanych, łatwych do zrozumienia formatach opisów, które są czytelne zarówno dla człowieka, jak i maszynowo.",
      en: "Metadata used to describe data assets should be based on well-defined, easy-to-understand description formats that are both human- and machine-readable."),
    capability("C5", "Ecosystem participants can be discovered",
      tr: "Uczestnicy ekosystemu mogą być wyszukiwani i identyfikowani"),
    req("RC5.1",
      tr: "Uczestnicy ekosystemu (np. użytkownicy i dostawcy danych) powinni mieć możliwość wzajemnego wyszukiwania się w ramach ekosystemu wymiany danych.",
      en: "Ecosystem participants (e.g. data users and providers) should be able to discover each other within a data-sharing ecosystem."),
    req("RC5.2",
      tr: "W odniesieniu do każdego uczestnika ekosystemu powinny być dostępne wystarczające metadane, aby możliwe było ustalenie jego wiarygodności istotnej z punktu widzenia wymiany danych.",
      en: "Sufficient metadata about each ecosystem participant should be available to ascertain their trustworthiness relevant for data exchange."),
    req("RC5.3",
      tr: "Dostawcy danych powinni mieć możliwość niezawodnej identyfikacji użytkowników danych pragnących uzyskać dostęp do ich zasobów danych oraz weryfikacji ich metadanych przed udzieleniem dostępu.",
      en: "Data providers should be able to reliably identify data users who want to access their data assets and verify their metadata before granting access."),
    req("RC5.4",
      tr: "Użytkownicy danych powinni mieć możliwość identyfikacji dostawców danych udostępniających dane w ekosystemie danych przed uzyskaniem dostępu do tych danych lub ich wykorzystaniem.",
      en: "Data users should be able to identify data providers who share data in a data ecosystem before accessing or using that data."),
    req("RC5.5",
      tr: "Uczestnicy ekosystemu mogą również zdecydować się na zachowanie anonimowości, o ile pozwala na to model zarządzania ekosystemem wymiany danych. W takim przypadku wymagania od RC5.1 do RC5.4 można pominąć.",
      en: "Ecosystem participants may also choose to remain anonymous if the governance model of the data-sharing ecosystem allows for it. In this case, RC5.1 to RC5.4 can be ignored."),
    capability("C6", "Data exchange can be agreed upon",
      tr: "Wymiana danych może zostać uzgodniona"),
    req("RC6.1",
      tr: "Użytkownicy i dostawcy danych powinni mieć możliwość wyrażenia zgody na wymianę danych oraz na powiązane z nią warunki (np. poprzez akceptację regulaminu, złożenie prawnie wiążącego podpisu pod umową lub w drodze negocjacji).",
      en: "Data users and providers should be able to agree to a data exchange and the terms and conditions associated with it (e.g. acceptance of terms, legal signature of an agreement, or negotiation)."),
    req("RC6.2",
      tr: "Użytkownicy i dostawcy danych powinni mieć możliwość zakończenia uprzednio uzgodnionej wymiany danych zgodnie z warunkami z nią powiązanymi.",
      en: "Data users and providers should be able to terminate a previously agreed-upon data exchange in accordance with the terms and conditions associated with it."),
    req("RC6.3",
      tr: "W miarę możliwości można zapewnić środki elektroniczne służące do zawierania porozumień i kończenia wymiany danych.",
      en: "Where possible, electronic means for the agreement and termination of a data exchange may be provided."),
    capability("C7", "New data currently not available can be requested",
      tr: "Można wnioskować o udostępnienie nowych danych, które są obecnie niedostępne"),
    req("RC7.1",
      tr: "Użytkownicy danych powinni mieć możliwość zgłaszania zapotrzebowania na zasoby danych, które są obecnie niedostępne w ekosystemie wymiany danych.",
      en: "Data users should be able to express their interest in data assets currently unavailable in the data sharing ecosystem."),
    req("RC7.2",
      tr: "Dostawcy danych powinni mieć możliwość odbierania zapytań składanych przez użytkowników danych o nowe zasoby danych.",
      en: "Data providers should be able to obtain requests made by data users for new data assets."),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/exchanging-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 checklist")[
  #mim-page(
    id:       "MIM6",
    name:     "Bezpieczeństwo danych",
    question: "Czy nasze dane są bezpieczne?",
    url:      "https://mims.oascities.org/securing-data",
    intro:    "Inteligentne miasta są celem cyberataków. MIM6 celowo ogranicza zakres do wymogów wąskich i praktycznych: szyfrowanie danych w transmisji, stosowanie standardowych mechanizmów logowania zamiast rozwiązań własnościowych, kontrola i rejestrowanie tego, kto ma dostęp do zasobów. Żadne z tych wymagań nie jest egzotyczne — wszystkie muszą znaleźć się w umowie.",
    list:     "Lista",
  )

  #item("Cała transmisja danych jest szyfrowana (TLS 1.3 lub aktualnie obowiązujące najlepsze praktyki).",
    why:  "Podstawowa higiena; NIS2 również tego wymaga, jeśli ma do Ciebie zastosowanie.",
    refs: "MIM6 R2.1, M1.1",
    num:  "6.1")

  #item("Logowanie użytkowników i dostęp maszynowy wykorzystują otwarte standardy — OAuth 2.0 / OpenID Connect — i umożliwiają integrację z istniejącym miejskim dostawcą tożsamości.",
    why:  "Jedno konto dla pracownika zamiast osobnego konta w systemie każdego dostawcy; odchodzący pracownik traci dostęp do wszystkich usług jednocześnie.",
    refs: "MIM6 R3.1, M1.2, M1.3",
    num:  "6.2")

  #item("Prawa dostępu są oparte na rolach, weryfikowalne i odwołalne; dostęp i działania administracyjne są rejestrowane.",
    why:  "Audyty i reagowanie na incydenty stają się w ogóle możliwe. Rejestrowanie logów to norma ISO/IEC 27001:2022, Załącznik A, środek 8.15, który MIM6 wymienia wśród swoich wymagań wstępnych.",
    refs: "MIM6 R1.1, R1.3, 8.15",
    num:  "6.3")

  #item("Wykonawca wykazuje zgodność z normą ISO/IEC 27001:2022 (lub równoważną) w odniesieniu do świadczonej przez siebie usługi.",
    why:  "Bezpieczeństwo to proces ciągły, a nie jednorazowe odznaczenie wymogu przy odbiorze. Specyfikacja powołuje się na środki bezpieczeństwa ISO/IEC 27001, a nie na sam certyfikat.",
    refs: "MIM6 C1–C3 (ISO/IEC 27001)",
    num:  "6.4",
    label: "Miejsce tego zapisu jest w warunkach udziału w postępowaniu, a nie w opisie przedmiotu zamówienia")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Przełamanie zabezpieczeń w jednym systemie nie otwiera dostępu do pozostałych.",
      "Tam, gdzie ma zastosowanie dyrektywa NIS2, spełnienie jej wymogów oraz krajowych przepisów o cyberbezpieczeństwie staje się wymiernie prostsze.",
      "Po incydencie dzienniki zdarzeń pokazują, co się stało i kto podjął działania.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "Wyłącznie własnościowe logowanie.",
      "„Dzienniki zdarzeń udostępniane na żądanie”.",
      "Współdzielone konta administratora.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM6",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM6",
    capability("C1", "Data is only accessible to users that should have access to it",
      tr: "Dane są dostępne wyłącznie dla użytkowników, którzy powinni posiadać do nich dostęp"),
    req("R1.1",
      tr: "Zasady kontroli dostępu fizycznego i logicznego do informacji oraz powiązanych z nimi innych aktywów MAJĄ OBOWIĄZEK zostać ustalone i wdrożone w oparciu o wymagania biznesowe i bezpieczeństwa informacji. (ISO 27001 5.15 Kontrola dostępu)",
      en: "Rules to control physical and logical access to information and other associated assets SHALL be established and implemented based on business and information security requirements. (ISO 27001 5.15 Access control)"),
    req("R1.2",
      tr: "Przydzielanie informacji uwierzytelniających i zarządzanie nimi MA OBOWIĄZEK podlegać procedurze zarządczej, w tym instruowaniu personelu w zakresie właściwego obchodzenia się z informacjami uwierzytelniającymi. (ISO 27001 5.17 Informacje uwierzytelniające)",
      en: "Allocation and management of authentication information SHALL be controlled by a management process, including advising personnel on appropriate handling of authentication information. (ISO 27001 5.17: Authentication information)"),
    req("R1.3",
      tr: "Prawa dostępu do informacji oraz powiązanych z nimi innych aktywów MAJĄ OBOWIĄZEK być przydzielane, weryfikowane, modyfikowane i odbierane zgodnie z polityką i zasadami kontroli dostępu właściwymi dla danej organizacji. (ISO 27001 5.18 Prawa dostępu)",
      en: "Access rights to information and other associated assets SHALL be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control. (ISO 27001 5.18: Access rights)"),
    capability("C2", "Data accessed by users has not been altered",
      tr: "Dane, do których uzyskują dostęp użytkownicy, nie zostały zmienione"),
    req("R2.1",
      tr: "Zasady efektywnego wykorzystania kryptografii, w tym zarządzania kluczami kryptograficznymi, MAJĄ OBOWIĄZEK zostać zdefiniowane i wdrożone. (ISO 27001 8.24 Wykorzystanie kryptografii)",
      en: "Rules for the effective use of cryptography, including cryptographic key management, SHALL be defined and implemented. (ISO 27001 8.24 Use of cryptography)"),
    capability("C3", "Data accessed by users originates from a verified source",
      tr: "Dane, do których dostęp uzyskują użytkownicy, pochodzą ze zweryfikowanego źródła"),
    req("R3.1",
      tr: "Bezpieczne technologie i procedury uwierzytelniania muszą zostać wdrożone w oparciu o ograniczenia dostępu do informacji oraz szczegółową politykę kontroli dostępu. (ISO 27001 8.5 Bezpieczne uwierzytelnianie)",
      en: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control. (ISO 27001 8.5 Secure authentication)"),
    capability("M1", "Mechanism candidate",
      tr: "Kandydat na mechanizm"),
    req("M1.1",
      tr: "Protokół Transport Layer Security (TLS), wersja 1.3",
      en: "The Transport Layer Security (TLS) Protocol, Version 1.3"),
    req("M1.2",
      tr: "Struktura autoryzacji OAuth 2.0 (The OAuth 2.0 Authorization Framework)",
      en: "The OAuth 2.0 Authorization Framework"),
    req("M1.3",
      tr: "OpenID Connect 1.0, warstwa tożsamości do uwierzytelniania w oparciu o protokół OAuth 2.0",
      en: "OpenID Connect 1.0, Identity layer for authentication on OAuth 2.0"),
    req("M1.4",
      tr: "OIDC4VCI / OIDC4VP, specyfikacja OpenID służąca do wydawania i prezentacji weryfikowalnych poświadczeń",
      en: "OIDC4VCI / OIDC4VP, OpenID for Verifiable Credential Issuance and Presentations"),
    capability("P", "Pre- and Post-requisites (based on ISO 27001 Annex A): the control this booklet refers to",
      tr: "Wymagania wstępne i następcze (w oparciu o Załącznik A do ISO 27001): środek bezpieczeństwa, do którego odwołuje się niniejszy poradnik"),
    req("8.15",
      tr: "Rejestrowanie zdarzeń. Dzienniki rejestrujące aktywność, wyjątki, usterki i inne istotne zdarzenia muszą być generowane, przechowywane, chronione i poddawane analizie.",
      en: "Logging. Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed."),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/securing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 checklist")[
  #mim-page(
    id:       "MIM7",
    name:     "Dane geoprzestrzenne",
    question: "Czy to działa na mapie?",
    url:      "https://mims.oascities.org/geospatial-data",
    intro:    "Niemal wszystko, czym zarządza miasto, ma swoje położenie w przestrzeni. MIM7 gwarantuje, że to położenie nie sprowadza się do zrzutu ekranu: dane przestrzenne są przekazywane przez standardowe interfejsy OGC, w otwartych formatach, zawsze ze zdefiniowanym układem współrzędnych — tak aby każda nowa warstwa mapy pasowała do warstw, którymi już dysponujesz.",
    list:     "Lista",
  )

  #item("Dane geoprzestrzenne są udostępniane przez interfejsy oparte na standardach (OGC API Features, SensorThings; w przypadku systemów starszego typu dopuszcza się WFS).",
    why:  "Każde narzędzie GIS na rynku może je odczytać od ręki.",
    refs: "MIM7 R1.1",
    num:  "7.1")

  #item("Dane geoprzestrzenne są kodowane w otwartych formatach (GeoJSON, CityJSON; w uzasadnionych przypadkach GML/CityGML).",
    why:  "Bez licencji na konwertery, bez ślepych zaułków.",
    refs: "MIM7 R2.1",
    num:  "7.2")

  #item("Układ odniesienia współrzędnych jest zawsze jawnie określony (kod EPSG), a dane można przekształcić do wspólnego układu CRS.",
    why:  "Warstwy pochodzące z różnych źródeł idealnie pokrywają się na mapie.",
    refs: "MIM7 R5.1",
    num:  "7.3")

  #item("Obiekty przestrzenne posiadają te same trwałe identyfikatory, o których mowa w MIM1.",
    why:  "Punkt widoczny na mapie i rekord w ewidencji majątku to dokładnie ten sam obiekt.",
    refs: "MIM7 R4.1",
    num:  "7.4")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Jedna mapa miejska zamiast dziesięciu przeglądarek dostawców.",
      "Zobowiązania wobec INSPIRE i krajowego geoportalu stają się łatwiejsze, a nie trudniejsze.",
      "Dane 3D i BIM można później włączyć do tego samego obrazu.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "Dane mapowe można przeglądać wyłącznie w aplikacji dostawcy.",
      "„Eksport do formatu PDF / zrzut ekranu”.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM7",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM7",
    capability("C1", "Cities and communities can easily transfer geospatial data between internal and external (including IoT-related) IT systems",
      tr: "Miasta i społeczności mogą z łatwością przesyłać dane geoprzestrzenne pomiędzy wewnętrznymi i zewnętrznymi systemami IT (w tym systemami IoT)"),
    req("R1.1",
      tr: "Dane geoprzestrzenne muszą być udostępniane za pośrednictwem interfejsu usługi sieciowej opartego na standardach.",
      en: "Geospatial data shall be exposed through a standards-based web service interface."),
    capability("C2", "Cities and communities can integrate 2D and 3D geospatial data coming from a variety of sources, for example geodata and building information models, and share that data within and between them in an interoperable way",
      tr: "Miasta i społeczności mogą integrować dwuwymiarowe (2D) i trójwymiarowe (3D) dane geoprzestrzenne pochodzące z różnych źródeł, np. geodane i modele informacji o budynku (BIM), oraz wymieniać je w sposób interoperacyjny w ramach własnych struktur i między sobą"),
    req("R2.1",
      tr: "Dane geoprzestrzenne muszą być kodowane przy użyciu otwartych standardów. Zaleca się stosowanie odpowiednich standardów organizacji OGC oraz BuildingSMART International.",
      en: "Geospatial data shall be encoded using open standards. It is recommended to use relevant standards from OGC and BuildingSMART International."),
    capability("C3", "Cities and communities can integrate geospatial data with other data that can provide further information about the context",
      tr: "Miasta i społeczności mogą integrować dane geoprzestrzenne z innymi danymi, które dostarczają dodatkowych informacji o kontekście"),
    req("R3.1",
      tr: "Wszystkie zbiory danych wykorzystywane do dostarczania dodatkowych informacji o kontekście opisywanym przez dane geoprzestrzenne muszą być zgodne z wymaganiami MIM1 oraz MIM2.",
      en: "All data sets used to provide further information about the context covered by geospatial data shall comply with MIM1 and MIM2."),
    capability("C4", "Cities and communities have a consistent and persistent way of describing individual instances of all features, things or entities included in the geospatial data sources",
      tr: "Miasta i społeczności dysponują spójnym i trwałym sposobem opisywania poszczególnych instancji wszystkich obiektów, zjawisk i bytów występujących w geoprzestrzennych źródłach danych"),
    req("R4.1",
      tr: "Do identyfikacji poszczególnych instancji dowolnego obiektu występującego w zbiorach danych muszą być stosowane unikalne i trwałe identyfikatory. (Zob. MIM1: Łączenie danych).",
      en: "Unique and persistent identifiers shall be used to identify particular instances of any entity used in data sets. (See MIM1: Interlinking Data.)"),
    capability("C5", "Coordinate Reference Systems (CRS) used in data sharing are easily transformable into a common CRS",
      tr: "Układy odniesienia współrzędnych (CRS) stosowane w ramach wymiany danych dają się łatwo transformować do wspólnego układu CRS"),
    req("R5.1",
      tr: "Układy odniesienia współrzędnych (CRS) muszą być zgodne ze standardami, a informacja o tym, jaki standard (np. EPSG:4326, EPSG:3857) jest stosowany, musi zostać podana. Obejmuje to numer EPSG lub oznaczenie WGS, wraz z informacją o wszelkich wariantach opartych na układach krajowych, takich jak łotewski LKS-92, tak aby dane mogły zostać przekształcone do wspólnego układu CRS. (Uwaga: Na terytorium UE w odniesieniu do danych geoprzestrzennych wymaga się stosowania metadanych zgodnych z dyrektywą INSPIRE, w tym metadanych niezbędnych do opisania informacji o układzie CRS).",
      en: "Coordinate Reference Systems (CRS) shall comply with standards, and information shall be provided regarding which standard (e.g. EPSG:4326, EPSG:3857) is being used. This includes the EPSG number or WGS number, along with information about any variation based on national systems such as the Latvian LKS-92, so that data can be transformed to a common CRS. (Note: Within the EU, for geospatial data it is required to use metadata compliant with the INSPIRE Directive, including the metadata needed to describe the CRS information.)"),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/geospatial-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 checklist")[
  #mim-page(
    id:       "MIM8",
    name:     "Lokalne cyfrowe bliźniaki",
    question: "Czy nasz cyfrowy bliźniak może się rozwijać?",
    url:      "https://mims.oascities.org/local-digital-twins",
    intro:    "Cyfrowy bliźniak to inwestycja długoterminowa: dane, modele 3D, symulacje, decyzje zarządcze. MIM8 chroni tę inwestycję — dane i modele bliźniaka pozostają dostępne i udokumentowane, wyniki można odtworzyć, a komponenty opracowane w jednym projekcie mogą posłużyć w kolejnym. Stosuj tę stronę przy zamawianiu platform cyfrowych bliźniaków, modeli symulacyjnych lub miejskich narzędzi 3D.",
    list:     "Lista",
  )

  #item("Zbiory danych, parametry wejściowe modeli oraz wyniki symulacji są dostępne przez API (zgodnie z MIM0), a nie zablokowane wewnątrz platformy cyfrowego bliźniaka.",
    why:  "Wyniki zasilają raporty, panele menedżerskie i kolejne przedsięwzięcia.",
    refs: "MIM8 R1.1",
    num:  "8.1")

  #item("Modele są udokumentowane (metodologia, parametry, wejścia/wyjścia) i mogą być wywoływane przez udokumentowany interfejs.",
    why:  "Model powodziowy kupiony raz może być ponownie wykorzystany przez inne wydziały — oraz przez inne miasta.",
    refs: "MIM8 R3.1, R3.2",
    num:  "8.2")

  #item("Dane wyjściowe wykorzystują standardowe formaty (GeoJSON, CityJSON, 3D Tiles, NetCDF…) czytelne dla narzędzi podmiotów trzecich.",
    why:  "Rynek narzędzi do wizualizacji i zaawansowanej analityki pozostaje konkurencyjny.",
    refs: "MIM8 M2",
    num:  "8.3")

  #item("Przebiegi procesów rejestrują pochodzenie danych (provenance): która wersja danych, jaki model i jakie parametry wygenerowały dany wynik.",
    why:  "Decyzje podejmowane w oparciu o cyfrowego bliźniaka można w przyszłości rzetelnie wyjaśnić i obronić.",
    refs: "MIM8 R4.4",
    num:  "8.4")

  #panels(
    why:   ("Dlaczego to ma znaczenie", (
      "Bliźniak przetrwa każdego pojedynczego dostawcę lub budżet projektu.",
      "Symulacje można zweryfikować, powtórzyć i wykorzystać jako twardy dowód w miejskim procesie decyzyjnym.",
      "Modele i gotowe komponenty mogą być wymieniane pomiędzy różnymi miastami.",
    )),
    flags: ("Sygnały ostrzegawcze", (
      "Wyniki symulacji można przeglądać wyłącznie w portalu dostawcy.",
      "Modele jako zamknięte czarne skrzynki bez metadanych.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM8",
    title:  "Co mówi specyfikacja",
    leadin: "Każdy wymóg tego MIM, dosłownie z MIMs Plus 9.0: Specyfikacja istnieje wyłącznie w języku angielskim: treść w języku polskim jest nieoficjalnym tłumaczeniem sporządzonym przez autora niniejszego poradnika; wiążący jest znajdujący się pod nią angielski oryginał.",
    back:   "powrót do listy",
  )

  #spec-list(mim: "MIM8",
    capability("C1", "Provide access to datasets used within the LDT, including static, real-time, and simulation data and calculation models",
      tr: "Zapewnienie dostępu do zbiorów danych wykorzystywanych w ramach cyfrowego bliźniaka (LDT), w tym danych statycznych, czasu rzeczywistego, symulacyjnych oraz modeli obliczeniowych"),
    req("R1.1",
      tr: "Cyfrowy bliźniak (LDT) musi zapewniać dostęp do wyników symulacji oraz danych wejściowych modeli obliczeniowych w przypadkach, gdy są one wymagane w ramach procesów roboczych LDT.",
      en: "The LDT shall provide access to simulation outputs and calculation-model inputs where these are needed as part of LDT workflows."),
    req("R1.2",
      tr: "Cyfrowy bliźniak (LDT) powinien wyraźnie rozróżniać surowe dane źródłowe, przekształcone dane przygotowane do procesów przetwarzania, dane wejściowe modeli oraz dane wynikowe generowane przez modele.",
      en: "The LDT should distinguish clearly between raw source data, transformed workflow-ready data, model inputs, and model outputs."),
    capability("C2", "Exchange data with external systems and other LDTs using interoperable interfaces",
      tr: "Wymiana danych z systemami zewnętrznymi oraz innymi cyfrowymi bliźniakami (LDT) przy użyciu interoperacyjnych interfejsów"),
    req("C2",
      tr: "Ta zdolność opiera się na MIM3 (Wymiana danych) w zakresie wymiany danych.",
      en: "This capability relies on MIM3 (Exchanging Data) for data exchange."),
    capability("C3", "Reuse deterministic or AI models across different domains, communities, use cases, and/or LDTs",
      tr: "Ponowne wykorzystanie modeli deterministycznych lub modeli AI w różnych dziedzinach, społecznościach, przypadkach użycia i/lub LDT"),
    req("R3.1",
      tr: "Model powinien udostępniać standardowe metadane modelu, w tym opis jego metod i parametrów oraz parametrów danych (przekazywanych przez wartość lub przez referencję). W tym celu należy stosować powszechne standardy metadanych.",
      en: "The model should provide standard model metadata, including a description of its methods and parameters, and data-parameters (either by value or by reference). To this end common metadata standards should be used."),
    req("R3.2",
      tr: "Model musi udostępniać interfejs lub umożliwiać wywołanie za pośrednictwem udokumentowanego interfejsu, najlepiej z wykorzystaniem powszechnie znanego, standaryzowanego API. Zbiór danych stanowiący wynik działania modelu musi zostać opisany (na poziomie danych).",
      en: "The model shall expose or be callable through a documented interface, preferably using a known standardised API. The dataset that forms the outcome of the model shall be described (at data-level)."),
    req("R3.3",
      tr: "Należy zabezpieczyć godne zaufania, niezawodne i etyczne wykorzystanie innowacyjnych metod (LLM, agentowa AI itp.). Stronniczość powinna być minimalizowana tam, gdzie ma to zastosowanie. Metody stosowane w celu zagwarantowania tego powinny być opisane.",
      en: "Trustworthy, reliable, and ethical use of innovative methods (LLMs, agentic AI, etc.) should be safeguarded. Bias should minimised [sic] where applicable. The methods used to guarantee this, should be described."),
    req("R3.4",
      tr: "Model musi być w stanie uzyskać dostęp do danych w imieniu użytkownika końcowego lub organizacji. Zob. MIM3",
      en: "The model must be able to access data on behalf of the end-user or organisation. See MIM3"),
    req("R3.5",
      tr: "W przypadku danych przeznaczonych do wykorzystania w modelach AI należy zagwarantować ich pochodzenie oraz wiarygodność. W niektórych przypadkach musi zostać wskazane wiarygodne źródło, takie jak instytucja publiczna.",
      en: "For data to be used in AI models, provenance and trust should be guaranteed. In some cases, an authoratitive sourc [sic], such as a government agency must be listed."),
    capability("C4", "Coordinate and manage data, models, and processing workflows within an LDT (intra-LDT) and across LDTs (inter-LDT)",
      tr: "Koordynowanie i zarządzanie danymi, modelami i procesami przetwarzania w ramach jednego cyfrowego bliźniaka (intra-LDT) oraz pomiędzy różnymi cyfrowymi bliźniakami (inter-LDT)"),
    req("R4.1",
      tr: "Cyfrowy bliźniak (LDT) obsługuje przepływy pracy (workflows) łączące źródła danych, przekształcenia danych, wykonywanie modeli, procesy symulacji oraz dane wynikowe.",
      en: "The LDT supports workflows that connect data sources, data transformations, model execution, simulation processes, and outputs."),
    req("R4.2",
      tr: "Cyfrowy bliźniak (LDT) łączy kroki przepływu pracy w łańcuchy, w których wynik jednego kroku może zostać wykorzystany jako dane wejściowe dla innego.",
      en: "The LDT chains workflow steps, where the output of one step can be used as the input for another."),
    req("R4.3",
      tr: "Cyfrowy bliźniak (LDT) monitoruje status wykonywania przepływów pracy, w tym procesy zakończone, nieudane oraz przerwane.",
      en: "The LDT monitors workflow execution status, including completed, failed, and interrupted processes."),
    req("R4.4",
      tr: "Cyfrowy bliźniak (LDT) rejestruje pochodzenie danych (provenance) w procesach roboczych, w tym wykorzystane zbiory danych (wraz z oznaczeniem wersji i znacznikiem czasu), uruchomione modele, wybrane parametry oraz wygenerowane wyniki.",
      en: "The LDT records workflow provenance, including datasets used (including version, timestamped), models executed, parameters selected, and outputs generated."),
    capability("C5", "Provide multiple visualisations of data and results (e.g. 2D, 3D, dashboards) from common underlying data and models for interaction and comparison",
      tr: "Udostępnianie wielu form wizualizacji danych i wyników (np. mapy 2D, sceny 3D, pulpity menedżerskie) bazujących na wspólnych danych i modelach w celu umożliwienia interakcji i porównań"),
    req("R5.1",
      tr: "Cyfrowy bliźniak (LDT) dostarcza metadane objaśniające prezentowaną wizualizację, w tym znacznik czasu, zakres przestrzenny, źródło danych oraz, w stosownych przypadkach, założenia dotyczące scenariuszy i wariantów.",
      en: "The LDT provides metadata explaining what is visualised, including timestamp, spatial scope, data source, and scenario- and variant-assumptions where relevant."),
    req("R5.2",
      tr: "Cyfrowy bliźniak (LDT) obsługuje różne rodzaje interaktywnych wizualizacji, takie jak mapy 2D, sceny 3D, pulpity nawigacyjne (dashboards), raporty lub widoki udostępniane publicznie.",
      en: "The LDT supports different interactive visualisation types, such as 2D maps, 3D scenes, dashboards, reports, or public-facing views."),
    capability("C6", "Ensure that data exchanged (and simulation outputs) within and between LDTs can be interpreted consistently through shared or mapped semantics and clear provenance",
      tr: "Zapewnienie, że dane wymieniane w ramach cyfrowych bliźniaków (LDT) i między nimi (w tym dane wynikowe z symulacji) mogą być interpretowane w sposób spójny dzięki wspólnym lub powiązanym regułom semantycznym i jasnej informacji o pochodzeniu danych"),
    req("R6.1",
      tr: "Cyfrowy bliźniak (LDT) powinien dokumentować nierozwiązane rozbieżności semantyczne, przyjęte założenia lub mapowania, które mogą wpływać na interpretację, ponowne wykorzystanie lub porównywanie wyników.",
      en: "The LDT should document unresolved semantic gaps, assumptions, or mappings that may affect the interpretation, reuse, or comparison of results."),
    capability("M", "Mechanisms (under active development)",
      tr: "Mechanizmy (w fazie aktywnego rozwoju)"),
    req("M1",
      tr: "Dostęp do zasobów LDT oparty na API",
      en: "API-based LDT Resource Access"),
    req("M2",
      tr: "Standaryzowane formaty danych i wyników",
      en: "Standardised Data and Output Formats"),
    req("M3",
      tr: "Model jako usługa (Model-as-a-Service)",
      en: "Model-as-a-Service"),
    req("M4",
      tr: "Orkiestracja przepływów pracy LDT",
      en: "LDT Workflow Orchestration"),
    req("M5",
      tr: "Wielowidokowy dostęp do wyników i wizualizacji",
      en: "Multi-view Output and Visualisation Access"),
  )

  #spec-link("Pełna treść specyfikacji:", "https://mims.oascities.org/local-digital-twins")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  CROSS-CUTTING CONTRACT CLAUSES
// ════════════════════════════════════════════════════════════════════════════
#fit-page("clauses")[
  #band("Horyzontalne klauzule umowne", sub: "Zabezpieczenia przed uzależnieniem", id: "clauses")

  #intro(size: 9.8pt, "Te klauzule powinny znaleźć się w każdym zamówieniu, niezależnie od przedmiotu zakupu. Wywodzą się z praktyki zamówień publicznych wokół standardów MIMs i inicjatywy living-in.eu. Większość z nich nie wynika z jednego konkretnego wymogu specyfikacji, dlatego nie przypisano im kodów referencyjnych (wersjonowanie API stanowi również zalecenie MIM0 C2). Ich wprowadzenie wiąże się z minimalnym kosztem; ich pominięcie może kosztować wszystko.")

  #clauses(
    clause("Klauzula wyjścia",
      "Z chwilą zakończenia umowy wszystkie dane miasta (wraz z konfiguracją) zostaną przekazane w otwartych, udokumentowanych formatach bez dodatkowych opłat."),
    clause("Prawa do danych",
      "Wszelkie prawa do danych zebranych i wytworzonych w trakcie realizacji umowy przysługują wyłącznie zamawiającemu."),
    clause("Brak opłat za własne dane",
      "Zamawiający nie ponosi żadnych opłat za dostęp do własnych danych, ani w podziale na użytkowników, ani za pojedyncze zapytania."),
    clause("Stabilność i wersjonowanie API",
      "Wykonawca gwarantuje wsteczną kompatybilność interfejsu API przez cały okres obowiązywania umowy. Zmiany naruszające kompatybilność będą ogłaszane z co najmniej 6-miesięcznym wyprzedzeniem i publikowane jako nowa wersja, podczas gdy wersja dotychczasowa pozostanie dostępna do uzgodnionego dnia migracji."),
    clause("Dowody zamiast obietnic",
      "Wykonawcy wykazują spełnianie wymagań na etapie oceny ofert, zamiast składać wyłącznie oświadczenia własne. W przypadku API oznacza to przedstawienie opublikowanej interaktywnej dokumentacji (np. OpenAPI) oraz wykonanie działającego wywołania zwracającego prawidłowe dane. Każdy zaznaczony punkt jest ponownie weryfikowany podczas odbioru."),
    clause("Wskazanie otwartych standardów",
      "Dokumentacja zamówienia wymienia konkretne standardy; oświadczenia o „zgodności z” muszą precyzować dokładny interfejs i jego wersję. Każde odesłanie do normy lub specyfikacji technicznej dopuszcza rozwiązanie równoważne; ciężar udowodnienia równoważności spoczywa na wykonawcy."),
    clause("Oświadczenie o zgodności z MIMs",
      "Wykonawca wypełnia tabelę zgodności (str. 28); stanowi ona integralny załącznik do umowy."),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT
// ════════════════════════════════════════════════════════════════════════════
#fit-page("example")[
  #band("Przykład: miasto kupuje sieć czujników jakości powietrza", id: "example")

  #intro(size: 9.8pt, "Zaznaczone strony: MIM0, MIM1, MIM2, MIM6 oraz MIM7 (dane będą prezentowane na mapie). Z MIM3 wyłącznie punkt 3.1 (dane o jakości powietrza są publikowane jako otwarte dane, powinny więc trafić do katalogu); MIM8 nie ma zastosowania: system nie jest cyfrowym bliźniakiem.")

  #text(size: 10pt, weight: "bold", fill: eu-blue, "Gdzie co wpisać")
  #v(4pt)

  #doc-table(
    ("Dokument", "Pojęcie w dyrektywie 2014/24/UE", "Co należy w nim zawrzeć"),
    (
      ("Opis przedmiotu zamówienia (OPZ)",
       "specyfikacje techniczne (art. 42)",
       "zaznaczone punkty z MIM0, MIM1, MIM2, MIM3 (tylko 3.1), MIM6 (z wyjątkiem 6.4) i MIM7, w dosłownym brzmieniu, z kodami specyfikacji, uzupełnione o klauzulę o równoważności"),
      ("Warunki udziału w postępowaniu",
       "kryteria kwalifikacji (art. 58 i 62)",
       "wykazanie zgodności z normą ISO/IEC 27001:2022 lub równoważną (punkt 6.4)"),
      ("Przedmiotowe środki dowodowe",
       "sprawozdania z badań, certyfikacja i inne środki dowodowe (art. 44)",
       "tabela zgodności jako obowiązkowy załącznik do oferty: litery S, R lub N przy każdej pozycji wraz z dowodami (adres dokumentacji API, dostęp testowy)"),
      ("Projektowane postanowienia umowy",
       "warunki realizacji zamówienia (art. 70)",
       "Klauzula wyjścia, Prawa do danych, Brak opłat za własne dane, Stabilność i wersjonowanie API; wypełniona tabela zgodności jako załącznik"),
      ("Protokół odbioru",
       "warunki realizacji zamówienia (art. 70)",
       "kolumna „Zweryfikowano” w tabeli zgodności jako protokół testów odbiorczych"),
    ),
  )

  #sample-text("Przykładowe zapisy do opisu przedmiotu zamówienia", (
    "4.3 Interoperacyjność i dostęp do danych",
    "4.3.1 Wszystkie dane zbierane lub generowane przez system można pobrać w co najmniej jednym formacie odczytywalnym maszynowo (np. JSON, CSV) za pośrednictwem standardowego interfejsu API. (MIMs Plus 9.0, MIM0 R1.1, R1.2)",
    "4.3.2 API jest formalnie opisane w otwartym, odczytywalnym maszynowo dokumencie (na przykład OpenAPI), opublikowanym pod stabilnym adresem. (MIM0 R1.3)",
    "4.3.3 API umożliwia filtrowanie danych według czasu i miejsca wykonania pomiaru. (MIM0 R2.1, R2.2)",
    "… 4.3.4 do 4.3.21: pozostałe zaznaczone punkty …",
    "4.3.22 Każde odesłanie do normy lub specyfikacji technicznej dopuszcza rozwiązanie równoważne; ciężar udowodnienia równoważności spoczywa na wykonawcy.",
    "4.3.23 Wykonawca wypełnia tabelę zgodności (załącznik do dokumentów zamówienia) i przedstawia dowody dla każdego wymaganego punktu. W toku badania i oceny ofert wykonawca demonstruje punkty od 4.3.1 do 4.3.21 (na przykład poprzez wywołanie API na żywo); oferta, która nie spełnia wymaganego punktu, jest niezgodna z warunkami zamówienia. Zamawiający weryfikuje te punkty ponownie na etapie odbioru; negatywny wynik weryfikacji stanowi podstawę do odmowy odbioru.",
  ))

  #note(size: 9pt, "Punkt 4.3.3 pokazuje, jak można doprecyzować dany wymóg pod kątem przedmiotu zamówienia: w przypadku czujników w pełni uzasadnione jest żądanie filtrowania według czasu i miejsca pomiaru.")

  #v(4pt)
  #text(size: 10pt, weight: "bold", fill: eu-blue, "Wypełniona tabela zgodności (wyciąg)")
  #v(4pt)

  #filled-table(
    ("Lp.", "Wymóg (skrót)", "S / R / N", "Środki dowodowe: jak i gdzie", "Zweryfikowano"),
    (
      ("0.1", "Dane odczytywalne maszynowo przez standardowe API", "S", "REST API zwraca JSON oraz CSV; dokumentacja pod adresem podanym w ofercie, str. 12; dane dostępowe do środowiska testowego w załączniku 3", "✓"),
      ("0.4", "Subskrypcja powiadomień o zmianach w razie potrzeby", "N", "jeszcze nieobsługiwane; planowane w następnej wersji", "—"),
      ("7.2", "Otwarte formaty danych przestrzennych", "R", "system dostarcza dane w formacie GeoPackage (otwarty standard OGC) zamiast GeoJSON; wykazanie równoważności opisano w ofercie, str. 15", "✓"),
    ),
  )

  #note(size: 9pt, gap: 5pt, "Zobowiązanie do wprowadzenia funkcjonalności w przyszłości traktuje się jako N: komisja weryfikuje wyłącznie to, co wykonawca jest w stanie wykazać. W przypadku wymaganego punktu ocena N oznacza, że oferta nie spełnia warunków zamówienia.")

  #note(size: 9pt, gap: 5pt, "Dostosuj powyższe sformułowania do przepisów prawa krajowego i skonsultuj je z osobą odpowiedzialną za prowadzenie postępowania przetargowego.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)
// ════════════════════════════════════════════════════════════════════════════
#band("Tabela zgodności", id: "table")

#intro(size: 9.4pt, gap: 5pt, "Jeden wiersz na każdy punkt. Zamawiający zaznacza wymagania obowiązujące w danym zamówieniu i dołącza tabelę do dokumentów zamówienia jako obowiązkowy załącznik do oferty. Dla każdego wymaganego punktu wykonawca wpisuje S (spełnia), R (spełnia w sposób równoważny) lub N (nie spełnia), opisuje zwięźle sposób realizacji oraz wskazuje dowód: adres dokumentacji, dostęp testowy, numer strony w ofercie. Samo oświadczenie bez poparcia dowodami jest niewystarczające. Komisja przetargowa weryfikuje każdy punkt podczas oceny ofert oraz ponownie na etapie odbioru (✓ potwierdzone, ✗ niepotwierdzone, — niesprawdzone).")

#intro(size: 9.4pt, gap: 8pt, "Wypełniona tabela stanowi element oferty i staje się załącznikiem do umowy w sprawie zamówienia. Służy weryfikacji, czy oferowany przedmiot zamówienia spełnia wymagania zamawiającego (spełnia / nie spełnia); nie stanowi ona kryterium oceny ofert. Jeżeli zamawiający zamierza punktować stopień spełnienia wymagań, musi to wyraźnie określić w ramach kryteriów oceny ofert opublikowanych uprzednio w dokumentach zamówienia (dyrektywa 2014/24/UE, art. 67).")

#score-sheet(
  headers: ("Lp.", "Wymóg (skrót)", "Odn. do spec.", "Wymagane?", "S / R / N", "Środki dowodowe: jak i gdzie", "Zweryfikowano"),
  roles: ("zamawiający", "wykonawca", "wykonawca", "komisja"),
  section("MIM0 · Czy możemy wydobyć nasze dane?",
    ("0.1", "Dane w formacie maszynowym przez standardowe API", "MIM0 R1.1, R1.2"),
    ("0.2", "Otwarty opis API (OpenAPI) pod stałym adresem", "MIM0 R1.3"),
    ("0.3", "Filtrowanie według czasu, lokalizacji i atrybutów", "MIM0 R2.1, R2.2"),
    ("0.4", "Subskrypcja zmian danych w razie potrzeby", "MIM0 R3.1"),
    ("0.5", "Standardowe błędy HTTP, cache i limity zapytań", "MIM0 C2"),
  ),
  section("MIM1 · Czy każdy obiekt ma trwałą nazwę?",
    ("1.1", "Trwały, unikalny identyfikator każdego obiektu", "MIM1 R1.1, R1.5"),
    ("1.2", "Odpytanie identyfikatora zwraca dane i typ", "MIM1 R1.2, R2.1, R2.2"),
    ("1.3", "Mapowanie identyfikatorów między systemami", "MIM1 R1.3, R1.4"),
    ("1.4", "Brak struktur dostawcy w identyfikatorach", "MIM1 M1 §3.1"),
  ),
  section("MIM2 · Czy mówimy wspólnym językiem?",
    ("2.1", "Standardowe modele danych, gdy to możliwe", "MIM2 R1.2a"),
    ("2.2", "Udokumentowane modele i jawne jednostki miar", "MIM2 R1.1"),
    ("2.3", "Rozszerzenia jako profile, nigdy jako forki", "MIM2 R1.2b, R4.1, R4.2"),
    ("2.4", "Otwarta serializacja walidowana schematem", "MIM2 R3.1, R3.4"),
  ),
  section("MIM3 · Czy możemy udostępniać na jasnych warunkach?",
    ("3.1", "Katalogowanie danych z metadanymi standardowymi", "MIM3 RC4.1–RC4.3"),
    ("3.2", "Wzorcowe licencje i umowy wymiany danych", "MIM3 RC2.2, RC2.3"),
    ("3.3", "Samodzielne zarządzanie warunkami dostępu", "MIM3 RC1.1, RC2.1"),
  ),
  section("MIM6 · Czy nasze dane są bezpieczne?",
    ("6.1", "Szyfrowanie transmisji danych (TLS 1.3)", "MIM6 R2.1, M1.1"),
    ("6.2", "Standardowe logowanie (OAuth 2.0 / OIDC)", "MIM6 R3.1, M1.2, M1.3"),
    ("6.3", "Dostęp oparty na rolach i logi audytowe", "MIM6 R1.1, R1.3, 8.15"),
    ("6.4", "Wykazana zgodność z normą ISO/IEC 27001:2022", "MIM6 C1–C3 (ISO/IEC 27001)"),
  ),
  section("MIM7 · Czy to działa na mapie?",
    ("7.1", "Standardowe interfejsy OGC", "MIM7 R1.1"),
    ("7.2", "Otwarte formaty danych geoprzestrzennych", "MIM7 R2.1"),
    ("7.3", "Jawnie zadeklarowany układ CRS (kody EPSG)", "MIM7 R5.1"),
    ("7.4", "Trwałe identyfikatory obiektów (zob. 1.1)", "MIM7 R4.1"),
  ),
  section("MIM8 · Czy nasz cyfrowy bliźniak może się rozwijać?",
    ("8.1", "Dostęp do danych bliźniaka i wyników przez API", "MIM8 R1.1"),
    ("8.2", "Udokumentowane i wywoływalne modele", "MIM8 R3.1, R3.2"),
    ("8.3", "Standardowe formaty wyjściowe", "MIM8 M2"),
    ("8.4", "Rejestrowanie pochodzenia danych w procesach", "MIM8 R4.4"),
  ),
  section("Horyzontalne klauzule umowne", accent: magenta, note: "Wykonawca potwierdza akceptację danego warunku umownego (S / N).",
    ("X.1", "Klauzula wyjścia: bezpłatne przekazanie danych w otwartym formacie", "—"),
    ("X.2", "Prawa do danych przysługują zamawiającemu", "—"),
    ("X.3", "Brak opłat za dostęp do danych własnych", "—"),
    ("X.4", "Stabilność API: wersjonowanie, 6 mies. wyprzedzenia", "—"),
  ),
)

#note(size: 8.4pt, gap: 6pt, "Poniższe krótkie etykiety odpowiadają pełnym punktom listy kontrolnej na stronach MIM — w razie wątpliwości rozstrzyga pełny tekst punktu.")
#spec-link("Edytowalna wersja tabeli znajduje się pod adresem:", "https://marek-mraz.github.io/mims-procurement-checklist/")
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  GLOSSARY AND FURTHER READING
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glossary")[
  #band("Krótki słowniczek", id: "glossary")

  #glossary(
    term("API",
      "Interfejs, za pomocą którego jeden program komputerowy pobiera dane z innego — przez sieć, bez ingerencji człowieka."),
    term("Model danych",
      "Uzgodniona struktura informacji: jakie pola występują w zbiorze, co one oznaczają i w jakich jednostkach są wyrażane."),
    term("DCAT-AP",
      "Europejski profil metadanych dla katalogów danych; pozwala na automatyczne odnajdywanie zbiorów danych również na portalach krajowych i unijnych."),
    term("EPSG",
      "Rejestr kodów numerycznych dla przestrzennych układów odniesienia współrzędnych (np. EPSG:4326 dla układu WGS 84)."),
    term("Identyfikator",
      "Trwała nazwa nadana jednemu obiektowi (np. konkretnej latarni lub budynkowi), używana przez wszystkie systemy do jednoznacznego wskazania tego obiektu."),
    term("Interoperacyjność",
      "Zdolność systemów różnych dostawców do wymiany danych i ich rozumienia."),
    term("IRI",
      "Międzynarodowy identyfikator zasobów w internecie (rozszerzenie adresu URL dopuszczające znaki narodowe). MIM1 wykorzystuje go do jednoznacznego nazywania obiektów."),
    term("LDT",
      "Lokalny cyfrowy bliźniak: cyfrowy model miasta lub jego części, połączony z danymi i symulacjami."),
    term("Format odczytywalny maszynowo",
      "Ustrukturyzowane tak, że program może je bezpośrednio przetwarzać (JSON, CSV) — PDF tabeli taki nie jest."),
    term("Metadane",
      "Dane opisujące inne dane: co zawiera dany zbiór, kto jest jego dostawcą, jak bardzo jest aktualny i na jakich zasadach licencyjnych został udostępniony."),
    term("OAuth 2.0 / OIDC",
      "Otwarte standardy uwierzytelniania i autoryzacji dostępu. Standard OpenID Connect (OIDC) rozszerza OAuth 2.0 o bezpieczną weryfikację tożsamości użytkownika."),
    term("OGC",
      "Open Geospatial Consortium: międzynarodowa organizacja opracowująca i publikująca otwarte standardy dla danych i usług geoprzestrzennych (OGC API, WFS, SensorThings)."),
    term("Otwarty standard",
      "Reguła techniczna, którą każdy może bezpłatnie i bez specjalnego zezwolenia przeczytać oraz wdrożyć."),
    term("OpenAPI",
      "Otwarty format maszynowego opisu sieciowych interfejsów API: zawiera adresy punktów końcowych, parametry zapytań i schematy zwracanych odpowiedzi."),
    term("Serializacja",
      "Zapisywanie danych w konkretnym formacie (np. JSON, XML), aby można je było przechowywać lub wysyłać."),
    term("TLS",
      "Protokół szyfrujący dane podczas przesyłania przez sieć (podstawa HTTPS)."),
    term("Uzależnienie od dostawcy (vendor lock-in)",
      "Stan, w którym koszt związany z danymi, formatami lub opłatami sprawia, że zmiana dostawcy jest w praktyce niemożliwa."),
    term("Webhook / MQTT",
      "Dwa mechanizmy aktywnego raportowania zdarzeń przez system: mechanizm webhook wywołuje wskazany adres URL, natomiast protokół MQTT rozsyła komunikaty do subskrybentów."),
  )

  #more-links("Gdzie dowiedzieć się więcej",
    more-link("mims.oascities.org", "Pełna specyfikacja MIMs Plus, rozwijana i utrzymywana przez OASC."),
    more-link("living-in.eu", "Europejski ruch na rzecz cyfrowej transformacji miast — deklaracja i kontekst wdrożeniowy MIMs Plus."),
    more-link("smartdatamodels.org", "Otwarta biblioteka standaryzowanych modeli danych (inicjatywa FIWARE, TM Forum, IUDX, OASC)."),
    more-link("oascities.org/academy", "CITYxCITY Academy — kursy dla pracowników miast, tworzone przez miasta."),
  )
]


// ════════════════════════════════════════════════════════════════════════════
//  BACK COVER
// ════════════════════════════════════════════════════════════════════════════
#pagebreak()
#back-cover(
  "Opracowano na podstawie specyfikacji MIMs Plus 9.0 opublikowanej przez Open & Agile Smart Cities (mims.oascities.org). Prawa autorskie do treści specyfikacji: © OASC. Niniejszy poradnik stanowi niezależne, przystępnie napisane kompendium wspierające zamówienia publiczne w samorządach; w razie rozbieżności rozstrzygająca jest oficjalna treść specyfikacji.",
  "Stworzono za pomocą otwartych narzędzi. Można swobodnie wykorzystywać i dostosowywać na potrzeby swojego miasta.",
  author: "Autor poradnika: Marek Mráz",
)
