// ════════════════════════════════════════════════════════════════════════════
//  MIMs procurement booklet, edition: lv
//
//  GENERATED by gen_typ.py from content/lv.json + shared.json + quotes.json.
//  Do not edit: change the JSON and run ./build.sh.
//
//  How to read it: the file runs top to bottom in page order. Each #name(…)
//  is one block on the page; what the block looks like (sizes, colours,
//  spacing) is described next to its definition in ../style.typ.
//  #fit-page("name")[ … ] is one physical page.
//  One-letter prepositions may be followed by a no-break space (U+00A0),
//  which looks like a normal space here.
//
//  Build:  typst compile --root .. --font-path ../tools/fonts booklet-lv.typ
// ════════════════════════════════════════════════════════════════════════════
#import "../style.typ": *

#show: booklet.with(title: "Iepirkumu kontrolsaraksts · izmantojot minimālos · savietojamības mehānismus (MIMs)", lang: "lv",
  nav: (overview: "Pārskats", clauses: "Noteikumi", example: "Piemērs", table: "Atbilstības tabula", glossary: "Vārdnīca", list: "Kontrolsaraksts", back: "atpakaļ uz kontrolsarakstu", page: "lpp."),
  mims: ("MIM0", "MIM1", "MIM2", "MIM3", "MIM6", "MIM7", "MIM8",))


// ════════════════════════════════════════════════════════════════════════════
//  COVER
// ════════════════════════════════════════════════════════════════════════════
#cover(
  title:    "Iepirkumu kontrolsaraksts · izmantojot minimālos · savietojamības mehānismus (MIMs)",
  subtitle: "Ko iekļaut iepirkumā, lai pilsēta saglabātu kontroli pār saviem datiem",
  tagline:  "Paredzēts OASC MIMs Plus 9.0",
  footer:   "Eiropas pašvaldību iepirkumu speciālistiem, projektu vadītājiem un IT vadītājiem",
  author:   "Brošūras autors: Marek Mráz",
)


// ════════════════════════════════════════════════════════════════════════════
//  WHY THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("why")[
  #band("Kāpēc šī brošūra ir nepieciešama")

  #lead("Katru gadu pilsētas iegādājas programmatūru: stāvvietu sistēmas, sensoru platformas, karšu portālus, digitālos dvīņus. Pārāk bieži šo sistēmu savāktie dati paliek tajās ieslēgti. Kad līgums beidzas, dati — par kuriem samaksāts ar publiskajiem līdzekļiem — aiziet kopā ar piegādātāju vai paliek iesprostoti formātā, ko neviens cits nespēj nolasīt.")

  #lead("Tā tam nav jābūt. Minimālie savietojamības mehānismi (MIMs), ko uztur organizācija Open & Agile Smart Cities (OASC) un atbalsta Eiropas kustība living-in.eu, apraksta minimālās tehniskās prasības, kas nodrošina datu atvērtību, atkārtotu izmantojamību un neatkarību no piegādātāja. Tie apzināti veidoti vienkārši: tā nav sarežģīta arhitektūra, bet tikai daži priekšnoteikumi, lai sistēmas spētu savstarpēji sazināties.")

  #lead("Lai tos izmantotu, nav jābūt inženierim. Katrs kontrolsaraksts pārvērš vienu MIM saprotamos kontrolsaraksta punktos, kurus varat iekļaut iepirkumā, vienlaikus paskaidrojot, kā katrs punkts aizsargā jūsu intereses. Tūlīt pēc kontrolsaraksta atrodama katra konkrētā MIM prasība vārdu pa vārdam, lai tehniskie kolēģi un pretendenti varētu iepazīties ar detaļām.")

  #lead("Pilsētas, kas prasa MIMs ievērošanu, iepērk vienreiz un izmanto daudzkārt: gaisa kvalitātes dati papildina skolu informācijas paneļus, ielu apgaismojuma reģistrs kalpo enerģētikas plānam, un nākamais piegādātājs var turpināt darbu no vietas, kur iepriekšējais apstājās. Lūk, ko savietojamība nozīmē praksē — un tas arvien biežāk tiek prasīts ES finansētajos projektos.")

  #pull-quote(
    "Minimālie savietojamības mehānismi (MIMs) nodrošina minimālu, bet pietiekamu savietojamības līmeni datiem, sistēmām un pakalpojumiem tieši viedo pilsētu risinājumu kontekstā. · Šī dokumenta mērķauditorija ir: · 1. Risinājumu piegādātāji, kuri vēlas nodrošināt, ka viņu risinājumi ir savietojami ar citiem un nodrošina brīvu datu apmaiņu viedo pilsētu un kopienu kontekstā. · 2. Pasūtītāji, kuri vēlas iepirkt nākotnes prasībām atbilstošus risinājumus, kas nodrošina rentablu integrāciju esošajā viedo pilsētu un kopienu informācijas un komunikācijas tehnoloģiju (IKT) arhitektūrā.",
  )

  #policy-box("Kā MIMs saskan ar ES tiesību aktiem",
    "MIMs ir tehniska specifikācija, nevis likums. Tie atbilst ES noteikumiem, kas jau tiek piemēroti publiskajiem datiem un digitālajiem pakalpojumiem:",
    law("Publisko iepirkumu direktīva", "Direktīva 2014/24/ES, 42. pants",
      "tehniskajās specifikācijās var atsaukties uz standartiem, vienmēr pievienojot norādi “vai ekvivalents”; parasti nedrīkst norādīt konkrētu zīmolu vai ražojumu."),
    law("Datu akts", "Regula (ES) 2023/2854",
      "piekļuve savienoto izstrādājumu datiem un mākoņpakalpojumu sniedzēju maiņa bez piesaistes riskam."),
    law("Savietojamas Eiropas akts", "Regula (ES) 2024/903",
      "savietojamības novērtējumi pārrobežu digitālajiem publiskajiem pakalpojumiem un atvērto risinājumu atkārtota izmantošana."),
    law("Atvērto datu direktīva", "Direktīva (ES) 2019/1024",
      "augstvērtīgas datu kopas tiek publicētas bez maksas, mašīnlasāmā formātā, izmantojot API."),
    law("NIS2 direktīva", "Direktīva (ES) 2022/2555",
      "kiberdrošības pamatprasības; valsts tiesību akti nosaka, cik lielā mērā tās attiecas uz vietējām pārvaldes iestādēm."),
    law("VDAR", "Regula (ES) 2016/679",
      "personas dati pilsētas sistēmās (stāvvietās, kamerās, mobilitātes risinājumos)."),
    law("Mākslīgā intelekta akts", "Regula (ES) 2024/1689",
      "noteikumi mākslīgā intelekta sistēmām; attiecas uz MI modeļiem digitālajos dvīņos."),
    note: "Tikai orientējošam nolūkam. Pārbaudiet, kā katrs akts ir pārņemts jūsu valsts tiesību aktos.",
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  HOW TO USE THIS BOOKLET
// ════════════════════════════════════════════════════════════════════════════
#fit-page("howto")[
  #band("Kā izmantot šo brošūru")

  #steps(
    step("Sagatavojiet",
      "Izlasiet septiņus kontrolsarakstus. Atzīmējiet tos, kas attiecas uz iepērkamo risinājumu. Lielākajai daļai iepirkumu nepieciešami MIM0, MIM1, MIM2 un MIM6; pievienojiet MIM3, ja dati tiek kopīgoti ar trešajām pusēm vai datu portālā, MIM7 visam, kas saistīts ar kartēm, un MIM8 digitālajiem dvīņiem."),
    step("Iepērciet",
      "Iekopējiet atzīmētos kontrolsaraksta punktus savās prasībās. Katrs punkts ir noformulēts kā gatavs teikums. Pievienojiet vispārīgos līguma noteikumus: tie prasa minimālus ieguldījumus un novērš piesaisti vienam piegādātājam.",
      links: (("clauses", "Noteikumi"), ("example", "Piemērs"), )),
    step("Vērtējiet",
      "Pieprasiet, lai pretendenti demonstrē, nevis tikai sola (sk. attiecīgo noteikumu). Pārbaudiet atbilstību, izmantojot pretendenta aizpildīto atbilstības tabulu.",
      links: (("table", "Atbilstības tabula"), )),
    step("Pieņemiet",
      "Pieņemšanas laikā atkārtoti pārbaudiet katru atzīmēto punktu. Prasība, kas netiek pārbaudīta pieņemšanas brīdī, patiesībā nekad nav bijusi prasība.",
      links: (("table", "Atbilstības tabula"), )),
  )

  #legend("Specifikācijas citātu lasīšana",
    note: "Kontrolsaraksta punktos lietots vārds “jābūt” pat tad, ja specifikācijā ir tikai ieteikums (vajadzētu) vai minēts kandidātmehānisms. Tā ir līgumslēdzējas iestādes izvēle.",
    entry("JĀBŪT / OBLIGĀTI (SHALL / MUST)", "obligāta prasība. Bez tās sistēma neatbilst prasībām."),
    entry("NEDRĪKST (MUST NOT)", "aizliegts. Sistēma, kas to dara, neatbilst prasībām."),
    entry("VAJADZĒTU (SHOULD)", "ļoti ieteicams. Atkāpēm nepieciešams pamatots rakstisks pamatojums."),
    entry("DRĪKST (MAY)", "neobligāti. Vēlams, bet netiek pieprasīts."),
    entry("VAR (CAN)", "iespējamība, nevis prasība. Norāda uz iespēju un nevienu neuzliek par pienākumu."),
  )

  #note("Katram kontrolsaraksta punktam ir neliela atsauce, piemēram, → MIM0 R1.1. Tā apzīmē MIMs Plus 9.0 prasību, no kuras tas izriet; tūlīt pēc kontrolsaraksta atrodama katra konkrētā MIM prasība vārdu pa vārdam. Tikai MIM0 definē normatīvos atslēgvārdus: tiem ir saistošs spēks, ja tie rakstīti ar lielajiem burtiem saskaņā ar IETF RFC 2119 un RFC 8174 vienošanos (CAN izriet no ISO/IEC direktīvu 2. daļas). Pārējos MIM šādu definīciju nav: MIM6 lielākoties raksta SHALL ar lielajiem burtiem, MIM2, MIM3, MIM7 un MIM8 raksta shall, should un must ar mazajiem burtiem, bet MIM1 tos lieto tikai mehānisma aprakstā (MUST NOT 3.1. sadaļā). Šajā brošūrā vārdi ar mazajiem burtiem tiek traktēti tāpat; pretendents tos var interpretēt brīvāk.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  THE SEVEN MIMs AT A GLANCE
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glance")[
  #band("Septiņi MIM un trīs rīki", id: "glance")

  #intro("Septiņi nelieli mehānismi, viens mērķis: jūsu dati paliek jūsu rīcībā, un sistēmas spēj savstarpēji sazināties.")

  #glance(
    note: "Par numerāciju: MIMs Plus 9.0 nosaka septiņus mehānismus, kas numurēti ar 0, 1, 2, 3, 6, 7 un 8. MIM4 (personas dati) un MIM5 (taisnīgs MI) pieder pie agrākām OASC versijām un nav iekļauti 9.0 versijā. Šajā brošūrā nekas netrūkst.",
    card("MIM0", "Piekļuve datiem",
      "Vai varam iegūt savus datus?",
      "Dati ir iegūstami, izmantojot standarta tīmekļa API mašīnlasāmos formātos.",
      "https://mims.oascities.org/accessing-data"),
    card("MIM1", "Datu sasaiste",
      "Vai katram objektam ir noturīgs nosaukums?",
      "Katram sensoram, lukturim un ēkai ir unikāls, noturīgs identifikators.",
      "https://mims.oascities.org/interlinking-data"),
    card("MIM2", "Datu reprezentācija",
      "Vai mēs runājam kopīgā valodā?",
      "Dati atbilst standarta, dokumentētiem datu modeļiem ar skaidrām mērvienībām.",
      "https://mims.oascities.org/representing-data"),
    card("MIM3", "Datu apmaiņa",
      "Vai varam kopīgot datus ar skaidriem nosacījumiem?",
      "Datu kopas ir katalogā un tiek kopīgotas saskaņā ar parauglīcencēm un pārvaldību.",
      "https://mims.oascities.org/exchanging-data"),
    card("MIM6", "Datu drošība",
      "Vai mūsu dati ir drošībā?",
      "Šifrēta pārraide, standarta autentifikācija, lomu piekļuve, audita žurnāli.",
      "https://mims.oascities.org/securing-data"),
    card("MIM7", "Ģeotelpiskie dati",
      "Vai tas darbojas kartē?",
      "Telpiskie dati izmanto OGC saskarnes, atvērtus formātus un norādītas koordinātu sistēmas.",
      "https://mims.oascities.org/geospatial-data"),
    card("MIM8", "Vietējie digitālie dvīņi",
      "Vai digitālais dvīnis var attīstīties?",
      "Dvīņa dati, modeļi un rezultāti paliek pieejami, dokumentēti un atkārtoti izmantojami.",
      "https://mims.oascities.org/local-digital-twins"),
  )

  #tools("Rīki jūsu iepirkumam",
    tool("clauses", "Vispārīgie iepirkuma noteikumi",
      "Kam jābūt katrā līgumā?",
      "Līguma izbeigšana, datu tiesības, API stabilitāte."),
    tool("example", "Piemērs: gaisa kvalitātes sensori",
      "Kā tas izskatās praksē?",
      "Kas kurā vietā jāiekļauj, un teksta paraugi iekopēšanai."),
    tool("table", "Atbilstības tabula",
      "Kā pretendents to apliecina?",
      "Pretendents aizpilda, komisija pārbauda, pievieno līgumam kā pielikumu."),
  )

  #menu-line(("glossary", "Īsa vārdnīca"), ("more", "Kur uzzināt vairāk"))
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 checklist")[
  #mim-page(
    id:       "MIM0",
    name:     "Piekļuve datiem",
    question: "Vai varam iegūt savus datus?",
    url:      "https://mims.oascities.org/accessing-data",
    intro:    "Tas ir pamats. Ja dati nevar atstāt sistēmu caur standarta saskarni, viss pārējais šajā brošūrā ir tikai teorija. MIM0 izvirza vienu prasību katrai iegādātajai sistēmai: datiem jābūt pieejamiem mašīnlasāmā formātā, izmantojot parasto tīmekli.",
    list:     "Kontrolsaraksts",
  )

  #item("Visi dati, ko sistēma vāc vai rada, ir iegūstami vismaz vienā mašīnlasāmā formātā (piem., JSON, CSV), izmantojot standarta tīmekļa API.",
    why:  "Nākamais izpildītājs — vai jūsu darbinieki — var izmantot datus, nevēršoties pie piegādātāja.",
    refs: "MIM0 R1.1, R1.2",
    num:  "0.1")

  #item("API ir formāli aprakstīts atvērtā, mašīnlasāmā dokumentā (piemēram, OpenAPI), kas publicēts nemainīgā adresē.",
    why:  "Jebkurš izstrādātājs var izveidot savienojumu bez maksas “integrācijas semināriem”.",
    refs: "MIM0 R1.3",
    num:  "0.2")

  #item("Datus var filtrēt pēc laika, vietas un atribūtiem tieši API.",
    why:  "Jūs saņemat to, kas nepieciešams, nevis pilnu datu izgūšanu katru nakti.",
    refs: "MIM0 R2.1, R2.2",
    num:  "0.3")

  #item("Ja lietojuma gadījumā nepieciešami reāllaika dati, lietotāji var abonēt izmaiņas (tīmekļa āķi, MQTT vai līdzīgi), nevis nepārtraukti veikt pieprasījumus.",
    why:  "Reāllaika paneļi un brīdinājumi kļūst iespējami un lēti.",
    refs: "MIM0 R3.1",
    num:  "0.4")

  #item("Kļūdas, kešatmiņa un pieprasījumu ierobežojumi izmanto standarta HTTP metodes un ir dokumentēti.",
    why:  "Integrācijas kļūmes tiek skaidri pamanītas un novērstas, nevis paliek apslēptas.",
    refs: "MIM0 C2",
    num:  "0.5")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Dati, par kuriem esat samaksājis, paliek izmantojami pēc līguma beigām.",
      "Jauni pakalpojumi balstās uz esošajiem datiem, nevis sākas no nulles.",
      "Integrācijas izmaksas samazinās katram nākamajam projektam.",
    )),
    flags: ("Brīdinājuma signāli", (
      "“Datu eksports pēc pieprasījuma, sazinoties ar mūsu atbalsta dienestu.”",
      "“API ir pieejams kā maksas papildmodulis.”",
      "Maksa par katru pieprasījumu pilsētas pašas datiem (sk. noteikumu “Bez maksas par lietotāju vai pieprasījumu”).",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM0 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM0 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM0",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM0",
    capability("C1", "Machine-readable data is retrievable through the web",
      tr: "Mašīnlasāmi dati ir iegūstami, izmantojot tīmekli"),
    req("R1.1",
      tr: "Sistēmām JĀBŪT tādām, kas ļauj izgūt datus vismaz vienā mašīnlasāmā formātā. Formātus var norādīt, izmantojot HTTP satura saskaņošanu",
      en: "Systems SHALL allow retrieval of data in at least one machine-readable format. Formats can be specified through HTTP Content-Negotiation"),
    req("R1.2",
      tr: "Datiem JĀBŪT izgūstamiem, izmantojot vismaz vienu standarta tīmekļa mehānismu",
      en: "Data SHALL be retrievable via at least one standard web-based mechanism"),
    req("R1.3",
      tr: "Piekļuves mehānismam(-iem) JĀBŪT formāli aprakstītam(-iem)",
      en: "Access mechanism(s) SHALL be formally described"),
    req("R1.4",
      tr: "Datu modeļiem, ko izmanto datu derīgajā kravā, vajadzētu būt norādītiem (sk. MIM2)",
      en: "Data Models used by payloads should be specified (see MIM2)"),
    capability("C2", "Access is structured and queryable",
      tr: "Piekļuve ir strukturēta un pieļauj vaicājumu veikšanu"),
    req("R2.1",
      tr: "Sistēmām JĀBŪT tādām, kas nodrošina datus, izmantojot strukturētu un konsekventu saskarni",
      en: "Systems SHALL provide data through a structured and consistent interface"),
    req("R2.2",
      tr: "Sistēmām JĀBŪT tādām, kas atbalsta pamata vaicājumus un/vai filtrēšanu (piem., pēc laika, atrašanās vietas, atribūtiem)",
      en: "Systems SHALL support basic querying and/or filtering (e.g. by time, location, attributes)"),
    capability("C2 best practice", "Additional best practice to consider:",
      tr: "Papildu labākā prakse, ko vērts apsvērt:", sub: true),
    req("C2",
      tr: "API VAJADZĒTU atbalstīt pašreizējo datu izgūšanu · API VAJADZĒTU atbalstīt vēsturisko datu izgūšanu, ja piemērojams · API VAJADZĒTU atbalstīt ģeotelpiskos vaicājumus, ja piemērojams (sk. MIM7) · API VAJADZĒTU atbalstīt izmaiņu abonēšanu, ja piemērojams · API VAJADZĒTU uzrādīt nākamā paredzamā atjauninājuma laika zīmogu · API VAJADZĒTU atbalstīt skaidru galapunktu versiju pārvaldību · API VAJADZĒTU nodrošināt derīgās kravas piemērus vai testa vaicājumus · API VAJADZĒTU atbalstīt standarta HTTP kešatmiņas galvenes · API VAJADZĒTU paziņot par pieprasījumu limita statusu, izmantojot standarta HTTP galvenes · API VAJADZĒTU atgriezt strukturētu kļūdas pamattekstu · API DRĪKST atbalstīt daļējas atbildes vai vaicājumu projekcijas · API DRĪKST nodrošināt standarta darbspējas/statusa galapunktu",
      en: "APIs SHOULD support retrieval of current data · APIs SHOULD support retrieval of historical data when applicable · APIs SHOULD support geospatial querying when applicable (see MIM7) · APIs SHOULD support subscription to changes when applicable · APIs SHOULD expose next expected update timestamp · APIs SHOULD support explicit versioning of endpoints · APIs SHOULD provide example payloads or test queries · APIs SHOULD support standard HTTP caching headers · APIs SHOULD communicate rate limit status via standard HTTP headers · APIs SHOULD return structured error bodies · APIs MAY support partial responses or query projections · APIs MAY expose a standard health/status endpoint"),
    capability("C3", "Changes in data can be subscribed to",
      tr: "Var veikt datu izmaiņu abonēšanu"),
    req("R3.1",
      tr: "Sistēmām lietojuma gadījumos, kuros nepieciešami paziņojumi, JĀBŪT nodrošinātam vismaz vienam mehānismam atjauninājumu saņemšanai par datu izmaiņām",
      en: "Systems for use cases that require notifications SHALL provide at least one mechanism to receive updates on data changes"),
    req("R3.2",
      tr: "Sistēmas DRĪKST atbalstīt vairākus abonēšanas mehānismus atkarībā no lietojuma gadījuma",
      en: "Systems MAY support multiple subscription mechanisms depending on use case"),
    capability("C4", "Access to information can be restricted",
      tr: "Piekļuvi informācijai var ierobežot"),
    req("C4",
      tr: "Ja šādi ierobežojumi ir noteikti, tiem JĀBŪT saskaņā ar MIM3 un MIM6 noteiktajām prasībām, konkrēti: dalībnieku identifikācija (MIM3.C5.R0), autorizācija un dalībnieku lomas (MIM6.C1.R4), datu aktīvu līmeņa politikas (MIM6.C1.R4)",
      en: "If such restrictions are in place, they SHALL follow the requirements defined in MIM3 and MIM6, specifically: actor identification (MIM3.C5.R0), authorization and actor roles (MIM6.C1.R4), data asset-level policies (MIM6.C1.R4)"),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/accessing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 checklist")[
  #mim-page(
    id:       "MIM1",
    name:     "Datu sasaiste",
    question: "Vai katram objektam ir noturīgs nosaukums?",
    url:      "https://mims.oascities.org/interlinking-data",
    intro:    "Pilsēta ir pilna ar objektiem: lukturiem, caurulēm, ēkām, autostāvvietām. Sistēmas nāk un iet, bet objekti paliek. MIM1 prasa, lai katrs objekts iegūtu nosaukumu — identifikatoru —, kas pastāv ilgāk par programmatūru, kura to pirmo reizi reģistrēja, lai tā vēsture un saites ar citiem datiem saglabātos katrā migrācijā.",
    list:     "Kontrolsaraksts",
  )

  #item("Katram objektam (sensoram, lukturim, ēkai, autostāvvietai…) ir unikāls, noturīgs identifikators, kas nemainās, nomainot programmatūru.",
    why:  "Vēsture un saiknes starp sistēmām saglabājas neatkarīgi no piegādātāja.",
    refs: "MIM1 R1.1, R1.5",
    num:  "1.1")

  #item("Identifikatoru var izmantot, lai mašīnlasāmā veidā iegūtu objekta datus un tā nozīmi (tipu).",
    why:  "Citas sistēmas var automātiski sekot saitei.",
    refs: "MIM1 R1.2, R2.1, R2.2",
    num:  "1.2")

  #item("Ja viens un tas pats reālās pasaules objekts pastāv vairākās sistēmās, identifikatorus var savstarpēji sasaistīt.",
    why:  "ĢIS reģistrētā ēka un enerģētikas sistēmas ēka ir pierādāmi viena un tā pati ēka.",
    refs: "MIM1 R1.3, R1.4",
    num:  "1.3")

  #item("Identifikatoros netiek iekļautas piegādātāja iekšējās detaļas (datubāzes rindu ID, serveru nosaukumi).",
    why:  "Pretējā gadījumā identifikatori beidzas līdz ar līgumu.",
    refs: "MIM1 M1 §3.1",
    num:  "1.4")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Desmit gadu mērījumi paliek piesaistīti pareizajam apgaismes stabam.",
      "Nodaļām vairs nav jāuztur pieci pretrunīgi vienu un to pašu aktīvu reģistri.",
      "Datu kopu sasaistīšana kļūst par vienkāršu vaicājumu, nevis dārgu konsultāciju projektu.",
    )),
    flags: ("Brīdinājuma signāli", (
      "“Identifikatori ir mūsu platformas iekšējā informācija.”",
      "Identifikatori tiek ģenerēti no jauna katrā datu migrācijā.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM1 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM1 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM1",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM1",
    capability("C1", "Entities are identified using unique identifiers",
      tr: "Objekti tiek identificēti, izmantojot unikālus identifikatorus"),
    req("R1.1",
      tr: "Katram sistēmas objektam ir unikāls identifikators",
      en: "Every entity within the system has a unique identifier"),
    req("R1.2",
      tr: "Pastāv veids, kā iegūt informāciju par objektu, meklējot identifikatoru sistēmā",
      en: "There exists a way to retrieve information about an entity by looking up the identifier within a system"),
    req("R1.3",
      tr: "ja unikāls identifikators norāda uz vienu un to pašu objektu vairākās sistēmās, ir iespējams noteikt veidu, kā meklēt informāciju par to katrā no šīm sistēmām",
      en: "if a unique identifier points to the same entity within multiple systems, it is possible to derive the way to look up information about it in each of these systems"),
    req("R1.4",
      tr: "ja vairāki unikāli identifikatori norāda uz vienu un to pašu objektu, tos ir iespējams savstarpēji sasaistīt",
      en: "if a multiple [sic] unique identifiers point to the same entity, it is possible to map them"),
    req("R1.5",
      tr: "Ir iespējams izveidot identifikatorus, kas ir noturīgi laikā",
      en: "It is possible to create identifiers that are persistent over time"),
    capability("C2", "Entities can be typed",
      tr: "Objektiem var norādīt tipus"),
    req("R2.1",
      tr: "Pastāv veids, kā iegūt objekta semantiku, izmantojot tikai tā unikālo identifikatoru",
      en: "There is a way to retreive [sic] the semantics of an entity, only using its unique identifier"),
    req("R2.2",
      tr: "Šī semantika ir aprakstīta mašīnlasāmā formātā",
      en: "These semantics are described in a machine-readable format"),
    capability("C3", "Entities can be (de)referenced",
      tr: "Objektus var (de)referencēt"),
    req("R3.1",
      tr: "Pastāv veids, kā atsaukties uz objektam definētu relāciju",
      en: "There exists a way to dereference a relation defined on an entity"),
    req("R3.2",
      tr: "Pastāv veids, kā piemērot papildu semantiku esošai ontoloģijai",
      en: "There exists a way to apply additional semantics to an existing ontology"),
    capability("M1", "Mechanism 1, section 3.1: Entity Identification with Globally Unique IRIs",
      tr: "1. mehānisms, 3.1. sadaļa: Vienību identificēšana ar globāli unikāliem IRI"),
    req("§3.1",
      tr: "IRI tiek uzskatīts par kanonisko identifikatoru visās pakārtotajās sistēmās; ieviešanas risinājumos NEDRĪKST ģenerēt IRI, kuros iekļautas mainīgas implementācijas detaļas, piemēram, datubāzes rindu ID vai serveru resursdatoru nosaukumi.",
      en: "The IRI is treated as the canonical identifier in all downstream systems; implementations MUST NOT generate IRIs that embed volatile implementation details such as database row IDs or server hostnames."),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/interlinking-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 checklist")[
  #mim-page(
    id:       "MIM2",
    name:     "Datu reprezentācija",
    question: "Vai mēs runājam kopīgā valodā?",
    url:      "https://mims.oascities.org/representing-data",
    intro:    "Divas sistēmas var eksportēt JSON un tomēr nesaprast viena otru. MIM2 ir par nozīmi: izmantot kopīgus, dokumentētus datu modeļus — ar skaidrām mērvienībām un formātiem —, lai “temperatūra”, “autostāvvieta” vai “gaisa kvalitāte” nozīmētu vienu un to pašu katrā jūsu sistēmā.",
    list:     "Kontrolsaraksts",
  )

  #item("Dati izmanto vispāratzītus standarta datu modeļus, kur vien tie pastāv (piem., Smart Data Models, SAREF, ISO/IEC 5087); atkāpes tiek pamatotas rakstiski.",
    why:  "Dati no diviem piegādātājiem apvienojas bez nepieciešamības veikt datu pielāgošanu.",
    refs: "MIM2 R1.2a",
    num:  "2.1")

  #item("Visi izmantotie datu modeļi ir skaidri dokumentēti, norādot mērvienības un datuma/laika formātus.",
    why:  "“Temperatūra: 23” ir bezjēdzīga, ja neviens nav piefiksējis, vai tie ir °C vai °F.",
    refs: "MIM2 R1.1",
    num:  "2.2")

  #item("Paplašinājumi tiek piegādāti kā dokumentēti profili/papildinājumi standarta modelim — nekad kā modificēts privāts atzars.",
    why:  "Jūs saglabājat saderību ar kopienu un turpmākajiem atjauninājumiem.",
    refs: "MIM2 R1.2b, R4.1, R4.2",
    num:  "2.3")

  #item("Katram modelim ir vismaz viena atvērta, pēc shēmas validējama serializācija (piemēram, JSON ar JSON Schema).",
    why:  "Ienākošos datus var automātiski pārbaudīt to ievades brīdī.",
    refs: "MIM2 R3.1, R3.4",
    num:  "2.4")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Viens informācijas panelis nolasa datus no daudziem piegādātājiem bez adapteriem.",
      "Jūsu datus saprot citu pilsētu rīki — un viņu datus saprot jūsu rīki.",
      "Automātiska validācija atklāj kļūdainus datus, pirms tie izplatās.",
    )),
    flags: ("Brīdinājuma signāli", (
      "“Mūsu patentētais datu modelis ir bagātāks par standartu.”",
      "Dokumentācija pieejama tikai ar NDA.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM2 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM2 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM2",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM2",
    capability("C1", "All entities included in data sources are described using consistent data models to enable interoperability for applications and systems",
      tr: "Visi datu avotos iekļautie objekti tiek aprakstīti, izmantojot konsekventus datu modeļus, lai nodrošinātu lietojumprogrammu un sistēmu savietojamību"),
    req("R1.1",
      tr: "Datu modeļiem, ko izmanto visiem objektiem jebkurā datu avotā, jābūt skaidri norādītiem. Tiem jābūt labi dokumentētiem un ar aprakstošiem metadatiem, kur izmantotie termini ir semantiski viennozīmīgi. Atribūtiem, kas saistīti ar mērvienībām, laika formātiem utt., izmantotajām mērvienībām, formātiem utt. jābūt skaidri norādītiem. Datu modeļus vajadzētu iekļaut katalogā, lai tie būtu viegli atrodami.",
      en: "Data models used for all entities in any data source shall be made explicit. They shall be well documented and have descriptive metadata, where the terms used shall be semantically unambiguous. For attributes related to units of measurement, time formats etc, the units, formats etc, used shall be made explicit. The data models should be catalogued so that they can be easily findable."),
    req("R1.2a",
      tr: "Izmantotajiem datu modeļiem (kur vien iespējams) jābalstās uz vispāratzītiem standartizētiem datu modeļiem, kā norādīts tālāk",
      en: "Data models used shall be based (wherever possible) on commonly recognised standardised data models as listed below"),
    req("R1.2b",
      tr: "Ja nav iespējams izmantot esošos standartizētos datu modeļus, jāpieliek pūles, lai paplašinātu visciešāk atbilstošos esošos standartizētos datu modeļus vai definētu jaunus, ievērojot labāko praksi un tās kopienas vai organizācijas principus, kura definē datu modeļus.",
      en: "Where it is not possible to use existing standardised data models, efforts shall be made to extend existing standardised data models that are most closely aligned or to define new ones, following best practice and conventions of the community or organisation defining the data models."),
    req("R1.3",
      tr: "Izmantotajiem datu modeļiem jāatbalsta datu apmaiņa, izmantojot attiecīgās MIM prasības par piekļuvi datiem un datu sasaisti",
      en: "Data models used shall support the exchange of data by using the relevant requirements of the MIMs on Accessing data and Interlinking data"),
    capability("C2", "Different data models for the same entity that are used within a common data sharing ecosystem should be easily transformable into a common data model",
      tr: "Dažādiem viena un tā paša objekta datu modeļiem, ko izmanto kopīgā datu apmaiņas ekosistēmā, vajadzētu būt viegli pārveidojamiem kopējā datu modelī"),
    req("R2.1",
      tr: "Jebkurai datu ekosistēmai vajadzētu izstrādāt kopēju datu modeli katram galvenajam objektam. Šim kopējam datu modelim vajadzētu saturēt visus laukus, kas iekļauti dažādajos šī objekta datu modeļos, kurus izmanto šajā datu ekosistēmā. Pēc tam katru atšķirīgo datu modeli, ko izmanto šajā datu ekosistēmā, varētu pārveidot kopējā datu modelī.",
      en: "A common data model for each key entity should be developed for any data ecosystem. That common data model should contain all the fields included within the different data models for that entity that are used within that data ecosystem. Each different data model used within that data ecosystem could then be transformed into the common data model."),
    capability("C3", "Any data and its associated metadata can be shared in open, standardised, data transport formats so that data can be exchanged and interpreted consistently by different tools and implementations",
      tr: "Jebkurus datus un ar tiem saistītos metadatus var kopīgot atvērtos, standartizētos datu transporta formātos, lai dažādi rīki un implementācijas varētu datus apmainīt un interpretēt konsekventi"),
    req("R3.1",
      tr: "Katram izmantotajam datu modelim jābūt vismaz vienam definētam mašīnlasāmam datu transporta formātam (“serializācijai”), kas ir atvērts, publiski pieejams un neatkarīgs no implementācijas.",
      en: "Each data model used shall have at least one defined machine-readable data transport format (“serialisation”) that is open, publicly available and implementation-independent."),
    req("R3.2",
      tr: "Datu transporta formāta dokumentācijai vajadzētu būt pietiekamai, lai ļautu izveidot nepatentētu lietojumprogrammu vai interpretatoru, kas spēj rekonstruēt visus šādā datu formātā saglabātos datus.",
      en: "The documentation of the data transport format should be sufficient to allow the creation of non-proprietary application or interpretor that is able to reconstruct all the data stored in such a data format."),
    req("R3.3",
      tr: "Ja vienam un tam pašam datu modelim tiek atbalstīti vairāki datu transporta formāti, tiem jāatspoguļo viens un tas pats informācijas saturs konsekventi un bez nozīmes zuduma.",
      en: "Where multiple data transport formats are supported for the same data model, they shall represent the same information content consistently and without loss of meaning."),
    req("R3.4",
      tr: "Reprezentācijai vajadzētu atbalstīt validāciju, izmantojot atklāti publicētas shēmas, gramatikas vai līdzvērtīgus mašīnlasāmus ierobežojumus, ja izvēlētajam formātam šādi validācijas mehānismi pastāv.",
      en: "The representation should support validation using openly published schemas, grammars, or equivalent machine-readable constraints, where such validation mechanisms exist for the chosen format."),
    capability("C4", "When useful, it should be possible to create \"Application Profiles\" for a data model, so that use case specific attributes can be added or specified without changing the underlying data model",
      tr: "Kad tas ir lietderīgi, vajadzētu būt iespējai izveidot datu modeļa “lietojumprogrammu profilus”, lai varētu pievienot vai precizēt konkrētam lietojuma gadījumam specifiskus atribūtus, nemainot pamatā esošo datu modeli"),
    req("R4.1",
      tr: "Lietojumprogrammu profiliem, kas paplašina datu modeli, nevajadzētu ietekmēt jau esošo modeli un tā lietotājus",
      en: "Application Profiles that extend a data model should not impact the already existing model and its users"),
    req("R4.2",
      tr: "Modeļa lietojumprogrammas profilā ieviestajām specializācijām vai paplašinājumiem vajadzētu būt labi dokumentētiem, atsevišķi no bāzes datu modeļa",
      en: "The specialisations or extensions introduced in the Application Profile of the model should be well documented, separate from the base data model"),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/representing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 checklist")[
  #mim-page(
    id:       "MIM3",
    name:     "Datu apmaiņa",
    question: "Vai varam kopīgot datus ar skaidriem nosacījumiem?",
    url:      "https://mims.oascities.org/exchanging-data",
    intro:    "Ne visus pilsētas datus var vienkārši publicēt: daži ir komerciāli, daži sensitīvi. MIM3 paredz pārējo datu drošu kopīgošanu: meklējamu katalogu, licences uz paraugu bāzes, nevis pielāgotus juridiskus tekstus, un pārvaldības noteikumus, ko var izlasīt ikviens. Specifikācijā gandrīz viss MIM3 formulēts kā ieteikums (sk. 3. lpp.).",
    list:     "Kontrolsaraksts",
  )

  #item("Katra sistēmas piedāvātā datu kopa tiek aprakstīta ar standarta metadatiem (piemēram, DCAT-AP) katalogā, lai citi to varētu atrast.",
    why:  "Dati, kurus neviens nevar atrast, ir dati, kurus neviens neizmanto.",
    refs: "MIM3 RC4.1–RC4.3",
    num:  "3.1")

  #item("Datu izmantošanas noteikumi un licences ir balstītas uz plaši zināmiem paraugiem (piem., atvērtām licencēm, standarta datu kopīgošanas līgumiem), nevis pielāgotiem juridiskiem tekstiem katrai datu kopai.",
    why:  "Vienošanās ir mērogojamas; juristi nekļūst par šķērsli procesam.",
    refs: "MIM3 RC2.2, RC2.3",
    num:  "3.2")

  #item("Pilsēta var noteikt, kurš drīkst piekļūt konkrētiem datu aktīviem un ar kādiem nosacījumiem, un mainīt to bez piegādātāja iesaistes.",
    why:  "Pārvaldība paliek pašvaldības rokās.",
    refs: "MIM3 RC1.1, RC2.1",
    num:  "3.3")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Vietējie uzņēmumi un pētnieki attīsta risinājumus, balstoties uz pilsētas datiem — vērtība paliek reģionā.",
      "Sensitīvus datus var kopīgot ar precīzi noteiktiem partneriem, nevis ar visiem vai nevienu.",
      "Viens noteikumu kopums aizstāj daudzus individuālus datu kopīgošanas līgumus.",
    )),
    flags: ("Brīdinājuma signāli", (
      "Piegādātājs piesaka tiesības uz pilsētas datiem (sk. noteikumu “Datu īpašumtiesības”).",
      "Datu kopīgošanai ar trešo pusi nepieciešama piegādātāja piekrišana vai papildu maksa.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM3 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM3 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM3",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM3",
    capability("C1", "Governance rules for the data sharing ecosystem can be defined",
      tr: "Var definēt datu kopīgošanas ekosistēmas pārvaldības noteikumus"),
    req("RC1.1",
      tr: "Datu ekosistēmas vadītājam vajadzētu spēt definēt pārvaldības modeli (piemēram, noteikumu kopumu), kurā izklāstīti dalības noteikumi, ekosistēmas dalībnieku lomas, pienākumi un saistības, kā arī vispārējie principi, kas regulē datu apmaiņu starp tiem.",
      en: "The orchestrator of a data ecosystem should be able to define a governance model (e.g. a rulebook) that outlines membership rules, the roles, responsibilities and obligations of ecosystem participants, and the overall principles that govern data exchange between them."),
    req("RC1.2",
      tr: "Dalībniekiem, kuri piedalās datu ekosistēmā, vajadzētu būt informētiem par tās pārvaldības modeli un jebkādām tajā veiktajām izmaiņām.",
      en: "Members who participate in a data ecosystem should be aware of its governance model and any changes made to it."),
    req("RC1.3",
      tr: "Pārvaldības modelim vajadzētu būt viegli saprotamam visiem ekosistēmas dalībniekiem.",
      en: "The governance model should be easily comprehensible by all ecosystem participants."),
    capability("C2", "Terms and conditions for data sharing can be defined",
      tr: "Var definēt datu kopīgošanas noteikumus un nosacījumus"),
    req("RC2.1",
      tr: "Datu sniedzēji var brīvi noteikt noteikumus un nosacījumus, saskaņā ar kuriem tie vēlas nodrošināt savu datu apmaiņu. (Piezīme: Pirms datu aktīvu kopīgošanas datu sniedzējiem vajadzētu pārliecināties, ka tiem ir atbilstoša datu īpašnieku atļauja.)",
      en: "Data providers are free to define terms and conditions under which they want their data to be exchanged. (Note: Before sharing data assets, data providers should ensure they have adequate permission from data owners.)"),
    req("RC2.2",
      tr: "Datu apmaiņas noteikumiem un nosacījumiem vajadzētu būt aprakstītiem skaidri un viennozīmīgi, lai tie būtu viegli saprotami datu lietotājiem.",
      en: "Terms and conditions for a data exchange should be described clearly and unambiguously so that they are easily understandable for data users."),
    req("RC2.3",
      tr: "Datu apmaiņas noteikumiem un nosacījumiem vajadzētu būt izteiktiem ar datu licencēm vai datu kopīgošanas līgumiem, kuru pamatā ir skaidri definēti paraugi vai standarti.",
      en: "Terms and conditions for a data exchange should be expressed through data licences or data sharing agreements based on well-defined templates or standards."),
    req("RC2.4",
      tr: "Noteikumiem un nosacījumiem vajadzētu atbilst datu ekosistēmas vispārējam pārvaldības modelim, un tie NEDRĪKST būt pretrunā ar to. (Piezīme: Datu sniedzējs var izlemt nepiedalīties datu ekosistēmā, ja tās pamatā esošais pārvaldības modelis ir pārāk ierobežojošs vai pārāk pieļaujošs.)",
      en: "Terms and conditions should be in line with the overall governance model of the data ecosystem and must not conflict with it. (Note: A data provider can decide not to participate in a data ecosystem if the underlying governance model is too restrictive or too permissive.)"),
    capability("C3", "Compliance with data sharing terms and conditions can be validated",
      tr: "Var pārbaudīt atbilstību datu kopīgošanas noteikumiem un nosacījumiem"),
    req("RC3.1",
      tr: "Datu ekosistēmas vadītājam jāspēj pārliecināties par tās dalībnieku atbilstību pamatā esošajam pārvaldības modelim.",
      en: "The orchestrator of a data ecosystem must be able to ascertain compliance of its participants with the underlying governance model."),
    req("RC3.2",
      tr: "Datu sniedzējiem vajadzētu spēt pārliecināties, ka datu lietotāja veikta datu izmantošana atbilst iepriekš saskaņotajiem noteikumiem un nosacījumiem.",
      en: "Data providers should be able to ascertain that the use of data by a data user complies with previously agreed-upon terms and conditions."),
    req("RC3.3",
      tr: "Datu lietotājiem vajadzētu spēt pārliecināties, ka datu sniedzēja veiktā datu piegāde atbilst iepriekš saskaņotajiem noteikumiem un nosacījumiem.",
      en: "Data users should be able to ascertain that the data provider's supply of data follows previously agreed-upon terms and conditions."),
    capability("C4", "Available data assets can be discovered",
      tr: "Pieejamos datu aktīvus var atrast"),
    req("RC4.1",
      tr: "Datu lietotājiem vajadzētu spēt uzzināt, kādi dati ir pieejami datu kopīgošanas ekosistēmā, bez iepriekšējām zināšanām par to.",
      en: "Data users should be able to discover what data is available in a data sharing ecosystem without prior knowledge of it."),
    req("RC4.2",
      tr: "Datu aktīviem vajadzētu būt atbilstoši aprakstītiem ar metadatiem, lai datu lietotāji varētu pieņemt pamatotus lēmumus par to turpmāku paredzēto izmantošanu.",
      en: "Data assets should be adequately described with metadata so that data users can make reliable decisions about their further intended use."),
    req("RC4.3",
      tr: "Metadatiem, ko izmanto datu aktīvu aprakstīšanai, vajadzētu balstīties uz skaidri definētiem, viegli saprotamiem apraksta formātiem, kas ir gan cilvēkam, gan mašīnai lasāmi.",
      en: "Metadata used to describe data assets should be based on well-defined, easy-to-understand description formats that are both human- and machine-readable."),
    capability("C5", "Ecosystem participants can be discovered",
      tr: "Ekosistēmas dalībniekus var atrast"),
    req("RC5.1",
      tr: "Ekosistēmas dalībniekiem (piemēram, datu lietotājiem un sniedzējiem) vajadzētu spēt atrast vienam otru datu kopīgošanas ekosistēmā.",
      en: "Ecosystem participants (e.g. data users and providers) should be able to discover each other within a data-sharing ecosystem."),
    req("RC5.2",
      tr: "Vajadzētu būt pieejamiem pietiekamiem metadatiem par katru ekosistēmas dalībnieku, lai pārliecinātos par tā uzticamību datu apmaiņas kontekstā.",
      en: "Sufficient metadata about each ecosystem participant should be available to ascertain their trustworthiness relevant for data exchange."),
    req("RC5.3",
      tr: "Datu sniedzējiem vajadzētu spēt droši identificēt datu lietotājus, kuri vēlas piekļūt to datu aktīviem, un pārbaudīt to metadatus pirms piekļuves piešķiršanas.",
      en: "Data providers should be able to reliably identify data users who want to access their data assets and verify their metadata before granting access."),
    req("RC5.4",
      tr: "Datu lietotājiem vajadzētu spēt identificēt datu sniedzējus, kuri kopīgo datus datu ekosistēmā, pirms piekļūšanas šiem datiem vai to izmantošanas.",
      en: "Data users should be able to identify data providers who share data in a data ecosystem before accessing or using that data."),
    req("RC5.5",
      tr: "Ekosistēmas dalībnieki drīkst arī izvēlēties palikt anonīmi, ja datu kopīgošanas ekosistēmas pārvaldības modelis to pieļauj. Šādā gadījumā prasības no RC5.1 līdz RC5.4 var neņemt vērā.",
      en: "Ecosystem participants may also choose to remain anonymous if the governance model of the data-sharing ecosystem allows for it. In this case, RC5.1 to RC5.4 can be ignored."),
    capability("C6", "Data exchange can be agreed upon",
      tr: "Par datu apmaiņu var vienoties"),
    req("RC6.1",
      tr: "Datu lietotājiem un sniedzējiem vajadzētu spēt vienoties par datu apmaiņu un ar to saistītajiem noteikumiem un nosacījumiem (piemēram, noteikumu pieņemšana, līguma parakstīšana vai pārrunas).",
      en: "Data users and providers should be able to agree to a data exchange and the terms and conditions associated with it (e.g. acceptance of terms, legal signature of an agreement, or negotiation)."),
    req("RC6.2",
      tr: "Datu lietotājiem un sniedzējiem vajadzētu spēt pārtraukt iepriekš saskaņotu datu apmaiņu saskaņā ar tās noteikumiem un nosacījumiem.",
      en: "Data users and providers should be able to terminate a previously agreed-upon data exchange in accordance with the terms and conditions associated with it."),
    req("RC6.3",
      tr: "Kur iespējams, drīkst nodrošināt elektroniskus līdzekļus datu apmaiņas saskaņošanai un pārtraukšanai.",
      en: "Where possible, electronic means for the agreement and termination of a data exchange may be provided."),
    capability("C7", "New data currently not available can be requested",
      tr: "Var pieprasīt jaunus datus, kas pašlaik nav pieejami"),
    req("RC7.1",
      tr: "Datu lietotājiem vajadzētu spēt paust interesi par datu aktīviem, kas pašlaik nav pieejami datu kopīgošanas ekosistēmā.",
      en: "Data users should be able to express their interest in data assets currently unavailable in the data sharing ecosystem."),
    req("RC7.2",
      tr: "Datu sniedzējiem vajadzētu spēt saņemt datu lietotāju izteiktos pieprasījumus pēc jauniem datu aktīviem.",
      en: "Data providers should be able to obtain requests made by data users for new data assets."),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/exchanging-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 checklist")[
  #mim-page(
    id:       "MIM6",
    name:     "Datu drošība",
    question: "Vai mūsu dati ir drošībā pārraidē un lietošanā?",
    url:      "https://mims.oascities.org/securing-data",
    intro:    "Viedās pilsētas ir mērķis uzbrukumiem. MIM6 saglabā apzināti šauru un praktisku tvērumu: šifrēt datus kustībā, izmantot standarta pieteikšanos, nevis patentētus risinājumus, kontrolēt un reģistrēt, kurš kam piekļūst. Nekas no tā nav eksotisks — visam jābūt iekļautam līgumā.",
    list:     "Kontrolsaraksts",
  )

  #item("Visa datu pārraide ir šifrēta (TLS 1.3 vai pašreizējā labākā prakse).",
    why:  "Pamata drošības prasība; to paredz arī NIS2, ja tā uz jums attiecas.",
    refs: "MIM6 R2.1, M1.1",
    num:  "6.1")

  #item("Lietotāju un mašīnu piekļuvei tiek izmantoti atvērtie standarti — OAuth 2.0 / OpenID Connect —, un to var integrēt pilsētas esošajā identitātes pārvaldības sistēmā.",
    why:  "Viens konts katram darbiniekam, nevis atsevišķs konts katram piegādātāja produktam; darbiniekam aizejot, piekļuve tiek pārtraukta visur vienlaikus.",
    refs: "MIM6 R3.1, M1.2, M1.3",
    num:  "6.2")

  #item("Piekļuves tiesības ir balstītas uz lomām, pārskatāmas un atceļamas; piekļuves un administratora darbības tiek reģistrētas žurnālā.",
    why:  "Kļūst iespējams veikt auditus un reaģēt uz incidentiem. Reģistrēšana žurnālā atbilst ISO/IEC 27001:2022 A pielikuma 8.15. kontrolei, ko MIM6 iekļauj savos priekšnoteikumos.",
    refs: "MIM6 R1.1, R1.3, 8.15",
    num:  "6.3")

  #item("Piegādātājam jāapliecina atbilstība ISO/IEC 27001:2022 (vai ekvivalentam) pakalpojumam, ko tas nodrošina.",
    why:  "Drošība ir process, nevis tikai atzīme pieņemšanas brīdī. Specifikācijā ir minētas ISO/IEC 27001 kontroles, nevis pats sertifikāts.",
    refs: "MIM6 C1–C3 (ISO/IEC 27001)",
    num:  "6.4",
    label: "Jāiekļauj dalības nosacījumos, nevis tehniskajā specifikācijā")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Drošības pārkāpums vienā sistēmā neatver piekļuvi visām sistēmām.",
      "Ja uz jums attiecas NIS2, atbilstības nodrošināšana tai un valsts kiberdrošības noteikumiem kļūst ievērojami vienkāršāka.",
      "Ja kaut kas noiet greizi, žurnāli parāda, kas un ko tieši izdarīja.",
    )),
    flags: ("Brīdinājuma signāli", (
      "Tikai patentēta pieteikšanās.",
      "“Žurnāli pieejami pēc pieprasījuma.”",
      "Kopīgi administratoru konti.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM6 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM6 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM6",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM6",
    capability("C1", "Data is only accessible to users that should have access to it",
      tr: "Dati ir pieejami tikai tiem lietotājiem, kuriem tiem jābūt pieejamiem"),
    req("R1.1",
      tr: "Noteikumiem fiziskās un loģiskās piekļuves kontrolei informācijai un citiem saistītajiem aktīviem JĀBŪT izstrādātiem un ieviestiem, pamatojoties uz darbības un informācijas drošības prasībām. (ISO 27001 5.15 Piekļuves kontrole)",
      en: "Rules to control physical and logical access to information and other associated assets SHALL be established and implemented based on business and information security requirements. (ISO 27001 5.15 Access control)"),
    req("R1.2",
      tr: "Autentifikācijas informācijas piešķiršanai un pārvaldībai JĀBŪT kontrolētai ar pārvaldības procesu, tostarp konsultējot personālu par atbilstošu rīcību ar autentifikācijas informāciju. (ISO 27001 5.17: Autentifikācijas informācija)",
      en: "Allocation and management of authentication information SHALL be controlled by a management process, including advising personnel on appropriate handling of authentication information. (ISO 27001 5.17: Authentication information)"),
    req("R1.3",
      tr: "Piekļuves tiesībām informācijai un citiem saistītajiem aktīviem JĀBŪT piešķirtām, pārskatītām, modificētām un atceltām saskaņā ar organizācijas konkrētajai tēmai veltīto politiku un piekļuves kontroles noteikumiem. (ISO 27001 5.18: Piekļuves tiesības)",
      en: "Access rights to information and other associated assets SHALL be provisioned, reviewed, modified and removed in accordance with the organization’s topic-specific policy on and rules for access control. (ISO 27001 5.18: Access rights)"),
    capability("C2", "Data accessed by users has not been altered",
      tr: "Dati, kuriem lietotāji piekļūst, nav tikuši mainīti"),
    req("R2.1",
      tr: "Kriptogrāfijas efektīvas izmantošanas noteikumiem, tostarp kriptogrāfisko atslēgu pārvaldībai, JĀBŪT definētiem un ieviestiem. (ISO 27001 8.24 Kriptogrāfijas izmantošana)",
      en: "Rules for the effective use of cryptography, including cryptographic key management, SHALL be defined and implemented. (ISO 27001 8.24 Use of cryptography)"),
    capability("C3", "Data accessed by users originates from a verified source",
      tr: "Dati, kuriem lietotāji piekļūst, nāk no pārbaudīta avota"),
    req("R3.1",
      tr: "Drošas autentifikācijas tehnoloģijām un procedūrām jābūt ieviestām, pamatojoties uz informācijas piekļuves ierobežojumiem un konkrētajai tēmai veltīto piekļuves kontroles politiku. (ISO 27001 8.5 Droša autentifikācija)",
      en: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control. (ISO 27001 8.5 Secure authentication)"),
    capability("M1", "Mechanism candidate",
      tr: "Mehānisma kandidāts"),
    req("M1.1",
      tr: "Transport Layer Security (TLS) protokols, versija 1.3",
      en: "The Transport Layer Security (TLS) Protocol, Version 1.3"),
    req("M1.2",
      tr: "OAuth 2.0 autorizācijas ietvars",
      en: "The OAuth 2.0 Authorization Framework"),
    req("M1.3",
      tr: "OpenID Connect 1.0, identitātes slānis autentifikācijai virs OAuth 2.0",
      en: "OpenID Connect 1.0, Identity layer for authentication on OAuth 2.0"),
    req("M1.4",
      tr: "OIDC4VCI / OIDC4VP, OpenID pārbaudāmu akreditācijas datu izsniegšanai un uzrādīšanai",
      en: "OIDC4VCI / OIDC4VP, OpenID for Verifiable Credential Issuance and Presentations"),
    capability("P", "Pre- and Post-requisites (based on ISO 27001 Annex A): the control this booklet refers to",
      tr: "Priekšnoteikumi un pēcnoteikumi (balstīti uz ISO 27001 A pielikumu): kontrole, uz kuru atsaucas šī brošūra"),
    req("8.15",
      tr: "Reģistrēšana žurnālā. Žurnāliem, kuros tiek reģistrētas darbības, izņēmumi, kļūdas un citi būtiski notikumi, jābūt veidotiem, glabātiem, aizsargātiem un analizētiem.",
      en: "Logging. Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed."),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/securing-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 checklist")[
  #mim-page(
    id:       "MIM7",
    name:     "Ģeotelpiskie dati",
    question: "Vai tas darbojas kartē?",
    url:      "https://mims.oascities.org/geospatial-data",
    intro:    "Gandrīz visam, kas pieder pilsētai, ir sava atrašanās vieta. MIM7 nodrošina, ka atrašanās vieta nav tikai ekrānuzņēmums: telpiskie dati tiek nodoti caur standarta OGC saskarnēm atvērtos formātos un ar vienmēr norādītu koordinātu sistēmu — lai katrs iepirktais kartes slānis precīzi sakristu ar esošajiem.",
    list:     "Kontrolsaraksts",
  )

  #item("Ģeotelpiskie dati tiek nodrošināti, izmantojot uz standartiem balstītas saskarnes (OGC API Features, SensorThings; mantotajām sistēmām pieļaujams WFS).",
    why:  "Jebkurš tirgū pieejamais ĢIS rīks spēj tos nolasīt bez papildu pielāgojumiem.",
    refs: "MIM7 R1.1",
    num:  "7.1")

  #item("Ģeotelpiskie dati tiek kodēti atvērtos formātos (GeoJSON, CityJSON; ja nepieciešams, GML/CityGML).",
    why:  "Nav nepieciešamas konvertētāju licences, nav strupceļu.",
    refs: "MIM7 R2.1",
    num:  "7.2")

  #item("Koordinātu atskaites sistēma vienmēr ir norādīta (EPSG kods), un dati ir transformējami uz vienotu CRS.",
    why:  "Slāņi no dažādiem avotiem kartē precīzi sakrīt.",
    refs: "MIM7 R5.1",
    num:  "7.3")

  #item("Telpiskajiem objektiem ir tādi paši noturīgi identifikatori kā MIM1.",
    why:  "Punkts kartē un ieraksts reģistrā ir viens un tas pats objekts.",
    refs: "MIM7 R4.1",
    num:  "7.4")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Viena pilsētas karte, nevis desmit dažādu piegādātāju skatītāji.",
      "INSPIRE un valsts ģeoportāla saistību izpilde kļūst vienkāršāka, nevis sarežģītāka.",
      "Vēlāk šajā pašā ainā var integrēt 3D un BIM datus.",
    )),
    flags: ("Brīdinājuma signāli", (
      "Karšu dati pieejami tikai piegādātāja skatītājā.",
      "“Eksports kā PDF/ekrānuzņēmums.”",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM7 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM7 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM7",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM7",
    capability("C1", "Cities and communities can easily transfer geospatial data between internal and external (including IoT-related) IT systems",
      tr: "Pilsētas un kopienas var viegli nodot ģeotelpiskos datus starp iekšējām un ārējām (tostarp ar IoT saistītām) IT sistēmām"),
    req("R1.1",
      tr: "Ģeotelpiskajiem datiem jābūt pieejamiem, izmantojot uz standartiem balstītu tīmekļa pakalpojumu saskarni.",
      en: "Geospatial data shall be exposed through a standards-based web service interface."),
    capability("C2", "Cities and communities can integrate 2D and 3D geospatial data coming from a variety of sources, for example geodata and building information models, and share that data within and between them in an interoperable way",
      tr: "Pilsētas un kopienas var integrēt 2D un 3D ģeotelpiskos datus no dažādiem avotiem, piemēram, ģeodatus un būves informācijas modeļus, un kopīgot šos datus savā starpā savietojamā veidā"),
    req("R2.1",
      tr: "Ģeotelpiskajiem datiem jābūt kodētiem, izmantojot atvērtos standartus. Ieteicams izmantot attiecīgos OGC un BuildingSMART International standartus.",
      en: "Geospatial data shall be encoded using open standards. It is recommended to use relevant standards from OGC and BuildingSMART International."),
    capability("C3", "Cities and communities can integrate geospatial data with other data that can provide further information about the context",
      tr: "Pilsētas un kopienas var integrēt ģeotelpiskos datus ar citiem datiem, kas var sniegt papildu informāciju par kontekstu"),
    req("R3.1",
      tr: "Visām datu kopām, ko izmanto, lai sniegtu papildu informāciju par ģeotelpisko datu aptverto kontekstu, jāatbilst MIM1 un MIM2 prasībām.",
      en: "All data sets used to provide further information about the context covered by geospatial data shall comply with MIM1 and MIM2."),
    capability("C4", "Cities and communities have a consistent and persistent way of describing individual instances of all features, things or entities included in the geospatial data sources",
      tr: "Pilsētām un kopienām ir konsekvents un noturīgs veids, kā aprakstīt visu ģeotelpisko datu avotos iekļauto objektu, lietu vai vienību atsevišķas instances"),
    req("R4.1",
      tr: "Unikāliem un noturīgiem identifikatoriem jābūt izmantotiem, lai identificētu konkrētas datu kopās izmantoto objektu instances. (Sk. MIM1: Datu sasaiste.)",
      en: "Unique and persistent identifiers shall be used to identify particular instances of any entity used in data sets. (See MIM1: Interlinking Data.)"),
    capability("C5", "Coordinate Reference Systems (CRS) used in data sharing are easily transformable into a common CRS",
      tr: "Datu kopīgošanā izmantotās koordinātu atskaites sistēmas (CRS) ir viegli transformējamas uz vienotu CRS"),
    req("R5.1",
      tr: "Koordinātu atskaites sistēmām (CRS) jāatbilst standartiem, un jāsniedz informācija par to, kurš standarts (piem., EPSG:4326, EPSG:3857) tiek izmantots. Tas ietver EPSG numuru vai WGS numuru, kā arī informāciju par jebkādām variācijām, kuru pamatā ir nacionālās sistēmas, piemēram, Latvijas LKS-92, lai datus varētu transformēt uz vienotu CRS. (Piezīme: Eiropas Savienībā ģeotelpiskajiem datiem ir obligāti jāizmanto metadati, kas atbilst INSPIRE direktīvai, tostarp metadati, kas nepieciešami CRS informācijas aprakstīšanai.)",
      en: "Coordinate Reference Systems (CRS) shall comply with standards, and information shall be provided regarding which standard (e.g. EPSG:4326, EPSG:3857) is being used. This includes the EPSG number or WGS number, along with information about any variation based on national systems such as the Latvian LKS-92, so that data can be transformed to a common CRS. (Note: Within the EU, for geospatial data it is required to use metadata compliant with the INSPIRE Directive, including the metadata needed to describe the CRS information.)"),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/geospatial-data")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · LEFT PAGE · CHECKLIST
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 checklist")[
  #mim-page(
    id:       "MIM8",
    name:     "Vietējie digitālie dvīņi",
    question: "Vai digitālais dvīnis var attīstīties?",
    url:      "https://mims.oascities.org/local-digital-twins",
    intro:    "Digitālais dvīnis ir ilgtermiņa ieguldījums: dati, 3D modeļi, simulācijas, lēmumi. MIM8 aizsargā šo ieguldījumu — dvīņa dati un modeļi paliek pieejami un dokumentēti, rezultāti ir reproducējami, un viena projekta komponentus var izmantot nākamajā. Izmantojiet šo sadaļu, iegādājoties dvīņu platformas, simulācijas modeļus vai 3D pilsētas rīkus.",
    list:     "Kontrolsaraksts",
  )

  #item("Datu kopas, modeļu ievaddati un simulāciju rezultāti ir pieejami, izmantojot API (atbilstoši MIM0), un nepaliek iesprostoti digitālajā dvīnī.",
    why:  "Rezultāti papildina ziņojumus, informācijas paneļus un nākamos projektus.",
    refs: "MIM8 R1.1",
    num:  "8.1")

  #item("Modeļi ir dokumentēti (metode, parametri, ievaddati/izvaddati) un izsaucami, izmantojot dokumentētu saskarni.",
    why:  "Vienreiz iegādātu plūdu modeli var atkārtoti izmantot dažādās nodaļās — un arī citās pilsētās.",
    refs: "MIM8 R3.1, R3.2",
    num:  "8.2")

  #item("Izvaddatos tiek izmantoti standarta formāti (GeoJSON, CityJSON, 3D Tiles, NetCDF…), ko var izmantot rīki, kurus neiepērkat no šī piegādātāja.",
    why:  "Vizualizācija un analīze paliek konkurētspējīgs tirgus.",
    refs: "MIM8 M2",
    num:  "8.3")

  #item("Darbplūsmas reģistrē izcelsmi: kura datu versija, kurš modelis un kādi parametri radīja konkrēto rezultātu.",
    why:  "Lēmumus, kas balstīti uz digitālo dvīni, vēlāk var pamatot un aizstāvēt.",
    refs: "MIM8 R4.4",
    num:  "8.4")

  #panels(
    why:   ("Kāpēc tas ir svarīgi", (
      "Dvīnis pastāv ilgāk par jebkuru atsevišķu piegādātāju vai projekta budžetu.",
      "Simulācijas var pārbaudīt, atkārtot un pamatot pašvaldības lēmumu pieņemšanā.",
      "Modeļus un komponentus var kopīgot starp pilsētām.",
    )),
    flags: ("Brīdinājuma signāli", (
      "Simulācijas rezultāti apskatāmi tikai piegādātāja portālā.",
      "Modeļi ir kā noslēgtas melnās kastes bez metadatiem.",
    )),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  MIM8 · RIGHT PAGE · WHAT THE SPECIFICATION SAYS
// ════════════════════════════════════════════════════════════════════════════
#fit-page("MIM8 specification", floor: 92, flow: true)[
  #spec-page(
    id:     "MIM8",
    title:  "Ko nosaka specifikācija",
    leadin: "Katra šī MIM prasība burtiskā tulkojumā no MIMs Plus 9.0: Specifikācija ir pieejama tikai angļu valodā: teksts latviešu valodā ir šīs brošūras autora neoficiāls tulkojums; saistošs ir zem tā esošais oriģinālteksts angļu valodā.",
    back:   "atpakaļ uz kontrolsarakstu",
  )

  #spec-list(mim: "MIM8",
    capability("C1", "Provide access to datasets used within the LDT, including static, real-time, and simulation data and calculation models",
      tr: "Nodrošināt piekļuvi datu kopām, ko izmanto LDT, tostarp statiskajiem, reāllaika un simulāciju datiem un aprēķinu modeļiem"),
    req("R1.1",
      tr: "LDT jānodrošina piekļuve simulāciju rezultātiem un aprēķinu modeļu ievaddatiem, ja tie ir nepieciešami LDT darbplūsmu ietvaros.",
      en: "The LDT shall provide access to simulation outputs and calculation-model inputs where these are needed as part of LDT workflows."),
    req("R1.2",
      tr: "LDT vajadzētu skaidri nošķirt neapstrādātus avota datus, pārveidotus darbplūsmai sagatavotus datus, modeļu ievaddatus un modeļu izvaddatus.",
      en: "The LDT should distinguish clearly between raw source data, transformed workflow-ready data, model inputs, and model outputs."),
    capability("C2", "Exchange data with external systems and other LDTs using interoperable interfaces",
      tr: "Apmainīties ar datiem ar ārējām sistēmām un citiem LDT, izmantojot savietojamas saskarnes"),
    req("C2",
      tr: "Šī spēja balstās uz MIM3 (Datu apmaiņa) datu apmaiņas nodrošināšanai.",
      en: "This capability relies on MIM3 (Exchanging Data) for data exchange."),
    capability("C3", "Reuse deterministic or AI models across different domains, communities, use cases, and/or LDTs",
      tr: "Atkārtoti izmantot deterministiskos vai MI modeļus dažādās jomās, kopienās, lietojuma gadījumos un/vai LDT"),
    req("R3.1",
      tr: "Modelim vajadzētu nodrošināt standarta modeļa metadatus, tostarp tā metožu un parametru, kā arī datu parametru aprakstu (pēc vērtības vai pēc atsauces). Šim nolūkam vajadzētu izmantot kopīgus metadatu standartus.",
      en: "The model should provide standard model metadata, including a description of its methods and parameters, and data-parameters (either by value or by reference). To this end common metadata standards should be used."),
    req("R3.2",
      tr: "Modelim jānodrošina piekļuve vai jābūt izsaucamam, izmantojot dokumentētu saskarni, vēlams izmantojot zināmu standartizētu API. Datu kopai, kas veido modeļa rezultātu, jābūt aprakstītai (datu līmenī).",
      en: "The model shall expose or be callable through a documented interface, preferably using a known standardised API. The dataset that forms the outcome of the model shall be described (at data-level)."),
    req("R3.3",
      tr: "Vajadzētu nodrošināt inovatīvu metožu (LLM, aģentu MI u. c.) uzticamu, drošu un ētisku izmantošanu. Nobīdēm vajadzētu būt samazinātām līdz minimumam, kur tas attiecināms. Izmantotajām metodēm, kas to garantē, vajadzētu būt aprakstītām.",
      en: "Trustworthy, reliable, and ethical use of innovative methods (LLMs, agentic AI, etc.) should be safeguarded. Bias should minimised [sic] where applicable. The methods used to guarantee this, should be described."),
    req("R3.4",
      tr: "Modelim jāspēj piekļūt datiem gala lietotāja vai organizācijas vārdā. Sk. MIM3",
      en: "The model must be able to access data on behalf of the end-user or organisation. See MIM3"),
    req("R3.5",
      tr: "Datiem, ko izmanto MI modeļos, vajadzētu garantēt izcelsmi un uzticamību. Dažos gadījumos jānorāda autoritatīvs avots, piemēram, valsts iestāde.",
      en: "For data to be used in AI models, provenance and trust should be guaranteed. In some cases, an authoratitive sourc [sic], such as a government agency must be listed."),
    capability("C4", "Coordinate and manage data, models, and processing workflows within an LDT (intra-LDT) and across LDTs (inter-LDT)",
      tr: "Koordinēt un pārvaldīt datus, modeļus un apstrādes darbplūsmas LDT iekšienē (intra-LDT) un starp LDT (inter-LDT)"),
    req("R4.1",
      tr: "LDT atbalsta darbplūsmas, kas savieno datu avotus, datu transformācijas, modeļu izpildi, simulācijas procesus un rezultātus.",
      en: "The LDT supports workflows that connect data sources, data transformations, model execution, simulation processes, and outputs."),
    req("R4.2",
      tr: "LDT savieno darbplūsmas soļus ķēdē, kur viena soļa rezultātu var izmantot kā cita soļa ievaddatus.",
      en: "The LDT chains workflow steps, where the output of one step can be used as the input for another."),
    req("R4.3",
      tr: "LDT uzrauga darbplūsmas izpildes statusu, tostarp pabeigtos, neizdevušos un pārtrauktos procesus.",
      en: "The LDT monitors workflow execution status, including completed, failed, and interrupted processes."),
    req("R4.4",
      tr: "LDT reģistrē darbplūsmas izcelsmi, tostarp izmantotās datu kopas (ieskaitot versiju ar laika zīmogu), izpildītos modeļus, atlasītos parametrus un iegūtos rezultātus.",
      en: "The LDT records workflow provenance, including datasets used (including version, timestamped), models executed, parameters selected, and outputs generated."),
    capability("C5", "Provide multiple visualisations of data and results (e.g. 2D, 3D, dashboards) from common underlying data and models for interaction and comparison",
      tr: "Nodrošināt vairākas datu un rezultātu vizualizācijas (piem., 2D, 3D, informācijas paneļus) no kopējiem pamatdatiem un modeļiem mijiedarbībai un salīdzināšanai"),
    req("R5.1",
      tr: "LDT nodrošina metadatus, kas paskaidro vizualizēto saturu, tostarp laika zīmogu, telpisko tvērumu, datu avotu un scenāriju un variantu pieņēmumus, ja attiecināms.",
      en: "The LDT provides metadata explaining what is visualised, including timestamp, spatial scope, data source, and scenario- and variant-assumptions where relevant."),
    req("R5.2",
      tr: "LDT atbalsta dažādus interaktīvas vizualizācijas veidus, piemēram, 2D kartes, 3D ainas, informācijas paneļus, ziņojumus vai sabiedrībai paredzētus skatus.",
      en: "The LDT supports different interactive visualisation types, such as 2D maps, 3D scenes, dashboards, reports, or public-facing views."),
    capability("C6", "Ensure that data exchanged (and simulation outputs) within and between LDTs can be interpreted consistently through shared or mapped semantics and clear provenance",
      tr: "Nodrošināt, ka LDT iekšienē un starp LDT apmainītos datus (un simulāciju rezultātus) var interpretēt konsekventi, izmantojot kopīgu vai saskaņotu semantiku un skaidru izcelsmi"),
    req("R6.1",
      tr: "LDT vajadzētu dokumentēt neatrisinātās semantiskās atšķirības, pieņēmumus vai kartējumus, kas var ietekmēt rezultātu interpretāciju, atkārtotu izmantošanu vai salīdzināšanu.",
      en: "The LDT should document unresolved semantic gaps, assumptions, or mappings that may affect the interpretation, reuse, or comparison of results."),
    capability("M", "Mechanisms (under active development)",
      tr: "Mehānismi (tiek aktīvi izstrādāti)"),
    req("M1",
      tr: "Uz API balstīta piekļuve LDT resursiem",
      en: "API-based LDT Resource Access"),
    req("M2",
      tr: "Standartizēti datu un izvades formāti",
      en: "Standardised Data and Output Formats"),
    req("M3",
      tr: "Modelis kā pakalpojums",
      en: "Model-as-a-Service"),
    req("M4",
      tr: "LDT darbplūsmu orķestrēšana",
      en: "LDT Workflow Orchestration"),
    req("M5",
      tr: "Piekļuve vairāku skatu izvadei un vizualizācijai",
      en: "Multi-view Output and Visualisation Access"),
  )

  #spec-link("Pilna specifikācija:", "https://mims.oascities.org/local-digital-twins")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  CROSS-CUTTING CONTRACT CLAUSES
// ════════════════════════════════════════════════════════════════════════════
#fit-page("clauses")[
  #band("Vispārīgie iepirkuma noteikumi", sub: "Aizsardzība pret piesaisti piegādātājam", id: "clauses")

  #intro(size: 9.8pt, "Šie noteikumi jāiekļauj katrā iepirkumā neatkarīgi no tā, ko iegādājaties. Tie izriet no iepirkumu prakses ap MIMs un living-in.eu. Lielākā daļa no tiem nebalstās uz vienu konkrētu specifikācijas prasību, tāpēc tiem nav norāžu kodu (API versiju pārvaldība ir arī MIM0 C2 ieteikums). To iekļaušana maksā maz; to neiekļaušana var maksāt visu.")

  #clauses(
    clause("Līguma izbeigšanas noteikums",
      "Līguma beigās visi pilsētas dati (un konfigurācija) tiek nodoti atvērtos, dokumentētos formātos bez papildu maksas."),
    clause("Tiesības uz datiem",
      "Visas tiesības uz līguma ietvaros savāktajiem un atvasinātajiem datiem pieder līgumslēdzējai iestādei."),
    clause("Bez maksas par lietotāju vai pieprasījumu",
      "Netiek piemērota maksa par pilsētas piekļuvi tās pašas datiem."),
    clause("API stabilitāte un versiju pārvaldība",
      "Piegādātājs nodrošina API atpakaļejošu saderību visu līguma darbības laiku. Par izmaiņām, kas pārtrauc saderību, tiek paziņots vismaz 6 mēnešus iepriekš, un tās tiek izlaistas kā jauna versija, vienlaikus saglabājot iepriekšējo versiju pieejamu līdz saskaņotajam pārejas datumam."),
    clause("Demonstrēt, nevis solīt",
      "Pretendenti piedāvājumu vērtēšanas laikā demonstrē atbilstību, nevis iesniedz pašdeklarācijas. API gadījumā tas nozīmē publicētu interaktīvu dokumentāciju (piemēram, OpenAPI) un reāllaika izsaukumu, kas atgriež derīgus datus. Katrs atzīmētais punkts tiek atkārtoti pārbaudīts pieņemšanas laikā."),
    clause("Norādīti atvērtie standarti",
      "Iepirkumā tiek norādīti iepriekš minētie standarti; apgalvojumos par saderību jānorāda precīza saskarne un versija. Katra atsauce uz standartu vai tehnisko specifikāciju pieļauj ekvivalentu risinājumu; pretendents pierāda ekvivalenci."),
    clause("Apliecinājums par atbilstību MIMs",
      "Pretendents aizpilda atbilstības tabulu (23. lpp.); tā kļūst par līguma pielikumu."),
  )
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT
// ════════════════════════════════════════════════════════════════════════════
#fit-page("example")[
  #band("Piemērs: pilsēta iepērk gaisa kvalitātes sensoru tīklu", id: "example")

  #intro(size: 9.8pt, "Atzīmētās lapas: MIM0, MIM1, MIM2, MIM6 un MIM7 (dati tiek parādīti kartē). No MIM3 tikai 3.1. punkts (gaisa kvalitātes dati tiek publicēti kā atvērtie dati, tādēļ tie iekļaujami katalogā); MIM8 netiek iekļauts: tas nav digitālais dvīnis.")

  #text(size: 10pt, weight: "bold", fill: eu-blue, "Kas kurā vietā jāiekļauj")
  #v(4pt)

  #doc-table(
    ("Dokuments", "Termins Direktīvā 2014/24/ES", "Kas tajā jāiekļauj"),
    (
      ("Tehniskā specifikācija",
       "tehniskās specifikācijas (42. pants)",
       "atzīmētie punkti no MIM0, MIM1, MIM2, MIM3 (tikai 3.1.), MIM6 (izņemot 6.4.) un MIM7 vārdu pa vārdam ar specifikācijas kodu, kā arī teikums par ekvivalenci"),
      ("Dalības nosacījumi",
       "atlases kritēriji (58. un 62. pants)",
       "pierādīta atbilstība standartam ISO/IEC 27001:2022 vai ekvivalentam (6.4. punkts)"),
      ("Pārbaudes līdzekļi",
       "testu ziņojumi, sertifikācija un citi pārbaudes līdzekļi (44. pants)",
       "atbilstības tabula kā obligāts piedāvājuma pielikums: A, E vai N katram punktam ar pierādījumiem (API dokumentācijas adrese, testa piekļuve)"),
      ("Līguma projekts",
       "līguma izpildes noteikumi (70. pants)",
       "Līguma izbeigšanas noteikums, Datu īpašumtiesības, Bez maksas par lietotāju vai pieprasījumu, API stabilitāte un versiju pārvaldība; aizpildītā atbilstības tabula kā pielikums"),
      ("Pieņemšanas akts",
       "līguma izpildes noteikumi (70. pants)",
       "atbilstības tabulas kolonna “Pārbaudīts” kā pārbaudes protokols"),
    ),
  )

  #sample-text("Tehniskās specifikācijas teksta paraugs", (
    "4.3 Savietojamība un piekļuve datiem",
    "4.3.1 Visi dati, ko sistēma vāc vai rada, ir iegūstami vismaz vienā mašīnlasāmā formātā (piem., JSON, CSV), izmantojot standarta tīmekļa API. (MIMs Plus 9.0, MIM0 R1.1, R1.2)",
    "4.3.2 API ir formāli aprakstīts atvērtā, mašīnlasāmā dokumentā (piemēram, OpenAPI), kas publicēts nemainīgā adresē. (MIM0 R1.3)",
    "4.3.3 API nodrošina datu filtrēšanu pēc mērījuma laika un vietas. (MIM0 R2.1, R2.2)",
    "… no 4.3.4 līdz 4.3.21: pārējie atzīmētie punkti …",
    "4.3.22 Katra atsauce uz standartu vai tehnisko specifikāciju pieļauj ekvivalentu risinājumu; pretendents pierāda ekvivalenci.",
    "4.3.23 Pretendents aizpilda atbilstības tabulu (iepirkuma dokumentu pielikums) un sniedz pierādījumus par katru prasīto punktu. Pretendents demonstrē punktus no 4.3.1 līdz 4.3.21 ar reāllaika API izsaukumu piedāvājumu vērtēšanas laikā; līgumslēdzēja iestāde tos atkārtoti pārbauda pieņemšanas laikā. Prasību neizpilde ir pamats atteikt pieņemšanu.",
  ))

  #note(size: 9pt, "Punkts 4.3.3 parāda, ka prasību var precizēt atbilstoši iepirkuma priekšmetam: sensoriem ir pamatoti pieprasīt filtrēšanu pēc mērījuma laika un vietas.")

  #v(4pt)
  #text(size: 10pt, weight: "bold", fill: eu-blue, "Aizpildīta atbilstības tabula (izraksts)")
  #v(4pt)

  #filled-table(
    ("#", "Prasība (saīsināti)", "A / E / N", "Pierādījumi: kā un kur", "Pārbaudīts"),
    (
      ("0.1", "Mašīnlasāmi dati caur standarta tīmekļa API", "A", "REST API nodrošina JSON un CSV; dokumentācija adresē, kas norādīta piedāvājuma 12. lpp.; testa piekļuve 3. pielikumā", "✓"),
      ("0.4", "Izmaiņu abonēšana, kur nepieciešams", "N", "pagaidām netiek atbalstīts; plānots nākamajā versijā", "—"),
      ("7.2", "Atvērti ģeotelpiskie formāti", "E", "nodrošina GeoPackage (atvērtu OGC standartu) GeoJSON vietā; ekvivalence pamatota piedāvājuma 15. lpp.", "✓"),
    ),
  )

  #note(size: 9pt, gap: 5pt, "Solījums par nākotni ir N: komisija pārbauda tikai to, ko pretendents var demonstrēt.")

  #note(size: 9pt, gap: 5pt, "Pielāgojiet formulējumu nacionālajiem tiesību aktiem un nododiet to pārbaudei par iepirkumu atbildīgajai personai.")
]
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)
// ════════════════════════════════════════════════════════════════════════════
#band("Atbilstības tabula", id: "table")

#intro(size: 9.4pt, gap: 5pt, "Viena rinda katram punktam. Līgumslēdzēja iestāde atzīmē līgumam nepieciešamo un pievieno tabulu iepirkuma dokumentiem kā obligātu piedāvājuma pielikumu. Par katru prasīto punktu pretendents norāda A (atbilst), E (atbilst ar ekvivalentu) vai N (neatbilst), īsi paskaidro, kā tas tiek nodrošināts, un norāda pierādījumu atrašanās vietu: dokumentācijas adresi, testa piekļuvi, piedāvājuma lappusi. Ar vienkāršu deklarāciju bez pierādījumiem nepietiek. Vērtēšanas komisija pārbauda katru punktu, vērtējot piedāvājumus, un atkārtoti pieņemšanas laikā (✓ apstiprināts, ✗ nav apstiprināts, — nav pārbaudīts).")

#intro(size: 9.4pt, gap: 8pt, "Aizpildītā tabula ir piedāvājuma sastāvdaļa un kļūst par līguma pielikumu. Tā pārbauda, vai ir izpildītas iepirkuma priekšmeta prasības (atbilst vai neatbilst); tas nav piedāvājuma izvērtēšanas kritērijs. Lai vērtētu atbilstības pakāpi ar punktiem, tas jānorāda iepirkuma dokumentos iepriekš publicētajos piedāvājuma izvērtēšanas kritērijos (Direktīva 2014/24/ES, 67. pants).")

#score-sheet(
  headers: ("#", "Prasība (saīsināti)", "Spec. ref.", "Prasīts?", "A / E / N", "Pierādījumi: kā un kur", "Pārbaudīts"),
  roles: ("iestāde", "pretendents", "pretendents", "komisija"),
  section("MIM0 · Vai varam iegūt savus datus?",
    ("0.1", "Mašīnlasāmi dati caur standarta tīmekļa API", "MIM0 R1.1, R1.2"),
    ("0.2", "Atvērts API apraksts (OpenAPI) nemainīgā adresē", "MIM0 R1.3"),
    ("0.3", "Filtrēšana pēc laika, vietas, atribūtiem", "MIM0 R2.1, R2.2"),
    ("0.4", "Izmaiņu abonēšana, kur nepieciešams", "MIM0 R3.1"),
    ("0.5", "Standarta HTTP kļūdas, kešatmiņa, limiti", "MIM0 C2"),
  ),
  section("MIM1 · Vai katram objektam ir noturīgs nosaukums?",
    ("1.1", "Unikāls noturīgs identifikators katram objektam", "MIM1 R1.1, R1.5"),
    ("1.2", "Identifikatora meklēšana sniedz datus + tipu", "MIM1 R1.2, R2.1, R2.2"),
    ("1.3", "Starpsistēmu identifikatoru sasaiste", "MIM1 R1.3, R1.4"),
    ("1.4", "Identifikatoros nav piegādātāja iekšējo datu", "MIM1 M1 §3.1"),
  ),
  section("MIM2 · Vai mēs runājam kopīgā valodā?",
    ("2.1", "Standarta datu modeļi, kur vien iespējams", "MIM2 R1.2a"),
    ("2.2", "Modeļi dokumentēti, mērvienības skaidras", "MIM2 R1.1"),
    ("2.3", "Paplašinājumi kā profili, nekad kā atzari", "MIM2 R1.2b, R4.1, R4.2"),
    ("2.4", "Atvērta, pēc shēmas validējama serializācija", "MIM2 R3.1, R3.4"),
  ),
  section("MIM3 · Vai varam kopīgot datus ar skaidriem nosacījumiem?",
    ("3.1", "Datu kopas katalogā ar standarta metadatiem", "MIM3 RC4.1–RC4.3"),
    ("3.2", "Parauglīcences un parauglīgumi", "MIM3 RC2.2, RC2.3"),
    ("3.3", "Pilsēta pati kontrolē piekļuves nosacījumus", "MIM3 RC1.1, RC2.1"),
  ),
  section("MIM6 · Vai mūsu dati ir drošībā pārraidē un lietošanā?",
    ("6.1", "Šifrēta pārraide (TLS 1.3)", "MIM6 R2.1, M1.1"),
    ("6.2", "Standarta pieteikšanās (OAuth 2.0 / OIDC)", "MIM6 R3.1, M1.2, M1.3"),
    ("6.3", "Lomu piekļuve + audita žurnāli", "MIM6 R1.1, R1.3, 8.15"),
    ("6.4", "Apliecināta atbilstība ISO/IEC 27001:2022", "MIM6 C1–C3 (ISO/IEC 27001)"),
  ),
  section("MIM7 · Vai tas darbojas kartē?",
    ("7.1", "OGC standarta saskarnes", "MIM7 R1.1"),
    ("7.2", "Atvērti ģeotelpiskie formāti", "MIM7 R2.1"),
    ("7.3", "Norādīta CRS (EPSG)", "MIM7 R5.1"),
    ("7.4", "Noturīgi ID telpiskajiem objektiem (sk. 1.1)", "MIM7 R4.1"),
  ),
  section("MIM8 · Vai digitālais dvīnis var attīstīties?",
    ("8.1", "Dvīņa dati un rezultāti, izmantojot API", "MIM8 R1.1"),
    ("8.2", "Modeļi dokumentēti un izsaucami", "MIM8 R3.1, R3.2"),
    ("8.3", "Standarta izvades formāti", "MIM8 M2"),
    ("8.4", "Darbplūsmas izcelsme reģistrēta", "MIM8 R4.4"),
  ),
  section("Vispārīgie iepirkuma noteikumi", accent: magenta, note: "Pretendents apliecina piekrišanu līguma noteikumam (A / N).",
    ("X.1", "Izbeigšana: bezmaksas nodošana atvērtos formātos", "—"),
    ("X.2", "Tiesības uz datiem pieder līgumslēdzējai iestādei", "—"),
    ("X.3", "Bez maksas par piekļuvi saviem datiem", "—"),
    ("X.4", "API stabilitāte: versijas, 6 mēn. brīdinājums", "—"),
  ),
)

#note(size: 8.4pt, gap: 6pt, "Zemāk norādītie saīsinātie nosaukumi atbilst pilnajiem kontrolsaraksta punktiem MIM lapās — šaubu gadījumā noteicošais ir pilnais punkta teksts.")
#spec-link("Rediģējama tabulas versija pieejama:", "https://marek-mraz.github.io/mims-procurement-checklist/")
#pagebreak()


// ════════════════════════════════════════════════════════════════════════════
//  GLOSSARY AND FURTHER READING
// ════════════════════════════════════════════════════════════════════════════
#fit-page("glossary")[
  #band("Īsa vārdnīca", id: "glossary")

  #glossary(
    term("API",
      "Piekļuves punkts, caur kuru viena programma pieprasa datus no citas — tīmeklī, bez cilvēka iejaukšanās."),
    term("Datu modelis",
      "Vienota datu struktūra: kādi lauki pastāv, ko tie nozīmē un kādas mērvienības tajos izmanto."),
    term("DCAT-AP",
      "Eiropas metadatu profils datu katalogiem; tas ļauj atrast datu kopas arī valsts un Eiropas portālos."),
    term("EPSG",
      "Koordinātu atskaites sistēmu skaitlisko kodu reģistrs (piem., EPSG:4326 sistēmai WGS 84)."),
    term("Identifikators",
      "Pastāvīgs nosaukums vienam objektam (vienam lukturim, vienai ēkai), ko visas sistēmas izmanto šī objekta apzīmēšanai."),
    term("Savietojamība",
      "Dažādu piegādātāju sistēmu spēja apmainīties ar datiem un savstarpēji tos saprast."),
    term("IRI",
      "Starptautiska tīmekļa identifikatora forma (līdzīgi kā URL, atļaujot rakstzīmes ārpus ASCII). MIM1 to izmanto objektu nosaukšanai."),
    term("LDT",
      "Vietējais digitālais dvīnis: pilsētas vai tās daļas digitāls modelis, kas savienots ar datiem un simulācijām."),
    term("Mašīnlasāms",
      "Strukturēts tā, lai programma to varētu tieši apstrādāt (JSON, CSV) — tabulas PDF dokuments tāds nav."),
    term("Metadati",
      "Dati par datiem: ko datu kopa satur, kas to nodrošina, cik tā ir aktuāla un saskaņā ar kādu licenci."),
    term("OAuth 2.0 / OIDC",
      "Atvērtie standarti pieteikšanās procesam un piekļuves piešķiršanai. OpenID Connect (OIDC) papildina OAuth 2.0 ar identitātes pārbaudi."),
    term("OGC",
      "Open Geospatial Consortium: organizācija, kas publicē standartus ģeotelpiskajiem datiem un pakalpojumiem (OGC API, WFS, SensorThings)."),
    term("Atvērts standarts",
      "Tehnisks noteikums, ko ikviens var lasīt un ieviest bez maksas vai atļaujas prasīšanas."),
    term("OpenAPI",
      "Atvērts formāts tīmekļa API mašīnlasāmam aprakstam: adreses, parametri, atbildes."),
    term("Serializācija",
      "Datu pārvēršana konkrētā formātā (piem., JSON, XML), lai tos varētu saglabāt vai pārsūtīt."),
    term("TLS",
      "Protokols, kas šifrē datus to pārraidē tīklā (HTTPS pamats)."),
    term("Piesaiste piegādātājam",
      "Situācija, kad piegādātāja maiņa prasa tik daudz līdzekļu — datu, formātu vai maksājumu dēļ —, ka to faktiski nav iespējams izdarīt."),
    term("Tīmekļa āķis / MQTT",
      "Divi veidi, kā sistēma pati paziņo par izmaiņām: tīmekļa āķis (webhook) izsauc jūsu adresi, MQTT piegādā ziņojumus abonentiem."),
  )

  #more-links("Kur uzzināt vairāk",
    more-link("mims.oascities.org", "Pilna MIMs Plus specifikācija, ko uztur OASC."),
    more-link("living-in.eu", "Eiropas kustība pilsētu digitālajai transformācijai — deklarācija un MIMs Plus konteksts."),
    more-link("smartdatamodels.org", "Standarta datu modeļu atvērtā bibliotēka (FIWARE, TM Forum, IUDX, OASC)."),
    more-link("oascities.org/academy", "CITYxCITY Academy — pilsētu darbinieku kursi, ko veidojušas pilsētas."),
  )
]


// ════════════════════════════════════════════════════════════════════════════
//  BACK COVER
// ════════════════════════════════════════════════════════════════════════════
#pagebreak()
#back-cover(
  "Sagatavots, balstoties uz Open & Agile Smart Cities izstrādāto MIMs Plus specifikāciju 9.0 (mims.oascities.org). Specifikācijas saturs © OASC. Šī brošūra ir neatkarīgs, vienkāršā valodā sagatavots ceļvedis pašvaldību iepirkumiem; šaubu gadījumā noteicošā ir specifikācija.",
  "Izveidots ar atvērtā koda rīkiem. Brīvi izmantojiet un pielāgojiet savas pilsētas vajadzībām.",
  author: "Brošūras autors: Marek Mráz",
)
