#!/usr/bin/env python3
"""Write readable/booklet-<lang>.typ: the booklet with its text inline.

main.typ builds the PDF from the content JSON, so the words are invisible in the
Typst source. This writes the same booklet as a flat, top-to-bottom Typst file
per language: every block is one call into style.typ with the text right there.
Compiles to the same PDF as main.typ. Generated: edit the JSON, not these files.
"""
import os, textwrap

from content import load, languages

HERE = os.path.dirname(os.path.abspath(__file__))


def S(s):
    """Typst string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def tup(items, ind):
    """Typst array of strings, one per line (trailing comma keeps 1-item arrays arrays)."""
    pad = " " * ind
    return "(\n" + "".join(f"{pad}  {S(i)},\n" for i in items) + pad + ")"


def rule(title):
    return f"\n\n// {'═' * 76}\n//  {title}\n// {'═' * 76}"


def page(name, blocks, opts=""):
    """One fixed page: fit-page shrinks it if the text runs long (see style.typ)."""
    body = textwrap.indent("\n\n".join(blocks), "  ")
    return f"#fit-page({S(name)}{opts})[\n{body}\n]\n#pagebreak()"


def build(lang):
    L = load(lang)
    Q, tr, ctr, url = L["quotes"], L["quote_translations"], L["capability_translations"], L["urls"]
    notes, ex = L.get("quote_notes", {}), L["example"]
    short = lambda i: i.split(" · ")[-1]          # "MIM0 · R1.1" -> "R1.1"
    c, w, h, g, x, t, gl = (L[k] for k in ("cover", "why", "howto", "glance", "cross", "tearout", "glossary"))
    nav = L["nav"]
    step_links = [(), ("clauses", "example"), ("table",), ("table",)]   # as in main.typ
    links = lambda i: "".join(f"({S(k)}, {S(nav[k])}), " for k in (step_links[i] if i < len(step_links) else ()))
    o = [textwrap.dedent(f"""\
        // {'═' * 76}
        //  MIMs procurement booklet, edition: {lang}
        //
        //  GENERATED by gen_typ.py from content/{lang}.json + shared.json + quotes.json.
        //  Do not edit: change the JSON and run ./build.sh.
        //
        //  How to read it: the file runs top to bottom in page order. Each #name(…)
        //  is one block on the page; what the block looks like (sizes, colours,
        //  spacing) is described next to its definition in ../style.typ.
        //  #fit-page("name")[ … ] is one physical page.
        //  One-letter prepositions may be followed by a no-break space (U+00A0),
        //  which looks like a normal space here.
        //
        //  Build:  typst compile --root .. --font-path ../tools/fonts booklet-{lang}.typ
        // {'═' * 76}
        #import "../style.typ": *

        #show: booklet.with(title: {S(c['title'])}, lang: "{lang}",
          nav: ({", ".join(f"{k}: {S(v)}" for k, v in L["nav"].items())}),
          mims: ({", ".join(S(m["id"]) for m in L["mims"])},))""")]

    o += [rule("COVER"),
          f"#cover(\n  title:    {S(c['title'])},\n  subtitle: {S(c['subtitle'])},\n"
          f"  tagline:  {S(c['tagline'])},\n  footer:   {S(c['footer'])},\n  author:   {S(L['back']['author'])},\n)"]

    pol = w["policy"]
    o += [rule("WHY THIS BOOKLET"), page("why", [
        f"#band({S(w['title'])})",
        *[f"#lead({S(p)})" for p in w["paras"]],
        f"#pull-quote(\n  {S(w['quote']['text'])},\n)",
        f"#policy-box({S(pol['title'])},\n  {S(pol['intro'])},\n"
        + "".join(f"  law({S(i['name'])}, {S(i['ref'])},\n    {S(i['text'])}),\n" for i in pol["items"])
        + f"  note: {S(pol['note'])},\n)"])]

    o += [rule("HOW TO USE THIS BOOKLET"), page("howto", [
        f"#band({S(h['title'])})",
        "#steps(\n" + "".join(f"  step({S(s['name'])},\n    {S(s['text'])}"
                                + (f",\n    links: ({links(i)})" if links(i) else "") + "),\n"
                                for i, s in enumerate(h["steps"])) + ")",
        f"#legend({S(h['legend_title'])},\n  note: {S(h['legend_note'])},\n"
        + "".join(f"  entry({S(e['term'])}, {S(e['text'])}),\n" for e in h["legend"]) + ")",
        f"#note({S(h['note'])})"])]

    o += [rule("THE SEVEN MIMs AT A GLANCE"), page("glance", [
        f"#band({S(g['title'])}, id: \"glance\")",
        f"#intro({S(g['intro'])})",
        f"#glance(\n  note: {S(g['numbering_note'])},\n" + "".join(
            f"  card({S(m['id'])}, {S(m['name'])},\n    {S(m['q'])},\n    {S(m['d'])},\n"
            f"    {S(url[m['id']])}),\n" for m in g["items"]) + ")",
        f"#tools({S(g['tools_title'])},\n" + "".join(
            f"  tool({S(k)}, {S(v['name'])},\n    {S(v['q'])},\n    {S(v['d'])}),\n"
            for k, v in g["tools"].items()) + ")",
        f"#menu-line((\"glossary\", {S(gl['title'])}), (\"more\", {S(gl['more_title'])}))"])]

    for m in L["mims"]:
        o += [rule(f"{m['id']} · LEFT PAGE · CHECKLIST"), page(f"{m['id']} checklist", [
            f"#mim-page(\n  id:       {S(m['id'])},\n  name:     {S(m['name'])},\n"
            f"  question: {S(m['question'])},\n  url:      {S(url[m['id']])},\n"
            f"  intro:    {S(m['intro'])},\n  list:     {S(nav['list'])},\n)",
            *[f"#item({S(it['text'])},\n  why:  {S(it['why'])},\n  refs: {S(it['refs'])},\n"
              f"  num:  {S(m['id'][3:] + '.' + str(i))}"
              + (f",\n  label: {S(it['label'])}" if it.get("label") else "") + ")"
              for i, it in enumerate(m["items"], 1)],
            f"#panels(\n  why:   ({S(L['why_title'])}, {tup(m['why_panel'], 2)}),\n"
            f"  flags: ({S(L['flags_title'])}, {tup(m['red_flags'], 2)}),\n)"])]

        o += [rule(f"{m['id']} · RIGHT PAGE · WHAT THE SPECIFICATION SAYS"),
              page(f"{m['id']} specification", [
            f"#spec-page(\n  id:     {S(m['id'])},\n  title:  {S(L['spec_title'])},\n"
            f"  leadin: {S(L['spec_leadin'])},\n  back:   {S(nav['back'])},\n)",
            f"#spec-list(mim: {S(m['id'])},\n" + "".join(
                f"  capability({S(short(c['cap']))}, {S(c['title'])}"
                + (f",\n    tr: {S(ctr[c['cap']])}" if ctr.get(c["cap"]) else "")
                + (", sub: true" if c.get("sub") else "") + "),\n"
                + "".join(
                    f"  req({S(short(q['id']))},\n"
                    + (f"    tr: {S(tr[q['id']])},\n" if tr.get(q["id"]) else "")
                    + f"    en: {S(q['en'])}"
                    + (f",\n    note: {S(notes[q['id']])}" if q["id"] in notes else "") + "),\n" for q in c["quotes"])
                for c in Q[m["id"]]) + ")",
            f"#spec-link({S(L['spec_link_label'])}, {S(url[m['id']])})"],
            opts=", floor: 92, flow: true")]

    o += [rule("CROSS-CUTTING CONTRACT CLAUSES"), page("clauses", [
        f"#band({S(x['title'])}, sub: {S(x['subtitle'])}, id: \"clauses\")",
        f"#intro(size: 9.8pt, {S(x['intro'])})",
        "#clauses(\n" + "".join(f"  clause({S(i['name'])},\n    {S(i['text'])}),\n" for i in x["items"]) + ")"])]

    o += [rule("WORKED EXAMPLE: WHAT GOES INTO WHICH TENDER DOCUMENT"), page("example", [
        f"#band({S(ex['title'])}, id: \"example\")",
        f"#intro(size: 9.8pt, {S(ex['scenario'])})",
        f"#text(size: 10pt, weight: \"bold\", fill: eu-blue, {S(ex['table_title'])})\n#v(4pt)",
        "#doc-table(\n  (" + ", ".join(S(i) for i in ex["table_headers"]) + "),\n  (\n"
        + "".join("    (" + ",\n     ".join(S(c) for c in r) + "),\n" for r in ex["table_rows"]) + "  ),\n)",
        f"#sample-text({S(ex['sample_title'])}, {tup(ex['sample'], 0)})",
        f"#note(size: 9pt, {S(ex['tip'])})",
        f"#v(4pt)\n#text(size: 10pt, weight: \"bold\", fill: eu-blue, {S(ex['filled_title'])})\n#v(4pt)",
        "#filled-table(\n  (" + ", ".join(S(t["headers"][i]) for i in (0, 1, 4, 5, 6)) + "),\n  (\n"
        + "".join("    (" + ", ".join(S(c) for c in r) + "),\n" for r in ex["filled_rows"]) + "  ),\n)",
        f"#note(size: 9pt, gap: 5pt, {S(ex['filled_note'])})",
        f"#note(size: 9pt, gap: 5pt, {S(ex['note'])})"])]

    sheet = ["#score-sheet(\n  headers: (" + ", ".join(S(i) for i in t["headers"]) + "),\n"
             "  roles: (" + ", ".join(S(i) for i in t["header_roles"]) + "),"]
    for m in L["mims"]:
        sheet += [f"  section({S(m['id'] + ' · ' + m['question'])},"]
        sheet += [f"    ({S(m['id'][3:] + '.' + str(i))}, {S(short)}, {S(m['items'][i - 1]['refs'])}),"
                  for i, short in enumerate(L["tearout_short"][m["id"]], 1)]
        sheet += ["  ),"]
    sheet += [f"  section({S(x['title'])}, accent: magenta, note: {S(t['cross_note'])},"]
    sheet += [f"    ({S('X.' + str(i))}, {S(short)}, {S('—')}),"
              for i, short in enumerate(L["tearout_short"]["CROSS"], 1)]
    sheet += ["  ),", ")"]
    o += [rule("COMPLIANCE TABLE (a table that may run over two pages, so no fit-page)"),
          f"#band({S(t['title'])}, id: \"table\")\n", f"#intro(size: 9.4pt, gap: 5pt, {S(t['intro'])})\n", f"#intro(size: 9.4pt, gap: 8pt, {S(t['intro2'])})\n",
          "\n".join(sheet) + "\n", f"#note(size: 8.4pt, gap: 6pt, {S(t['note'])})"]
    if L["sheet_url"]:
        o += [f"#spec-link({S(t['download_label'])}, {S(L['sheet_url'])})"]
    o += ["#pagebreak()"]

    o += [rule("GLOSSARY AND FURTHER READING"), page("glossary", [
        f"#band({S(gl['title'])}, id: \"glossary\")",
        "#glossary(\n" + "".join(f"  term({S(i['t'])},\n    {S(i['d'])}),\n" for i in gl["terms"]) + ")",
        f"#more-links({S(gl['more_title'])},\n"
        + "".join(f"  more-link({S(i['name'])}, {S(i['d'])}),\n" for i in gl["links"]) + ")"])]
    o[-1] = o[-1].removesuffix("\n#pagebreak()")   # main.typ breaks before the back cover instead

    o += [rule("BACK COVER"), "#pagebreak()",
          f"#back-cover(\n  {S(L['back']['text'])},\n  {S(L['back']['credits'])},\n  author: {S(L['back']['author'])},\n)"]

    os.makedirs(f"{HERE}/readable", exist_ok=True)
    out = f"{HERE}/readable/booklet-{lang}.typ"
    open(out, "w").write("\n".join(o) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    for lang in languages():
        build(lang)
