// =============================================================================
//  style.typ — ALL formatting of the MIMs procurement booklet lives here.
//
//  The booklet text never appears in this file. Two files use it:
//    main.typ                  builds the PDF straight from content/<lang>.json
//    readable/booklet-xx.typ   the same booklet with the text written inline
//                              (generated by gen_typ.py, easy to read and diff)
//
//  HOW A PAGE IS PUT TOGETHER
//  Every building block below is a function. It takes plain text and returns a
//  finished, styled piece of page, INCLUDING the gap underneath it, so the
//  calling file is a flat list of blocks with no spacing numbers in it.
//
//    fit-page ......... wraps one page; shrinks it when a translation runs long
//    cover ............ full-bleed blue title page with skyline
//    band ............. big blue page title with a short gold rule under it
//    lead, pull-quote . opening paragraphs and the framed quotation
//    policy-box ....... cream box listing the EU laws the MIMs line up with
//    steps, legend .... numbered 4-step strip, SHALL/SHOULD/MAY key
//    glance ........... two-column grid of MIM summary cards
//    mim-page ......... LEFT page of a spread: icon, badge, question, intro
//    item ............. one ☐ checklist line with its "why" and spec reference
//    panels ........... blue "why it matters" box beside red "red flags" box
//    spec-page ........ RIGHT page of a spread: heading for the requirement list
//    spec-list ........ every requirement of the MIM as cards (translation, English original)
//    spec-link ........ bottom of the right page
//    doc-table, sample-text ... the worked example page
//    clauses .......... grid of cross-cutting contract clauses
//    score-sheet ...... the tear-out scoring table
//    glossary, more-links, back-cover
//
//  Sizes are in pt. Text is Inter 9.6pt unless a block says otherwise.
// =============================================================================


// ── 1. COLOURS ───────────────────────────────────────────────────────────────
#let eu-blue      = rgb("#003399")   // headings, badges, table headers
#let eu-blue-dark = rgb("#002266")   // cover gradient start, back cover
#let eu-gold      = rgb("#FFCC00")   // short rules, cover subtitle
#let magenta      = rgb("#c2186f")   // accents: questions, spec references
#let warm-bg      = rgb("#FAF6EE")   // cream panels, table zebra rows
#let blue-tint    = rgb("#EDF1FA")   // pale blue panels, table header rows
#let red-tint     = rgb("#FBEeee")   // "red flags" panel
#let flag-red     = rgb("#a02020")   // "red flags" title and bullets
#let ink          = rgb("#1a1a2e")   // body text
#let gray-ink     = rgb("#5a5a6e")   // secondary text, footers


// ── 1b. VERSION STAMP ───────────────────────────────────────────────────────
// build.sh passes the edition number and the build date:
//   typst compile --input version=9.0.2 --input date=2026-09-18 …
// Printed on the cover, in every page footer and on the back cover.
// Every build that is not a published edition (version ends in "dev": your machine,
// the dev branch, pull requests) carries a red see-through DRAFT across each page.
#let draft = sys.inputs.at("version", default: "dev").ends-with("dev")
#let stamp = "v" + sys.inputs.at("version", default: "dev") + {
  let d = sys.inputs.at("date", default: "")
  if d != "" { " · " + d }
}


// ── 1c. NAVIGATION ──────────────────────────────────────────────────────────
// Sections carry a label: "glance", "MIM0" … "MIM8" (checklist page), "MIM0-spec",
// "clauses", "example", "table", "glossary", "more". Every requirement card carries
// "q:MIM0 · R1.1", every capability heading "c:MIM0 · C1".
//   anchor  an invisible heading: the PDF bookmark (side panel) and, with a key, the label
//   go      internal link, plain when the target does not exist; never underlined or recoloured
//   see     "→ name s. 26" as a link, the page number read from the target
//   pnum    "s. 26" alone
#let page-abbr = state("page-abbr", "p.")
#let anchor(key, title, level: 1) = {
  let h = heading(level: level, outlined: false, bookmarked: true, title)
  if key == none { h } else [#h#label(key)]
}
#let go(key, body) = context if query(label(key)).len() > 0 { link(label(key), body) } else { body }
#let pnum(key) = context if query(label(key)).len() > 0 {
  page-abbr.get() + "\u{a0}" + str(counter(page).at(label(key)).first())
}
#let see(key, name) = go(key, text(size: 7.8pt, fill: magenta, weight: "medium", [→ #name #pnum(key)]))

// "MIM0 R1.1, R1.2" with every code a link to its card on the specification page.
// strip: true drops the "MIM0 " prefix (the compliance table names the MIM in the band above).
#let strip-mim(refs) = refs.replace(regex("^MIM\\d "), "")
#let ref-links(refs, strip: false) = {
  let mim = refs.find(regex("^MIM\\d"))
  if mim == none { return refs }
  let rest = strip-mim(refs)
  let out = (if strip { "" } else { mim + " " },)
  let pos = 0
  for m in rest.matches(regex("RC?\\d\\.\\d[ab]?|M\\d(\\.\\d)?|C\\d|§[\\d.]+|\\d+\\.\\d+")) {
    out.push(rest.slice(pos, m.start))
    out.push(context {
      let hit = ("q:", "c:").map(k => label(k + mim + " · " + m.text)).filter(l => query(l).len() > 0)
      if hit.len() > 0 { link(hit.first(), m.text) } else { m.text }
    })
    pos = m.end
  }
  out.push(rest.slice(pos))
  out.join()
}


// ── 2. PAGE SETUP ────────────────────────────────────────────────────────────
// Use as:  #show: booklet.with(title: "…", lang: "cs")
// A4, 1.7 cm side margins. Every page except the covers carries a footer: thin rule,
// then a clickable strip "MIM0 · … · MIM8 | Clauses · Example · Table · Glossary",
// the section of the current page in bold blue, "↑ Overview" and the page number.
// nav: the short names (content JSON, key "nav"), mims: the MIM ids in order.
// Version and date are on the cover and the back cover only.
//
// Languages that build long compound words get hyphenation, otherwise one word
// can be wider than a narrow column. The others are set without it.
#let long-word-langs = ("de", "nl", "da", "sv", "fi", "et", "hu", "lv", "lt", "el", "bg", "mt")

#let booklet(title: "", lang: "en", author: "Marek Mráz", nav: (:), mims: (), body) = {
  show heading: none                             // headings exist only as PDF bookmarks
  page-abbr.update(nav.page)
  set document(title: title.replace(" · ", " "), author: author)     // PDF properties
  set text(font: "Inter", size: 9.6pt, fill: ink, lang: lang,
    hyphenate: lang in long-word-langs)
  set par(justify: false, leading: 0.62em)
  // draft.svg is the word as outlines, so copying text from the PDF never picks it up.
  // Its strength is the opacity value inside draft.svg.
  set page(foreground: if draft {
    place(center + horizon, rotate(-50deg, reflow: false, image("draft.svg", width: 21cm)))
  })
  set page(paper: "a4", margin: (x: 1.7cm, top: 1.8cm, bottom: 1.7cm),
    footer: context {
      let p = counter(page).get().first()
      if p > 1 {
        set text(size: 7.6pt, fill: gray-ink)
        line(length: 100%, stroke: 0.5pt + eu-blue.lighten(60%))
        v(2pt)
        let secs = mims.map(id => (id, id)) + ("clauses", "example", "table", "glossary").map(k => (k, nav.at(k)))
        let cur = none                             // last section that starts on or before this page
        for (k, _) in secs {
          if query(label(k)).len() > 0 and counter(page).at(label(k)).first() <= p { cur = k }
        }
        let entry(s) = go(s.at(0), if s.at(0) == cur { text(weight: "bold", fill: eu-blue, s.at(1)) } else { s.at(1) })
        grid(columns: (1fr, auto, auto), column-gutter: 12pt,
          secs.slice(0, mims.len()).map(entry).join(" · ") + h(5pt) + "|" + h(5pt)
            + secs.slice(mims.len()).map(entry).join(" · "),
          go("glance", "↑ " + nav.overview),
          text(weight: "bold", str(p)))
      }
    }
  )
  body
}


// ── 2b. ONE PAGE THAT ALWAYS FITS ───────────────────────────────────────────
// Translations run longer than English (German and Finnish by a third). A page
// that overflows would push every later spread one page off. So each fixed page
// is wrapped in fit-page: when its content is taller than the page, the whole
// page is zoomed out in 2 % steps until it fits, down to 76 %. Text, gaps and
// boxes shrink together, so the design holds. Pages that fit are left untouched.
// floor: sets another lowest zoom. flow: true lets a page that is still too long
// at that zoom run on to the next page at full size (the specification pages,
// which list every requirement of a MIM, use floor: 92, flow: true).
//
// Every fit-page also leaves a record (page name, zoom, still overflowing?) that
// check_content.py reads with `typst query … "<fit>"` to report tight pages.
#let fit-page(name, floor: 76, flow: false, body) = layout(size => {
  let pct = 100
  let h = measure(width: size.width, body).height
  while h * pct / 100 > size.height and pct > floor {
    pct -= 2
    h = measure(width: size.width * 100 / pct, body).height
  }
  let over = h * pct / 100 > size.height
  if over and flow { pct = 100 }        // too long even when zoomed: run on to the next page
  if pct == 100 { body } else {
    scale(pct * 1%, origin: top + left, reflow: true,
      block(width: size.width * 100 / pct, body))
  }
  [#metadata((page: name, zoom: pct, overflow: over and not flow, flows: over and flow))<fit>]
})

// Quotation marks in the style of the document language: “…” „…“ «…» …
#let quoted(body) = [#smartquote()#body#smartquote()]

// Text made of several sentences joined by " · " (the MIM0 C2 list, the opening
// quote) is set with one sentence per line.
#let lines(body) = body.split(" · ").join(linebreak())


// ── 3. SMALL PARTS ───────────────────────────────────────────────────────────

// Empty tick box, 10 × 10 pt, blue outline.
#let checkbox = box(baseline: 1.5pt, width: 10pt, height: 10pt,
  stroke: 1.2pt + eu-blue, radius: 2pt, fill: white)

// Rounded label "MIM0". Blue with white text; dark: true gives gold with blue text.
#let mim-badge(id, dark: false) = box(
  fill: if dark { eu-gold } else { eu-blue }, radius: 3pt, inset: (x: 6pt, y: 3.5pt),
  text(fill: if dark { eu-blue } else { white }, weight: "bold", size: 9pt, id))

// Short coloured rule that sits under headings.
#let rule(colour) = box(width: 3.2cm, height: 3pt, fill: colour, radius: 2pt)

// The web address without "https://", as shown on the page.
#let bare(url) = url.replace("https://", "")

// Tinted box with an upper-case title and a bulleted list.
//   tint = background colour, bar = colour of the title and the bullets
#let panel(title, items, tint, bar) = block(
  fill: tint, radius: 6pt, inset: 10pt, width: 100%, breakable: false, {
    text(fill: bar, weight: "bold", size: 9pt, upper(title))
    v(4pt)
    for it in items {
      grid(columns: (7pt, 1fr), gutter: 4pt,
        text(fill: bar, weight: "bold", "•"), text(size: 8.8pt, it))
      v(2.5pt)
    }
  })

// 26 × 26 pt pictogram per MIM, drawn with Typst shapes (no image files).
#let icon(id) = {
  let s = 26pt
  box(width: s, height: s, {
    if id == "MIM0" {
      // box with an arrow leaving it: data gets out
      place(dx: 1pt, dy: 4pt, rect(width: 12pt, height: 18pt, stroke: 1.8pt + eu-blue, radius: 2pt))
      place(dx: 9pt, dy: 13pt, line(length: 11pt, stroke: 2pt + magenta))
      place(dx: 19.5pt, dy: 8.8pt, polygon(fill: magenta, (0pt, 0pt), (5.5pt, 4.2pt), (0pt, 8.4pt)))
    } else if id == "MIM1" {
      // three linked nodes
      place(dx: 7.8pt, dy: 9.6pt, line(start: (0pt, 0pt), end: (3.4pt, 6.8pt), stroke: 1.4pt + gray-ink))
      place(dx: 18.2pt, dy: 9.6pt, line(start: (0pt, 0pt), end: (-3.4pt, 6.8pt), stroke: 1.4pt + gray-ink))
      place(dx: 10pt, dy: 6pt, line(length: 6pt, stroke: 1.4pt + gray-ink))
      place(dx: 2pt, dy: 2pt, circle(radius: 4pt, stroke: 1.8pt + eu-blue, fill: white))
      place(dx: 16pt, dy: 2pt, circle(radius: 4pt, stroke: 1.8pt + magenta, fill: white))
      place(dx: 9pt, dy: 16pt, circle(radius: 4pt, stroke: 1.8pt + eu-blue, fill: white))
    } else if id == "MIM2" {
      // document with a title line and text lines: the documented data model
      place(dx: 4pt, dy: 2pt, rect(width: 16pt, height: 21pt, stroke: 1.8pt + eu-blue, radius: 2pt, fill: white))
      place(dx: 7.5pt, dy: 7pt, line(length: 9pt, stroke: 1.8pt + magenta))
      place(dx: 7.5pt, dy: 12pt, line(length: 9pt, stroke: 1.4pt + gray-ink))
      place(dx: 7.5pt, dy: 16pt, line(length: 6pt, stroke: 1.4pt + gray-ink))
    } else if id == "MIM3" {
      // two opposing arrows: exchange. A stroke is centred on its line, so a head
      // sits at line y - 4.2pt; the pair mirrors around the icon centre (13, 13).
      place(dx: 2.5pt, dy: 8pt, line(length: 16pt, stroke: 2pt + eu-blue))
      place(dx: 18pt, dy: 3.8pt, polygon(fill: eu-blue, (0pt, 0pt), (5.5pt, 4.2pt), (0pt, 8.4pt)))
      place(dx: 7.5pt, dy: 18pt, line(length: 16pt, stroke: 2pt + magenta))
      place(dx: 2.5pt, dy: 13.8pt, polygon(fill: magenta, (5.5pt, 0pt), (0pt, 4.2pt), (5.5pt, 8.4pt)))
    } else if id == "MIM6" {
      // padlock: shackle arc behind a filled body, gold keyhole on the centre axis
      place(dx: 8pt, dy: 2pt, circle(radius: 5pt, stroke: 2.2pt + magenta))
      place(dx: 5pt, dy: 10pt, rect(width: 16pt, height: 13pt, fill: eu-blue, radius: 2.5pt))
      place(dx: 11pt, dy: 13.2pt, circle(radius: 2pt, fill: eu-gold))
      place(dx: 12.1pt, dy: 16.4pt, rect(width: 1.8pt, height: 3.6pt, fill: eu-gold))
    } else if id == "MIM7" {
      // map pin
      place(polygon(fill: magenta, (8.6pt, 11.5pt), (17.4pt, 11.5pt), (13pt, 23pt)))
      place(dx: 6.5pt, dy: 1.5pt, circle(radius: 6.5pt, fill: magenta))
      place(dx: 10.5pt, dy: 5.5pt, circle(radius: 2.5pt, fill: white))
      place(dx: 3pt, dy: 24pt, line(length: 20pt, stroke: 1.6pt + eu-blue))
    } else if id == "MIM8" {
      // physical + digital twin: two overlapping circles
      place(dx: 1.5pt, dy: 6pt, circle(radius: 7pt, stroke: 2pt + eu-blue))
      place(dx: 10.5pt, dy: 6pt, circle(radius: 7pt, stroke: 2pt + magenta))
    }
  })
}


// ── 4. COVER AND BACK COVER ──────────────────────────────────────────────────

// Full-bleed page, diagonal blue gradient, no margins, no footer.
// Centred: title 30pt bold white, subtitle 14pt gold, gold rule, tagline 10.5pt.
// Bottom: translucent skyline bars with the audience line over them.
#let cover(title: "", subtitle: "", tagline: "", footer: "", author: none) = page(margin: 0pt, footer: none, {
  rect(width: 100%, height: 100%, fill: gradient.linear(eu-blue-dark, eu-blue, angle: 35deg), {
    place(center + horizon, dy: -0.6cm, block(width: 78%, {
      set align(center)
      set text(fill: white)
      // " · " in the title is a line break; a long title (the full name of the booklet) is set smaller
      text(size: if title.clusters().len() > 60 { 24pt } else { 30pt }, weight: "bold", lines(title))
      v(14pt)
      text(size: 14pt, fill: eu-gold, weight: "medium", subtitle)
      v(22pt)
      box(width: 4cm, height: 2.5pt, fill: eu-gold, radius: 2pt)
      v(22pt)
      text(size: 10.5pt, fill: white.transparentize(15%), tagline)
    }))
    // skyline silhouette across the full page width: (relative width, height) per building
    place(bottom, grid(
      columns: (28, 20, 34, 16, 30, 22, 40, 18, 28, 24, 36, 20, 30, 26, 38, 18, 32, 22, 30).map(w => w * 1fr),
      column-gutter: 3pt, align: bottom,
      ..(40, 66, 52, 84, 46, 72, 58, 92, 48, 64, 44, 76, 56, 68, 42, 60, 50, 80, 54).map(h =>
        box(width: 100%, height: h * 1pt, fill: white.transparentize(82%)))))
    // audience line, author and version stamp sit above the skyline, never on it
    place(bottom + center, dy: -3.7cm, {
      set align(center)
      set par(leading: 0.8em)
      text(size: 9pt, fill: white.transparentize(25%), footer)
      linebreak()
      if author != none { text(size: 8.5pt, fill: white.transparentize(25%), author); linebreak() }
      text(size: 8pt, fill: eu-gold, stamp)
    })
  })
})

// Solid dark-blue page: credits text, gold rule, licence line in gold.
#let back-cover(body, credits, author: none) = page(margin: 0pt, footer: none, {
  rect(width: 100%, height: 100%, fill: eu-blue-dark, {
    place(center + horizon, block(width: 70%, {
      set align(center)
      set text(fill: white)
      text(size: 9.6pt, fill: white.transparentize(10%), body)
      v(14pt)
      box(width: 3cm, height: 2pt, fill: eu-gold)
      v(14pt)
      text(size: 9pt, fill: eu-gold, credits)
      v(10pt)
      if author != none { text(size: 8.5pt, fill: white.transparentize(25%), author); linebreak() }
      text(size: 8.5pt, fill: white.transparentize(25%), stamp)
    }))
  })
})


// ── 5. HEADINGS AND RUNNING TEXT ─────────────────────────────────────────────

// Page title: 19pt bold blue, optional 10.5pt magenta subtitle, gold rule, 10pt gap.
// id: the section label other pages link to; the title is also the PDF bookmark.
#let band(title, sub: none, id: none) = {
  block(width: 100%, breakable: false, {
    anchor(id, title)
    text(size: 19pt, weight: "bold", fill: eu-blue, title)
    if sub != none { v(1pt); text(size: 10.5pt, fill: magenta, weight: "medium", sub) }
    v(4pt)
    rule(eu-gold)
  })
  v(10pt)
}

// Opening paragraph, slightly larger than body text (10.3pt), 6pt gap after.
#let lead(body) = { par(text(size: 10.3pt, body)); v(6pt) }

// Sentence under a page title. size = text size, gap = space below it.
#let intro(body, size: 10.3pt, gap: 10pt) = { text(size: size, body); v(gap) }

// Pale blue box with a blue bar on the left: italic quotation, source below in gray.
#let pull-quote(body) = {
  // body: sentences joined by " · ". A sentence that starts with "1. ", "2. " … is set
  // as a numbered point with a hanging indent; the others are plain paragraphs.
  let parts = body.split(" · ")
  v(6pt)
  block(fill: blue-tint, radius: 6pt, inset: (x: 14pt, y: 12pt), width: 100%,
    stroke: (left: 3pt + eu-blue), context {
    set text(size: 9.4pt, style: "italic")
    // The quote opens in the first paragraph and closes in the last one, which
    // smartquote() cannot pair across paragraphs, so the marks are picked here.
    let marks = if text.lang in ("sk", "cs", "de", "sl", "hr", "bg", "lt", "et") { ("„", "“") }
      else if text.lang in ("fr", "es", "it", "pt", "el") { ("«", "»") }
      else if text.lang in ("pl", "ro", "nl", "hu") { ("„", "”") }
      else if text.lang in ("fi", "sv") { ("”", "”") }
      else { ("“", "”") }
    for (i, part) in parts.enumerate() {
      let open = if i == 0 { marks.first() }
      let close = if i == parts.len() - 1 { marks.last() }
      let m = part.match(regex("^(\\d+)\\.\\s+"))
      if m == none {
        block(above: 9pt, below: 9pt, [#open#part#close])
      } else {
        block(above: 7pt, below: 7pt, inset: (left: 6pt), grid(columns: (13pt, 1fr), gutter: 3pt,
          text(fill: eu-blue, weight: "bold", style: "normal", m.captures.first() + "."),
          [#open#part.slice(m.end)#close]))
      }
    }
  })
}

#let law(name, ref, text) = (name: name, ref: ref, text: text)

// Cream box with a gold bar on the left. Title in bold blue, one intro sentence,
// then one row per law: name in bold blue with its official number in small gray
// underneath (4.4 cm column), what the law asks for on the right. A gray italic
// disclaimer closes the box.
#let policy-box(title, intro, note: none, ..laws) = {
  v(12pt)
  block(fill: warm-bg, radius: 6pt, inset: 12pt, width: 100%, breakable: false,
    stroke: (left: 3pt + eu-gold), {
    text(fill: eu-blue, weight: "bold", size: 10.5pt, title)
    v(4pt)
    text(size: 9.2pt, intro)
    v(7pt)
    for l in laws.pos() {
      grid(columns: (4.4cm, 1fr), gutter: 10pt,
        {
          text(weight: "bold", size: 9.2pt, fill: eu-blue, l.name)
          linebreak()
          text(size: 7.6pt, fill: gray-ink, l.ref)
        },
        text(size: 9pt, l.text))
      v(5pt)
    }
    if note != none { v(1pt); text(size: 8pt, fill: gray-ink, style: "italic", note) }
  })
}

// Small gray italic remark.
#let note(body, size: 9pt, gap: 8pt) = {
  v(gap)
  text(size: size, fill: gray-ink, style: "italic", body)
}


// ── 6. "HOW TO USE" PAGE ─────────────────────────────────────────────────────

// links: pairs (section label, short name) shown under the step as "→ name s. 26"
#let step(name, text, links: ()) = (name: name, text: text, links: links)

// Equal columns, one per step: numbered circle (blue, magenta, blue, …),
// step name in bold blue, explanation 8.8pt underneath.
#let steps(..s) = {
  let all = s.pos()
  block(breakable: false, {
    grid(columns: (1fr,) * all.len(), column-gutter: 10pt,
      ..all.enumerate().map(((i, s)) => {
        block(width: 100%, {
          align(center, {
            box(width: 30pt, height: 30pt, fill: if calc.rem(i, 2) == 0 { eu-blue } else { magenta },
              radius: 15pt, align(center + horizon,
                text(fill: white, weight: "bold", size: 13pt, str(i + 1))))
          })
          v(5pt)
          align(center, text(weight: "bold", size: 10.5pt, fill: eu-blue, s.name))
          v(4pt)
          text(size: 8.8pt, s.text)
          for (k, n) in s.at("links", default: ()) { v(3pt); see(k, n) }
        })
      })
    )
  })
}

#let entry(term, text) = (term: term, text: text)

// Cream box explaining SHALL / SHOULD / MAY: each keyword on a gold chip.
#let legend(title, note: none, ..entries) = {
  v(14pt)
  block(fill: warm-bg, radius: 6pt, inset: 11pt, width: 100%, {
    text(fill: eu-blue, weight: "bold", size: 9.5pt, title)
    v(5pt)
    for l in entries.pos() {
      grid(columns: (7pt, 1fr), gutter: 4pt,
        text(fill: eu-gold.darken(15%), "▪"),
        {
          box(fill: eu-gold.lighten(35%), radius: 2pt, inset: (x: 3.5pt, y: 1.5pt),
            text(size: 9pt, weight: "bold", fill: eu-blue-dark, l.term))
          h(4pt)
          text(size: 9pt, l.text)
        })
      v(3pt)
    }
    if note != none { v(3pt); text(size: 9pt, note) }     // closing sentence, no chip
  })
}


// ── 7. "AT A GLANCE" PAGE ────────────────────────────────────────────────────

#let card(id, name, q, d, url) = (id: id, name: name, q: q, d: d, url: url)

// Two columns of cream cards: icon + badge + name, the question in magenta,
// a one-line description in gray, the web address in small blue.
// note: the remark on the numbering, set in the free cell beside the seventh card.
#let glance(note: none, ..cards) = grid(columns: (1fr, 1fr), gutter: 9pt, align: horizon,
  ..cards.pos().map(m => block(
    fill: warm-bg, radius: 6pt, inset: (x: 10pt, y: 8pt), width: 100%, breakable: false, {
      // the card is the menu entry for its MIM: everything but the web address links to it
      go(m.id, {
        grid(columns: (auto, auto, 1fr, auto), gutter: 6pt, align: horizon,
          icon(m.id), mim-badge(m.id), text(weight: "bold", size: 9.5pt, fill: eu-blue, m.name),
          text(size: 8pt, weight: "medium", fill: eu-blue, pnum(m.id)))
        v(5pt)
        text(size: 9.3pt, weight: "medium", fill: magenta, m.q)
        v(3pt)
        text(size: 8.6pt, fill: gray-ink, m.d)
      })
      v(4pt)
      link(m.url, text(size: 7.3pt, fill: eu-blue, bare(m.url)))
    })),
  if note != none { pad(x: 8pt, text(size: 8.4pt, fill: gray-ink, style: "italic", note)) }
)


// Second row of the menu: three cards in the same style for the pages a buyer uses most.
//   #tools("title", tool("clauses", "name", "question?", "one line"), …)
#let tool(key, name, q, d) = (key: key, name: name, q: q, d: d)
#let tools(title, ..cards) = {
  v(10pt)
  text(size: 10.5pt, weight: "bold", fill: eu-blue, title)
  v(5pt)
  let card(c, height: auto) = block(
    fill: blue-tint, radius: 6pt, inset: (x: 10pt, y: 8pt), width: 100%, height: height, breakable: false, {
      text(weight: "bold", size: 9.5pt, fill: eu-blue, c.name)
      v(4pt)
      text(size: 9.3pt, weight: "medium", fill: magenta, c.q)
      v(3pt)
      text(size: 8.6pt, fill: gray-ink, c.d)
      v(4pt)
      text(size: 8pt, weight: "medium", fill: eu-blue, pnum(c.key))
    })
  // all cards as tall as the tallest one
  layout(size => {
    let n = cards.pos().len()
    let w = (size.width - 9pt * (n - 1)) / n
    let tall = calc.max(..cards.pos().map(c => measure(width: w, card(c)).height))
    grid(columns: (1fr,) * n, gutter: 9pt, ..cards.pos().map(c => go(c.key, card(c, height: tall))))
  })
}

// One centred line under the menu: "Glossary s. 30 · Where to learn more s. 30"
#let menu-line(..entries) = {
  v(8pt)
  align(center, text(size: 8.6pt, fill: eu-blue, weight: "medium",
    entries.pos().map(e => go(e.at(0), [#e.at(1) #pnum(e.at(0))])).join(h(6pt) + "·" + h(6pt))))
}


// ── 8. MIM SPREAD, LEFT PAGE: THE CHECKLIST ──────────────────────────────────

// Header: icon, then badge + MIM name in gray, then the question 17.5pt bold blue.
// Under it a gold rule with the web address, then the intro paragraph.
// list: the bookmark name of this page under the MIM ("Checklist").
#let mim-page(id: "", name: "", question: "", url: "", intro: "", list: none) = {
  block(breakable: false, {
    anchor(id, id + " · " + name)
    if list != none { anchor(none, list, level: 2) }
    grid(columns: (auto, 1fr, auto), gutter: 10pt, align: horizon,
      icon(id),
      {
        mim-badge(id)
        h(6pt)
        text(size: 10pt, fill: gray-ink, name)
        v(3pt)
        text(size: 17.5pt, weight: "bold", fill: eu-blue, question)
      },
      none)
    v(4pt)
    rule(eu-gold)
    h(10pt)
    link(url, text(size: 7.8pt, fill: gray-ink, bare(url)))
  })
  v(8pt)
  text(size: 9.6pt, intro)
  v(9pt)
}

// One checklist line. Never splits across pages.
//   ☐  requirement sentence, 9.6pt medium weight
//      why it protects the city, 8.6pt gray italic   → MIM0 R1.1 (7.6pt magenta)
// num: "0.1", the number the compliance table uses for the same item (same in every language).
// label: a small magenta line above the item, for an item that belongs in another tender document.
#let item(body, why: "", refs: "", num: none, label: none) = {
  block(breakable: false, {
    grid(columns: (14pt, 1fr), gutter: 5pt,
      checkbox,
      {
        if label != none { text(size: 7.8pt, weight: "bold", fill: magenta, upper(label)); linebreak() }
        if num != none { text(size: 9.6pt, weight: "bold", fill: eu-blue, num); h(5pt) }
        text(size: 9.6pt, weight: "medium", body)
        v(2pt)
        text(size: 8.6pt, fill: gray-ink, style: "italic", why)
        h(6pt)
        text(size: 7.6pt, fill: magenta, weight: "medium", [→ #ref-links(refs)])
      })
  })
  v(6.5pt)
}

// Two boxes side by side: blue "why it matters" (wider) and red "red flags".
// Each argument is (title, (bullet, bullet, …)).
#let panels(why: ("", ()), flags: ("", ())) = {
  v(2pt)
  grid(columns: (1.15fr, 1fr), gutter: 9pt,
    panel(why.at(0), why.at(1), blue-tint, eu-blue),
    panel(flags.at(0), flags.at(1), red-tint, flag-red))
}


// ── 9. MIM SPREAD, RIGHT PAGE: WHAT THE SPECIFICATION SAYS ───────────────────

// Header: badge + title 15.5pt bold blue, magenta rule, gray lead-in sentence.
// back: the words of the link to the checklist page ("back to the checklist").
#let spec-page(id: "", title: "", leadin: "", back: none) = {
  block(breakable: false, {
    anchor(id + "-spec", title, level: 2)
    grid(columns: (1fr, auto), align: (left + horizon, right + horizon), {
      mim-badge(id)
      h(6pt)
      text(size: 15.5pt, weight: "bold", fill: eu-blue, title)
    }, if back != none { go(id, text(size: 7.8pt, fill: magenta, weight: "medium", "← " + back)) })
    v(4pt)
    rule(magenta)
  })
  v(7pt)
  text(size: 9pt, fill: gray-ink, leadin)
  v(7pt)
}

// Every requirement of one MIM, grouped by capability, full page width.
//   #spec-list(
//     capability("C1", "English title", tr: "translated title"),
//     req("R1.1", en: "verbatim English", tr: "translation"),
//     …)
// capability: blue chip with the id, bold blue heading (with tr: the translation,
//   the English heading small and gray under it). It stays with its first card.
// req: cream card with a magenta bar; the id on the left, the text on the right.
//   With tr: the translation in italics, the English original small and gray
//   under it. Without tr (English edition): the English original in italics.
// A card whose id equals its capability heading (MIM0 C4) shows no id, only the space.
// Cards are never split; the list itself runs on to the next page when needed.
// sub: true is a heading of the specification inside a capability ("Additional best
//   practice to consider:"): same type, no chip, and the capability above stays current.
#let capability(id, title, tr: none, sub: false) = (cap: true, id: id, en: title, tr: tr, sub: sub)
// note: a remark of this booklet under the card text (small, upright)
#let req(id, en: "", tr: none, note: none) = (cap: false, id: id, en: en, tr: tr, note: note)

// mim: the MIM id; with it every card and heading gets its label (see 1c).
#let spec-list(mim: "", ..rows) = {
  let mark(kind, id) = if mim != "" [#box()#label(kind + mim + " · " + id)]
  let heading = none          // id of the capability heading above the current card
  for r in rows.pos() {
    if r.cap {
      if not r.sub { heading = r.id }
      block(sticky: true, above: 11pt, below: 5pt,
        grid(columns: (auto, 1fr), gutter: 6pt, align: top,
          mark("c:", r.id) + if not r.sub { box(fill: eu-blue, radius: 3pt, inset: (x: 5pt, y: 2.5pt),
            text(fill: white, weight: "bold", size: 7.8pt, r.id)) },
          {
            text(size: 9.4pt, weight: "bold", fill: eu-blue, if r.tr != none { r.tr } else { r.en })
            if r.tr != none { linebreak(); text(size: 7.8pt, fill: gray-ink, lang: "en", r.en) }
          }))
    } else {
      block(fill: warm-bg, radius: 4pt, width: 100%, breakable: false,
        inset: (left: 11pt, rest: 9pt), stroke: (left: 2.5pt + magenta), below: 6pt,
        grid(columns: (1.15cm, 1fr), gutter: 4pt,
          // a statement of the capability itself (no R number): the chip above already names it
          mark("q:", r.id) + text(fill: magenta, weight: "bold", size: 8.6pt, if r.id != heading { r.id }),
          if r.tr != none {
            text(size: 9.2pt, style: "italic", quoted(lines(r.tr)))
            block(above: 10pt, text(size: 8pt, fill: gray-ink, lang: "en", quoted(lines(r.en))))   // original stays English
          } else {
            text(size: 9.2pt, style: "italic", lang: "en", quoted(lines(r.en)))
          } + if r.note != none {
            block(above: 7pt, text(size: 7.8pt, fill: magenta.darken(10%), r.note))
          }))
    }
  }
  v(8pt)
}

// "Full specification: https://…" with the address as a blue link.
#let spec-link(label, url) = {
  text(size: 8.4pt, fill: gray-ink, weight: "medium", label + " ")
  link(url, text(size: 8.4pt, fill: eu-blue, url))
}


// ── 10. CROSS-CUTTING CLAUSES ────────────────────────────────────────────────

#let clause(name, text) = (name: name, text: text)

// Two columns of boxes, pale blue and cream alternating: ☐ + clause name in
// bold blue, the clause text 9pt below.
#let clauses(..c) = grid(columns: (1fr, 1fr), gutter: 9pt,
  ..c.pos().enumerate().map(((i, c)) => block(
    fill: if calc.rem(i, 2) == 0 { blue-tint } else { warm-bg },
    radius: 6pt, inset: 11pt, width: 100%, breakable: false, {
      // X.1, X.2 …: the first clauses are the rows of block X in the compliance table
      grid(columns: (14pt, 1fr), gutter: 5pt, checkbox,
        text(weight: "bold", size: 9.8pt, fill: eu-blue, "X." + str(i + 1) + h(5pt) + c.name))
      v(4pt)
      text(size: 9pt, c.text)
    }))
)


// ── 10b. WORKED EXAMPLE ─────────────────────────────────────────────────────
// doc-table: which tender document gets what. First column bold blue, header row
//   pale blue, hairlines between rows.
// sample-text: a piece of tender wording in a cream box with a magenta bar. The first
//   line is its heading (bold); lines that start with a clause number get a hanging indent.
#let doc-table(headers, rows) = {
  set par(leading: 0.5em)
  table(columns: (2.9cm, 4.4cm, 1fr), inset: (x: 6pt, y: 5pt),
    stroke: (x, y) => (bottom: 0.4pt + eu-blue.lighten(70%)),
    fill: (x, y) => if y == 0 { blue-tint },
    ..headers.map(h => text(size: 8.6pt, weight: "bold", fill: eu-blue, h)),
    ..rows.map(r => (
      text(size: 8.8pt, weight: "bold", fill: eu-blue, r.at(0)),
      text(size: 8.2pt, fill: gray-ink, r.at(1)),
      text(size: 8.8pt, r.at(2)))).flatten())
}

// Extract of a completed compliance table: #, requirement, S/E/N, evidence, verified.
#let filled-table(headers, rows) = {
  set par(leading: 0.5em)
  table(columns: (0.9cm, 4.4cm, auto, 1fr, auto), inset: (x: 6pt, y: 5pt),
    stroke: (x, y) => (bottom: 0.4pt + eu-blue.lighten(70%)),
    fill: (x, y) => if y == 0 { blue-tint },
    align: (x, y) => if x == 2 or x == 4 { center } else { left },
    ..headers.map(h => text(size: 8.2pt, weight: "bold", fill: eu-blue, h)),
    ..rows.map(r => (
      text(size: 8.4pt, r.at(0)), text(size: 8.4pt, r.at(1)),
      text(size: 8.8pt, weight: "bold", fill: magenta, r.at(2)),
      text(size: 8.4pt, style: "italic", r.at(3)),
      text(size: 8.8pt, weight: "bold", fill: eu-blue, r.at(4)))).flatten())
}

#let sample-text(title, lines) = {
  v(10pt)
  text(size: 10pt, weight: "bold", fill: eu-blue, title)
  v(5pt)
  block(fill: warm-bg, radius: 5pt, width: 100%, inset: (left: 12pt, rest: 10pt),
    stroke: (left: 2.5pt + magenta), {
      set text(size: 8.8pt)
      for (i, l) in lines.enumerate() {
        let m = l.match(regex("^(\\d+(\\.\\d+)+)\\s+"))
        if i == 0 { block(below: 7pt, text(weight: "bold", l)) }
        else if m == none { block(above: 6pt, below: 6pt, text(fill: gray-ink, style: "italic", l)) }
        else { block(above: 6pt, below: 6pt, grid(columns: (1.05cm, 1fr), gutter: 3pt,
          text(weight: "bold", fill: magenta, m.captures.first()), l.slice(m.end))) }
      }
    })
}


// ── 11. COMPLIANCE TABLE ─────────────────────────────────────────────────────

// One group of rows. accent = colour of the full-width group header
// (blue for a MIM, magenta for the cross-cutting clauses).
// Each row is (number, short requirement, spec reference).
// note: a remark in the group header, after the title (what the bidder answers in this block).
#let section(title, accent: eu-blue, note: none, ..rows) = (title: title, accent: accent, note: note, rows: rows.pos())

// Seven columns: # | requirement | spec ref (links) | required? ☐ | S/E/N | evidence | verified.
// roles: second header row, who fills in the last four columns.
// Pale blue header row, cream and white body rows alternating.
#let score-sheet(headers: (), roles: (), ..sections) = context {
  // Column widths are measured, not `auto`: a section band spans all columns and
  // would stretch every auto column. A reference never wraps; the two text columns
  // share what is left.
  let pad = 9.6pt
  let head(i) = measure(text(size: 8.2pt, weight: "bold", headers.at(i))).width + pad
  let ref-w = calc.max(head(2), ..sections.pos().map(s => s.rows.map(r =>
    measure(text(size: 7.6pt, strip-mim(r.at(2)))).width + pad)).flatten())
  let cells = ()
  for s in sections.pos() {
    cells.push(table.cell(colspan: 7, fill: s.accent,
      text(fill: white, weight: "bold", size: 8.6pt, s.title)
        + if s.note != none { h(8pt) + text(fill: white, size: 8pt, s.note) }))
    for r in s.rows {
      cells.push(text(size: 8.2pt, r.at(0)))
      cells.push(text(size: 8.2pt, r.at(1)))
      cells.push(text(size: 7.6pt, fill: gray-ink, ref-links(r.at(2), strip: true)))
      cells.push(align(center, checkbox))
      cells.push([])
      cells.push([])
      cells.push([])
    }
  }
  table(
    // S/E/N and "verified" take one character; the evidence column gets the width
    columns: (0.95cm, 1.15fr, ref-w, head(3), head(4), 1fr, head(6)),
    stroke: 0.5pt + eu-blue.lighten(55%),
    inset: 4.6pt,
    fill: (x, y) => if calc.odd(y) { warm-bg } else { white },
    // second header row: who fills the column in
    table.header(..headers.map(h =>
      table.cell(fill: blue-tint, text(size: 8.2pt, weight: "bold", fill: eu-blue, h))),
      ..((none,) * 3 + roles).map(r => table.cell(fill: blue-tint, inset: (top: 0pt, rest: 4.6pt),
        if r != none { text(size: 7pt, style: "italic", fill: gray-ink, r) }))),
    ..cells
  )
}


// ── 12. GLOSSARY ─────────────────────────────────────────────────────────────

#let term(t, d) = (t: t, d: d)

// Two columns: the term in bold blue, its definition 8.9pt below.
#let glossary(..terms) = grid(columns: (1fr, 1fr), gutter: 10pt,
  ..terms.pos().map(t => block(breakable: false, {
    text(weight: "bold", size: 9.6pt, fill: eu-blue, t.t)
    v(2pt)
    text(size: 8.9pt, t.d)
  }))
)

#let more-link(name, d) = (name: name, d: d)

// Magenta sub-heading, then rows: site name in blue (4.2 cm column) + description.
#let more-links(title, ..links) = {
  v(14pt)
  [#box()#label("more")]
  text(size: 12.5pt, weight: "bold", fill: magenta, title)
  v(6pt)
  for l in links.pos() {
    block(breakable: false, grid(columns: (4.2cm, 1fr), gutter: 8pt,
      text(weight: "medium", size: 9.2pt, fill: eu-blue, l.name),
      text(size: 9.2pt, l.d)))
    v(4pt)
  }
}
